DROP PROCEDURE IF EXISTS TEMP_RENTAL_CUSTOMER_INSERT;
CREATE PROCEDURE TEMP_RENTAL_CUSTOMER_INSERT(IN SOURCESCHEMA  VARCHAR(40),IN DESTINATIONSCHEMA  VARCHAR(40))
BEGIN
    SET FOREIGN_KEY_CHECKS=0; 
    SET @DROP_TEMP_RENTAL_CUSTOMER=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_RENTAL_CUSTOMER'));
    PREPARE DROP_TEMP_RENTAL_CUSTOMER_STMT FROM @DROP_TEMP_RENTAL_CUSTOMER;
    EXECUTE DROP_TEMP_RENTAL_CUSTOMER_STMT;	
	SET @CREATE_TEMP_RENTAL_CUSTOMER=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.TEMP_RENTAL_CUSTOMER(ID INTEGER NOT NULL AUTO_INCREMENT,CUST_ID INTEGER,CUSTOMER_NAME CHAR(100),
	UNITNO INTEGER,PRIMARY KEY(ID))'));
	PREPARE CREATE_TEMP_RENTAL_CUSTOMER_STMT FROM @CREATE_TEMP_RENTAL_CUSTOMER;
    EXECUTE CREATE_TEMP_RENTAL_CUSTOMER_STMT;
	SET @INSERT_TEMP_RENTAL_CUSTOMER=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_RENTAL_CUSTOMER(CUST_ID,CUSTOMER_NAME,UNITNO)
	SELECT CC_CUST_ID,IF(CC_FIRST_NAME=CC_LAST_NAME,CC_FIRST_NAME, CONCAT(CC_FIRST_NAME,"_",CC_LAST_NAME)),CC_UNIT_NO FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_SCDB_FORMAT'));
	PREPARE INSERT_TEMP_RENTAL_CUSTOMER_STMT FROM @INSERT_TEMP_RENTAL_CUSTOMER;
    EXECUTE INSERT_TEMP_RENTAL_CUSTOMER_STMT;
	SET @UPDATE_TEMP_RENTAL_CUSTOMER=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_RENTAL_CUSTOMER SET CUSTOMER_NAME=',"'MAN_MAN'",' WHERE CUSTOMER_NAME=',"'MAN'"' AND UNITNO=',"'3906'"));
	PREPARE UPDATE_TEMP_RENTAL_CUSTOMER_STMT FROM @UPDATE_TEMP_RENTAL_CUSTOMER;
    EXECUTE UPDATE_TEMP_RENTAL_CUSTOMER_STMT;
    SET FOREIGN_KEY_CHECKS=1;    
END;
