-- VERSION:0.2 -- STARTDATE:01/07/2014 -- ENDDATE:01/07/2014 -- ISSUE NO:593 -- COMMENT NO:193 -- DESC CHANGES IN SP NAME FOR CLEARING THE ISSUE -- DONE BY:BHAVANI.R
-- VERSION:0.1 -- STARTDATE:25/06/2014 -- ENDDATE:25/06/2014 -- ISSUE NO:593 -- COMMENT NO:89 -- DESC CREATING TRIGGER SP FOR INSERTING AND UPDATING IN EXPENSE_DETAIL_DIGITAL_VOICE -- DONE BY:BHAVANI.R
DROP PROCEDURE IF EXISTS SP_TRG_BIZDTL_DIGITAL_VOICE_VALIDATION;
CREATE PROCEDURE SP_TRG_BIZDTL_DIGITAL_VOICE_VALIDATION(
IN OLDEDDVID INTEGER,
IN NEWEDDVID INTEGER,
IN NEWECNID INTEGER,
IN PROCESS TEXT)
BEGIN
	DECLARE MESSAGE_TEXT VARCHAR(50);
	-- IF INSERTION THEN CHK THE CONDITION FOR THROWING ERROR MESSAGE
	IF(PROCESS = 'INSERT') THEN
		IF(NEWECNID IS NOT NULL)THEN
			IF NOT EXISTS(SELECT ECN_ID FROM EXPENSE_CONFIGURATION WHERE ECN_ID = NEWECNID AND CGN_ID = 27)THEN
				SIGNAL SQLSTATE '45000'
				SET MESSAGE_TEXT = 'GIVE ECN_ID IN BETWEEN 19 TO 21';
			END IF;
		END IF;
	END IF;
		-- IF UPDATION THEN CHK THE CONDITION FOR THROWING ERROR MESSAGE
	IF(PROCESS = 'UPDATE') THEN
		IF(NEWECNID IS NOT NULL)THEN
			IF NOT EXISTS(SELECT ECN_ID FROM EXPENSE_CONFIGURATION WHERE ECN_ID = NEWECNID AND CGN_ID = 27)THEN
				SIGNAL SQLSTATE '45000'
				SET MESSAGE_TEXT = 'GIVE ECN_ID IN BETWEEN 19 TO 21';
			END IF;
		END IF;
	END IF;
END;