-- VERSION:0.2 -- STARTDATE:01/07/2014 -- ENDDATE:01/07/2014 -- ISSUE NO:593 -- COMMENT NO:193 -- DESC changes in sp for passing parameter from trigger sp -- DONE BY:BHAVANI.R
-- VERSION:0.1 -- STARTDATE:26/06/2014 -- ENDDATE:26/06/2014 -- ISSUE NO:593 -- COMMENT NO:109 -- DESC CREATING TRIGGER FOR VALIDATION OF DATAS WHILE UPDATION IN EXPENSE_DETAIL_STARHUB  -- DONE BY:BHAVANI.R

DROP TRIGGER IF EXISTS TRG_BIZDTL_STARHUB_UPDATE_VALIDATION;
CREATE TRIGGER TRG_BIZDTL_STARHUB_UPDATE_VALIDATION
BEFORE UPDATE ON EXPENSE_DETAIL_STARHUB
FOR EACH ROW
BEGIN
	CALL SP_TRG_BIZDTL_STARHUB_VALIDATION(OLD.EDSH_ID,NULL,NEW.UNIT_ID,NEW.ECN_ID,NEW.EDSH_APPL_DATE,NEW.EDSH_CABLE_START_DATE,NEW.EDSH_CABLE_END_DATE,NEW.EDSH_INTERNET_START_DATE,NEW.EDSH_INTERNET_END_DATE,'UPDATE');
END;