-- VERSION:0.2 -- STARTDATE:01/07/2014 -- ENDDATE:01/07/2014 -- ISSUE NO:593 -- COMMENT NO:193 -- DESC CHANGES IN SP NAME FOR CLEARING THE ISSUE -- DONE BY:BHAVANI.R
-- VERSION:0.1 -- STARTDATE:25/06/2014 -- ENDDATE:25/06/2014 -- ISSUE NO:595 -- COMMENT NO:89 -- DESC CREATING TRIGGER  FOR INSERTION IN EXPENSE_DETAIL_DIGITAL_VOICE -- DONE BY:BHAVANI.R
DROP TRIGGER IF EXISTS TRG_BIZDTL_DIGITAL_VOICE_INSERT_VALIDATION;
CREATE TRIGGER TRG_BIZDTL_DIGITAL_VOICE_INSERT_VALIDATION
BEFORE INSERT ON EXPENSE_DETAIL_DIGITAL_VOICE
FOR EACH ROW
BEGIN
	CALL SP_TRG_BIZDTL_DIGITAL_VOICE_VALIDATION(NULL,NULL,NEW.ECN_ID,'INSERT');
END;