DROP TRIGGER IF EXISTS TRG_USER_FILE_DETAILS_UPDATE;
CREATE TRIGGER TRG_USER_FILE_DETAILS_UPDATE  
AFTER UPDATE ON USER_FILE_DETAILS 
FOR EACH ROW
BEGIN 
DECLARE OLD_VALUE TEXT DEFAULT '';
DECLARE NEW_VALUE TEXT DEFAULT '';
IF ((OLD.RC_ID!= NEW.RC_ID) OR (OLD.FP_ID!= NEW.FP_ID)) THEN  
  SET OLD_VALUE = CONCAT(OLD_VALUE,'UFD_ID=', OLD.UFD_ID,','); 
END IF;
IF (OLD.RC_ID!= NEW.RC_ID) THEN  
  SET OLD_VALUE = CONCAT(OLD_VALUE,'RC_ID=', OLD.RC_ID,','); 
  SET NEW_VALUE = CONCAT(NEW_VALUE,'RC_ID=', NEW.RC_ID,','); 
END IF;
IF (OLD.FP_ID!= NEW.FP_ID) THEN  
  SET OLD_VALUE = CONCAT(OLD_VALUE,'FP_ID=', OLD.FP_ID,','); 
  SET NEW_VALUE = CONCAT(NEW_VALUE,'FP_ID=', NEW.FP_ID,',');
END IF;
IF ((OLD.RC_ID!= NEW.RC_ID) OR (OLD.FP_ID!= NEW.FP_ID)) THEN  
IF (OLD.ULD_ID!= NEW.ULD_ID) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'ULD_ID=', OLD.ULD_ID,','); 
END IF;
IF (OLD.UFD_TIMESTAMP!= NEW.UFD_TIMESTAMP) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'UFD_TIMESTAMP=', OLD.UFD_TIMESTAMP,','); 
END IF;
END IF;
IF (OLD_VALUE!='' AND NEW_VALUE!='') THEN
IF (OLD_VALUE != NEW_VALUE) THEN
     SET OLD_VALUE = SUBSTRING(OLD_VALUE,1,CHAR_LENGTH(OLD_VALUE)-1);
    SET NEW_VALUE = SUBSTRING(NEW_VALUE,1,CHAR_LENGTH(NEW_VALUE)-1);
INSERT INTO TICKLER_HISTORY
(ULD_ID,TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE)VALUES
((SELECT ULD_ID FROM USER_FILE_DETAILS WHERE UFD_ID=NEW.UFD_ID),
(SELECT TP_ID FROM TICKLER_PROFILE WHERE TP_TYPE='UPDATION'),
(SELECT TTIP_ID FROM TICKLER_TABID_PROFILE WHERE TTIP_DATA='USER_FILE_DETAILS'),OLD_VALUE,NEW_VALUE);
END IF;
END IF;
END;