DROP TRIGGER IF EXISTS TRG_USER_MENU_DETAILS_UPDATE;
CREATE TRIGGER TRG_USER_MENU_DETAILS_UPDATE  
AFTER UPDATE ON USER_MENU_DETAILS 
FOR EACH ROW
BEGIN 
DECLARE OLD_VALUE TEXT DEFAULT '';
DECLARE NEW_VALUE TEXT DEFAULT '';
IF ((OLD.MP_ID!=NEW.MP_ID)  OR (OLD.RC_ID!=NEW.RC_ID))THEN  
  SET OLD_VALUE = CONCAT(OLD_VALUE,'MD_ID=', OLD.MD_ID,','); 
END IF;
IF (OLD.MP_ID!= NEW.MP_ID) THEN  
  SET OLD_VALUE = CONCAT(OLD_VALUE,'MP_ID=', OLD.MP_ID,','); 
  SET NEW_VALUE = CONCAT(NEW_VALUE,'MP_ID=', NEW.MP_ID,','); 
END IF;
IF (OLD.RC_ID!= NEW.RC_ID) THEN  
  SET OLD_VALUE = CONCAT(OLD_VALUE,'RC_ID=', OLD.RC_ID,','); 
  SET NEW_VALUE = CONCAT(NEW_VALUE,'RC_ID=', NEW.RC_ID,','); 
END IF;
IF ((OLD.MP_ID!=NEW.MP_ID)  OR (OLD.RC_ID!=NEW.RC_ID))THEN  
IF (OLD.ULD_ID!= NEW.ULD_ID) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'ULD_ID=', OLD.ULD_ID,','); 
END IF;
IF (OLD.MD_TIMESTAMP!= NEW.MD_TIMESTAMP) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'MD_TIMESTAMP=', OLD.MD_TIMESTAMP,','); 
END IF;
END IF;
IF (OLD_VALUE!='' AND NEW_VALUE!='') THEN
IF (OLD_VALUE != NEW_VALUE)THEN
     SET OLD_VALUE = SUBSTRING(OLD_VALUE,1,CHAR_LENGTH(OLD_VALUE)-1);
     SET NEW_VALUE = SUBSTRING(NEW_VALUE,1,CHAR_LENGTH(NEW_VALUE)-1);
INSERT INTO TICKLER_HISTORY
(ULD_ID,TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE)VALUES
((SELECT ULD_ID FROM USER_MENU_DETAILS WHERE MD_ID=NEW.MD_ID),
(SELECT TP_ID FROM TICKLER_PROFILE WHERE TP_TYPE='UPDATION'),
(SELECT TTIP_ID FROM TICKLER_TABID_PROFILE WHERE TTIP_DATA='USER_MENU_DETAILS'),OLD_VALUE,NEW_VALUE);
END IF;
END IF;
END;