DROP TRIGGER IF EXISTS TRG_USER_LOGIN_DETAILS_UPDATE;
CREATE TRIGGER TRG_USER_LOGIN_DETAILS_UPDATE  
AFTER UPDATE ON USER_LOGIN_DETAILS 
FOR EACH ROW
BEGIN 
DECLARE OLD_VALUE TEXT DEFAULT '';
DECLARE NEW_VALUE TEXT DEFAULT '';
DECLARE ULDUSERSTAMP VARCHAR(50);
DECLARE ULDID INTEGER(2);
IF ((OLD.ULD_LOGINID!=NEW.ULD_LOGINID)) THEN  
  SET OLD_VALUE = CONCAT(OLD_VALUE,'ULD_ID=', OLD.ULD_ID,','); 
END IF;
IF (OLD.ULD_LOGINID!= NEW.ULD_LOGINID) THEN  
  SET OLD_VALUE = CONCAT(OLD_VALUE,'ULD_LOGINID=', OLD.ULD_LOGINID,','); 
  SET NEW_VALUE = CONCAT(NEW_VALUE,'ULD_LOGINID=', NEW.ULD_LOGINID,','); 
END IF;
IF ((OLD.ULD_LOGINID!=NEW.ULD_LOGINID)) THEN  
IF (OLD.ULD_USERSTAMP!= NEW.ULD_USERSTAMP) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'ULD_USERSTAMP=', OLD.ULD_USERSTAMP,','); 
END IF;
IF (OLD.ULD_TIMESTAMP!= NEW.ULD_TIMESTAMP) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'ULD_TIMESTAMP=', OLD.ULD_TIMESTAMP,','); 
END IF;
END IF;
IF (OLD_VALUE!='' AND NEW_VALUE!='') THEN
IF (OLD_VALUE != NEW_VALUE) THEN
     SET OLD_VALUE = SUBSTRING(OLD_VALUE,1,CHAR_LENGTH(OLD_VALUE)-1);
     SET NEW_VALUE = SUBSTRING(NEW_VALUE,1,CHAR_LENGTH(NEW_VALUE)-1);
	 SET ULDID = (SELECT ULD_ID FROM USER_LOGIN_DETAILS WHERE ULD_LOGINID=NEW.ULD_USERSTAMP);
INSERT INTO TICKLER_HISTORY
(ULD_ID,TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE)VALUES
(ULDID,(SELECT TP_ID FROM TICKLER_PROFILE WHERE TP_TYPE='UPDATION'),
(SELECT TTIP_ID FROM TICKLER_TABID_PROFILE WHERE TTIP_DATA='USER_LOGIN_DETAILS'),OLD_VALUE,NEW_VALUE);
END IF;
END IF;
END;