DROP TRIGGER IF EXISTS TRG_CHEQUE_ENTRY_DETAILS_INSERT_VALIDATION;
CREATE TRIGGER TRG_CHEQUE_ENTRY_DETAILS_INSERT_VALIDATION
BEFORE INSERT ON CHEQUE_ENTRY_DETAILS
FOR EACH ROW  
BEGIN
    CALL SP_TRG_CHEQUE_ENTRY_DETAILS_VALIDATION(NEW.CHEQUE_AMOUNT,'INSERT');
END;