DROP TRIGGER IF EXISTS TRG_BANK_TRANSFER_MODELS_UPDATE;
CREATE TRIGGER TRG_BANK_TRANSFER_MODELS_UPDATE
AFTER UPDATE ON BANK_TRANSFER_MODELS
FOR EACH ROW
BEGIN 
DECLARE OLD_VALUE TEXT DEFAULT '';
DECLARE NEW_VALUE TEXT DEFAULT '';
IF (OLD.BTM_DATA!= NEW.BTM_DATA) OR (OLD.BTM_OBSOLETE IS NULL AND NEW.BTM_OBSOLETE IS NOT NULL) OR (OLD.BTM_OBSOLETE IS NOT NULL AND NEW.BTM_OBSOLETE IS NULL) OR (OLD.BTM_OBSOLETE != NEW.BTM_OBSOLETE)  THEN  
  SET OLD_VALUE = CONCAT(OLD_VALUE,'BTM_ID=', OLD.BTM_ID,','); 
END IF;
  IF (OLD.BTM_DATA != NEW.BTM_DATA ) THEN 
      SET OLD_VALUE = CONCAT(OLD_VALUE,'BTM_DATA=', OLD.BTM_DATA,','); 
      SET NEW_VALUE = CONCAT(NEW_VALUE,'BTM_DATA=', NEW.BTM_DATA,',');
  END IF;
  IF (OLD.BTM_OBSOLETE IS NULL AND NEW.BTM_OBSOLETE IS NOT NULL) THEN
      SET OLD_VALUE = CONCAT(OLD_VALUE,'BTM_OBSOLETE=','<NULL>,');
      SET NEW_VALUE = CONCAT(NEW_VALUE,'BTM_OBSOLETE=',NEW.BTM_OBSOLETE,',');
  ELSEIF (OLD.BTM_OBSOLETE IS NOT NULL AND NEW.BTM_OBSOLETE IS NULL) THEN
      SET OLD_VALUE=CONCAT(OLD_VALUE,'BTM_OBSOLETE=',OLD.BTM_OBSOLETE,',');
      SET NEW_VALUE=CONCAT(NEW_VALUE,'BTM_OBSOLETE=','<NULL>');
  ELSEIF (OLD.BTM_OBSOLETE != NEW.BTM_OBSOLETE ) THEN 
      SET OLD_VALUE = CONCAT(OLD_VALUE,'BTM_OBSOLETE=', OLD.BTM_OBSOLETE,','); 
      SET NEW_VALUE = CONCAT(NEW_VALUE,'BTM_OBSOLETE=', NEW.BTM_OBSOLETE,',');
  END IF;
IF (OLD.BTM_DATA!= NEW.BTM_DATA) OR (OLD.BTM_OBSOLETE IS NULL AND NEW.BTM_OBSOLETE IS NOT NULL) OR (OLD.BTM_OBSOLETE IS NOT NULL AND NEW.BTM_OBSOLETE IS NULL) OR (OLD.BTM_OBSOLETE != NEW.BTM_OBSOLETE)  THEN  
IF (OLD.ULD_ID!= NEW.ULD_ID) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'ULD_ID=', OLD.ULD_ID,','); 
END IF;
IF (OLD.BTM_TIMESTAMP!= NEW.BTM_TIMESTAMP) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'BTM_TIMESTAMP=', OLD.BTM_TIMESTAMP,','); 
END IF;
END IF;
IF (OLD_VALUE!='' AND NEW_VALUE!='') THEN
IF(OLD_VALUE!=NEW_VALUE)THEN
     SET OLD_VALUE = SUBSTRING(OLD_VALUE,1,CHAR_LENGTH(OLD_VALUE)-1);
     SET NEW_VALUE = SUBSTRING(NEW_VALUE,1,CHAR_LENGTH(NEW_VALUE)-1);
INSERT INTO TICKLER_HISTORY
(ULD_ID,TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE)VALUES
((SELECT ULD_ID FROM BANK_TRANSFER_MODELS WHERE BTM_ID=NEW.BTM_ID),
(SELECT TP_ID FROM TICKLER_PROFILE WHERE TP_TYPE='UPDATION'),
(SELECT TTIP_ID FROM TICKLER_TABID_PROFILE WHERE TTIP_DATA='BANK_TRANSFER_MODELS'),OLD_VALUE,NEW_VALUE);
END IF;
END IF;
END;