-- version:0.4-- sdate:30/06/2014 -- edate:01/07/2014 -- issue:765 -- COMMENT NO:251 --desc:UPDATED MAXRECVER EPDATE,EPNO,PASSPORTDATE,PASSPORTNO SP --doneby:DHIVYA.A
-- version:0.3-- sdate:17/06/2014 -- edate:17/06/2014 -- issue:743 -- COMMENT NO:240 --desc:SPLITTED CUSTOMER_PERSONAL_DETAILS SP --doneby:DHIVYA.A
--VER 0.2 ISSUE NO:795 STARTDATE:02/04/2014 ENDDATE:02/04/2014 DESC:REMOVED PERSONAL DETAILS VIEW DONE BY:DHIVYA
--VER 0.1 ISSUE NO:765 STARTDATE:26/03/2014 ENDDATE:27/03/2014 DESC:MERGED ALL CUSTOMER RECVER INTO ONE HEADER DONE BY:DHIVYA

DROP PROCEDURE IF EXISTS SP_CUSTOMER_PERSONAL_DETAILS_INSERT_PART1;
CREATE PROCEDURE SP_CUSTOMER_PERSONAL_DETAILS_INSERT_PART1(IN SOURCESCHEMA VARCHAR(50),IN DESTINATIONSCHEMA VARCHAR(50),IN MIGUSERSTAMP VARCHAR(50),IN PART INTEGER,IN MINCUSTOMERID INTEGER,IN MAXCUSTOMERID INTEGER)
BEGIN
DECLARE MINID INTEGER;
DECLARE MAXID INTEGER;
DECLARE MINCUSTID INTEGER;
DECLARE MAXCUSTID INTEGER;
DECLARE CUSTOMER_COMMENTS TEXT;
DECLARE MINRECVER INTEGER;
DECLARE MAXRECVER INTEGER;
DECLARE MERGECOMMENTS TEXT;
DECLARE MINRECVERID INTEGER;
DECLARE MAXRECVERID INTEGER;
DECLARE MINACCESSID INTEGER;
DECLARE MAXACCESSID INTEGER;
DECLARE ACCESS_FNAME VARCHAR(50);
DECLARE ACCESS_LNAME VARCHAR(50);
DECLARE ACCESS_UNITNO INTEGER;
DECLARE AC_MINID INTEGER;
DECLARE AC_MAXID INTEGER;
DECLARE ACCOMMENTS TEXT;
DECLARE START_TIME TIME;
DECLARE END_TIME TIME;
DECLARE DURATION TIME;
DECLARE INITTIME TIME;
DECLARE MAXDURATIONID INTEGER;
DECLARE MINDURATIONID INTEGER;
DECLARE MIN_CUSTOMERID INTEGER;
DECLARE MAX_CUSTOMERID INTEGER;
DECLARE CPDMOBILE VARCHAR(8);
DECLARE CPDINTLMOBILE VARCHAR(20);
DECLARE CPDPASSPORTNO VARCHAR(15);
DECLARE CPDPASSPORTDATE DATE;
DECLARE CPDDOB DATE;
DECLARE CPDEPNO VARCHAR(15);
DECLARE CPDEPDATE DATE;
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
	ROLLBACK;
	END;
	START TRANSACTION;
	SET START_TIME=(SELECT CURTIME());
	IF PART=1 THEN
	SET @DROPCUSTOMERPERSONAL=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.CUSTOMER_PERSONAL_DETAILS'));
	PREPARE DRCUSPERSONAL FROM @DROPCUSTOMERPERSONAL;
	EXECUTE DRCUSPERSONAL;
	SET @CRCUSTOMERPERSONAL=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.CUSTOMER_PERSONAL_DETAILS(
	CPD_ID INTEGER NOT NULL	AUTO_INCREMENT,
	CUSTOMER_ID	INTEGER NOT NULL,
	NC_ID INTEGER NOT NULL,
	CPD_MOBILE VARCHAR(8) NULL,	
	CPD_INTL_MOBILE	VARCHAR(20) NULL,	
	CPD_EMAIL VARCHAR(40) NOT NULL,	
	CPD_PASSPORT_NO	VARCHAR(15) NULL,	
	CPD_PASSPORT_DATE DATE NULL,	
	CPD_DOB	DATE NULL,	
	CPD_EP_NO VARCHAR(15) NULL,	
	CPD_EP_DATE	DATE NULL,	
	CPD_COMMENTS TEXT NULL,	
	PRIMARY KEY(CPD_ID),
	FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
	FOREIGN KEY(NC_ID) REFERENCES NATIONALITY_CONFIGURATION(NC_ID))'));
	PREPARE CUSTOMERPERONAL FROM @CRCUSTOMERPERSONAL;
	EXECUTE CUSTOMERPERONAL;
	SET @INCUSTOMERPERSONAL=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.CUSTOMER_PERSONAL_DETAILS(CUSTOMER_ID,NC_ID,CPD_MOBILE,CPD_INTL_MOBILE,CPD_EMAIL,
	CPD_PASSPORT_NO,CPD_PASSPORT_DATE,CPD_DOB,CPD_EP_NO,CPD_EP_DATE) 
	SELECT CSF.CC_CUST_ID,NC.NC_ID,CSF.CC_MOBILE,CSF.CC_MOBILE2,CSF.CC_EMAIL,CSF.CC_PASSPORT_NO,CSF.CC_PASSPORT_DATE,
	CSF.CC_DOB,CSF.CC_EP_NO,CSF.CC_EP_DATE FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_SCDB_FORMAT CSF,',DESTINATIONSCHEMA,'.NATIONALITY_CONFIGURATION NC WHERE 
	CSF.CC_NATIONALITY = NC.NC_DATA AND CSF.CC_NATIONALITY IS NOT NULL AND CSF.CC_EMAIL IS NOT NULL	GROUP BY CSF.CC_CUST_ID'));
	PREPARE IN_CUS_PERSONAL FROM @INCUSTOMERPERSONAL;
	EXECUTE IN_CUS_PERSONAL;
	SET @EMPTY=NULL	;
	SET @UP_CUS_PER=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.CUSTOMER_PERSONAL_DETAILS SET CPD_MOBILE=@EMPTY,CPD_INTL_MOBILE=@EMPTY,CPD_PASSPORT_NO=@EMPTY,CPD_PASSPORT_DATE=@EMPTY,CPD_DOB=@EMPTY,CPD_EP_NO=@EMPTY,CPD_EP_DATE=@EMPTY'));
	PREPARE UP_CUS_PER_STMT FROM @UP_CUS_PER;
	EXECUTE UP_CUS_PER_STMT;
	END IF;
	SET MIN_CUSTOMERID=(SELECT MIN(CC_CUST_ID) FROM CUSTOMER_SCDB_FORMAT);
	SET MAX_CUSTOMERID=(SELECT MAX(CC_CUST_ID) FROM CUSTOMER_SCDB_FORMAT);
	WHILE MIN_CUSTOMERID<=MAX_CUSTOMERID DO
	SET CPDMOBILE=(SELECT CC_MOBILE FROM CUSTOMER_SCDB_FORMAT WHERE CC_CUST_ID=MIN_CUSTOMERID AND CC_REC_VER=(SELECT MAX(CC_REC_VER) FROM CUSTOMER_SCDB_FORMAT WHERE CC_CUST_ID=MIN_CUSTOMERID AND CC_MOBILE IS NOT NULL));
	IF CPDMOBILE IS NOT NULL THEN
		SET @UPDATE_CUST_PER_MOBILE=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.CUSTOMER_PERSONAL_DETAILS SET CPD_MOBILE=','"',CPDMOBILE,'"',' WHERE CUSTOMER_ID=',MIN_CUSTOMERID));
		PREPARE UPDATE_CUST_PER_MOBILE_STMT FROM @UPDATE_CUST_PER_MOBILE;
		EXECUTE UPDATE_CUST_PER_MOBILE_STMT;
	END IF;
	SET CPDINTLMOBILE=(SELECT CC_MOBILE2 FROM CUSTOMER_SCDB_FORMAT WHERE CC_CUST_ID=MIN_CUSTOMERID AND CC_REC_VER=(SELECT MAX(CC_REC_VER) FROM CUSTOMER_SCDB_FORMAT WHERE CC_CUST_ID=MIN_CUSTOMERID AND CC_MOBILE2 IS NOT NULL));
	IF CPDINTLMOBILE IS NOT NULL THEN
		SET @UPDATE_CUST_PER_INT_MOB=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.CUSTOMER_PERSONAL_DETAILS SET CPD_INTL_MOBILE=','"',CPDINTLMOBILE,'"',' WHERE CUSTOMER_ID=',MIN_CUSTOMERID));
		PREPARE UPDATE_CUST_PER_INT_MOB_STMT FROM @UPDATE_CUST_PER_INT_MOB;
		EXECUTE UPDATE_CUST_PER_INT_MOB_STMT;
	END IF;
	SET CPDPASSPORTNO=(SELECT CC_PASSPORT_NO FROM CUSTOMER_SCDB_FORMAT WHERE CC_CUST_ID=MIN_CUSTOMERID AND CC_REC_VER=(SELECT MAX(CC_REC_VER) FROM CUSTOMER_SCDB_FORMAT WHERE CC_CUST_ID=MIN_CUSTOMERID AND CC_PASSPORT_NO IS NOT NULL));
	IF CPDPASSPORTNO IS NOT NULL THEN
	SET @UPDATE_CUST_PER_PASSNO=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.CUSTOMER_PERSONAL_DETAILS SET CPD_PASSPORT_NO=','"',CPDPASSPORTNO,'"',' WHERE CUSTOMER_ID=',MIN_CUSTOMERID));
		PREPARE UPDATE_CUST_PER_PASSNO_STMT FROM @UPDATE_CUST_PER_PASSNO;
		EXECUTE UPDATE_CUST_PER_PASSNO_STMT;
	END IF;
	SET CPDPASSPORTDATE=(SELECT CC_PASSPORT_DATE FROM CUSTOMER_SCDB_FORMAT WHERE CC_CUST_ID=MIN_CUSTOMERID AND CC_REC_VER=(SELECT MAX(CC_REC_VER) FROM CUSTOMER_SCDB_FORMAT WHERE CC_CUST_ID=MIN_CUSTOMERID AND CC_PASSPORT_DATE IS NOT NULL));
	IF CPDPASSPORTDATE IS NOT NULL THEN
		SET @UPDATE_CUST_PER_PASSDATE=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.CUSTOMER_PERSONAL_DETAILS SET CPD_PASSPORT_DATE=','"',CPDPASSPORTDATE,'"',' WHERE CUSTOMER_ID=',MIN_CUSTOMERID));
		PREPARE UPDATE_CUST_PER_PASSDATE_STMT FROM @UPDATE_CUST_PER_PASSDATE;
		EXECUTE UPDATE_CUST_PER_PASSDATE_STMT;
	END IF;
	SET CPDDOB=(SELECT CC_DOB FROM CUSTOMER_SCDB_FORMAT WHERE CC_CUST_ID=MIN_CUSTOMERID AND CC_REC_VER=(SELECT MAX(CC_REC_VER) FROM CUSTOMER_SCDB_FORMAT WHERE CC_CUST_ID=MIN_CUSTOMERID AND CC_DOB IS NOT NULL));
	IF CPDDOB IS NOT NULL THEN
		SET @UPDATE_CUST_PER_CPDOB=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.CUSTOMER_PERSONAL_DETAILS SET CPD_DOB=','"',CPDDOB,'"',' WHERE CUSTOMER_ID=',MIN_CUSTOMERID));
		PREPARE UPDATE_CUST_PER_CPDOB_STMT FROM @UPDATE_CUST_PER_CPDOB;
		EXECUTE UPDATE_CUST_PER_CPDOB_STMT;
	END IF;
	SET CPDEPNO=(SELECT CC_EP_NO FROM CUSTOMER_SCDB_FORMAT WHERE CC_CUST_ID=MIN_CUSTOMERID AND CC_REC_VER=(SELECT MAX(CC_REC_VER) FROM CUSTOMER_SCDB_FORMAT WHERE CC_CUST_ID=MIN_CUSTOMERID AND CC_EP_NO IS NOT NULL));
	IF CPDEPNO IS NOT NULL THEN
		SET @UPDATE_CUST_PER_CPDEPNO=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.CUSTOMER_PERSONAL_DETAILS SET CPD_EP_NO=','"',CPDEPNO,'"',' WHERE CUSTOMER_ID=',MIN_CUSTOMERID));
		PREPARE UPDATE_CUST_PER_CPDEPNO_STMT FROM @UPDATE_CUST_PER_CPDEPNO;
		EXECUTE UPDATE_CUST_PER_CPDEPNO_STMT;
	END IF;
	SET CPDEPDATE=(SELECT CC_EP_DATE FROM CUSTOMER_SCDB_FORMAT WHERE CC_CUST_ID=MIN_CUSTOMERID AND CC_REC_VER=(SELECT MAX(CC_REC_VER) FROM CUSTOMER_SCDB_FORMAT WHERE CC_CUST_ID=MIN_CUSTOMERID AND CC_EP_DATE IS NOT NULL));
	IF CPDEPDATE IS NOT NULL THEN
		SET @UPDATE_CUST_PER_CPDEPDATE=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.CUSTOMER_PERSONAL_DETAILS SET CPD_EP_DATE=','"',CPDEPDATE,'"',' WHERE CUSTOMER_ID=',MIN_CUSTOMERID));
		PREPARE UPDATE_CUST_PER_CPDEPDATE_STMT FROM @UPDATE_CUST_PER_CPDEPDATE;
		EXECUTE UPDATE_CUST_PER_CPDEPDATE_STMT;
	END IF;
	SET MIN_CUSTOMERID=MIN_CUSTOMERID+1;
	END WHILE;
	SET @UPDATECPDEMAIL=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.CUSTOMER_PERSONAL_DETAILS SET CPD_EMAIL=','"dhandapani.sattanathan@ssomens.com"'));
	PREPARE UPDATECPDEMAILSTMT FROM @UPDATECPDEMAIL;
	EXECUTE UPDATECPDEMAILSTMT;	
	DROP TABLE IF EXISTS TEMP_CUSTOMER_PERSONAL_DETAILS;
	SET @CREATE_TEMP_PERSONAL=(SELECT CONCAT('CREATE TABLE TEMP_CUSTOMER_PERSONAL_DETAILS AS SELECT * FROM ',DESTINATIONSCHEMA,'.CUSTOMER_PERSONAL_DETAILS'));
	PREPARE CREATE_TEMP_PERSONAL_STMT FROM @CREATE_TEMP_PERSONAL;
	EXECUTE CREATE_TEMP_PERSONAL_STMT;
SET CUSTOMER_COMMENTS=' ';
DROP TABLE IF EXISTS TEMP_CUSTOMER_ACCESS_COMMENT;
CREATE TABLE TEMP_CUSTOMER_ACCESS_COMMENT
(ID INTEGER PRIMARY KEY AUTO_INCREMENT,
CUSTOMERID INTEGER,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
UNIT_NO INTEGER,
ACCESS_COMMENTS TEXT);
INSERT INTO TEMP_CUSTOMER_ACCESS_COMMENT(FIRST_NAME,LAST_NAME,UNIT_NO,ACCESS_COMMENTS)
SELECT AC_FIRST_NAME,AC_LAST_NAME,AC_UNIT_NO,AC_COMMENTS FROM ACCESS_SCDB_FORMAT;
UPDATE TEMP_CUSTOMER_ACCESS_COMMENT SET LAST_NAME=FIRST_NAME WHERE LAST_NAME IS NULL;
SET MINACCESSID=(SELECT MIN(ID) FROM TEMP_CUSTOMER_ACCESS_COMMENT);
SET MAXACCESSID=(SELECT MAX(ID) FROM TEMP_CUSTOMER_ACCESS_COMMENT);
WHILE MINACCESSID<=MAXACCESSID DO
SET ACCESS_FNAME=(SELECT FIRST_NAME FROM TEMP_CUSTOMER_ACCESS_COMMENT WHERE ID=MINACCESSID);
SET ACCESS_LNAME=(SELECT LAST_NAME FROM TEMP_CUSTOMER_ACCESS_COMMENT WHERE ID=MINACCESSID);
SET ACCESS_UNITNO=(SELECT UNIT_NO FROM TEMP_CUSTOMER_ACCESS_COMMENT WHERE ID=MINACCESSID);
SET @UPDATETEMPACCESS=(SELECT CONCAT('UPDATE TEMP_CUSTOMER_ACCESS_COMMENT SET CUSTOMERID=(SELECT DISTINCT CC_CUST_ID FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_SCDB_FORMAT WHERE CC_FIRST_NAME=','"',ACCESS_FNAME,'"',' AND CC_LAST_NAME=','"',ACCESS_LNAME,'"',' AND CC_UNIT_NO=',ACCESS_UNITNO,') WHERE ID=',MINACCESSID));
PREPARE UPDATETEMPACCESSSTMT FROM @UPDATETEMPACCESS;
EXECUTE UPDATETEMPACCESSSTMT;
SET MINACCESSID=MINACCESSID+1;
END WHILE;
DROP TABLE IF EXISTS TEMP_CUSTOMER_PERSONAL;
CREATE TABLE TEMP_CUSTOMER_PERSONAL
(
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
CUSTOMER_ID INTEGER,
CED_REC_VER INTEGER,
GUESTFLAG CHAR(1),
COMMENTS TEXT);
SET @INSERTCUSTOMERPERSONAL=(SELECT CONCAT('INSERT INTO TEMP_CUSTOMER_PERSONAL(CUSTOMER_ID,CED_REC_VER,GUESTFLAG,COMMENTS)
SELECT CUSTOMER_ID,CED_REC_VER,CTD_GUEST_CARD,CC_COMMENTS FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS ORDER BY CUSTOMER_ID,CED_REC_VER'));
PREPARE INSERTCUSTOMERPERSONALSTMT FROM @INSERTCUSTOMERPERSONAL;
EXECUTE INSERTCUSTOMERPERSONALSTMT;
SET @INSERTCUSTOMERPERSONALGUEST=(SELECT CONCAT('INSERT INTO TEMP_CUSTOMER_PERSONAL(CUSTOMER_ID,CED_REC_VER,GUESTFLAG,COMMENTS)
SELECT CUSTOMER_ID,CED_REC_VER,CTD_GUEST_CARD,CC_COMMENTS FROM ',DESTINATIONSCHEMA,'.TEMP_GUEST_CUSTOMER_TERMINATION_DETAILS ORDER BY CUSTOMER_ID,CED_REC_VER'));
PREPARE INSERTCUSTOMERPERSONALGUESTSTMT FROM @INSERTCUSTOMERPERSONALGUEST;
EXECUTE INSERTCUSTOMERPERSONALGUESTSTMT;
SET MINCUSTID=MINCUSTOMERID;
SET MAXCUSTID=MAXCUSTOMERID;
WHILE MINCUSTID<=MAXCUSTID DO
		DROP TABLE IF EXISTS TEMP_CUSTOMER_COMMENTS_UPDATE;
		CREATE TABLE TEMP_CUSTOMER_COMMENTS_UPDATE(
		ID INTEGER PRIMARY KEY AUTO_INCREMENT,
		CUSTOMER_ID INTEGER,
		CED_REC_VER INTEGER,
		GUESTFLAG CHAR(1),
		COMMENTS TEXT);
		INSERT INTO TEMP_CUSTOMER_COMMENTS_UPDATE(CUSTOMER_ID,CED_REC_VER,GUESTFLAG,COMMENTS)
		SELECT CUSTOMER_ID,CED_REC_VER,GUESTFLAG,COMMENTS FROM TEMP_CUSTOMER_PERSONAL WHERE CUSTOMER_ID=MINCUSTID ORDER BY CUSTOMER_ID,CED_REC_VER;	
				SET MINRECVER=(SELECT MIN(CED_REC_VER) FROM TEMP_CUSTOMER_COMMENTS_UPDATE);
				SET MAXRECVER=(SELECT MAX(CED_REC_VER) FROM TEMP_CUSTOMER_COMMENTS_UPDATE);
					WHILE MINRECVER<=MAXRECVER DO
						DROP TABLE IF EXISTS TEMP_RECVER;
						CREATE TABLE TEMP_RECVER(ID INTEGER AUTO_INCREMENT PRIMARY KEY,COMMENTS TEXT);
						INSERT INTO TEMP_RECVER(COMMENTS)SELECT DISTINCT COMMENTS FROM TEMP_CUSTOMER_COMMENTS_UPDATE WHERE CED_REC_VER=MINRECVER;
						SET MINRECVERID=(SELECT MIN(ID)FROM TEMP_RECVER);
						SET MAXRECVERID=(SELECT MAX(ID) FROM TEMP_RECVER);
						WHILE MINRECVERID<=MAXRECVERID DO						
							SET MERGECOMMENTS=(SELECT COMMENTS FROM TEMP_RECVER WHERE ID=MINRECVERID);
							IF MERGECOMMENTS IS NULL THEN
								SET MERGECOMMENTS=' ';
							END IF;
							SET CUSTOMER_COMMENTS=(SELECT CONCAT(CUSTOMER_COMMENTS,'\n',MERGECOMMENTS));
							SET MINRECVERID=MINRECVERID+1;
						END WHILE;
					SET MINRECVER=MINRECVER+1;
					END WHILE;
					DROP TABLE IF EXISTS TEMP_ACCESS_COMMENTS;
					CREATE TABLE TEMP_ACCESS_COMMENTS
					(
					ID INTEGER PRIMARY KEY AUTO_INCREMENT,
					AC_COMMENTS TEXT);
					INSERT INTO TEMP_ACCESS_COMMENTS(AC_COMMENTS)
					SELECT DISTINCT ACCESS_COMMENTS FROM TEMP_CUSTOMER_ACCESS_COMMENT WHERE CUSTOMERID=MINCUSTID;
					SET AC_MINID=(SELECT MIN(ID) FROM TEMP_ACCESS_COMMENTS);
					SET AC_MAXID=(SELECT MAX(ID) FROM TEMP_ACCESS_COMMENTS);
					WHILE AC_MINID<=AC_MAXID DO
					SET ACCOMMENTS=(SELECT AC_COMMENTS FROM TEMP_ACCESS_COMMENTS WHERE ID =AC_MINID);
					IF ACCOMMENTS IS NULL THEN
						SET ACCOMMENTS=' ';
					END IF;
					SET AC_MINID=AC_MINID+1;
					END WHILE;
					IF AC_MINID IS NOT NULL THEN
					SET CUSTOMER_COMMENTS=(SELECT CONCAT(CUSTOMER_COMMENTS,'\n',ACCOMMENTS));	
					ELSE
					SET CUSTOMER_COMMENTS=CUSTOMER_COMMENTS;
					END IF;
					SET @PERSONALCOMMENTS=CUSTOMER_COMMENTS;
				SET @UPDATECPD=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.CUSTOMER_PERSONAL_DETAILS SET CPD_COMMENTS=@PERSONALCOMMENTS WHERE CUSTOMER_ID=',MINCUSTID));
				PREPARE UPDATECPDSTMT FROM @UPDATECPD;
				EXECUTE UPDATECPDSTMT;
			SET CUSTOMER_COMMENTS=' ';
      SET @PERSONALCOMMENTS=NULL;
SET MINCUSTID=MINCUSTID+1;
END WHILE;
SET @UPDATECPDCOMMENTS=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.CUSTOMER_PERSONAL_DETAILS SET CPD_COMMENTS=NULL WHERE CPD_COMMENTS=','" \n"'));
PREPARE UPDATECPDCOMMENTSSTMT FROM @UPDATECPDCOMMENTS;
EXECUTE UPDATECPDCOMMENTSSTMT;
SET END_TIME=(SELECT CURTIME());
SET DURATION=(SELECT TIMEDIFF(END_TIME,START_TIME));
IF PART=1 THEN
DROP TABLE IF EXISTS TEMP_PERSONAL_PART1;
CREATE TABLE TEMP_PERSONAL_PART1(ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,SPLITTED_DURATION TIME);
INSERT INTO TEMP_PERSONAL_PART1(SPLITTED_DURATION)VALUES(DURATION);
ELSE
INSERT INTO TEMP_PERSONAL_PART1(SPLITTED_DURATION)VALUES(DURATION);
END IF;
DROP TABLE IF EXISTS TEMP_PERSONAL_PART2;
CREATE TABLE TEMP_PERSONAL_PART2(ID INTEGER PRIMARY KEY AUTO_INCREMENT,SPLITTED_DURATION TIME);
SET INITTIME='00:00:00';
SET MINDURATIONID=(SELECT MIN(ID) FROM TEMP_PERSONAL_PART1);
SET MAXDURATIONID=(SELECT MAX(ID)FROM TEMP_PERSONAL_PART1);
WHILE MINDURATIONID<=MAXDURATIONID DO
SET INITTIME=(SELECT ADDTIME(INITTIME,(SELECT SPLITTED_DURATION FROM TEMP_PERSONAL_PART1 WHERE ID=MINDURATIONID)));
SET MINDURATIONID=MINDURATIONID+1;
END WHILE;
INSERT INTO TEMP_PERSONAL_PART2(SPLITTED_DURATION)VALUES(INITTIME);
COMMIT;
END;
