-- version:0.4 -- sdate:09/06/2014 -- edate:09/06/2014 -- issue:566 -- COMMENT NO:12 --desc:IMPLEMENTED ROLL BACK AND COMMIT --doneby:DHIVYA.A
-- version:0.3 -- sdate:04/04/2014 -- edate:04/04/2014 -- issue:797 -- COMMENT NO:4 --desc:CHANGING CUSTOMER_TERMINATION_DETAILS AS CUSTOMER_LP_DETAILS --doneby:BHAVANI.R
-- version:0.2 -- sdate:17/03/2014 -- edate:17/03/2014 -- issue:765 --desc:droped temp table --doneby:RL
--version:0.1--sdate:21/02/2014 --edate:21/02/2014 --issue:750 -desc:CALL ALL CUSTOMER SP IN SINGLE  done by:dhivya



DROP PROCEDURE IF EXISTS SP_ALL_CUSTOMER_MIG_INSERT;
CREATE PROCEDURE SP_ALL_CUSTOMER_MIG_INSERT(IN SOURCESCHEMA VARCHAR(50),IN DESTINATIONSCHEMA VARCHAR(50),IN MIGUSERSTAMP VARCHAR(100))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
END;
START TRANSACTION;
CALL SP_TEMP_CUSTOMER_SCDB_FORMAT(SOURCESCHEMA,DESTINATIONSCHEMA);
CALL SP_MIG_CUSTOMER_INSERT(SOURCESCHEMA,DESTINATIONSCHEMA,MIGUSERSTAMP);
CALL SP_MIG_CUSTOMER_ENTRY_DETAILS(SOURCESCHEMA,DESTINATIONSCHEMA,MIGUSERSTAMP);
CALL SP_MIG_CUSTOMER_LP_DETAILS(SOURCESCHEMA,DESTINATIONSCHEMA,MIGUSERSTAMP);
CALL SP_MIG_CUSTOMER_FEE_INSERT(SOURCESCHEMA,DESTINATIONSCHEMA,MIGUSERSTAMP);
CALL SP_CUSTOMER_PERSONAL_DETAILS_INSERT_PART1(SOURCESCHEMA,DESTINATIONSCHEMA,MIGUSERSTAMP,1,1,100);
CALL SP_CUSTOMER_PERSONAL_DETAILS_INSERT_PART1(SOURCESCHEMA,DESTINATIONSCHEMA,MIGUSERSTAMP,2,101,(SELECT MAX(CUSTOMER_ID) FROM TEMP_CUSTOMER_PERSONAL_DETAILS));
CALL SP_CUSTOMER_PERSONAL_DETAILS_INSERT_PART2(SOURCESCHEMA,DESTINATIONSCHEMA,MIGUSERSTAMP);
CALL SP_TEMP_CUSTOMER_ACCESS_CARD_DETAILS(SOURCESCHEMA,DESTINATIONSCHEMA);
CALL SP_CUSTOMER_ACCESS_CARD_DETAILS(SOURCESCHEMA,DESTINATIONSCHEMA,MIGUSERSTAMP);
COMMIT;
END;

