-- ver 0.9 sdate:11/07/2014 edate:11/07/2014 issue no:345 COMMENT:732 desc:ADDED DEFAULT 1 CONSTRAINT FOR ULD_MAX_TIMES HEADER done by:DHIVYA.A
-- ver 0.8 sdate:10/07/2014 edate:10/07/2014 issue no:345 COMMENT:728 desc:ADDED ULD_MAX_TIMES HEADER done by:DHIVYA.A
-- ver 0.6 sdate:04/04/2014 edate:04/04/2014 issue no:797 COMMENT:4 desc:changed customer_termination_details AS CUSTOMER_LP_DETAILS done by:BHAVANI.R
-- ver 0.5 sdate:21/03/2014 edate:27/03/2014 issue no:765 desc:changed customer_termination_details table dynamically done by:DHIVYA
-- version:0.7 -- sdate:17/03/2014 -- edate:17/03/2014 -- issue:765 --desc:droped temp table --doneby:RL
 --version:0.6 --sdate:25/02/2014 --edate:26/02/2014 --issue:750 comment:#30 -desc:added uld_id header and source timestamp by:dhivya
--version:0.5--sdate:20/02/2014 --edate:20/02/2014 --issue:750 -desc:added preaudit and post audit queries done by:dhivya
--VER 0.4 STARTDATE:06/02/2014 ENDDATE:06/02/2014 ISSUE NO:594 COMMENT :#86 DESC:REMOVED TERMINATE='X' FOR GUEST CARDS DONE BY:DHIVYA.A
--VER 0.3 STARTDATE:29/01/2014 ENDDATE:29/01/2014 ISSUE NO:594 COMMENT :#70 DESC:CUSTOMER_ENTRY_DETAILS TABLE S UPDATED AS PER STIME AND ETIME DATATYPE UPDATION DONE BY:DHIVYA.A
--VER 0.2 STARTDATE:21/01/2014 ENDDATE:22/01/2014 ISSUE NO:594 COMMENT :#50 DESC:ALL UPDATION DONE IN THE SPLITTED TABLE ITSELF NOT IN THE CUSTOMER SCDB FORMAT TABLE DONE BY:DHIVYA


DROP PROCEDURE IF EXISTS SP_MIG_CUSTOMER_LP_DETAILS;
CREATE PROCEDURE SP_MIG_CUSTOMER_LP_DETAILS(IN SOURCESCHEMA VARCHAR(50),IN DESTINATIONSCHEMA VARCHAR(50),IN MIGUSERSTAMP VARCHAR(100))
BEGIN
    -- VARIABLE DECLARATION
    DECLARE MAX_CUSTOMER INT;
     DECLARE MIN_CUSTOMER INT;
    DECLARE RE INT;
    DECLARE MAX_CTD_ID INT;
    DECLARE MIN_CTD_ID INT;
    DECLARE MIN_REC_VER INT;
    DECLARE MAX_REC_VER INT;
    DECLARE CUSTOMERID INT;
    DECLARE RECHECKCUSTOMER INTEGER;
    DECLARE MAX_GUEST_CTD_ID INT;
    DECLARE MIN_GUEST_CTD_ID INT;
    DECLARE CUSTID INT;
    DECLARE STARTDATE DATE;
    DECLARE ENDDATE DATE;
    DECLARE PRETERMINATEDATE DATE;
    DECLARE RECVER INTEGER;
    DECLARE GUEST_RECVER INTEGER;
    DECLARE ACTIVE_REC_VER INTEGER;
    DECLARE MIN_RECHECKINID INTEGER;
    DECLARE MAX_RECHECKINID INTEGER;
	DECLARE TIME_MAX_REC_VER INTEGER;
	DECLARE TIME_PRETERMINATE_DATE DATE;
	DECLARE START_TIME TIME;
	DECLARE END_TIME TIME;
	DECLARE DURATION TIME;
	DECLARE NONRECHECKCUSTOMER INTEGER;
	DECLARE PREDATE DATE;
	DECLARE TIME_PREDATE DATE;
	DECLARE TERMINATION_CUSTOMERID INTEGER;
	DECLARE CANCELDATE DATE;
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
	ROLLBACK;
	END;
	START TRANSACTION;
	
		SET @LOGIN_ID=(SELECT CONCAT('SELECT ULD_ID INTO @USERSTAMPID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=','"',MIGUSERSTAMP,'"'));
	PREPARE LOGINID FROM @LOGIN_ID;
	EXECUTE LOGINID;
	
	 
	
  SET START_TIME=(SELECT CURTIME());
  	SET @PREDATEENTRY=NULL;
    SET @PRE_TERMDATE=NULL;
  
-- TEMP TABLE FOR CUSTOMER_TERMINATION_DETAILS
SET @DRTEMPCUSTERMINATIONDETAILS=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS'));
PREPARE DROPTEMPCUSTTERMSTMT FROM @DRTEMPCUSTERMINATIONDETAILS;
EXECUTE DROPTEMPCUSTTERMSTMT;
-- DEALLOCATE PREPARE DROPTEMPTERSTMT;

SET @CRTEMPCUSTERMDETAILS=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS(
CTD_ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
CUSTOMER_ID INTEGER NOT NULL,
UASD_ID INTEGER,
CED_REC_VER INTEGER,
CTD_STARTDATE DATE NOT NULL,
CTD_ENDDATE DATE NOT NULL,
CTD_PRETERMINATEDATE DATE ,
CTD_TERMINATE CHAR(1),
CED_RECHECKIN CHAR(1),
CTD_GUEST_CARD CHAR(1),
RENT_AMOUNT DECIMAL(7,2),
DEPOSIT DECIMAL(7,2),
PROCESSING_FEE DECIMAL(7,2),
AIRCON_FIXED_FEE DECIMAL(7,2),
ELECTRICITY_CAP DECIMAL(7,2),
DRYCLEAN_FEE DECIMAL(7,2),
AIRCON_QUARTERLY_FEE DECIMAL(7,2),
CHECKOUT_CLEANING_FEE DECIMAL(7,2),
ULD_ID INTEGER NOT NULL,
CTD_TIMESTAMP VARCHAR(50) NOT NULL,
CC_COMMENTS TEXT)'));
PREPARE CRTEMPCUSTERMDETAILSSTMT FROM @CRTEMPCUSTERMDETAILS;
EXECUTE CRTEMPCUSTERMDETAILSSTMT;
-- DEALLOCATE PREPARE CRTEMPCUSTERMDETAILSSTMT;

-- TEMP TABLE FOR TEMP_TERMINATION_DETAILS
SET @DRTEMPTERMINATIONDETAILS=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_TERMINATION_DETAILS'));
PREPARE DROPTEMPTERSTMT FROM @DRTEMPTERMINATIONDETAILS;
EXECUTE DROPTEMPTERSTMT;
-- DEALLOCATE PREPARE DROPTEMPTERSTMT;

SET @CRTEMPTERMINATIONDETAILS=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.TEMP_TERMINATION_DETAILS(
CTD_ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
CUSTOMER_ID INTEGER NOT NULL,
UASD_ID INTEGER,
CED_REC_VER INTEGER,
CTD_STARTDATE DATE NOT NULL,
CTD_ENDDATE DATE NOT NULL,
CTD_PRETERMINATEDATE DATE ,
CTD_TERMINATE CHAR(1),
CED_RECHECKIN CHAR(1),
CTD_GUEST_CARD CHAR(1),
RENT_AMOUNT DECIMAL(7,2),
DEPOSIT DECIMAL(7,2),
PROCESSING_FEE DECIMAL(7,2),
AIRCON_FIXED_FEE DECIMAL(7,2),
ELECTRICITY_CAP DECIMAL(7,2),
DRYCLEAN_FEE DECIMAL(7,2),
AIRCON_QUARTERLY_FEE DECIMAL(7,2),
CHECKOUT_CLEANING_FEE DECIMAL(7,2),
ULD_ID INTEGER NOT NULL,
CTD_TIMESTAMP VARCHAR(50) NOT NULL,
CC_COMMENTS TEXT)'));
PREPARE CRTERMTEMPSTMT FROM @CRTEMPTERMINATIONDETAILS;
EXECUTE CRTERMTEMPSTMT;
-- DEALLOCATE PREPARE CRTERMTEMPSTMT;

--TEMP TABLE FOR TEMP_GUEST_CUSTOMER_TERMINATION_DETAILS
SET @DRTEMPGUESTTERMDETAILS=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_GUEST_CUSTOMER_TERMINATION_DETAILS'));
PREPARE DRTERMGUESTTEMPSTMT FROM @DRTEMPGUESTTERMDETAILS;
EXECUTE DRTERMGUESTTEMPSTMT;
-- DEALLOCATE PREPARE DRTERMGUESTTEMPSTMT;

SET @CRTEMPGUESTTERMDETAILS=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.TEMP_GUEST_CUSTOMER_TERMINATION_DETAILS(
CTD_ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
CUSTOMER_ID INTEGER NOT NULL,
UASD_ID INTEGER,
CED_REC_VER INTEGER,
CTD_STARTDATE DATE NOT NULL,
CTD_ENDDATE DATE NOT NULL,
CTD_PRETERMINATEDATE DATE ,
CTD_TERMINATE CHAR(1),
CTD_GUEST_CARD CHAR(1),
ULD_ID INTEGER NOT NULL,
CTD_TIMESTAMP VARCHAR(50) NOT NULL,
CC_COMMENTS TEXT)'));
PREPARE CRTERMGUESTTEMPSTMT FROM @CRTEMPGUESTTERMDETAILS;
EXECUTE CRTERMGUESTTEMPSTMT;
-- DEALLOCATE PREPARE CRTERMGUESTTEMPSTMT;

-- INSERT QUERY FOR TEMP_TERMINATION_DETAILS
SET @INSERTTEMPTERM=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_TERMINATION_DETAILS(CUSTOMER_ID,UASD_ID,CED_REC_VER,CTD_STARTDATE,CTD_ENDDATE,CTD_PRETERMINATEDATE,CTD_TERMINATE,CTD_GUEST_CARD,RENT_AMOUNT,DEPOSIT,PROCESSING_FEE,AIRCON_FIXED_FEE,ELECTRICITY_CAP,DRYCLEAN_FEE,AIRCON_QUARTERLY_FEE,CHECKOUT_CLEANING_FEE,ULD_ID,CTD_TIMESTAMP,CC_COMMENTS)
SELECT M.CC_CUST_ID,U.UASD_ID,M.CC_REC_VER,M.CC_STARTDATE,M.CC_ENDDATE,M.CC_PRE_TERMINATE_DATE,M.CC_TERMINATE,M.CC_GUEST_CARD_NO,M.CC_RENT_AMOUNT,M.CC_DEPOSIT,M.CC_PROCESSING_FEE,M.CC_AIRCON_FIXED_FEE,M.CC_ELECTRICITY_CAP,M.CC_DRYCLEAN_FEE,M.CC_AIRCON_QUARTERLY_FEE,M.CC_CHECKOUT_CLEANING_FEE,ULD.ULD_ID,M.TIMESTAMP,M.CC_COMMENTS FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_SCDB_FORMAT M,',DESTINATIONSCHEMA,'.UNIT_ACCESS_STAMP_DETAILS U,',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS ULD WHERE ULD.ULD_LOGINID=M.USERSTAMP AND U.UASD_ACCESS_CARD=M.CC_CARD_NO AND M.CC_GUEST_CARD_NO IS NULL ORDER BY M.CC_CUST_ID,M.CC_REC_VER'));
PREPARE INSERTTEMPTERMSTMT FROM @INSERTTEMPTERM;
EXECUTE INSERTTEMPTERMSTMT;
-- DEALLOCATE PREPARE INSERTTEMPTERMSTMT;

SET @INSERTGUESTTEMPTERM=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_TERMINATION_DETAILS(CUSTOMER_ID,CED_REC_VER,CTD_STARTDATE,CTD_ENDDATE,CTD_PRETERMINATEDATE,CTD_TERMINATE,CTD_GUEST_CARD,RENT_AMOUNT,DEPOSIT,PROCESSING_FEE,AIRCON_FIXED_FEE,ELECTRICITY_CAP,DRYCLEAN_FEE,AIRCON_QUARTERLY_FEE,CHECKOUT_CLEANING_FEE,ULD_ID,CTD_TIMESTAMP,CC_COMMENTS)
SELECT M.CC_CUST_ID,M.CC_REC_VER,M.CC_STARTDATE,M.CC_ENDDATE,M.CC_PRE_TERMINATE_DATE,M.CC_TERMINATE,M.CC_GUEST_CARD_NO,M.CC_RENT_AMOUNT,M.CC_DEPOSIT,M.CC_PROCESSING_FEE,M.CC_AIRCON_FIXED_FEE,M.CC_ELECTRICITY_CAP,M.CC_DRYCLEAN_FEE,M.CC_AIRCON_QUARTERLY_FEE,M.CC_CHECKOUT_CLEANING_FEE,ULD.ULD_ID,M.TIMESTAMP,M.CC_COMMENTS FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_SCDB_FORMAT M,',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS ULD WHERE M.CC_CARD_NO IS NULL AND M.USERSTAMP=ULD.ULD_LOGINID AND M.CC_GUEST_CARD_NO IS NULL ORDER BY M.CC_CUST_ID,M.CC_REC_VER'));
PREPARE INSERTGUESTTEMPTERMSTMT FROM @INSERTGUESTTEMPTERM;
EXECUTE INSERTGUESTTEMPTERMSTMT;
-- DEALLOCATE PREPARE INSERTGUESTTEMPTERMSTMT;


-- INSERT QUERY FOR TEMP_CUSTOMER_TERMINATION_DETAILS
SET @INSERTTEMPCUSTERM=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS(CUSTOMER_ID,UASD_ID,CED_REC_VER,CTD_STARTDATE,CTD_ENDDATE,CTD_PRETERMINATEDATE,CTD_TERMINATE,CTD_GUEST_CARD,RENT_AMOUNT,DEPOSIT,PROCESSING_FEE,AIRCON_FIXED_FEE,ELECTRICITY_CAP,DRYCLEAN_FEE,AIRCON_QUARTERLY_FEE,CHECKOUT_CLEANING_FEE,ULD_ID,CTD_TIMESTAMP,CC_COMMENTS)
SELECT CUSTOMER_ID,UASD_ID,CED_REC_VER,CTD_STARTDATE,CTD_ENDDATE,CTD_PRETERMINATEDATE,CTD_TERMINATE,CTD_GUEST_CARD,RENT_AMOUNT,DEPOSIT,PROCESSING_FEE,AIRCON_FIXED_FEE,ELECTRICITY_CAP,DRYCLEAN_FEE,AIRCON_QUARTERLY_FEE,CHECKOUT_CLEANING_FEE,ULD_ID,CTD_TIMESTAMP,CC_COMMENTS FROM ',DESTINATIONSCHEMA,'.TEMP_TERMINATION_DETAILS ORDER BY CUSTOMER_ID,CED_REC_VER'));
PREPARE INSERTTEMPCUSTERMSTMT FROM @INSERTTEMPCUSTERM;
EXECUTE INSERTTEMPCUSTERMSTMT;
-- DEALLOCATE PREPARE INSERTTEMPCUSTERMSTMT;

-- INSERT QUERY FOR TEMP_GUEST_CUSTOMER_TERMINATION_DETAILS
SET @INSERTTEMPGUESTCUSTERM=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_GUEST_CUSTOMER_TERMINATION_DETAILS(CUSTOMER_ID,UASD_ID,CED_REC_VER,CTD_STARTDATE,CTD_ENDDATE,CTD_PRETERMINATEDATE,CTD_TERMINATE,CTD_GUEST_CARD,ULD_ID,CTD_TIMESTAMP,CC_COMMENTS)
SELECT M.CC_CUST_ID,U.UASD_ID,M.CC_REC_VER,M.CC_STARTDATE,M.CC_ENDDATE,M.CC_PRE_TERMINATE_DATE,M.CC_TERMINATE,M.CC_GUEST_CARD_NO,ULD.ULD_ID,M.TIMESTAMP,M.CC_COMMENTS FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_SCDB_FORMAT M,',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS ULD,',DESTINATIONSCHEMA,'.UNIT_ACCESS_STAMP_DETAILS U WHERE U.UASD_ACCESS_CARD=M.CC_CARD_NO AND ULD.ULD_LOGINID=M.USERSTAMP AND M.CC_GUEST_CARD_NO IS NOT NULL ORDER BY M.CC_CUST_ID,M.CC_REC_VER'));
PREPARE INSERTTEMPGUESTCUSTERMSTMT FROM @INSERTTEMPGUESTCUSTERM;
EXECUTE INSERTTEMPGUESTCUSTERMSTMT;
-- DEALLOCATE PREPARE INSERTTEMPGUESTCUSTERMSTMT;

SET @INSERTNULLCARDCUSTOMER=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_GUEST_CUSTOMER_TERMINATION_DETAILS(CUSTOMER_ID,CED_REC_VER,CTD_STARTDATE,CTD_ENDDATE,CTD_PRETERMINATEDATE,CTD_TERMINATE,CTD_GUEST_CARD,ULD_ID,CTD_TIMESTAMP,CC_COMMENTS)
SELECT M.CC_CUST_ID,M.CC_REC_VER,M.CC_STARTDATE,M.CC_ENDDATE,M.CC_PRE_TERMINATE_DATE,M.CC_TERMINATE,M.CC_GUEST_CARD_NO,ULD.ULD_ID,M.TIMESTAMP,M.CC_COMMENTS FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_SCDB_FORMAT M,',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS ULD WHERE M.CC_CARD_NO IS NULL AND ULD.ULD_LOGINID=M.USERSTAMP AND  M.CC_GUEST_CARD_NO IS NOT NULL ORDER BY M.CC_CUST_ID,M.CC_REC_VER'));
PREPARE INSERTNULLCARDCUSTOMERSTMT FROM @INSERTNULLCARDCUSTOMER;
EXECUTE INSERTNULLCARDCUSTOMERSTMT;
-- DEALLOCATE PREPARE INSERTNULLCARDCUSTOMERSTMT;

SET @UPTEMPGUESTTERM=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_GUEST_CUSTOMER_TERMINATION_DETAILS SET CTD_TERMINATE=NULL'));
PREPARE UPTEMPGUESTTERMSTMT FROM @UPTEMPGUESTTERM;
EXECUTE UPTEMPGUESTTERMSTMT;
-- DEALLOCATE PREPARE UPTEMPGUESTTERMSTMT;

SET @UPTEMPTERM=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS SET CTD_TERMINATE=NULL'));
PREPARE UPTEMPTERMSTMT FROM @UPTEMPTERM;
EXECUTE UPTEMPTERMSTMT;
-- DEALLOCATE PREPARE UPTEMPTERMSTMT;
  
  
    SET @MAX_CUSTOMER_STMT =(SELECT CONCAT('SELECT MAX(CUSTOMER_ID)INTO @MAXID FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS'));
	PREPARE MAXCUSTOMERSTMT FROM @MAX_CUSTOMER_STMT;
	EXECUTE MAXCUSTOMERSTMT;
	SET MAX_CUSTOMER=@MAXID;
    SET @MIN_CUSTOMER_STMT=(SELECT CONCAT('SELECT MIN(CUSTOMER_ID)INTO @MINID FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS'));
	PREPARE MINCUSTOMERSTMT FROM @MIN_CUSTOMER_STMT;
	EXECUTE MINCUSTOMERSTMT;
	SET MIN_CUSTOMER=@MINID;
  
    WHILE MIN_CUSTOMER<= MAX_CUSTOMER DO
	
	SET @CHECK_CUST_ID_STMT=(SELECT CONCAT('SELECT DISTINCT CUSTOMER_ID INTO @CHECK_CUSTID FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS WHERE CUSTOMER_ID=',MIN_CUSTOMER));
	PREPARE CHECKCUSTIDSTMT FROM @CHECK_CUST_ID_STMT;
	EXECUTE CHECKCUSTIDSTMT;
	SET TERMINATION_CUSTOMERID=@CHECK_CUSTID;
	
	IF TERMINATION_CUSTOMERID IS NOT NULL THEN
    SET @MAX_CTD_ID_STMT=(SELECT CONCAT('SELECT MAX(CTD_ID) INTO @MAXCTDID FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS WHERE CUSTOMER_ID=',MIN_CUSTOMER));
	PREPARE MAXCTDIDSTMT FROM @MAX_CTD_ID_STMT;
	EXECUTE MAXCTDIDSTMT;
	SET MAX_CTD_ID=@MAXCTDID;
    SET @MIN_CTD_ID_STMT=(SELECT CONCAT('SELECT MIN(CTD_ID) INTO @MINCTDID FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS WHERE CUSTOMER_ID=',MIN_CUSTOMER ));
	PREPARE MINCTDIDSTMT FROM @MIN_CTD_ID_STMT;
	EXECUTE MINCTDIDSTMT;
	SET MIN_CTD_ID=@MINCTDID;
  

    SET RE=1;
        WHILE MIN_CTD_ID<=MAX_CTD_ID DO
      
			-- UPDATE RECVER IN TEMP_CUSTOMER_TERMINATION_DETAILS
			
            SET @UPCUSTTERM=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS SET CED_REC_VER=',RE,' WHERE CTD_ID=',MIN_CTD_ID));
			PREPARE UPCUSTTERMSTMT FROM @UPCUSTTERM;
			EXECUTE UPCUSTTERMSTMT;
			
            SET @CUSTIDSTMT=(SELECT CONCAT('SELECT CUSTOMER_ID INTO @TERMCUSTID FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS WHERE CTD_ID=',MIN_CTD_ID));
			PREPARE TERMCUSTIDSTMT FROM @CUSTIDSTMT;
			EXECUTE TERMCUSTIDSTMT;
			SET CUSTID=@TERMCUSTID;
            SET @RECVERSTMT=(SELECT CONCAT('SELECT CED_REC_VER INTO @TERMRECVER FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS WHERE CTD_ID=',MIN_CTD_ID));
			PREPARE TERMRECVERSTMT FROM @RECVERSTMT;
			EXECUTE TERMRECVERSTMT;
			SET RECVER=@TERMRECVER;
			
			-- UPDATE RECHECKIN FLAG IN TEMP_CUSTOMER_TERMINATION_DETAILS
			
            SET @UPCUSTERMRECRECHECKIN=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS SET CED_RECHECKIN=(SELECT CED_RECHECKIN FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_ENTRY_DETAILS WHERE
            CUSTOMER_ID=',CUSTID,' AND CED_REC_VER=',RECVER,')WHERE CTD_ID=',MIN_CTD_ID));
			PREPARE UPCUSTERMRECHECKINSTMT FROM @UPCUSTERMRECRECHECKIN;
			EXECUTE UPCUSTERMRECHECKINSTMT;
			SET RE=RE+1;
            SET MIN_CTD_ID=MIN_CTD_ID+1;
            END WHILE;
          
			-- TEMP TABLE FOR TEMP_RECHECKIN_CUSTOMER FOR PUTTING TERMINATE COLUMN AS 'X'
            SET @DRTEMPRECHECKINCUS=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_RECHECKIN_CUSTOMER'));
			PREPARE DR_TEMP_CUS_STMT FROM @DRTEMPRECHECKINCUS;
			EXECUTE DR_TEMP_CUS_STMT;
			
            SET @CRTEMPRECHECKINCUS=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.TEMP_RECHECKIN_CUSTOMER(ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,CUSTOMER_ID INTEGER,RECHECK_REC_VER INTEGER)'));
			PREPARE CRTEMPRECHECKCUSSTMT FROM @CRTEMPRECHECKINCUS;
			EXECUTE CRTEMPRECHECKCUSSTMT;
			
            SET @INSERTTEMPRECHECKIN=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_RECHECKIN_CUSTOMER(CUSTOMER_ID,RECHECK_REC_VER) SELECT CUSTOMER_ID,CED_REC_VER FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS WHERE CUSTOMER_ID=',MIN_CUSTOMER,' AND CED_RECHECKIN=','"X"'));
			PREPARE INSERTTEMPRECHECKINSTMT FROM @INSERTTEMPRECHECKIN;
			EXECUTE INSERTTEMPRECHECKINSTMT;

		-- IF THE DATA NOT IN THE TEMP_RECHECKIN_CUSTOMER THAT CUSTOMER S NOT A RECHECKIN CUSTOMER 
		SET @COUNTRECHECKINCUS=(SELECT CONCAT('SELECT COUNT(*)INTO @COUNTRECHECKCUS FROM ',DESTINATIONSCHEMA,'.TEMP_RECHECKIN_CUSTOMER'));
		PREPARE COUNTRECHECKINCUSSTMT FROM @COUNTRECHECKINCUS;
		EXECUTE COUNTRECHECKINCUSSTMT;
		SET NONRECHECKCUSTOMER=@COUNTRECHECKCUS;
		
        IF NONRECHECKCUSTOMER=0 THEN
            SET @ACTIVERECVER=(SELECT CONCAT('SELECT MAX(CED_REC_VER)INTO @TERM_ACTIVE_REC_VER FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS WHERE CUSTOMER_ID=',MIN_CUSTOMER,' AND IF(CTD_PRETERMINATEDATE IS NOT NULL,CTD_PRETERMINATEDATE>CTD_STARTDATE,CTD_ENDDATE>CTD_STARTDATE)AND IF(CTD_PRETERMINATEDATE IS NOT NULL,CTD_PRETERMINATEDATE>CURDATE(),CTD_ENDDATE>CURDATE())'));
			PREPARE ACTIVERECVERSTMT FROM @ACTIVERECVER;
			EXECUTE ACTIVERECVERSTMT;
			SET ACTIVE_REC_VER=@TERM_ACTIVE_REC_VER;
			
                IF ACTIVE_REC_VER IS NULL THEN
                    SET @MAXRECVER=(SELECT CONCAT('SELECT MAX(CED_REC_VER)INTO @TERM_MAX_REC_VER FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS WHERE CUSTOMER_ID=',MIN_CUSTOMER,' AND IF(CTD_PRETERMINATEDATE IS NOT NULL,CTD_PRETERMINATEDATE>CTD_STARTDATE,CTD_ENDDATE>=CTD_STARTDATE)AND IF(CTD_PRETERMINATEDATE IS NOT NULL,CTD_PRETERMINATEDATE<=CURDATE(),CTD_ENDDATE<=CURDATE())'));
					PREPARE MAXRECVERSTMT FROM @MAXRECVER;
					EXECUTE MAXRECVERSTMT;
					SET MAX_REC_VER=@TERM_MAX_REC_VER;
                        IF MAX_REC_VER IS NOT NULL THEN
						SET @SETCANCELDATE=(SELECT CONCAT('SELECT CED_CANCEL_DATE INTO @CDATE FROM ',DESTINATIONSCHEMA,'.CUSTOMER_ENTRY_DETAILS WHERE CUSTOMER_ID=',MIN_CUSTOMER,' AND CED_REC_VER=',MAX_REC_VER));
						PREPARE SETCANCELDATESTMT FROM @SETCANCELDATE;
						EXECUTE SETCANCELDATESTMT;
						SET CANCELDATE=@CDATE;
						IF CANCELDATE IS NULL THEN
						SET @UPDATETERMDETAILS=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS SET CTD_TERMINATE=','"X"',' WHERE CUSTOMER_ID=',MIN_CUSTOMER,' AND CED_REC_VER=',MAX_REC_VER));
						PREPARE UPDATETERMDETSTMT FROM @UPDATETERMDETAILS;
						EXECUTE UPDATETERMDETSTMT;
						END IF;
                        END IF;
                END IF;
      
        END IF;
		
		SET @CHECKRECHECKCUS=(SELECT CONCAT('SELECT COUNT(*)INTO @CHECKRECHECKCUS FROM ',DESTINATIONSCHEMA,'.TEMP_RECHECKIN_CUSTOMER '));
		PREPARE CHECKRECHECKCUSSTMT FROM @CHECKRECHECKCUS;
		EXECUTE CHECKRECHECKCUSSTMT;
		SET RECHECKCUSTOMER=@CHECKRECHECKCUS;
		
        IF RECHECKCUSTOMER>=1 THEN
        SET @MINRECHECKINID=(SELECT CONCAT('SELECT MIN(ID)INTO @MINRECHECKID FROM ',DESTINATIONSCHEMA,'.TEMP_RECHECKIN_CUSTOMER'));
		PREPARE MINRECHECKINIDSTMT FROM @MINRECHECKINID;
		EXECUTE MINRECHECKINIDSTMT;
		SET MIN_RECHECKINID=@MINRECHECKID;
        SET @MAXRECHECKINID=(SELECT CONCAT('SELECT MAX(ID)INTO @MAXRECHECKINID FROM ',DESTINATIONSCHEMA,'.TEMP_RECHECKIN_CUSTOMER'));
		PREPARE MAXRECHECKINIDSTMT FROM @MAXRECHECKINID;
		EXECUTE MAXRECHECKINIDSTMT;
		SET MAX_RECHECKINID=@MAXRECHECKINID;
            WHILE MIN_RECHECKINID<=MAX_RECHECKINID DO
              
                    SET @MAXRECVER=(SELECT CONCAT('SELECT MAX(CED_REC_VER)INTO @MAXTERMID FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS WHERE CUSTOMER_ID=',MIN_CUSTOMER,' AND CED_REC_VER<(SELECT RECHECK_REC_VER FROM ',DESTINATIONSCHEMA,'.TEMP_RECHECKIN_CUSTOMER WHERE ID=',MIN_RECHECKINID,') AND IF(CTD_PRETERMINATEDATE IS NOT NULL,CTD_PRETERMINATEDATE>CTD_STARTDATE,CTD_ENDDATE>CTD_STARTDATE)AND IF(CTD_PRETERMINATEDATE IS NOT NULL,CTD_PRETERMINATEDATE<=CURDATE(),CTD_ENDDATE<=CURDATE())'));
					PREPARE MAXRECVERSTMT FROM @MAXRECVER;
					EXECUTE MAXRECVERSTMT;
					SET MAX_REC_VER=@MAXTERMID;
                        IF MAX_REC_VER>=1 THEN
                            SET @UPCUSTERMDTL=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS SET CTD_TERMINATE=','"X"','WHERE CUSTOMER_ID=',MIN_CUSTOMER,' AND CED_REC_VER=',MAX_REC_VER));
							PREPARE UPCUSTERMDTLSTMT FROM @UPCUSTERMDTL;
							EXECUTE UPCUSTERMDTLSTMT;
						END IF;
							-- CUSTOMER_ENTRY_DETAILS TIME PROFILE UPDATION
							SET @CUSPRETERMINTEDATE=(SELECT CONCAT('SELECT CTD_PRETERMINATEDATE INTO @PRE_TERMDATE FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS WHERE CUSTOMER_ID=',MIN_CUSTOMER,' AND CTD_GUEST_CARD IS NULL AND CED_REC_VER=',MAX_REC_VER,' AND CTD_PRETERMINATEDATE!=','" "'));
							PREPARE CUSPRETERMINTEDATESTMT FROM @CUSPRETERMINTEDATE;
							EXECUTE CUSPRETERMINTEDATESTMT;
							SET PREDATE=@PRE_TERMDATE;
						IF PREDATE IS NOT NULL THEN
							SET @UPDATECED=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.CUSTOMER_ENTRY_DETAILS SET CED_ED_STIME=','"25"',',','CED_ED_ETIME=','"26"',' WHERE CUSTOMER_ID=',MIN_CUSTOMER,' AND CED_REC_VER=',MAX_REC_VER));
							PREPARE UPDATECEDSTMT FROM @UPDATECED;
							EXECUTE UPDATECEDSTMT;
							SET @PRE_TERMDATE=NULL;
						END IF;
                   
          
  
            SET MIN_RECHECKINID=MIN_RECHECKINID+1;
            END WHILE;
        END IF;
    SET @TERM_ACTIVE_REC_VER=(SELECT CONCAT('SELECT MAX(CED_REC_VER)INTO @TERMMAXRECVER FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS WHERE CUSTOMER_ID=',MIN_CUSTOMER,'  AND IF(CTD_PRETERMINATEDATE IS NOT NULL,CTD_PRETERMINATEDATE>CTD_STARTDATE,CTD_ENDDATE>CTD_STARTDATE)AND IF(CTD_PRETERMINATEDATE IS NOT NULL,CTD_PRETERMINATEDATE>CURDATE(),CTD_ENDDATE>CURDATE())'));
	PREPARE TERM_ACTIVE_REC_VER_STMT FROM @TERM_ACTIVE_REC_VER;
	EXECUTE TERM_ACTIVE_REC_VER_STMT;
	SET ACTIVE_REC_VER=@TERMMAXRECVER;
    IF ACTIVE_REC_VER IS NULL THEN
        SET @TERM_MAX_REC_VER=(SELECT CONCAT('SELECT MAX(CED_REC_VER)INTO @TERM_MAX_REC_VER FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS WHERE CUSTOMER_ID=',MIN_CUSTOMER,' AND IF(CTD_PRETERMINATEDATE IS NOT NULL,CTD_PRETERMINATEDATE>CTD_STARTDATE,CTD_ENDDATE>=CTD_STARTDATE)AND IF(CTD_PRETERMINATEDATE IS NOT NULL,CTD_PRETERMINATEDATE<=CURDATE(),CTD_ENDDATE<=CURDATE())'));
		PREPARE TERM_MAX_REC_VER_STMT FROM @TERM_MAX_REC_VER;
		EXECUTE TERM_MAX_REC_VER_STMT;
		SET MAX_REC_VER=@TERM_MAX_REC_VER;
            IF MAX_REC_VER IS NOT NULL THEN
				SET @SETCANCELDATE=(SELECT CONCAT('SELECT CED_CANCEL_DATE INTO @CDATE FROM ',DESTINATIONSCHEMA,'.CUSTOMER_ENTRY_DETAILS WHERE CUSTOMER_ID=',MIN_CUSTOMER,' AND CED_REC_VER=',MAX_REC_VER));
				PREPARE SETCANCELDATESTMT FROM @SETCANCELDATE;
				EXECUTE SETCANCELDATESTMT;
				SET CANCELDATE=@CDATE;
				IF CANCELDATE IS NULL THEN
                SET @UPTEMPTERMDETAILS=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS SET CTD_TERMINATE=','"X"',' WHERE CUSTOMER_ID=',MIN_CUSTOMER,' AND CED_REC_VER=',MAX_REC_VER));
				PREPARE UPTEMPTERMDETAILSSTMT FROM @UPTEMPTERMDETAILS;
				EXECUTE UPTEMPTERMDETAILSSTMT;
				END IF;
            END IF;
    END IF;
			
			SET @TIME_MAXRECVER_STMT=(SELECT CONCAT('SELECT MAX(CED_REC_VER) INTO @PREDATEMAXRECVER FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS WHERE CUSTOMER_ID=',MIN_CUSTOMER,' AND IF(CTD_PRETERMINATEDATE IS NOT NULL,CTD_PRETERMINATEDATE>CTD_STARTDATE,CTD_ENDDATE>=CTD_STARTDATE)'));
			PREPARE TIMEMAXRECVERSTMT FROM @TIME_MAXRECVER_STMT;
			EXECUTE TIMEMAXRECVERSTMT;
			SET TIME_MAX_REC_VER=@PREDATEMAXRECVER;
			
			-- UPDATE TIME_PROFILE ID IN CUSTOMER_ENTRY_DETAILS TABLE
			SET @ENTRYPRETERMINATESTMT=(SELECT CONCAT('SELECT CTD_PRETERMINATEDATE INTO @PREDATEENTRY FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS WHERE CUSTOMER_ID=',MIN_CUSTOMER,' AND CED_REC_VER=',TIME_MAX_REC_VER,' AND CTD_PRETERMINATEDATE!=','" "'));
			PREPARE TERMPRETERMINATESTMT FROM @ENTRYPRETERMINATESTMT;
			EXECUTE TERMPRETERMINATESTMT;
			SET TIME_PREDATE=@PREDATEENTRY;
			IF TIME_PREDATE IS NOT NULL THEN
				SET @TIMEUPDATECED=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.CUSTOMER_ENTRY_DETAILS SET CED_ED_STIME=25,CED_ED_ETIME=26 WHERE CUSTOMER_ID=',MIN_CUSTOMER,' AND CED_REC_VER=',TIME_MAX_REC_VER));
				PREPARE TIMEUPDATECEDSTMT FROM @TIMEUPDATECED;
				EXECUTE TIMEUPDATECEDSTMT;
				SET @PREDATEENTRY=NULL;
			END IF;
			END IF;
			SET @CHECK_CUSTID=NULL;
			SET @CDATE=NULL;
		SET MIN_CUSTOMER=MIN_CUSTOMER+1;
    END WHILE;
  
    SET @UPTEMPTERMGUEST=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_GUEST_CUSTOMER_TERMINATION_DETAILS SET CED_REC_VER=NULL'));
	PREPARE UPTEMPTERMGUESTSTMT FROM @UPTEMPTERMGUEST;
	EXECUTE UPTEMPTERMGUESTSTMT;
	
    SET @MAXGUESTCTDID=(SELECT CONCAT('SELECT MAX(CTD_ID)INTO @MAXCTDID FROM ',DESTINATIONSCHEMA,'.TEMP_GUEST_CUSTOMER_TERMINATION_DETAILS'));
	PREPARE MAXGUESTCTDIDSTMT FROM @MAXGUESTCTDID;
	EXECUTE MAXGUESTCTDIDSTMT;
	SET MAX_GUEST_CTD_ID=@MAXCTDID;
	
    SET @MINGUESTCTDID=(SELECT CONCAT('SELECT MIN(CTD_ID)INTO @MINCTDID FROM ',DESTINATIONSCHEMA,'.TEMP_GUEST_CUSTOMER_TERMINATION_DETAILS'));
	PREPARE MINGUESTCTDIDSTMT FROM @MINGUESTCTDID;
	EXECUTE MINGUESTCTDIDSTMT;
	SET MIN_GUEST_CTD_ID=@MINCTDID;
    WHILE MIN_GUEST_CTD_ID<=MAX_GUEST_CTD_ID DO
        SET @GUESTCUSTID=(SELECT CONCAT('SELECT CUSTOMER_ID INTO @GUEST_CUST_ID FROM ',DESTINATIONSCHEMA,'.TEMP_GUEST_CUSTOMER_TERMINATION_DETAILS WHERE CTD_ID=',MIN_GUEST_CTD_ID));
		PREPARE GUESTCUSTIDSTMT FROM @GUESTCUSTID;
		EXECUTE GUESTCUSTIDSTMT;
		SET CUSTID=@GUEST_CUST_ID;
        SET @GUESTSTARTDATE=(SELECT CONCAT('SELECT CTD_STARTDATE INTO @GUEST_SDATE FROM ',DESTINATIONSCHEMA,'.TEMP_GUEST_CUSTOMER_TERMINATION_DETAILS WHERE CTD_ID=',MIN_GUEST_CTD_ID));
		PREPARE GUESTSTARTDATESTMT FROM @GUESTSTARTDATE;
		EXECUTE GUESTSTARTDATESTMT;
		SET STARTDATE=@GUEST_SDATE;
		
		SET @GUESTPRETERMINATEDATE=(SELECT CONCAT('SELECT CTD_PRETERMINATEDATE INTO @GUEST_PREDATE FROM ',DESTINATIONSCHEMA,'.TEMP_GUEST_CUSTOMER_TERMINATION_DETAILS WHERE CTD_ID=',MIN_GUEST_CTD_ID));
		PREPARE GUESTPRETERMINATEDATESTMT FROM @GUESTPRETERMINATEDATE;
		EXECUTE GUESTPRETERMINATEDATESTMT;
		SET PRETERMINATEDATE=@GUEST_PREDATE;
		
        IF PRETERMINATEDATE IS NOT NULL THEN
            SET @GUESTPREDATE=(SELECT CONCAT('SELECT CTD_PRETERMINATEDATE INTO @GUESTPREDATE FROM ',DESTINATIONSCHEMA,'.TEMP_GUEST_CUSTOMER_TERMINATION_DETAILS WHERE CTD_ID=',MIN_GUEST_CTD_ID));
			PREPARE GUESTPREDATESTMT FROM @GUESTPREDATE;
			EXECUTE GUESTPREDATESTMT;
			SET ENDDATE=@GUESTPREDATE;
        ELSE
            SET @GUESTENDDATE=(SELECT CONCAT('SELECT CTD_ENDDATE INTO @GUEST_EDATE FROM ',DESTINATIONSCHEMA,'.TEMP_GUEST_CUSTOMER_TERMINATION_DETAILS WHERE CTD_ID=',MIN_GUEST_CTD_ID));
			PREPARE GUESTENDDATESTMT FROM @GUESTENDDATE;
			EXECUTE GUESTENDDATESTMT;
			SET ENDDATE=@GUEST_EDATE;
        END IF;
        SET @UPGUESTTERMDTL=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_GUEST_CUSTOMER_TERMINATION_DETAILS  SET CED_REC_VER=(SELECT CED_REC_VER FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS WHERE CUSTOMER_ID=',CUSTID,' AND CTD_STARTDATE<=','"',STARTDATE,'"',' AND IF (CTD_PRETERMINATEDATE IS NOT NULL,CTD_PRETERMINATEDATE>=','"',ENDDATE,'"',',CTD_ENDDATE>=','"',ENDDATE,'"',')) WHERE CTD_ID=',MIN_GUEST_CTD_ID));
		PREPARE UPGUESTTERMDTLSTMT FROM @UPGUESTTERMDTL;
		EXECUTE UPGUESTTERMDTLSTMT;
		
        SET @GUESTTERMRECVER=(SELECT CONCAT('SELECT CED_REC_VER INTO @GUESTRECVER FROM ',DESTINATIONSCHEMA,'.TEMP_GUEST_CUSTOMER_TERMINATION_DETAILS WHERE CTD_ID=',MIN_GUEST_CTD_ID));
		PREPARE GUESTRECVERSTMT FROM @GUESTTERMRECVER;
		EXECUTE GUESTRECVERSTMT;
		SET GUEST_RECVER=@GUESTRECVER;
		SET MIN_GUEST_CTD_ID=MIN_GUEST_CTD_ID+1;
    END WHILE;
  
    SET FOREIGN_KEY_CHECKS=0;
	
	SET @DRCUSTERMDTL=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.CUSTOMER_LP_DETAILS'));
	PREPARE DRCUSTERMDTLSTMT FROM @DRCUSTERMDTL;
	EXECUTE DRCUSTERMDTLSTMT;
	
	SET @CREATE_CUST_TERM=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.CUSTOMER_LP_DETAILS(
	CLP_ID INTEGER NOT NULL	AUTO_INCREMENT,
	CUSTOMER_ID	INTEGER NOT NULL,
	CED_REC_VER	INTEGER NOT NULL,
	UASD_ID	INTEGER NULL,
	CLP_STARTDATE DATE NOT NULL,
	CLP_ENDDATE	DATE NOT NULL,
	CLP_TERMINATE CHAR(1) NULL,
	CLP_PRETERMINATE_DATE DATE NULL,
	CLP_GUEST_CARD CHAR(1) NULL,
	ULD_TS_MAXTIMES INTEGER NOT NULL DEFAULT 1,
	ULD_ID INTEGER(2) NOT NULL,	
	CLP_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(CLP_ID),
	FOREIGN KEY(CUSTOMER_ID) REFERENCES ',DESTINATIONSCHEMA,'.CUSTOMER(CUSTOMER_ID),
	FOREIGN KEY(ULD_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS(ULD_ID))'));
	PREPARE CREATE_CUST_TERM_STMT FROM @CREATE_CUST_TERM;
	EXECUTE CREATE_CUST_TERM_STMT;
	-- INSERT QUERY FOR CUSTOMER_LP_DETAILS TABLE
    SET @INSERT_CUS_TERM_DTL=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.CUSTOMER_LP_DETAILS(CUSTOMER_ID,CED_REC_VER,UASD_ID,CLP_STARTDATE,CLP_ENDDATE,CLP_TERMINATE,CLP_PRETERMINATE_DATE,CLP_GUEST_CARD,ULD_ID,CLP_TIMESTAMP)
    SELECT CUSTOMER_ID,CED_REC_VER,UASD_ID,CTD_STARTDATE,CTD_ENDDATE,CTD_TERMINATE,CTD_PRETERMINATEDATE,CTD_GUEST_CARD,ULD_ID,CTD_TIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS'));
	PREPARE INSERT_CUS_TERM_DTL_STMT FROM @INSERT_CUS_TERM_DTL;
	EXECUTE INSERT_CUS_TERM_DTL_STMT;
    SET @INSERT_GUEST_TERM_DTL=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.CUSTOMER_LP_DETAILS(CUSTOMER_ID,CED_REC_VER,UASD_ID,CLP_STARTDATE,CLP_ENDDATE,CLP_TERMINATE,CLP_PRETERMINATE_DATE,CLP_GUEST_CARD,ULD_ID,CLP_TIMESTAMP)
    SELECT CUSTOMER_ID,CED_REC_VER,UASD_ID,CTD_STARTDATE,CTD_ENDDATE,CTD_TERMINATE,CTD_PRETERMINATEDATE,CTD_GUEST_CARD,ULD_ID,CTD_TIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_GUEST_CUSTOMER_TERMINATION_DETAILS'));
	PREPARE INSERT_GUEST_TERM_DTL_STMT FROM @INSERT_GUEST_TERM_DTL;
	EXECUTE INSERT_GUEST_TERM_DTL_STMT;
  
 SET END_TIME=(SELECT CURTIME());
 SET DURATION=(SELECT TIMEDIFF(END_TIME,START_TIME));
 
 SET @COUNT_SCDB_CTD_STMT=(SELECT CONCAT('SELECT COUNT(*)INTO @COUNT_SCDB_CTD FROM ',SOURCESCHEMA,'.CUSTOMER_SCDB_FORMAT'));
 PREPARE COUNTSCDBCTD FROM @COUNT_SCDB_CTD_STMT;
 EXECUTE COUNTSCDBCTD;
 
 SET @COUNT_SPLITTING_CTD_STMT=(SELECT CONCAT('SELECT COUNT(*)INTO @COUNT_SPLITTING_CTD FROM ',DESTINATIONSCHEMA,'.CUSTOMER_LP_DETAILS'));
 PREPARE COUNTSPLITTEDSTD FROM @COUNT_SPLITTING_CTD_STMT;
 EXECUTE COUNTSPLITTEDSTD;
 SET @REJECTION_COUNT=(@COUNT_SCDB_CTD-@COUNT_SPLITTING_CTD);
UPDATE PRE_AUDIT_SUB_PROFILE SET PREASP_NO_OF_REC=@COUNT_SCDB_CTD WHERE PREASP_DATA='CUSTOMER_LP_DETAILS';
	SET FOREIGN_KEY_CHECKS=0;	
INSERT INTO POST_AUDIT_HISTORY(POSTAP_ID,POSTAH_NO_OF_REC,PREASP_ID,PREAMP_ID,POSTAH_DURATION,POSTAH_NO_OF_REJ,ULD_ID)
VALUES((SELECT POSTAP_ID FROM POST_AUDIT_PROFILE WHERE POSTAP_DATA='CUSTOMER_LP_DETAILS'),@COUNT_SPLITTING_CTD,(SELECT PREASP_ID FROM PRE_AUDIT_SUB_PROFILE WHERE PREASP_DATA='CUSTOMER_LP_DETAILS'),
(SELECT PREAMP_ID FROM PRE_AUDIT_MAIN_PROFILE WHERE PREAMP_DATA='CUSTOMER'),DURATION,@REJECTION_COUNT,@USERSTAMPID);

-- DROP TEMP TABLES
SET @DRTEMPRECHECKCUSTOMER=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_RECHECKIN_CUSTOMER'));
PREPARE DRTEMPRECHECKCUSTOMERSTMT FROM @DRTEMPRECHECKCUSTOMER;
EXECUTE DRTEMPRECHECKCUSTOMERSTMT;


SET @DRTEMPTERMINATION=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_TERMINATION_DETAILS'));
PREPARE DRTEMPTERMINATIONSTMT FROM @DRTEMPTERMINATION;
EXECUTE DRTEMPTERMINATIONSTMT;

COMMIT;
END;