DROP TRIGGER IF EXISTS TRG_PAYMENT_DETAILS_UPDATE;
CREATE TRIGGER TRG_PAYMENT_DETAILS_UPDATE  
AFTER UPDATE ON PAYMENT_DETAILS
FOR EACH ROW
BEGIN 
DECLARE OLD_VALUE TEXT DEFAULT '';
DECLARE NEW_VALUE TEXT DEFAULT '';
IF ((OLD.UNIT_ID!= NEW.UNIT_ID) OR (OLD.CUSTOMER_ID!= NEW.CUSTOMER_ID) OR (OLD.PP_ID!= NEW.PP_ID) OR (OLD.CED_REC_VER!= NEW.CED_REC_VER) OR (OLD.PD_AMOUNT!= NEW.PD_AMOUNT) OR (OLD.PD_FOR_PERIOD!= NEW.PD_FOR_PERIOD) OR (OLD.PD_PAID_DATE!= NEW.PD_PAID_DATE) OR (OLD.PD_HIGHLIGHT_FLAG IS NULL AND NEW.PD_HIGHLIGHT_FLAG IS NOT NULL) OR (OLD.PD_HIGHLIGHT_FLAG IS NOT NULL AND NEW.PD_HIGHLIGHT_FLAG IS NULL) OR (OLD.PD_HIGHLIGHT_FLAG!= NEW.PD_HIGHLIGHT_FLAG) OR (OLD.PD_COMMENTS IS NULL AND NEW.PD_COMMENTS IS NOT NULL) OR (OLD.PD_COMMENTS IS NOT NULL AND NEW.PD_COMMENTS IS NULL) OR (OLD.PD_COMMENTS!= NEW.PD_COMMENTS)) THEN  
  SET OLD_VALUE = CONCAT(OLD_VALUE,'PD_ID=', OLD.PD_ID,','); 
END IF;
IF (OLD.UNIT_ID!= NEW.UNIT_ID) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'UNIT_ID=', OLD.UNIT_ID,','); 
END IF;
IF (OLD.UNIT_ID!= NEW.UNIT_ID) THEN SET 
NEW_VALUE = CONCAT(NEW_VALUE,'UNIT_ID=', NEW.UNIT_ID,','); 
END IF;
IF (OLD.CUSTOMER_ID!= NEW.CUSTOMER_ID) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'CUSTOMER_ID=', OLD.CUSTOMER_ID,','); 
END IF;
IF (OLD.CUSTOMER_ID!= NEW.CUSTOMER_ID) THEN SET 
NEW_VALUE = CONCAT(NEW_VALUE,'CUSTOMER_ID=', NEW.CUSTOMER_ID,','); 
END IF;
IF (OLD.PP_ID!= NEW.PP_ID) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'PP_ID=', OLD.PP_ID,','); 
END IF;
IF (OLD.PP_ID!= NEW.PP_ID) THEN SET 
NEW_VALUE = CONCAT(NEW_VALUE,'PP_ID=', NEW.PP_ID,','); 
END IF;
IF (OLD.CED_REC_VER!= NEW.CED_REC_VER) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'CED_REC_VER=', OLD.CED_REC_VER,','); 
END IF;
IF (OLD.CED_REC_VER!= NEW.CED_REC_VER) THEN SET 
NEW_VALUE = CONCAT(NEW_VALUE,'CED_REC_VER=', NEW.CED_REC_VER,','); 
END IF;
IF (OLD.PD_AMOUNT!= NEW.PD_AMOUNT) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'PD_AMOUNT=', OLD.PD_AMOUNT,','); 
END IF;
IF (OLD.PD_AMOUNT!= NEW.PD_AMOUNT) THEN SET 
NEW_VALUE = CONCAT(NEW_VALUE,'PD_AMOUNT=', NEW.PD_AMOUNT,','); 
END IF;
IF (OLD.PD_FOR_PERIOD!= NEW.PD_FOR_PERIOD) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'PD_FOR_PERIOD=', OLD.PD_FOR_PERIOD,','); 
END IF;
IF (OLD.PD_FOR_PERIOD!= NEW.PD_FOR_PERIOD) THEN SET 
NEW_VALUE = CONCAT(NEW_VALUE,'PD_FOR_PERIOD=', NEW.PD_FOR_PERIOD,','); 
END IF;
IF (OLD.PD_PAID_DATE!= NEW.PD_PAID_DATE) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'PD_PAID_DATE=', OLD.PD_PAID_DATE,','); 
END IF;
IF (OLD.PD_PAID_DATE!= NEW.PD_PAID_DATE) THEN SET 
NEW_VALUE = CONCAT(NEW_VALUE,'PD_PAID_DATE=', NEW.PD_PAID_DATE,','); 
END IF;
IF (OLD.PD_HIGHLIGHT_FLAG IS NULL AND NEW.PD_HIGHLIGHT_FLAG IS NOT NULL) THEN
SET OLD_VALUE=CONCAT(OLD_VALUE,'PD_HIGHLIGHT_FLAG=','<NULL>,');
SET NEW_VALUE=CONCAT(NEW_VALUE,'PD_HIGHLIGHT_FLAG=',NEW.PD_HIGHLIGHT_FLAG,',');
ELSEIF (OLD.PD_HIGHLIGHT_FLAG IS NOT NULL AND NEW.PD_HIGHLIGHT_FLAG IS NULL) THEN
SET OLD_VALUE=CONCAT(OLD_VALUE,'PD_HIGHLIGHT_FLAG=',OLD.PD_HIGHLIGHT_FLAG,',');
SET NEW_VALUE=CONCAT(NEW_VALUE,'PD_HIGHLIGHT_FLAG=','<NULL>,');
ELSEIF (OLD.PD_HIGHLIGHT_FLAG!= NEW.PD_HIGHLIGHT_FLAG) THEN 
SET OLD_VALUE = CONCAT(OLD_VALUE,'PD_HIGHLIGHT_FLAG=', OLD.PD_HIGHLIGHT_FLAG,','); 
SET NEW_VALUE = CONCAT(NEW_VALUE,'PD_HIGHLIGHT_FLAG=', NEW.PD_HIGHLIGHT_FLAG,','); 
END IF;
IF (OLD.PD_COMMENTS IS NULL AND NEW.PD_COMMENTS IS NOT NULL) THEN
SET OLD_VALUE=CONCAT(OLD_VALUE,'PD_COMMENTS=','<NULL>,');
SET NEW_VALUE=CONCAT(NEW_VALUE,'PD_COMMENTS=',NEW.PD_COMMENTS,',');
ELSEIF (OLD.PD_COMMENTS IS NOT NULL AND NEW.PD_COMMENTS IS NULL) THEN
SET OLD_VALUE=CONCAT(OLD_VALUE,'PD_COMMENTS=',OLD.PD_COMMENTS,',');
SET NEW_VALUE=CONCAT(NEW_VALUE,'PD_COMMENTS=','<NULL>,');
ELSEIF (OLD.PD_COMMENTS!= NEW.PD_COMMENTS) THEN 
SET OLD_VALUE = CONCAT(OLD_VALUE,'PD_COMMENTS=', OLD.PD_COMMENTS,','); 
SET NEW_VALUE = CONCAT(NEW_VALUE,'PD_COMMENTS=', NEW.PD_COMMENTS,','); 
END IF;
IF ((OLD.UNIT_ID!= NEW.UNIT_ID) OR (OLD.CUSTOMER_ID!= NEW.CUSTOMER_ID) OR (OLD.PP_ID!= NEW.PP_ID) OR (OLD.CED_REC_VER!= NEW.CED_REC_VER) OR (OLD.PD_AMOUNT!= NEW.PD_AMOUNT) OR (OLD.PD_FOR_PERIOD!= NEW.PD_FOR_PERIOD) OR (OLD.PD_PAID_DATE!= NEW.PD_PAID_DATE) OR (OLD.PD_HIGHLIGHT_FLAG IS NULL AND NEW.PD_HIGHLIGHT_FLAG IS NOT NULL) OR (OLD.PD_HIGHLIGHT_FLAG IS NOT NULL AND NEW.PD_HIGHLIGHT_FLAG IS NULL) OR (OLD.PD_HIGHLIGHT_FLAG!= NEW.PD_HIGHLIGHT_FLAG) OR (OLD.PD_COMMENTS IS NULL AND NEW.PD_COMMENTS IS NOT NULL) OR (OLD.PD_COMMENTS IS NOT NULL AND NEW.PD_COMMENTS IS NULL) OR (OLD.PD_COMMENTS!= NEW.PD_COMMENTS)) THEN  
IF (OLD.ULD_ID!= NEW.ULD_ID) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'ULD_ID=', OLD.ULD_ID,','); 
END IF;
IF (OLD.PD_TIMESTAMP!= NEW.PD_TIMESTAMP) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'PD_TIMESTAMP=', OLD.PD_TIMESTAMP,','); 
END IF;
END IF;
IF (OLD_VALUE!='' AND NEW_VALUE!='') THEN
IF(OLD_VALUE != NEW_VALUE)THEN
SET OLD_VALUE = SUBSTRING(OLD_VALUE,1,CHAR_LENGTH(OLD_VALUE)-1);
SET NEW_VALUE = SUBSTRING(NEW_VALUE,1,CHAR_LENGTH(NEW_VALUE)-1);
INSERT INTO TICKLER_HISTORY
(ULD_ID,TP_ID,TTIP_ID,CUSTOMER_ID,TH_OLD_VALUE,TH_NEW_VALUE)VALUES
((SELECT ULD_ID FROM PAYMENT_DETAILS WHERE PD_ID=NEW.PD_ID),
(SELECT TP_ID FROM TICKLER_PROFILE WHERE TP_TYPE='UPDATION'),
(SELECT TTIP_ID FROM TICKLER_TABID_PROFILE WHERE TTIP_DATA='PAYMENT_DETAILS'),
(SELECT CUSTOMER_ID FROM PAYMENT_DETAILS WHERE CUSTOMER_ID=NEW.CUSTOMER_ID AND PD_ID=NEW.PD_ID),OLD_VALUE,NEW_VALUE);
END IF;
END IF;
END;