-- VERSION:0.1 TRACKER NO:595, COMMENT: #29, START DATE:2014-01-06,END DATE:2014-01-08 DESCRIPTION: RETRIEVES COMPUTED CAR, CAR_LOAN, BABY EXPENSES AND PERSONAL EXPENSES. DONE BY RANJIDTH KUMAR.
-- VERSION:0.2 TRACKER NO:595, COMMENT: #, START DATE:2014-01-24,END DATE:2014-01-24 DESCRIPTION: FINE TUNED THE CODING. DONE BY MANIKANDAN.
-- VERSION:0.3 TRACKER NO:817, COMMENT: #35, START DATE:08-05-2014,END DATE:08-05-2014 DESCRIPTION: CHANGES IN TEMP TABLE FOR DYNAMIC PURPOSE. DONE BY:BHAVANI.R.
-- VERSION:0.4 TRACKER NO:566, COMMENT: #12, START DATE:09-06-2014,END DATE:09-06-2014 DESCRIPTION: ADDED ROLLBACK AND COMMIT DONE BY:SASIKALA
-- VER 0.5 TRACKER NO:817 COMMENT #139 STARTDATE:21/06/2014 ENDDATE:21/06/2014 DESC: DROPPING TEMP TABLE IF ROLLBACK OCCURS DONE BY:BHAVANI.R


DROP PROCEDURE IF EXISTS SP_CHARTS_PERSONAL_EXPENSE;

CREATE PROCEDURE SP_CHARTS_PERSONAL_EXPENSE(IN FROM_DATE VARCHAR(20),IN TO_DATE VARCHAR(20),IN USERSTAMP VARCHAR(50),OUT CHARTS_PERSONAL_EXPENSE_TEMPTBL TEXT )
BEGIN
    DECLARE FINAL_FROM_DATE VARCHAR(20);
    DECLARE FINAL_TO_DATE VARCHAR(20);
	DECLARE CHARTS_PERSONAL_EXPENSE_MAIN_TEMPTBL TEXT;
	DECLARE INTERMEDIATE_CHART_PERSONAL_EXPENSE TEXT;
	DECLARE CHART_INTERMEDIATE_PERSONAL_EXPENSE_TMPTBL TEXT;
	DECLARE USERSTAMP_ID INT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN 
      ROLLBACK;
    IF (CHART_INTERMEDIATE_PERSONAL_EXPENSE_TMPTBL IS NOT NULL) THEN
		SET @DROP_TEMP_INTERMEDIATE_CHART_PERSONAL_EXPENSE=(SELECT CONCAT('DROP TABLE IF EXISTS ',CHART_INTERMEDIATE_PERSONAL_EXPENSE_TMPTBL));
		PREPARE DROP_TEMP_INTERMEDIATE_CHART_PERSONAL_EXPENSE_STMT FROM @DROP_TEMP_INTERMEDIATE_CHART_PERSONAL_EXPENSE;
		EXECUTE DROP_TEMP_INTERMEDIATE_CHART_PERSONAL_EXPENSE_STMT;
	END IF;

    END;
    START TRANSACTION;
--   TEMP TABLE NAME START
	CALL SP_CHANGE_USERSTAMP_AS_ULDID(USERSTAMP,@ULDID);
	SET USERSTAMP_ID=(SELECT @ULDID);
	SET CHARTS_PERSONAL_EXPENSE_MAIN_TEMPTBL=(SELECT CONCAT('TEMP_CHARTS_PERSONAL_EXPENSE',SYSDATE()));
	SET INTERMEDIATE_CHART_PERSONAL_EXPENSE=(SELECT CONCAT('TEMP_INTERMEDIATE_CHART_PERSONAL_EXPENSE',SYSDATE()));
--    NAME FOR MAIN TEMP TABLE
	SET CHARTS_PERSONAL_EXPENSE_MAIN_TEMPTBL=(SELECT REPLACE(CHARTS_PERSONAL_EXPENSE_MAIN_TEMPTBL,' ',''));
	SET CHARTS_PERSONAL_EXPENSE_MAIN_TEMPTBL=(SELECT REPLACE(CHARTS_PERSONAL_EXPENSE_MAIN_TEMPTBL,'-',''));
	SET CHARTS_PERSONAL_EXPENSE_MAIN_TEMPTBL=(SELECT REPLACE(CHARTS_PERSONAL_EXPENSE_MAIN_TEMPTBL,':',''));
	SET CHARTS_PERSONAL_EXPENSE_TEMPTBL=(SELECT CONCAT(CHARTS_PERSONAL_EXPENSE_MAIN_TEMPTBL,'_',USERSTAMP_ID)); 
-- NAME FOR INTERMEDIATE TEMP TABLE
	SET INTERMEDIATE_CHART_PERSONAL_EXPENSE=(SELECT REPLACE(INTERMEDIATE_CHART_PERSONAL_EXPENSE,' ',''));
	SET INTERMEDIATE_CHART_PERSONAL_EXPENSE=(SELECT REPLACE(INTERMEDIATE_CHART_PERSONAL_EXPENSE,'-',''));
	SET INTERMEDIATE_CHART_PERSONAL_EXPENSE=(SELECT REPLACE(INTERMEDIATE_CHART_PERSONAL_EXPENSE,':',''));
	SET CHART_INTERMEDIATE_PERSONAL_EXPENSE_TMPTBL=(SELECT CONCAT(INTERMEDIATE_CHART_PERSONAL_EXPENSE,'_',USERSTAMP_ID));
--   TEMP TABLE NAME END

		SET @CREATE_TEMP_CHARTS_PERSONAL_EXPENSE=(SELECT CONCAT('CREATE TABLE ',CHARTS_PERSONAL_EXPENSE_TEMPTBL,'(MONTH_YEAR varchar(50) DEFAULT NULL, BABY_EXPENSES DECIMAL(20, 2) DEFAULT 0,
		CAR_EXPENSES DECIMAL(20, 2) DEFAULT 0, CAR_LOAN DECIMAL(20, 2) DEFAULT 0,
		PERSONAL_EXPENSES DECIMAL(20, 2) DEFAULT 0)'));
		PREPARE CREATE_TEMP_CHARTS_PERSONAL_EXPENSE_STMT FROM @CREATE_TEMP_CHARTS_PERSONAL_EXPENSE;
		EXECUTE CREATE_TEMP_CHARTS_PERSONAL_EXPENSE_STMT;

		SET @CREATE_TEMP_INTERMEDIATE_CHART_PERSONAL_EXPENSE=(SELECT CONCAT('CREATE TABLE ',CHART_INTERMEDIATE_PERSONAL_EXPENSE_TMPTBL,'(MONTH_YEAR varchar(50) DEFAULT NULL,
		BABY_EXPENSES DECIMAL(7, 2) DEFAULT 0, CAR_EXPENSES DECIMAL(7, 2) DEFAULT 0,CAR_LOAN DECIMAL(7, 2) DEFAULT 0,
		PERSONAL_EXPENSES DECIMAL(7, 2) DEFAULT 0,SORT_DATE DATE DEFAULT NULL)'));
		PREPARE CREATE_TEMP_INTERMEDIATE_CHART_PERSONAL_EXPENSE_STMT FROM @CREATE_TEMP_INTERMEDIATE_CHART_PERSONAL_EXPENSE;
		EXECUTE CREATE_TEMP_INTERMEDIATE_CHART_PERSONAL_EXPENSE_STMT;

-- Format the input date into proper date format.
		CALL SP_FORMAT_DATE(FROM_DATE,TO_DATE,@fd,@td);
		SELECT @fd INTO FINAL_FROM_DATE;
		SELECT @td INTO FINAL_TO_DATE;
  
     	SET @INSERT_TEMP_INTERMEDIATE_CHART_PERSONAL_EXPENSE=(SELECT CONCAT('INSERT INTO ',CHART_INTERMEDIATE_PERSONAL_EXPENSE_TMPTBL,' (MONTH_YEAR, CAR_EXPENSES, SORT_DATE) SELECT  DATE_FORMAT(CAR.EC_INVOICE_DATE,"%M-%Y") , (CAR.EC_AMOUNT), CAR.EC_INVOICE_DATE FROM EXPENSE_CAR CAR
		WHERE CAR.EC_INVOICE_DATE BETWEEN ','"',FINAL_FROM_DATE,'"', ' AND ','"',FINAL_TO_DATE,'"'));
		PREPARE INSERT_TEMP_INTERMEDIATE_CHART_PERSONAL_EXPENSE_STMT FROM @INSERT_TEMP_INTERMEDIATE_CHART_PERSONAL_EXPENSE;
		EXECUTE INSERT_TEMP_INTERMEDIATE_CHART_PERSONAL_EXPENSE_STMT;


      SET @INSERT_TEMP_INTERMEDIATE_CHART_PERSONAL_EXPENSE=(SELECT CONCAT('INSERT INTO ',CHART_INTERMEDIATE_PERSONAL_EXPENSE_TMPTBL,' (MONTH_YEAR, CAR_LOAN, SORT_DATE) SELECT  DATE_FORMAT(LOAN.ECL_PAID_DATE,"%M-%Y") , (LOAN.ECl_AMOUNT), LOAN.ECL_PAID_DATE FROM EXPENSE_CAR_LOAN LOAN
		WHERE LOAN.ECL_PAID_DATE  BETWEEN ','"',FINAL_FROM_DATE,'"', ' AND ','"',FINAL_TO_DATE,'"'));
		PREPARE INSERT_TEMP_INTERMEDIATE_CHART_PERSONAL_EXPENSE_STMT FROM @INSERT_TEMP_INTERMEDIATE_CHART_PERSONAL_EXPENSE;
		EXECUTE INSERT_TEMP_INTERMEDIATE_CHART_PERSONAL_EXPENSE_STMT;
		
     SET @INSERT_TEMP_INTERMEDIATE_CHART_PERSONAL_EXPENSE=(SELECT CONCAT('INSERT INTO ',CHART_INTERMEDIATE_PERSONAL_EXPENSE_TMPTBL,' (MONTH_YEAR, BABY_EXPENSES, SORT_DATE) SELECT  DATE_FORMAT(BABY.EB_INVOICE_DATE,"%M-%Y") , (BABY.EB_AMOUNT), BABY.EB_INVOICE_DATE  FROM EXPENSE_BABY BABY
		WHERE BABY.EB_INVOICE_DATE  BETWEEN ','"',FINAL_FROM_DATE,'"', ' AND ','"',FINAL_TO_DATE,'"'));
		PREPARE INSERT_TEMP_INTERMEDIATE_CHART_PERSONAL_EXPENSE_STMT FROM @INSERT_TEMP_INTERMEDIATE_CHART_PERSONAL_EXPENSE;
		EXECUTE INSERT_TEMP_INTERMEDIATE_CHART_PERSONAL_EXPENSE_STMT;
		
		SET @INSERT_TEMP_INTERMEDIATE_CHART_PERSONAL_EXPENSE=(SELECT CONCAT('INSERT INTO ',CHART_INTERMEDIATE_PERSONAL_EXPENSE_TMPTBL,' (MONTH_YEAR, PERSONAL_EXPENSES, SORT_DATE) SELECT  DATE_FORMAT(EP.EP_INVOICE_DATE,"%M-%Y") , (EP.EP_AMOUNT), EP.EP_INVOICE_DATE FROM EXPENSE_PERSONAL EP
		WHERE EP.EP_INVOICE_DATE  BETWEEN ','"',FINAL_FROM_DATE,'"', ' AND ','"',FINAL_TO_DATE,'"'));
		PREPARE INSERT_TEMP_INTERMEDIATE_CHART_PERSONAL_EXPENSE_STMT FROM @INSERT_TEMP_INTERMEDIATE_CHART_PERSONAL_EXPENSE;
		EXECUTE INSERT_TEMP_INTERMEDIATE_CHART_PERSONAL_EXPENSE_STMT;

		SET @INSERT_TEMP_CHARTS_PERSONAL_EXPENSE=(SELECT CONCAT('INSERT INTO ',CHARTS_PERSONAL_EXPENSE_TEMPTBL,'(MONTH_YEAR, BABY_EXPENSES, CAR_EXPENSES, CAR_LOAN, PERSONAL_EXPENSES) (select MONTH_YEAR, SUM(IFNULL(BABY_EXPENSES,0)), SUM(IFNULL(CAR_EXPENSES,0)), SUM(IFNULL(CAR_LOAN,0)), SUM(IFNULL(PERSONAL_EXPENSES,0)) FROM ',CHART_INTERMEDIATE_PERSONAL_EXPENSE_TMPTBL,' GROUP BY MONTH_YEAR ORDER BY SORT_DATE)'));
		PREPARE INSERT_TEMP_CHARTS_PERSONAL_EXPENSE_STMT FROM @INSERT_TEMP_CHARTS_PERSONAL_EXPENSE;
		EXECUTE INSERT_TEMP_CHARTS_PERSONAL_EXPENSE_STMT;
		
		SET @DROP_TEMP_INTERMEDIATE_CHART_PERSONAL_EXPENSE=(SELECT CONCAT('DROP TABLE IF EXISTS ',CHART_INTERMEDIATE_PERSONAL_EXPENSE_TMPTBL));
		PREPARE DROP_TEMP_INTERMEDIATE_CHART_PERSONAL_EXPENSE_STMT FROM @DROP_TEMP_INTERMEDIATE_CHART_PERSONAL_EXPENSE;
		EXECUTE DROP_TEMP_INTERMEDIATE_CHART_PERSONAL_EXPENSE_STMT;

COMMIT;
END;
/*
CALL SP_CHARTS_PERSONAL_EXPENSE( 'Jan-2013' , 'Jan-2014','EXPATSINTEGRATED@GMAIL.COM',@CHARTS_PERSONAL_EXPENSE_TEMPTBL);
SELECT @CHARTS_PERSONAL_EXPENSE_TEMPTBL;
*/