DROP PROCEDURE IF EXISTS SP_MIG_CUSTOMER_FEE_INSERT;
CREATE PROCEDURE SP_MIG_CUSTOMER_FEE_INSERT(IN SOURCESCHEMA VARCHAR(50),DESTINATIONSCHEMA VARCHAR(50),IN MIGUSERSTAMP VARCHAR(100))
BEGIN
	DECLARE MINCCID INT;
	DECLARE MAXCCID INT;
	DECLARE CUSTID INT;
	DECLARE RECVER INT;
	DECLARE START_TIME TIME;
	DECLARE END_TIME TIME;
	DECLARE DURATION TIME;
	DECLARE RENT_AMT DECIMAL(7,2);
	DECLARE DEPOSIT_AMT DECIMAL(7,2);
	DECLARE CHECKOUT_CLEANING_AMT DECIMAL(7,2);
	DECLARE AIRCON_QUAR_AMT DECIMAL(7,2);
	DECLARE DRY_CLEAN_FEE_AMT DECIMAL(7,2);
	DECLARE ELECTRICITY_CAP_AMT DECIMAL(7,2);
	DECLARE PROCESSING_FEE_AMT DECIMAL(7,2);
	DECLARE AIRCON_FIXED_FEE_AMT DECIMAL(7,2);
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
	ROLLBACK;
	END;
	START TRANSACTION;
	SET FOREIGN_KEY_CHECKS=0;	
	SET @LOGIN_ID=(SELECT CONCAT('SELECT ULD_ID INTO @USERSTAMPID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=','"',MIGUSERSTAMP,'"'));
	PREPARE LOGINID FROM @LOGIN_ID;
	EXECUTE LOGINID;	
	SET @DROP_CUS_FEE_DETAILS=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.CUSTOMER_FEE_DETAILS'));
	PREPARE DRCUSFEEDETAILS FROM @DROP_CUS_FEE_DETAILS;
	EXECUTE DRCUSFEEDETAILS;	
	SET @CR_CUS_FEE_DETAILS=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.CUSTOMER_FEE_DETAILS(
	CFD_ID INTEGER NOT NULL	AUTO_INCREMENT,
	CUSTOMER_ID	INTEGER NOT NULL,
	CED_REC_VER	INTEGER NOT NULL,
	CPP_ID INTEGER NOT NULL,
	CFD_AMOUNT DECIMAL(7,2) NOT NULL,
	PRIMARY KEY(CFD_ID),
	FOREIGN KEY(CUSTOMER_ID) REFERENCES ',DESTINATIONSCHEMA,'.CUSTOMER(CUSTOMER_ID),
	FOREIGN KEY(CPP_ID) REFERENCES ',DESTINATIONSCHEMA,'.CUSTOMER_PAYMENT_PROFILE(CPP_ID))'));
	PREPARE CRCUSFEEDETAILS FROM @CR_CUS_FEE_DETAILS;
	EXECUTE CRCUSFEEDETAILS;	
	SET @MIN_CC_ID=(SELECT CONCAT('SELECT MIN(CTD_ID) INTO @MINID FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS'));
	PREPARE MINICCID FROM @MIN_CC_ID;
	EXECUTE MINICCID;
	SET MINCCID=@MINID;		
	SET @MAX_CC_ID=(SELECT CONCAT('SELECT MAX(CTD_ID) INTO @MAXID FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS'));
	PREPARE MAXICCID FROM @MAX_CC_ID;
	EXECUTE MAXICCID;
	SET MAXCCID=@MAXID;	
	SET START_TIME=(SELECT CURTIME());	
	WHILE MINCCID<=MAXCCID DO
	SET @CUSTOMERID=(SELECT CONCAT('SELECT CUSTOMER_ID INTO @CUST_ID FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS WHERE CTD_ID=',MINCCID));	
	PREPARE CUSTOMERIDSTMT FROM @CUSTOMERID;
	EXECUTE CUSTOMERIDSTMT;
	SET CUSTID=@CUST_ID;	
	SET @REC_VERSION=(SELECT CONCAT('SELECT CED_REC_VER INTO @REC_VER FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS WHERE CTD_ID=',MINCCID));
	PREPARE RECVERSTMT FROM @REC_VERSION;
	EXECUTE RECVERSTMT;
	SET RECVER=@REC_VER;		
	SET @RENTAMOUNT_STMT=(SELECT CONCAT('SELECT RENT_AMOUNT INTO @RENT FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS WHERE CUSTOMER_ID=',CUSTID, ' AND CED_REC_VER=',RECVER, ' AND RENT_AMOUNT!=0'));
	PREPARE RENTAMTSTMT FROM @RENTAMOUNT_STMT;
	EXECUTE RENTAMTSTMT;
	SET RENT_AMT=@RENT;		
	IF RENT_AMT IS NOT NULL THEN
	SET @CUSTOMER_FEE_RENT=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.CUSTOMER_FEE_DETAILS(CUSTOMER_ID, CED_REC_VER, CPP_ID, CFD_AMOUNT)VALUES(',CUSTID,',',RECVER,',','1',',',RENT_AMT,')'));
	PREPARE CUSTOMERFEERENTSTMT FROM @CUSTOMER_FEE_RENT;
	EXECUTE CUSTOMERFEERENTSTMT;
	SET @RENT=NULL;
	END IF;	
	SET @DEPOSITAMT=(SELECT CONCAT('SELECT DEPOSIT INTO @DEPOSIT FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS WHERE CUSTOMER_ID=',CUSTID, ' AND CED_REC_VER=',RECVER, ' AND DEPOSIT!=0'));
	PREPARE DEPOSITAMTSTMT FROM @DEPOSITAMT;
	EXECUTE DEPOSITAMTSTMT;	
	SET DEPOSIT_AMT=@DEPOSIT;	
	IF DEPOSIT_AMT IS NOT NULL THEN
	SET @CUSTOMER_FEE_DEPOSIT=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.CUSTOMER_FEE_DETAILS(CUSTOMER_ID, CED_REC_VER, CPP_ID, CFD_AMOUNT)VALUES(',CUSTID,',',RECVER,',','2',',',DEPOSIT_AMT,')'));
	PREPARE CUSTOMERFEEDEPOSITSTMT FROM @CUSTOMER_FEE_DEPOSIT;
	EXECUTE CUSTOMERFEEDEPOSITSTMT;
	SET @DEPOSIT=NULL;
	END IF;		
	SET @PROCESSINGFEEAMT=(SELECT CONCAT('SELECT PROCESSING_FEE INTO @PROCESSINGFEE FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS WHERE CUSTOMER_ID=',CUSTID, ' AND CED_REC_VER=',RECVER, ' AND PROCESSING_FEE!=0'));
	PREPARE PROCESSINGFEEAMTSTMT FROM @PROCESSINGFEEAMT;
	EXECUTE PROCESSINGFEEAMTSTMT;
	SET PROCESSING_FEE_AMT=@PROCESSINGFEE;	
	IF PROCESSING_FEE_AMT IS NOT NULL THEN
	SET @CUSTOMER_PROCESSING_FEE=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.CUSTOMER_FEE_DETAILS(CUSTOMER_ID, CED_REC_VER, CPP_ID, CFD_AMOUNT)VALUES(',CUSTID,',',RECVER,',','3',',',PROCESSING_FEE_AMT,')'));
	PREPARE CUSTOMERPROCESSINGFEE FROM @CUSTOMER_PROCESSING_FEE;
	EXECUTE CUSTOMERPROCESSINGFEE;
	SET @PROCESSINGFEE=NULL;
	END IF;		
	SET @AIRCONFIXEDFEEAMT=(SELECT CONCAT('SELECT AIRCON_FIXED_FEE INTO @AIRCONFIXEDFEE FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS WHERE CUSTOMER_ID=',CUSTID, ' AND CED_REC_VER=',RECVER, ' AND AIRCON_FIXED_FEE!=0'));
	PREPARE AIRCONFIXEDFEEAMT FROM @AIRCONFIXEDFEEAMT;
	EXECUTE AIRCONFIXEDFEEAMT;	
	SET AIRCON_FIXED_FEE_AMT=@AIRCONFIXEDFEE;		
	IF AIRCON_FIXED_FEE_AMT IS NOT NULL THEN
		SET @CUSTOMER_AIRCON_FIXED_FEE=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.CUSTOMER_FEE_DETAILS(CUSTOMER_ID, CED_REC_VER, CPP_ID, CFD_AMOUNT)VALUES(',CUSTID,',',RECVER,',','4',',',AIRCON_FIXED_FEE_AMT,')'));
		PREPARE CUSTOMERAIRCONFIXEDFEESTMT FROM @CUSTOMER_AIRCON_FIXED_FEE;
		EXECUTE CUSTOMERAIRCONFIXEDFEESTMT;
		SET @AIRCONFIXEDFEE=NULL;
	END IF;			
	SET @ELECTRICITYCAPFEEAMT=(SELECT CONCAT('SELECT ELECTRICITY_CAP INTO @ELECTRICITYCAPFEE FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS WHERE CUSTOMER_ID=',CUSTID, ' AND CED_REC_VER=',RECVER, ' AND ELECTRICITY_CAP!=0'));
	PREPARE ELECTRICITYCAPFEEAMTSTMT FROM @ELECTRICITYCAPFEEAMT;
	EXECUTE ELECTRICITYCAPFEEAMTSTMT;
	SET ELECTRICITY_CAP_AMT=@ELECTRICITYCAPFEE;	
	IF ELECTRICITY_CAP_AMT IS NOT NULL THEN
		SET @CUSTOMER_ELEC_CAP_FEE=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.CUSTOMER_FEE_DETAILS(CUSTOMER_ID, CED_REC_VER, CPP_ID, CFD_AMOUNT)VALUES(',CUSTID,',',RECVER,',','5',',',ELECTRICITY_CAP_AMT,')'));
		PREPARE CUSTOMERELECCAPFEE FROM @CUSTOMER_ELEC_CAP_FEE;
		EXECUTE CUSTOMERELECCAPFEE;
		SET @ELECTRICITYCAPFEE=NULL;
	END IF;		
	SET @DRYCLEAN_FEE_AMT=(SELECT CONCAT('SELECT DRYCLEAN_FEE INTO @DRYCLEANFEE FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS WHERE CUSTOMER_ID=',CUSTID, ' AND CED_REC_VER=',RECVER, ' AND DRYCLEAN_FEE!=0'));
	PREPARE DRYCLEANFEEAMT FROM @DRYCLEAN_FEE_AMT;
	EXECUTE DRYCLEANFEEAMT;		
	SET DRY_CLEAN_FEE_AMT=@DRYCLEANFEE;	
	IF DRY_CLEAN_FEE_AMT IS NOT NULL THEN
		SET @CUSTOMER_DRYCLEAN_FEE=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.CUSTOMER_FEE_DETAILS(CUSTOMER_ID, CED_REC_VER, CPP_ID, CFD_AMOUNT)VALUES(',CUSTID,',',RECVER,',','6',',',DRY_CLEAN_FEE_AMT,')'));
		PREPARE CUSTOMERDRYCLEANFEE FROM @CUSTOMER_DRYCLEAN_FEE;
		EXECUTE CUSTOMERDRYCLEANFEE;
		SET @DRYCLEANFEE=NULL;
	END IF;		
	SET @AIRCON_QUAR_FEE_AMT=(SELECT CONCAT('SELECT AIRCON_QUARTERLY_FEE INTO @AIRCONQUARTELYFEE FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS WHERE CUSTOMER_ID=',CUSTID, ' AND CED_REC_VER=',RECVER, ' AND AIRCON_QUARTERLY_FEE!=0'));
	PREPARE AIRCONQUARFEEAMT FROM @AIRCON_QUAR_FEE_AMT;
	EXECUTE AIRCONQUARFEEAMT;
	SET AIRCON_QUAR_AMT=@AIRCONQUARTELYFEE;	
	IF AIRCON_QUAR_AMT IS NOT NULL THEN
		SET @CUSTOMER_DRYCLEAN_FEE=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.CUSTOMER_FEE_DETAILS(CUSTOMER_ID, CED_REC_VER, CPP_ID, CFD_AMOUNT)VALUES(',CUSTID,',',RECVER,',','7',',',AIRCON_QUAR_AMT,')'));
		PREPARE CUSTOMERDRYCLEANFEE FROM @CUSTOMER_DRYCLEAN_FEE;
		EXECUTE CUSTOMERDRYCLEANFEE;
		SET @AIRCONQUARTELYFEE=NULL;
	END IF;		
	SET @CHECKOUT_CLEANING_FEE_AMT=(SELECT CONCAT('SELECT CHECKOUT_CLEANING_FEE INTO @CHECKOUTCLEANINGFEE FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_TERMINATION_DETAILS WHERE CUSTOMER_ID=',CUSTID, ' AND CED_REC_VER=',RECVER, ' AND CHECKOUT_CLEANING_FEE!=0'));
	PREPARE CHECKOUTCLEANINGFEEAMT FROM @CHECKOUT_CLEANING_FEE_AMT;
	EXECUTE CHECKOUTCLEANINGFEEAMT;
	SET CHECKOUT_CLEANING_AMT=@CHECKOUTCLEANINGFEE;		
	IF CHECKOUT_CLEANING_AMT IS NOT NULL THEN
		SET @CUSTOMER_CHECKOUT_CLEANING_FEE=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.CUSTOMER_FEE_DETAILS(CUSTOMER_ID, CED_REC_VER, CPP_ID, CFD_AMOUNT)VALUES(',CUSTID,',',RECVER,',','8',',',CHECKOUT_CLEANING_AMT,')'));
		PREPARE CUSTOMERCHECKOUTCLEANINGFEE FROM @CUSTOMER_CHECKOUT_CLEANING_FEE;
		EXECUTE CUSTOMERCHECKOUTCLEANINGFEE;
		SET @CHECKOUTCLEANINGFEE=NULL;
	END IF;	
	SET MINCCID=MINCCID+1;
	END WHILE;
		SET END_TIME=(SELECT CURTIME());
		SET DURATION=(SELECT TIMEDIFF(END_TIME,START_TIME));		
	SET @RENT_COUNT=(SELECT CONCAT('SELECT COUNT(*) INTO @RENTAMOUNT FROM ',SOURCESCHEMA,'.CUSTOMER_SCDB_FORMAT WHERE CC_RENT_AMOUNT!=0 AND CC_GUEST_CARD_NO IS NULL'));
	PREPARE RENTAMTSTMT FROM @RENT_COUNT;
	EXECUTE RENTAMTSTMT;	
	SET @DEPOSIT_COUNT=(SELECT CONCAT('SELECT COUNT(*)INTO @DEPOSIT FROM ',SOURCESCHEMA,'.CUSTOMER_SCDB_FORMAT WHERE CC_DEPOSIT!=0 AND CC_GUEST_CARD_NO IS NULL'));
	PREPARE DEPOSITAMT FROM @DEPOSIT_COUNT;
	EXECUTE DEPOSITAMT;		
	SET @PROCESS_FEE_COUNT=(SELECT CONCAT('SELECT COUNT(*)INTO @PROCESS_FEE FROM ',SOURCESCHEMA,'.CUSTOMER_SCDB_FORMAT WHERE CC_PROCESSING_FEE!=0 AND CC_GUEST_CARD_NO IS NULL'));
	PREPARE PROCESSFEEAMT FROM @PROCESS_FEE_COUNT;
	EXECUTE PROCESSFEEAMT;	
	SET @AIRCON_FIXED_COUNT=(SELECT CONCAT('SELECT COUNT(*)INTO @AIRCON_FIXED_FEE FROM ',SOURCESCHEMA,'.CUSTOMER_SCDB_FORMAT WHERE CC_AIRCON_FIXED_FEE!=0 AND CC_GUEST_CARD_NO IS NULL'));
	PREPARE AIRCONFIXEDAMT FROM @AIRCON_FIXED_COUNT;
	EXECUTE AIRCONFIXEDAMT;		
	SET @ELECTRICITY_CAP_COUNT=(SELECT CONCAT('SELECT COUNT(*)INTO @ELECTRICITY_CAP FROM ',SOURCESCHEMA,'.CUSTOMER_SCDB_FORMAT WHERE CC_ELECTRICITY_CAP!=0 AND CC_GUEST_CARD_NO IS NULL'));
	PREPARE ELECCAPAMT FROM @ELECTRICITY_CAP_COUNT;
	EXECUTE ELECCAPAMT;	
	SET @DRYCLEAN_FEE_COUNT=(SELECT CONCAT('SELECT COUNT(*)INTO @DRYCLEAN_FEE FROM ',SOURCESCHEMA,'.CUSTOMER_SCDB_FORMAT WHERE CC_DRYCLEAN_FEE!=0 AND CC_GUEST_CARD_NO IS NULL'));
	PREPARE DRYCLEANFEEAMT FROM @DRYCLEAN_FEE_COUNT;
	EXECUTE DRYCLEANFEEAMT;	
	SET @QUARTELY_FEE_COUNT=(SELECT CONCAT('SELECT COUNT(*)INTO @QUARTELY_FEE FROM ',SOURCESCHEMA,'.CUSTOMER_SCDB_FORMAT WHERE CC_AIRCON_QUARTERLY_FEE!=0 AND CC_GUEST_CARD_NO IS NULL'));
	PREPARE QUARTELYFEEAMT FROM @QUARTELY_FEE_COUNT;
	EXECUTE QUARTELYFEEAMT;	
	SET @CLEANING_FEE_COUNT=(SELECT CONCAT('SELECT COUNT(*)INTO @CLEANING_FEE FROM ',SOURCESCHEMA,'.CUSTOMER_SCDB_FORMAT WHERE CC_CHECKOUT_CLEANING_FEE!=0 AND CC_GUEST_CARD_NO IS NULL'));
	PREPARE CLEANINGFEEAMT FROM @CLEANING_FEE_COUNT;
	EXECUTE CLEANINGFEEAMT;	
	SET @COUNTSCDBCFD=(SELECT CONCAT('SELECT SUM(@RENTAMOUNT+@DEPOSIT+@PROCESS_FEE+@AIRCON_FIXED_FEE+@ELECTRICITY_CAP+@DRYCLEAN_FEE+@QUARTELY_FEE+@CLEANING_FEE)INTO @COUNT_SCDB_CFD'));
	PREPARE COUNT_SCDB_CFDSTMT FROM @COUNTSCDBCFD;
	EXECUTE COUNT_SCDB_CFDSTMT;	
	SET @SPLITTED_CFD_COUNT=(SELECT CONCAT('SELECT COUNT(*)INTO @SPLITTED_CFD FROM ',DESTINATIONSCHEMA,'.CUSTOMER_FEE_DETAILS'));
	PREPARE SPLITTED_CFD_STMT FROM @SPLITTED_CFD_COUNT;
	EXECUTE SPLITTED_CFD_STMT;	
	SET @UP_AUDIT_CFD=(SELECT CONCAT('UPDATE PRE_AUDIT_SUB_PROFILE SET PREASP_NO_OF_REC=@COUNT_SCDB_CFD WHERE PREASP_DATA=',"'CUSTOMER_FEE_DETAILS'"));
	PREPARE UPAUDITCFD FROM @UP_AUDIT_CFD;
	EXECUTE UPAUDITCFD;	
SET @POSTAPIDSTMT=(SELECT CONCAT('SELECT POSTAP_ID INTO @POSTAPID FROM POST_AUDIT_PROFILE WHERE POSTAP_DATA=',"'CUSTOMER_FEE_DETAILS'"));
PREPARE POSTAPSTMT FROM @POSTAPIDSTMT;
EXECUTE POSTAPSTMT;
SET @PREASPSTMT=(SELECT CONCAT('SELECT PREASP_ID INTO @PREASPID FROM PRE_AUDIT_SUB_PROFILE WHERE PREASP_DATA=',"'CUSTOMER_FEE_DETAILS'"));
PREPARE PREASPIDSTMT FROM @PREASPSTMT;
EXECUTE PREASPIDSTMT;
SET @PREAMPSTMT=(SELECT CONCAT('SELECT PREAMP_ID INTO @PREAMPID FROM PRE_AUDIT_MAIN_PROFILE WHERE PREAMP_DATA=',"'CUSTOMER'"));
PREPARE PREAMPIDSTMT FROM @PREAMPSTMT;
EXECUTE PREAMPIDSTMT;
SET @DUR=DURATION;
SET @REJECTION_COUNT=(@COUNT_SCDB_CFD-@SPLITTED_CFD );
SET FOREIGN_KEY_CHECKS=0;
INSERT INTO POST_AUDIT_HISTORY(POSTAP_ID,POSTAH_NO_OF_REC,PREASP_ID,PREAMP_ID,POSTAH_DURATION,POSTAH_NO_OF_REJ,ULD_ID)
VALUES(@POSTAPID,@SPLITTED_CFD,@PREASPID,@PREAMPID,@DUR,@REJECTION_COUNT,@USERSTAMPID);	
SET FOREIGN_KEY_CHECKS=1;
COMMIT;
END;
