DROP PROCEDURE IF EXISTS SP_TEMP_CUSTOMER_ACCESS_CARD_DETAILS;
CREATE PROCEDURE SP_TEMP_CUSTOMER_ACCESS_CARD_DETAILS(IN SOURCESCHEMA VARCHAR(50),IN DESTINATIONSCHEMA VARCHAR(50))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
END;
START TRANSACTION;
SET @DROPTEMPCUSTOMERACCESS=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_ACCESS_CARD_DETAILS'));
PREPARE DRTEMPCUSTOMERACCESS FROM @DROPTEMPCUSTOMERACCESS;
EXECUTE DRTEMPCUSTOMERACCESS;
SET @CREATECUSTOMERACCESS=(SELECT CONCAT('
 CREATE TABLE ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_ACCESS_CARD_DETAILS(
 AC_ID INTEGER,
 AC_FIRST_NAME CHAR(30),
 AC_LAST_NAME CHAR(30),
 AC_CARD INTEGER,
 AC_GUEST_CARD CHAR(1),
 AC_REASON TEXT,
 AC_REC_VER INTEGER,
 AC_UNIT_NO INTEGER,
 AC_VALID_FROM DATE,
 AC_VALID_TILL DATE,
 AC_COMMENTS TEXT,
 ULDID INTEGER,
 ACCESS_TIMESTAMP VARCHAR(50))'));
 PREPARE CREATEACCESSSTMT FROM @CREATECUSTOMERACCESS;
 EXECUTE CREATEACCESSSTMT; 
 SET @DROPTEMPCUSTOMER=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER'));
PREPARE DRTEMPCUSTOMER FROM @DROPTEMPCUSTOMER;
EXECUTE DRTEMPCUSTOMER; 
SET @CREATETEMPCUSTOMER=(SELECT CONCAT('
 CREATE TABLE ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER(
 CC_CUST_ID INTEGER,
 CC_FIRST_NAME CHAR(30),
 CC_LAST_NAME CHAR(30),
 CC_STARTDATE DATE,
 CC_UNIT_NO INTEGER,
 CC_CARD_NO INTEGER)'));
 PREPARE CREATETEMPCUSTOMERSTMT FROM @CREATETEMPCUSTOMER;
 EXECUTE CREATETEMPCUSTOMERSTMT;
 SET @UPDATEACESS=(SELECT CONCAT('UPDATE ',SOURCESCHEMA,'.ACCESS_SCDB_FORMAT SET USERSTAMP=TRIM(USERSTAMP)'));
 PREPARE UPDATEACCESSSTMT FROM @UPDATEACESS;
EXECUTE  UPDATEACCESSSTMT;  
 SET @INSERTACCESS=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_ACCESS_CARD_DETAILS(AC_ID,AC_FIRST_NAME,AC_LAST_NAME,AC_CARD,AC_GUEST_CARD,AC_REASON,AC_REC_VER,AC_UNIT_NO,AC_VALID_FROM,AC_VALID_TILL,AC_COMMENTS,ULDID,ACCESS_TIMESTAMP)
 SELECT ASF.AC_ID,ASF.AC_FIRST_NAME,ASF.AC_LAST_NAME,ASF.AC_CARD,ASF.AC_GUEST_CARD,ASF.AC_REASON,ASF.AC_REC_VER,ASF.AC_UNIT_NO,ASF.AC_VALID_FROM,ASF.AC_VALID_TILL,ASF.AC_COMMENTS,ULD.ULD_ID,ASF.TIMESTAMP FROM ',SOURCESCHEMA,'.ACCESS_SCDB_FORMAT ASF,'
 ,DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS ULD WHERE ULD.ULD_LOGINID=ASF.USERSTAMP'));
 PREPARE INSERTACCESSSTMT FROM @INSERTACCESS;
 EXECUTE INSERTACCESSSTMT; 
 SET @UPDATEACCESS=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_ACCESS_CARD_DETAILS SET AC_LAST_NAME=AC_FIRST_NAME WHERE AC_LAST_NAME IS NULL'));
 PREPARE UPDATEACCESSSTMT FROM @UPDATEACCESS;
 EXECUTE UPDATEACCESSSTMT;
SET @UPDATETIMESTAMP=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_ACCESS_CARD_DETAILS SET ACCESS_TIMESTAMP=(SELECT CONVERT_TZ(ACCESS_TIMESTAMP, "+08:00","+0:00"))'));
PREPARE UPDATETIMESTAMPSTMT FROM @UPDATETIMESTAMP;
EXECUTE UPDATETIMESTAMPSTMT; 
 SET @INSERTTEMPACCESS=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER(CC_CUST_ID,CC_FIRST_NAME,CC_LAST_NAME,CC_STARTDATE,CC_UNIT_NO,CC_CARD_NO)
 SELECT CC_CUST_ID,CC_FIRST_NAME,CC_LAST_NAME,CC_STARTDATE,CC_UNIT_NO,CC_CARD_NO FROM ',SOURCESCHEMA,'.CUSTOMER_SCDB_FORMAT'));
 PREPARE INSERTTEMPACCESSSTMT FROM @INSERTTEMPACCESS;
 EXECUTE INSERTTEMPACCESSSTMT; 
 SET @UPDATETEMPACCESS=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER SET CC_LAST_NAME=CC_FIRST_NAME WHERE CC_LAST_NAME IS NULL'));
 PREPARE UPDATETEMPACCESSSTMT FROM @UPDATETEMPACCESS;
 EXECUTE UPDATETEMPACCESSSTMT; 
SET @DROPACCESSCARD=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.CUSTOMER_ACCESS_CARD_DETAILS'));
PREPARE DRACCESSSTMT FROM @DROPACCESSCARD;
EXECUTE DRACCESSSTMT;
SET @CREATECUSTOMERACCESS=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.CUSTOMER_ACCESS_CARD_DETAILS(
CACD_ID    INTEGER NOT NULL AUTO_INCREMENT,
CUSTOMER_ID	INTEGER NOT NULL,
UASD_ID	INTEGER NOT NULL,
ACN_ID INTEGER NULL,
CACD_VALID_FROM	DATE NOT NULL,
CACD_VALID_TILL	DATE NULL,
CACD_GUEST_CARD	CHAR(1) NULL,
ULD_ID INT(2) NOT NULL,	
CACD_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY(CACD_ID),
FOREIGN KEY(CUSTOMER_ID) REFERENCES ',DESTINATIONSCHEMA,'.CUSTOMER(CUSTOMER_ID),
FOREIGN KEY(UASD_ID) REFERENCES ',DESTINATIONSCHEMA,'.UNIT_ACCESS_STAMP_DETAILS(UASD_ID),
FOREIGN KEY(ULD_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS(ULD_ID))'));
PREPARE CREATECUSTOMERACCESSSTMT FROM @CREATECUSTOMERACCESS;
EXECUTE CREATECUSTOMERACCESSSTMT;
COMMIT;
END;   
