DROP PROCEDURE IF EXISTS SP_ALL_CUSTOMER_MIG_INSERT;
CREATE PROCEDURE SP_ALL_CUSTOMER_MIG_INSERT(IN SOURCESCHEMA VARCHAR(50),IN DESTINATIONSCHEMA VARCHAR(50),IN MIGUSERSTAMP VARCHAR(100))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
END;
START TRANSACTION;
CALL SP_TEMP_CUSTOMER_SCDB_FORMAT(SOURCESCHEMA,DESTINATIONSCHEMA);
CALL SP_MIG_CUSTOMER_INSERT(SOURCESCHEMA,DESTINATIONSCHEMA,MIGUSERSTAMP);
CALL SP_MIG_CUSTOMER_ENTRY_DETAILS(SOURCESCHEMA,DESTINATIONSCHEMA,MIGUSERSTAMP);
CALL SP_TEMP_CUSTOMER_ACCESS_CARD_DETAILS(SOURCESCHEMA,DESTINATIONSCHEMA);
CALL SP_CUSTOMER_ACCESS_CARD_DETAILS(SOURCESCHEMA,DESTINATIONSCHEMA,MIGUSERSTAMP);
COMMIT;
END;
CALL SP_ALL_CUSTOMER_MIG_INSERT(SOURCESCHEMA,DESTINATIONSCHEMA,MIGUSERSTAMP);