-- version:0.4 --startdate:23/05/2014 --enddate:23/05/2014 --issue:817 --ADDED USERSTAMP ID IN DYNAMIC TEMP TABLE CREATION BY PUNI
-- version:0.3 --startdate:26/04/2014 --enddate:26/04/2014 --issue:813 --comment #1,ADDED SYSDATE WITH THE TEMP TABLE CREATION BY PUNI
-- version:0.2 --startdate:22/04/2014 --enddate:22/04/2014 --issue:345 --UPDATED SP TO GET MIN N MAX RV TO FILTER NON STAYING PERIOD BY PUNI
-- version:0.1 --startdate:18/01/2014 --enddate:18/01/2014 --issue:345 --UPDATED SP TO GET MIN N MAX RV OF A CUST BY PUNI

DROP PROCEDURE IF EXISTS SP_CUSTOMER_MIN_MAX_RV;
CREATE PROCEDURE SP_CUSTOMER_MIN_MAX_RV(IN USERSTAMP VARCHAR(50),CUSTID INTEGER,OUT MNMAXTBLNAME TEXT)
BEGIN
DECLARE MIN_CUSTRV INTEGER;
DECLARE MAX_CUSTRV INTEGER;
DECLARE TNAME TEXT;
DECLARE USERSTAMP_ID INT;
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN 
ROLLBACK;
END;
START TRANSACTION;
--  TEMP TABLE NAME START
CALL SP_CHANGE_USERSTAMP_AS_ULDID(USERSTAMP,@ULDID);
SET USERSTAMP_ID=(SELECT @ULDID);
SET TNAME=(SELECT CONCAT('TEMP_CUSTOMER_MIN_MAX_RV_',SYSDATE()));-- temp table name
SET TNAME=(SELECT REPLACE(TNAME,' ',''));
SET TNAME=(SELECT REPLACE(TNAME,'-',''));
SET TNAME=(SELECT REPLACE(TNAME,':',''));
SET TNAME=(SELECT CONCAT(TNAME,'_',USERSTAMP_ID));
SET MNMAXTBLNAME=TNAME; 
--  TEMP TABLE NAME END
SET @CREATE_TEMP_CUSTOMER_MIN_MAX_RV=(SELECT CONCAT('CREATE TABLE ',TNAME,'(TCMM_ID INTEGER AUTO_INCREMENT NOT NULL,TCMM_CUSTOMERID INTEGER,TCMM_MINRV INTEGER,TCMM_MAXRV INTEGER,PRIMARY KEY(TCMM_ID))'));
PREPARE CREATE_TEMP_CUSTOMER_MIN_MAX_RV_STMT FROM @CREATE_TEMP_CUSTOMER_MIN_MAX_RV;
EXECUTE CREATE_TEMP_CUSTOMER_MIN_MAX_RV_STMT;
	-- GET MIN RV IF IT IS RECHKIN
	SET MIN_CUSTRV=(SELECT MAX(CED.CED_REC_VER) FROM CUSTOMER_ENTRY_DETAILS CED,CUSTOMER_LP_DETAILS CLP WHERE CED_RECHECKIN IS NOT NULL AND  IF(CLP.CLP_PRETERMINATE_DATE IS NOT NULL,CLP.CLP_STARTDATE< CLP.CLP_PRETERMINATE_DATE,CLP.CLP_STARTDATE< CLP.CLP_ENDDATE) AND CED.CUSTOMER_ID=CUSTID);
	-- GET MAX RV
	SET MAX_CUSTRV=(SELECT MAX(CED.CED_REC_VER) FROM CUSTOMER_ENTRY_DETAILS CED,CUSTOMER_LP_DETAILS CLP WHERE IF(CLP.CLP_PRETERMINATE_DATE IS NOT NULL,CLP.CLP_STARTDATE< CLP.CLP_PRETERMINATE_DATE,CLP.CLP_STARTDATE< CLP.CLP_ENDDATE) AND CED.CUSTOMER_ID=CUSTID);
	IF MIN_CUSTRV IS NOT NULL THEN
		SET @INSERT_TEMP_CUSTOMER_MIN_MAX_RV=(SELECT CONCAT('INSERT INTO ',TNAME,'(TCMM_CUSTOMERID,TCMM_MINRV,TCMM_MAXRV)VALUES(',CUSTID,',',MIN_CUSTRV,',',MAX_CUSTRV,')'));
		PREPARE INSERT_TEMP_CUSTOMER_MIN_MAX_RV_STMT FROM @INSERT_TEMP_CUSTOMER_MIN_MAX_RV;
		EXECUTE INSERT_TEMP_CUSTOMER_MIN_MAX_RV_STMT;
	ELSE
	-- GET MIN RV IF IT IS NOT RECHKIN
		SET MIN_CUSTRV=(SELECT MIN(CED.CED_REC_VER) FROM CUSTOMER_ENTRY_DETAILS CED,CUSTOMER_LP_DETAILS CLP WHERE IF(CLP.CLP_PRETERMINATE_DATE IS NOT NULL,CLP.CLP_STARTDATE< CLP.CLP_PRETERMINATE_DATE,CLP.CLP_STARTDATE< CLP.CLP_ENDDATE) AND CED.CUSTOMER_ID=CUSTID);
		SET @INSERT_TEMP_CUSTOMER_MIN_MAX_RV=(SELECT CONCAT('INSERT INTO ',TNAME,'(TCMM_CUSTOMERID,TCMM_MINRV,TCMM_MAXRV)VALUES(',CUSTID,',',MIN_CUSTRV,',',MAX_CUSTRV,')'));
		PREPARE INSERT_TEMP_CUSTOMER_MIN_MAX_RV_STMT FROM @INSERT_TEMP_CUSTOMER_MIN_MAX_RV;
		EXECUTE INSERT_TEMP_CUSTOMER_MIN_MAX_RV_STMT;
	END IF;	
COMMIT;
END;
