-- VER 0.5 ISSUE:817 COMMENT #139 STARTDATE:21/06/2014 ENDDATE:21/06/2014 DESC:DROPED TEMP TABLES INSIDE ROLL BACK AND COMMIT DONE BY:DHIVYA.A
--   VER0.04 SD:09/06/2014 ED:09/06/2014 COMMENTS:ADDED ROLLBACK AND COMMIT DONE BY SASIKALA
--   VER0.03 SD:30/04/2014 ED:30/04/2014 COMMENTS:ALL TEMP TABLES CHANGED DYNAMICALLY DONE BY KUMAR R
--  VER 0.2 ISSUE NO:797 COMMENT:#4 STARTDATE:03/04/2014 ENDDATE:03/04/2014 DESC:REPLACED TABLENAME AND HEADERNAME DONE BY:SASIKALA.D
--  VER 0.1 ISSUE NO:345 COMMENT:#564 STARTDATE:08/02/2014 ENDDATE:11/02/2014 DESC:SP FOR CUSTOMER SEARCH DYNAMIC TEMP TABLE DONE BY:DHIVYA.A

DROP PROCEDURE IF EXISTS SP_CUSTOMER_SEARCH_TEMP_TABLE;
CREATE PROCEDURE  SP_CUSTOMER_SEARCH_TEMP_TABLE
(
IN CUSTOMER_SEARCH_FROM_INPUT TEXT,
IN CUSTOMER_SEARCH_TO_INPUT TEXT,
IN SEARCH_OPTION_ID INTEGER,
IN USERSTAMP VARCHAR(50),
OUT TABLENAME TEXT)
BEGIN
--   DECLARATION PART
DECLARE SEARCHOPTION VARCHAR(50);
DECLARE REC_VER INT;
DECLARE MAXCUSTID INT;
DECLARE MONTHNUMBER VARCHAR(10);
DECLARE MONTHSTARTDATE DATE;
DECLARE MONTHENDATE DATE;
DECLARE TEMP_CUSTOMER_LIST TEXT;
DECLARE USERSTAMP_ID TEXT;
DECLARE SYSDATEANDTIME VARCHAR(50);
DECLARE SYSDATEANDULDID VARCHAR(50);
DECLARE FIRST_NAME VARCHAR(30);
DECLARE LAST_NAME VARCHAR(30);
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
IF TEMP_CUSTOMER_LIST IS NOT NULL THEN
SET @DROPQUERY=(SELECT CONCAT('DROP TABLE IF EXISTS ',TEMP_CUSTOMER_LIST));
PREPARE  STMT2 from @DROPQUERY;
EXECUTE STMT2 ;
END IF; 
END;
START TRANSACTION;
--   USERSTAMP ID CONVERT
CALL SP_CHANGE_USERSTAMP_AS_ULDID(USERSTAMP,@ULDID);
SET USERSTAMP_ID=(SELECT @ULDID);
--   GETTING SYSDATE AND TIME
SET SYSDATEANDTIME=(SELECT SYSDATE());
SET SYSDATEANDTIME=(SELECT REPLACE(SYSDATEANDTIME,' ',''));
SET SYSDATEANDTIME=(SELECT REPLACE(SYSDATEANDTIME,'-',''));
SET SYSDATEANDTIME=(SELECT REPLACE(SYSDATEANDTIME,':',''));
SET SYSDATEANDULDID=(SELECT CONCAT(SYSDATEANDTIME,'_',USERSTAMP_ID));
--   CREATE TEMP TABLE NAME
SET TEMP_CUSTOMER_LIST=(SELECT CONCAT('TEMP_CUSTOMER_LIST','',SYSDATEANDULDID));
SET @DYNAMIC_CUSTOMER_LIST_CREATEQUERY=(SELECT CONCAT('CREATE TABLE ',TEMP_CUSTOMER_LIST,'(ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,CUSTOMERID INTEGER,RECVER INTEGER)'));
PREPARE DYNAMIC_CUSTOMER_LIST_CREATESTMT FROM @DYNAMIC_CUSTOMER_LIST_CREATEQUERY;
EXECUTE DYNAMIC_CUSTOMER_LIST_CREATESTMT;
--  SEARCH OPTION INSERT QUERY
IF SEARCH_OPTION_ID=18 THEN
	SET SEARCHOPTION ='CARD_NO';  
	SET @TEMP_CUSTOMER_ID_INSERTQUERY=(SELECT CONCAT('INSERT INTO ',TEMP_CUSTOMER_LIST,'(CUSTOMERID,RECVER) (SELECT CUSTOMER_ID,CED_REC_VER FROM CUSTOMER_LP_DETAILS WHERE UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=',CUSTOMER_SEARCH_FROM_INPUT,'))'));
    END IF;
IF SEARCH_OPTION_ID=19 THEN
	SET SEARCHOPTION ='COMPANY_NAME';
	SET @TEMP_CUSTOMER_ID_INSERTQUERY=(SELECT CONCAT('INSERT INTO ',TEMP_CUSTOMER_LIST,'(CUSTOMERID)(SELECT CUSTOMER_ID FROM CUSTOMER_COMPANY_DETAILS WHERE CCD_COMPANY_NAME= ','"',CUSTOMER_SEARCH_FROM_INPUT,'"',')'));
END IF;
IF SEARCH_OPTION_ID=20 THEN
    SET SEARCHOPTION ='COMMENTS';
	SET @TEMP_CUSTOMER_ID_INSERTQUERY=(SELECT CONCAT('INSERT INTO ',TEMP_CUSTOMER_LIST,'(CUSTOMERID) (SELECT CUSTOMER_ID FROM CUSTOMER_PERSONAL_DETAILS WHERE CPD_COMMENTS= ','"',CUSTOMER_SEARCH_FROM_INPUT,'"',')'));
 END IF;
IF SEARCH_OPTION_ID=21 THEN
    SET SEARCHOPTION ='NAME';
	SET FIRST_NAME = SUBSTRING_INDEX(CUSTOMER_SEARCH_FROM_INPUT, '_', 1);
    SET LAST_NAME = SUBSTRING_INDEX(CUSTOMER_SEARCH_FROM_INPUT, '_', -1);
	SET @TEMP_CUSTOMER_ID_INSERTQUERY=(SELECT CONCAT('INSERT INTO ',TEMP_CUSTOMER_LIST,'(CUSTOMERID) (SELECT CUSTOMER_ID FROM CUSTOMER WHERE CUSTOMER_FIRST_NAME=','"',FIRST_NAME,'"',' AND CUSTOMER_LAST_NAME=','"',LAST_NAME,'"',')'));
END IF;
IF SEARCH_OPTION_ID=22 THEN
	SET SEARCHOPTION ='DEPOSIT';
    SET @TEMP_CUSTOMER_ID_INSERTQUERY=(SELECT CONCAT('INSERT INTO ',TEMP_CUSTOMER_LIST,'(CUSTOMERID,RECVER) (SELECT DISTINCT(CUSTOMER_ID),CED_REC_VER FROM CUSTOMER_FEE_DETAILS WHERE CPP_ID=2 AND CFD_AMOUNT >= ',CUSTOMER_SEARCH_FROM_INPUT,' AND CFD_AMOUNT <= ',CUSTOMER_SEARCH_TO_INPUT,')'));
 END IF;
IF SEARCH_OPTION_ID=23 THEN
    SET SEARCHOPTION ='DOB';
	SET @TEMP_CUSTOMER_ID_INSERTQUERY=(SELECT CONCAT('INSERT INTO ',TEMP_CUSTOMER_LIST,'(CUSTOMERID) (SELECT CUSTOMER_ID FROM CUSTOMER_PERSONAL_DETAILS WHERE CPD_DOB BETWEEN ','"',CUSTOMER_SEARCH_FROM_INPUT,'"',' AND ','"',CUSTOMER_SEARCH_TO_INPUT,'"',')'));
END IF;
IF SEARCH_OPTION_ID=24 THEN
    SET SEARCHOPTION ='EMAIL';
	SET @TEMP_CUSTOMER_ID_INSERTQUERY=(SELECT CONCAT('INSERT INTO ',TEMP_CUSTOMER_LIST,'(CUSTOMERID) (SELECT CUSTOMER_ID FROM CUSTOMER_PERSONAL_DETAILS WHERE CPD_EMAIL= ','"',CUSTOMER_SEARCH_FROM_INPUT,'"',')'));
 END IF;
IF SEARCH_OPTION_ID=25 THEN
    SET SEARCHOPTION ='EP_NUMBER';
	SET @TEMP_CUSTOMER_ID_INSERTQUERY=(SELECT CONCAT('INSERT INTO ',TEMP_CUSTOMER_LIST,'(CUSTOMERID) (SELECT CUSTOMER_ID FROM CUSTOMER_PERSONAL_DETAILS WHERE CPD_EP_NO= ','"',CUSTOMER_SEARCH_FROM_INPUT,'"',')'));
END IF;
IF SEARCH_OPTION_ID=26 THEN
    SET SEARCHOPTION ='MOBILE';
	SET @TEMP_CUSTOMER_ID_INSERTQUERY=(SELECT CONCAT('INSERT INTO ',TEMP_CUSTOMER_LIST,'(CUSTOMERID) (SELECT CUSTOMER_ID FROM CUSTOMER_PERSONAL_DETAILS WHERE CPD_MOBILE= ',CUSTOMER_SEARCH_FROM_INPUT,')'));
END IF;
IF SEARCH_OPTION_ID=27 THEN
    SET SEARCHOPTION ='NATIONALITY';
	SET @TEMP_CUSTOMER_ID_INSERTQUERY=(SELECT CONCAT('INSERT INTO ',TEMP_CUSTOMER_LIST,'(CUSTOMERID) (SELECT CUSTOMER_ID FROM CUSTOMER_PERSONAL_DETAILS WHERE NC_ID= (SELECT NC_ID FROM NATIONALITY_CONFIGURATION WHERE NC_DATA=','"',CUSTOMER_SEARCH_FROM_INPUT,'"','))'));
 END IF;
IF SEARCH_OPTION_ID=28 THEN
    SET SEARCHOPTION ='OFFICE_NUMBER';
	SET @TEMP_CUSTOMER_ID_INSERTQUERY=(SELECT CONCAT('INSERT INTO ',TEMP_CUSTOMER_LIST,'(CUSTOMERID) (SELECT CUSTOMER_ID FROM CUSTOMER_COMPANY_DETAILS WHERE CCD_OFFICE_NO=',CUSTOMER_SEARCH_FROM_INPUT,')'));
 END IF;
IF SEARCH_OPTION_ID=29 THEN
    SET SEARCHOPTION ='PASSPORT_NUMBER';
	SET @TEMP_CUSTOMER_ID_INSERTQUERY=(SELECT CONCAT('INSERT INTO ',TEMP_CUSTOMER_LIST,'(CUSTOMERID) (SELECT CUSTOMER_ID FROM CUSTOMER_PERSONAL_DETAILS WHERE CPD_PASSPORT_NO=','"',CUSTOMER_SEARCH_FROM_INPUT,'"',')'));
	END IF;
IF SEARCH_OPTION_ID=30 THEN
	SET SEARCHOPTION ='PAYMENT';
	SET @TEMP_CUSTOMER_ID_INSERTQUERY=(SELECT CONCAT('INSERT INTO ',TEMP_CUSTOMER_LIST,'(CUSTOMERID,RECVER)(SELECT DISTINCT(CUSTOMER_ID),CED_REC_VER FROM CUSTOMER_FEE_DETAILS WHERE CPP_ID=1 AND CFD_AMOUNT >= ',CUSTOMER_SEARCH_FROM_INPUT,' AND CFD_AMOUNT <= ',CUSTOMER_SEARCH_TO_INPUT,')'));
	END IF;
IF SEARCH_OPTION_ID=31 THEN
	SET SEARCHOPTION ='UNIT_NUMBER';
	SET @TEMP_CUSTOMER_ID_INSERTQUERY=(SELECT CONCAT('INSERT INTO ',TEMP_CUSTOMER_LIST,'(CUSTOMERID,RECVER) (SELECT CUSTOMER_ID,CED_REC_VER FROM CUSTOMER_ENTRY_DETAILS WHERE UNIT_ID=(SELECT UNIT_ID FROM UNIT WHERE UNIT_NO=',CUSTOMER_SEARCH_FROM_INPUT,'))'));
   END IF;
IF SEARCH_OPTION_ID=32 THEN
    SET SEARCHOPTION ='INTL_MOBILE';
	SET @TEMP_CUSTOMER_ID_INSERTQUERY=(SELECT CONCAT('INSERT INTO ',TEMP_CUSTOMER_LIST,'(CUSTOMERID) (SELECT CUSTOMER_ID FROM CUSTOMER_PERSONAL_DETAILS WHERE CPD_INTL_MOBILE=',CUSTOMER_SEARCH_FROM_INPUT,')'));
    END IF;
IF SEARCH_OPTION_ID=33 THEN
	SET SEARCHOPTION ='ROOM_TYPE';
	SET @TEMP_CUSTOMER_ID_INSERTQUERY=(SELECT CONCAT('INSERT INTO ',TEMP_CUSTOMER_LIST,'(CUSTOMERID,RECVER)  (SELECT CUSTOMER_ID,CED_REC_VER FROM CUSTOMER_ENTRY_DETAILS WHERE UASD_ID IN(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE URTD_ID IN (SELECT URTD_ID FROM UNIT_ROOM_TYPE_DETAILS WHERE URTD_ROOM_TYPE=','"',CUSTOMER_SEARCH_FROM_INPUT,'"',')))'));
    END IF;
IF SEARCH_OPTION_ID=34 THEN
    SET SEARCHOPTION ='LP';
    SET MONTHNUMBER=(SELECT SUBSTRING(CUSTOMER_SEARCH_FROM_INPUT,1,3));
    SET MONTHSTARTDATE=(SELECT CONCAT((SELECT SUBSTRING_INDEX(CUSTOMER_SEARCH_FROM_INPUT, '-', -1)),'-',(SELECT MONTH(STR_TO_DATE(MONTHNUMBER,'%b'))),'-','01'));
    SET MONTHENDATE=(SELECT LAST_DAY(MONTHSTARTDATE));
	SET @TEMP_CUSTOMER_ID_INSERTQUERY=(SELECT CONCAT('INSERT INTO ',TEMP_CUSTOMER_LIST,'(CUSTOMERID,RECVER)(SELECT CUSTOMER_ID,CED_REC_VER FROM CUSTOMER_LP_DETAILS WHERE (CLP_STARTDATE BETWEEN ','"',MONTHSTARTDATE,'"',' AND ','"',MONTHENDATE,'"',' OR CLP_ENDDATE BETWEEN ','"',MONTHSTARTDATE,'"',' AND ','"',MONTHENDATE,'"',') AND CLP_GUEST_CARD IS NULL)'));
END IF;
	PREPARE DYNAMIC_CUSTOMERID_TABLE FROM @TEMP_CUSTOMER_ID_INSERTQUERY;
	EXECUTE DYNAMIC_CUSTOMERID_TABLE;
--    TEMP CUSTOMER FEE DETAIL TABLE CREATION	
    SET TABLENAME=(SELECT CONCAT('TEMP_CUSTOMER_SEARCH_',SEARCHOPTION ,'_','FEE_DETAIL',SYSDATEANDULDID));
    SET @TABLENAME123=(SELECT CONCAT('TEMP_CUSTOMER_SEARCH_',SEARCHOPTION ,'_','FEE_DETAIL',SYSDATEANDULDID));
    SET @CREATEQUERY=(SELECT CONCAT('CREATE TABLE ',TABLENAME,'(SNO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT,
    CUSTOMER_REC_VER INT,
    CC_PAYMENT_AMOUNT DECIMAL(7,2),
    CC_DEPOSIT DECIMAL(7,2),
    CC_PROCESSING_FEE DECIMAL(7,2),
    CC_AIRCON_FIXED_FEE DECIMAL(7,2),
    CC_ELECTRICITY_CAP DECIMAL(7,2),
    CC_DRYCLEAN_FEE DECIMAL(7,2),
    CC_AIRCON_QUARTERLY_FEE DECIMAL(7,2),
    CC_CHECKOUT_CLEANING_FEE DECIMAL(7,2))'));
    PREPARE  STMT3 from @CREATEQUERY;
    EXECUTE STMT3 ;
--   INSERTING TEMP CUSTOMER FEE DETAILS RECORDS
  IF((SEARCH_OPTION_ID=19) OR (SEARCH_OPTION_ID=20) OR (SEARCH_OPTION_ID=21) OR (SEARCH_OPTION_ID=23) OR  (SEARCH_OPTION_ID=24) OR  (SEARCH_OPTION_ID=25) OR  (SEARCH_OPTION_ID=26) OR  (SEARCH_OPTION_ID=27) OR  (SEARCH_OPTION_ID=28) OR  (SEARCH_OPTION_ID=29) OR (SEARCH_OPTION_ID=32))THEN
    SET @CUST_MAX_ID_STMT = (SELECT CONCAT('SELECT MAX(ID)INTO @MAXID FROM ',TEMP_CUSTOMER_LIST));
    PREPARE CUST_MAX_ID_STATEMENT FROM @CUST_MAX_ID_STMT;
    EXECUTE CUST_MAX_ID_STATEMENT;
    SET MAXCUSTID=@MAXID;
    WHILE MAXCUSTID!=0 DO
	    SET @CUST_MINIDSTMT = (SELECT CONCAT('SELECT MAX(CED_REC_VER)INTO @TEMPMINID FROM CUSTOMER_FEE_DETAILS WHERE CUSTOMER_ID=(SELECT CUSTOMERID FROM  ',TEMP_CUSTOMER_LIST,' WHERE ID=',MAXCUSTID,')'));
	    PREPARE CUST_MINID_STATEMENT FROM @CUST_MINIDSTMT;
	    EXECUTE CUST_MINID_STATEMENT;
	    SET REC_VER=@TEMPMINID;
	   WHILE REC_VER !=0 DO
	      SET @CUSTOMER_ID_STMT =(SELECT CONCAT('SELECT CUSTOMERID INTO @TEMPCUSTID FROM  ',TEMP_CUSTOMER_LIST,' WHERE ID=',MAXCUSTID));
	      PREPARE CUSTOMER_ID_STATEMENT FROM @CUSTOMER_ID_STMT;
	      EXECUTE CUSTOMER_ID_STATEMENT;
	      SET @TEMP_CUSTOMERID=@TEMPCUSTID;
		    IF EXISTS (SELECT CED_REC_VER FROM CUSTOMER_FEE_DETAILS WHERE CUSTOMER_ID=@TEMP_CUSTOMERID AND CED_REC_VER=REC_VER) THEN
			    SET @ID=MAXCUSTID;
			    SET @RECVER=REC_VER;	
		      SET @TEMP_CUSTID=(SELECT CONCAT('SELECT CUSTOMERID INTO @TEMP_CUSTOMERID FROM ',TEMP_CUSTOMER_LIST,' WHERE ID=',@ID));
			    PREPARE TEMP_CUSTID_STMT FROM @TEMP_CUSTID;
			    EXECUTE TEMP_CUSTID_STMT;
			    SET @CUSTID=@TEMP_CUSTOMERID;
			    SET @PAYMENTAMOUNT=(SELECT CFD_AMOUNT FROM CUSTOMER_FEE_DETAILS WHERE CUSTOMER_ID=@CUSTID AND CED_REC_VER=@RECVER AND CPP_ID=1);
			    SET @DEPOSIT=(SELECT CFD_AMOUNT FROM CUSTOMER_FEE_DETAILS WHERE CUSTOMER_ID=@CUSTID AND CED_REC_VER=@RECVER AND CPP_ID=2);
			    SET @PROCESSING_FEE=(SELECT CFD_AMOUNT FROM CUSTOMER_FEE_DETAILS WHERE CUSTOMER_ID=@CUSTID AND CED_REC_VER=@RECVER AND CPP_ID=3);
			    SET @AIRCON_FIXED_FEE=(SELECT CFD_AMOUNT FROM CUSTOMER_FEE_DETAILS WHERE CUSTOMER_ID=@CUSTID AND CED_REC_VER=@RECVER AND CPP_ID=4);
			    SET @ELECTRICITY_CAP=(SELECT CFD_AMOUNT FROM CUSTOMER_FEE_DETAILS WHERE CUSTOMER_ID=@CUSTID AND CED_REC_VER=@RECVER AND CPP_ID=5);
			    SET @DRYCLEANFEE=(SELECT CFD_AMOUNT FROM CUSTOMER_FEE_DETAILS WHERE CUSTOMER_ID=@CUSTID AND CED_REC_VER=@RECVER AND CPP_ID=6);
			    SET @AIRCON_QUARTELY_FEE=(SELECT CFD_AMOUNT FROM CUSTOMER_FEE_DETAILS WHERE CUSTOMER_ID=@CUSTID AND CED_REC_VER=@RECVER AND CPP_ID=7);
			    SET @CHECKOUT_CLEANING_FEE=(SELECT CFD_AMOUNT FROM CUSTOMER_FEE_DETAILS WHERE CUSTOMER_ID=@CUSTID AND CED_REC_VER=@RECVER AND CPP_ID=8);
			    SET @INSERTQUERY=(SELECT CONCAT('INSERT INTO ',TABLENAME,'(CUSTOMER_ID,CUSTOMER_REC_VER,CC_PAYMENT_AMOUNT,CC_DEPOSIT,CC_PROCESSING_FEE,CC_AIRCON_FIXED_FEE,CC_ELECTRICITY_CAP,CC_DRYCLEAN_FEE,CC_AIRCON_QUARTERLY_FEE,CC_CHECKOUT_CLEANING_FEE)VALUES(@CUSTID,@RECVER, @PAYMENTAMOUNT, @DEPOSIT, @PROCESSING_FEE,@AIRCON_FIXED_FEE,@ELECTRICITY_CAP,@DRYCLEANFEE,@AIRCON_QUARTELY_FEE,@CHECKOUT_CLEANING_FEE)'));
			    PREPARE  STMT4 from @INSERTQUERY;
			    EXECUTE STMT4 ;
	     	END IF;
		    SET REC_VER=REC_VER-1;
	    END WHILE;
	    SET MAXCUSTID=MAXCUSTID-1;
    END WHILE;
ELSE
    SET @CUST_MAX_ID_STMT = (SELECT CONCAT('SELECT MAX(ID)INTO @MAXID FROM ',TEMP_CUSTOMER_LIST));
    PREPARE CUST_MAX_ID_STATEMENT FROM @CUST_MAX_ID_STMT;
    EXECUTE CUST_MAX_ID_STATEMENT;
    SET MAXCUSTID=@MAXID;
    WHILE MAXCUSTID!=0 DO
	  SET @AUTOID=MAXCUSTID;
	  SET @TEMP_CUSTID=(SELECT CONCAT('SELECT CUSTOMERID INTO @TEMP_CUSTOMERID FROM ',TEMP_CUSTOMER_LIST,' WHERE ID=',@AUTOID));
	  PREPARE TEMP_CUSTID_STMT FROM @TEMP_CUSTID;
	  EXECUTE TEMP_CUSTID_STMT;
	  SET @CUSTOMERID=@TEMP_CUSTOMERID;
      SET @TEMP_RECVER=(SELECT CONCAT('SELECT RECVER INTO @TEMP_RECVER FROM ',TEMP_CUSTOMER_LIST,' WHERE ID=',@AUTOID));
	  PREPARE TEMP_RECVER_STMT FROM @TEMP_RECVER;
	  EXECUTE TEMP_RECVER_STMT;
	  SET @RECVERSION=@TEMP_RECVER;
      SET @PAYMENTAMOUNT=(SELECT CFD_AMOUNT FROM CUSTOMER_FEE_DETAILS WHERE CUSTOMER_ID=@CUSTOMERID AND CED_REC_VER=@RECVERSION AND CPP_ID=1);
      SET @DEPOSIT=(SELECT CFD_AMOUNT FROM CUSTOMER_FEE_DETAILS WHERE CUSTOMER_ID=@CUSTOMERID AND CED_REC_VER=@RECVERSION AND CPP_ID=2);
      SET @PROCESSING_FEE=(SELECT CFD_AMOUNT FROM CUSTOMER_FEE_DETAILS WHERE CUSTOMER_ID=@CUSTOMERID AND CED_REC_VER=@RECVERSION AND CPP_ID=3);
      SET @AIRCON_FIXED_FEE=(SELECT CFD_AMOUNT FROM CUSTOMER_FEE_DETAILS WHERE CUSTOMER_ID=@CUSTOMERID AND CED_REC_VER=@RECVERSION AND CPP_ID=4);
      SET @ELECTRICITY_CAP=(SELECT CFD_AMOUNT FROM CUSTOMER_FEE_DETAILS WHERE CUSTOMER_ID=@CUSTOMERID AND CED_REC_VER=@RECVERSION AND CPP_ID=5);
      SET @DRYCLEANFEE=(SELECT CFD_AMOUNT FROM CUSTOMER_FEE_DETAILS WHERE CUSTOMER_ID=@CUSTOMERID AND CED_REC_VER=@RECVERSION AND CPP_ID=6);
      SET @AIRCON_QUARTELY_FEE=(SELECT CFD_AMOUNT FROM CUSTOMER_FEE_DETAILS WHERE CUSTOMER_ID=@CUSTOMERID AND CED_REC_VER=@RECVERSION AND CPP_ID=7);
      SET @CHECKOUT_CLEANING_FEE=(SELECT CFD_AMOUNT FROM CUSTOMER_FEE_DETAILS WHERE CUSTOMER_ID=@CUSTOMERID AND CED_REC_VER=@RECVERSION  AND CPP_ID=8);
      SET @INSERTQUERY=(SELECT CONCAT('INSERT INTO ',TABLENAME,'(CUSTOMER_ID,CUSTOMER_REC_VER,CC_PAYMENT_AMOUNT,CC_DEPOSIT,CC_PROCESSING_FEE,CC_AIRCON_FIXED_FEE,CC_ELECTRICITY_CAP,CC_DRYCLEAN_FEE,CC_AIRCON_QUARTERLY_FEE,CC_CHECKOUT_CLEANING_FEE)VALUES(@CUSTOMERID,@RECVERSION, @PAYMENTAMOUNT, @DEPOSIT, @PROCESSING_FEE,@AIRCON_FIXED_FEE,@ELECTRICITY_CAP,@DRYCLEANFEE,@AIRCON_QUARTELY_FEE,@CHECKOUT_CLEANING_FEE)'));
      PREPARE  STMT4 from @INSERTQUERY;
      EXECUTE STMT4 ;
      SET MAXCUSTID=MAXCUSTID-1;
    END WHILE;
  END IF;
 --   DROP QUERY FOR TEMP CUSTOMER LIST TABLE
SET @DROPQUERY=(SELECT CONCAT('DROP TABLE IF EXISTS ',TEMP_CUSTOMER_LIST));
PREPARE  STMT2 from @DROPQUERY;
EXECUTE STMT2 ;
COMMIT;
END;
