
-- STARHUB

-- QUERY FOR FINDING DUPLICATE INVOICE DATE FOR STARHUB
CREATE OR REPLACE VIEW VW_SUB_STARHUB AS SELECT U.UNIT_NO,E.ESH_ID,E.ESH_INVOICE_DATE,E.ESH_FROM_PERIOD,E.ESH_TO_PERIOD,E.ESH_AMOUNT,E.ESH_COMMENTS,E.ULD_ID,E.ESH_TIMESTAMP FROM EXPENSE_STARHUB E,EXPENSE_DETAIL_STARHUB EDS,UNIT U
WHERE E.EDSH_ID=EDS.EDSH_ID AND EDS.UNIT_ID=U.UNIT_ID GROUP BY U.UNIT_NO,E.ESH_INVOICE_DATE;


CREATE OR REPLACE VIEW VW_SUB_SHUB AS SELECT ES.*
FROM EXPENSE_STARHUB ES LEFT JOIN   VW_SUB_STARHUB V ON ES.ESH_ID = V.ESH_ID
WHERE V.ESH_ID IS NULL;

SELECT U.UNIT_NO,E.* FROM EXPENSE_STARHUB E,EXPENSE_DETAIL_STARHUB EDS,VW_SUB_SHUB V,UNIT U WHERE V.EDSH_ID=E.EDSH_ID AND V.ESH_INVOICE_DATE=E.ESH_INVOICE_DATE AND EDS.UNIT_ID=U.UNIT_ID AND E.EDSH_ID = EDS.EDSH_ID AND V.EDSH_ID=EDS.EDSH_ID GROUP BY E.ESH_ID ORDER BY U.UNIT_NO,E.EDSH_ID;

-- ELECTRICITY

-- QUERY FOR FINDING DUPLICATE INVOICE DATE FOR ELECTRICITY
CREATE OR REPLACE VIEW VW_SUB_ELECTRICITY AS SELECT U.UNIT_NO,E.EE_ID,E.EE_INVOICE_DATE,E.EE_FROM_PERIOD,E.ECN_ID,E.EE_AMOUNT,E.EE_COMMENTS,E.ULD_ID,E.EE_TIMESTAMP FROM EXPENSE_ELECTRICITY E,EXPENSE_DETAIL_ELECTRICITY EDE,UNIT U WHERE E.EDE_ID=EDE.EDE_ID AND EDE.UNIT_ID=U.UNIT_ID GROUP BY U.UNIT_NO,E.EE_INVOICE_DATE,E.ECN_ID;

CREATE OR REPLACE VIEW VW_SUB_ELEC AS SELECT EE.*
FROM EXPENSE_ELECTRICITY EE LEFT JOIN   VW_SUB_ELECTRICITY V ON EE.EE_ID = V.EE_ID
WHERE V.EE_ID IS NULL;

SELECT U.UNIT_NO,E.* FROM EXPENSE_ELECTRICITY E,EXPENSE_DETAIL_ELECTRICITY EDS,VW_SUB_ELEC V,UNIT U WHERE V.EDE_ID=E.EDE_ID AND V.EE_INVOICE_DATE=E.EE_INVOICE_DATE AND EDS.UNIT_ID=U.UNIT_ID AND E.EDE_ID = EDS.EDE_ID AND V.EDE_ID=EDS.EDE_ID AND V.ECN_ID=E.ECN_ID GROUP BY E.EE_ID ORDER BY U.UNIT_NO,E.EDE_ID;

