DROP PROCEDURE IF EXISTS SP_ROLE_CREATION_INSERT;
CREATE PROCEDURE SP_ROLE_CREATION_INSERT(
CUSTOM_ROLE VARCHAR(15),
BASIC_ROLE TEXT,
MENUID TEXT,
FILEID TEXT,
USERSTAMP VARCHAR(50),
DB_NAME VARCHAR(20),
OUT SUCCESS_FLAG INTEGER)
BEGIN
DECLARE MENU_LENGTH INTEGER;
DECLARE TEMP_MENU TEXT;
DECLARE MENU INTEGER;
DECLARE MENU_POSITION INTEGER;
DECLARE TEMP_FILE TEXT;
DECLARE FPID INTEGER;
DECLARE FILE_POSITION INTEGER;
DECLARE FILE_LENGTH INTEGER;
DECLARE GRANT_MP_ID TEXT DEFAULT "'";
DECLARE USER_NAME VARCHAR(50);
DECLARE V_USER_COUNT  SMALLINT(1);
DECLARE V_STRLEN    INT DEFAULT 0;
DECLARE V_SUBSTRLEN INT DEFAULT 0;
DECLARE V_MENU_ID   INT;
DECLARE USERSTAMP_ID INTEGER(2);
DECLARE TEMP_PM_TABLE TEXT;
DECLARE TEMP_PM_UNIQUE_TABLE TEXT;
DECLARE TEMP_PM_SP_TABLE TEXT;
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN 
	ROLLBACK; 
    SET SUCCESS_FLAG=0;
IF TEMP_PM_TABLE IS NOT NULL THEN
SET @DROP_TEMP_PM=(SELECT CONCAT('DROP TABLE IF EXISTS ',TEMP_PM_TABLE));
PREPARE DROP_TEMP_PM_STMT FROM @DROP_TEMP_PM;
EXECUTE DROP_TEMP_PM_STMT;
END IF;
IF TEMP_PM_UNIQUE_TABLE IS NOT NULL THEN
SET @DROP_TEMP_UNIQUE=(SELECT CONCAT('DROP TABLE IF EXISTS ',TEMP_PM_UNIQUE_TABLE));
PREPARE DROP_TEMP_UNIQUE_STMT FROM @DROP_TEMP_UNIQUE;
EXECUTE DROP_TEMP_UNIQUE_STMT;
END IF;
IF TEMP_PM_SP_TABLE IS NOT NULL THEN
SET @DROP_TEMP_PM_SP_TABLE=(SELECT CONCAT('DROP TABLE IF EXISTS ',TEMP_PM_SP_TABLE));
PREPARE DROP_TEMP_PM_SP_TABLE_STMT FROM @DROP_TEMP_PM_SP_TABLE;
EXECUTE DROP_TEMP_PM_SP_TABLE_STMT;
END IF;
END;
START TRANSACTION;
SET AUTOCOMMIT = 0;
CALL SP_CHANGE_USERSTAMP_AS_ULDID(USERSTAMP,@ULDID);
SET USERSTAMP_ID = (SELECT @ULDID);
	IF CUSTOM_ROLE IS NOT NULL AND BASIC_ROLE IS NOT NULL THEN
      IF NOT EXISTS (SELECT RC_ID FROM ROLE_CREATION WHERE RC_NAME = CUSTOM_ROLE) THEN
        INSERT INTO ROLE_CREATION(URC_ID,RC_NAME,RC_USERSTAMP) VALUES ((SELECT URC_ID FROM USER_RIGHTS_CONFIGURATION WHERE URC_DATA=BASIC_ROLE),CUSTOM_ROLE,USERSTAMP);
              SET SUCCESS_FLAG=1;
      END IF;
		END IF;
IF MENUID IS NOT NULL THEN
  SET TEMP_MENU = MENUID;
  SET MENU_LENGTH = 1;
 loop_label : LOOP
		SET MENU_POSITION=(SELECT LOCATE(',', TEMP_MENU,MENU_LENGTH));
		IF MENU_POSITION<=0 THEN
			SET MENU=TEMP_MENU;
		ELSE
			SELECT SUBSTRING(TEMP_MENU,MENU_LENGTH,MENU_POSITION-1) INTO MENU;
			SET TEMP_MENU=(SELECT SUBSTRING(TEMP_MENU,MENU_POSITION+1));
		END IF;
		INSERT INTO USER_MENU_DETAILS(MP_ID,RC_ID,ULD_ID)VALUES(MENU,(SELECT RC_ID FROM ROLE_CREATION WHERE RC_NAME=CUSTOM_ROLE),USERSTAMP_ID);
        SET SUCCESS_FLAG=1;
		IF MENU_POSITION<=0 THEN
			LEAVE  loop_label;
		END IF;
	END LOOP;
END IF;
IF FILEID IS NOT NULL THEN
	SET TEMP_FILE = FILEID;
	SET FILE_LENGTH=1;
	loop_label:  LOOP
		SET FILE_POSITION=(SELECT LOCATE(',', TEMP_FILE,FILE_LENGTH));
		IF FILE_POSITION<=0 THEN
			SET FPID=TEMP_FILE;
		ELSE
			SELECT SUBSTRING(TEMP_FILE,FILE_LENGTH,FILE_POSITION-1) INTO FPID;
			SET TEMP_FILE=(SELECT SUBSTRING(TEMP_FILE,FILE_POSITION+1));
		END IF;
		INSERT INTO USER_FILE_DETAILS(RC_ID,FP_ID,ULD_ID)VALUES((SELECT RC_ID FROM ROLE_CREATION WHERE RC_NAME=CUSTOM_ROLE),FPID,USERSTAMP_ID);
        SET SUCCESS_FLAG=1;
		IF FILE_POSITION<=0 THEN
			LEAVE  loop_label;
		END IF;
	END LOOP;
END IF; 
MAIN_LOOP:
  LOOP
    SET V_STRLEN = CHAR_LENGTH(MENUID);
    SET V_MENU_ID = SUBSTRING_INDEX(MENUID, ',', 1);   
    SET GRANT_MP_ID = CONCAT (GRANT_MP_ID,V_MENU_ID,''',''');
    SET V_SUBSTRLEN = CHAR_LENGTH(SUBSTRING_INDEX(MENUID, ',', 1)) + 2;
    SET MENUID = MID(MENUID, V_SUBSTRLEN, V_STRLEN);
    IF MENUID = '' THEN
      LEAVE MAIN_LOOP;
    END IF;    
  END LOOP MAIN_LOOP;
  SET GRANT_MP_ID = SUBSTRING(GRANT_MP_ID,1,CHAR_LENGTH(GRANT_MP_ID)-2);
      SET USER_NAME = CUSTOM_ROLE;
      SET @user_name = USER_NAME;
      select count(user) into V_USER_COUNT from mysql.user WHERE USER = @user_name;
      IF V_USER_COUNT = 0 THEN
      SET @sql = CONCAT('CREATE USER ''',USER_NAME,'''@','''%''',' IDENTIFIED BY ''',USER_NAME,"'");
       PREPARE s1 FROM @sql;
       EXECUTE s1;
       DEALLOCATE PREPARE s1;
       END IF;
CALL SP_PLATFORM_MGMT_DB_USER_RIGHTS_GRANT_REVOKE(DB_NAME, USER_NAME, GRANT_MP_ID,'GRANT',USERSTAMP_ID,@TEMP_PM_UNIQUE_TABLE_NAMES,@TEMP_UNIQUE_TABLE_NAMES,@TEMP_PM_UNIQUE_SP_NAMES);
SET TEMP_PM_TABLE=@TEMP_UNIQUE_TABLE_NAMES;
SET TEMP_PM_UNIQUE_TABLE=@TEMP_PM_UNIQUE_TABLE_NAMES;
SET TEMP_PM_SP_TABLE=@TEMP_PM_UNIQUE_SP_NAMES;
IF TEMP_PM_TABLE IS NOT NULL THEN
SET @DROP_TEMP_PM=(SELECT CONCAT('DROP TABLE IF EXISTS ',TEMP_PM_TABLE));
PREPARE DROP_TEMP_PM_STMT FROM @DROP_TEMP_PM;
EXECUTE DROP_TEMP_PM_STMT;
END IF;
IF TEMP_PM_UNIQUE_TABLE IS NOT NULL THEN
SET @DROP_TEMP_UNIQUE=(SELECT CONCAT('DROP TABLE IF EXISTS ',TEMP_PM_UNIQUE_TABLE));
PREPARE DROP_TEMP_UNIQUE_STMT FROM @DROP_TEMP_UNIQUE;
EXECUTE DROP_TEMP_UNIQUE_STMT;
END IF;
IF TEMP_PM_SP_TABLE IS NOT NULL THEN
SET @DROP_TEMP_PM_SP_TABLE=(SELECT CONCAT('DROP TABLE IF EXISTS ',TEMP_PM_SP_TABLE));
PREPARE DROP_TEMP_PM_SP_TABLE_STMT FROM @DROP_TEMP_PM_SP_TABLE;
EXECUTE DROP_TEMP_PM_SP_TABLE_STMT;
END IF;
COMMIT;
END;
