-- VER 0.3, STARTDATE:14/07/2014,ENDDATE:14/07/2014,TRACKER NO:694,COMMENTNO:#33 DESC:UPDATED UNSIGNED ZERO FOR UNIT NUMBER(3)
-- VER 0.2, STARTDATE:09/06/2014, END DATE:09/06/2014, TRACKER NO:566  COMMENTNO:#12, DESC:ADDED ROLLBACK AND COMMIT DONE BY:SASIKALA
-- VER 0.1, STARTDATE:17/05/2014, END DATE:17/05/2014, TRACKER NO:743  COMMENTNO:#168, DESC:SPLITTED THE SP CUSTOMER_TICKLER_DATA FOR DYNAMIC RUNNING PROCESS DONE BY:BHAVANI.R
DROP PROCEDURE IF EXISTS SP_CUSTOMER_TICKLER_PAYMENT_DETAILS;
CREATE PROCEDURE SP_CUSTOMER_TICKLER_PAYMENT_DETAILS()
BEGIN 
DECLARE FINAL_UNITNOPYMT SMALLINT(4) UNSIGNED ZEROFILL;
DECLARE NEWFINAL_UNITNO SMALLINT(4) UNSIGNED ZEROFILL;
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
END;
START TRANSACTION;
				PD_OV_CS_LOOP : LOOP
              
					CALL SP_GET_SPECIAL_CHARACTER_SEPERATED_VALUES(',',@TH_OLD_VALUE,@VALUE,@REMAINING_STRING);
					SELECT @REMAINING_STRING INTO @TH_OLD_VALUE;
              
					-- SEPERATING COLUMN NAME AND COLUMN VALUE 
					CALL SP_GET_SPECIAL_CHARACTER_SEPERATED_VALUES('=',@VALUE,@COLUMN_NAME,@COLUMN_VALUE);
              
            
					IF UPPER(@COLUMN_NAME) = 'UNIT_ID' THEN
						SELECT UNIT_NO INTO @UNIT_NO FROM UNIT WHERE UNIT_ID = @COLUMN_VALUE;
						IF(LENGTH (@UNIT_NO)=3 )THEN
						SET FINAL_UNITNOPYMT=(SELECT CONCAT ('0',@UNIT_NO));
						ELSE
						SET FINAL_UNITNOPYMT=@UNIT_NO;
						END IF;
						SET @REPLACE_STRING = CONCAT('UNIT_NO=',@UNIT_NO);
						SELECT REPLACE(@V_TEMP_OLD_VALUE,@VALUE,@REPLACE_STRING) INTO @V_TEMP_OLD_VALUE;
					END IF;
			  
					IF UPPER(@COLUMN_NAME) = 'CUSTOMER_ID' THEN
						SELECT CUSTOMER_FIRST_NAME,CUSTOMER_LAST_NAME INTO @FIRST_NAME_VALUE,@LAST_NAME_VALUE FROM CUSTOMER WHERE CUSTOMER_ID = @COLUMN_VALUE;
						SET @REPLACE_STRING = CONCAT('CUSTOMER_FIRST_NAME=',@FIRST_NAME_VALUE,',CUSTOMER_LAST_NAME=',@LAST_NAME_VALUE);
						SELECT REPLACE(@V_TEMP_OLD_VALUE,@VALUE,@REPLACE_STRING) INTO @V_TEMP_OLD_VALUE;
					END IF;
              
					IF UPPER(@COLUMN_NAME) = 'PP_ID' THEN
						SELECT PP_DATA INTO @PPDATA FROM PAYMENT_PROFILE WHERE PP_ID = @COLUMN_VALUE;
						SET @REPLACE_STRING = CONCAT('PP_DATA=',@PPDATA);
						SELECT REPLACE(@V_TEMP_OLD_VALUE,@VALUE,@REPLACE_STRING) INTO @V_TEMP_OLD_VALUE;
					END IF;
                       
					IF UPPER(@COLUMN_NAME) = 'ULD_ID' THEN
						SELECT ULD_LOGINID INTO @OLDPAYMENTDETAILID FROM USER_LOGIN_DETAILS WHERE ULD_ID = @COLUMN_VALUE;
						SET @REPLACE_STRING = CONCAT('ULD_LOGINID=',@OLDPAYMENTDETAILID);
						SELECT REPLACE(@V_TEMP_OLD_VALUE,@VALUE,@REPLACE_STRING) INTO @V_TEMP_OLD_VALUE;
						LEAVE PD_OV_CS_LOOP;
					END IF;	
              
					IF @TH_OLD_VALUE IS NULL THEN
						LEAVE  PD_OV_CS_LOOP;
					END IF;
	           END LOOP;             
           
           IF @TH_NEW_VALUE IS NOT NULL THEN
				SET @V_TEMP_NEW_VALUE = @TH_NEW_VALUE;
				PD_NV_CS_LOOP : LOOP
					CALL SP_GET_SPECIAL_CHARACTER_SEPERATED_VALUES(',',@TH_NEW_VALUE,@VALUE,@REMAINING_STRING);
					SELECT @REMAINING_STRING INTO @TH_NEW_VALUE;
					-- SEPERATING COLUMN NAME AND COLUMN VALUE 
					CALL SP_GET_SPECIAL_CHARACTER_SEPERATED_VALUES('=',@VALUE,@COLUMN_NAME,@COLUMN_VALUE);
              
					IF UPPER(@COLUMN_NAME) = 'UNIT_ID' THEN
						SELECT UNIT_NO INTO @NEWUNIT_NO FROM UNIT WHERE UNIT_ID = @COLUMN_VALUE;
						IF(LENGTH (@NEWUNIT_NO)=3 )THEN
						SET NEWFINAL_UNITNO=(SELECT CONCAT ('0',@NEWUNIT_NO));
						ELSE
						SET NEWFINAL_UNITNO=@NEWUNIT_NO;
						END IF;
						SET @REPLACE_STRING = CONCAT('UNIT_NO=',@NEWUNIT_NO);
						SELECT REPLACE(@V_TEMP_NEW_VALUE,@VALUE,@REPLACE_STRING) INTO @V_TEMP_NEW_VALUE;
					END IF;
			  
					IF UPPER(@COLUMN_NAME) = 'CUSTOMER_ID' THEN
						SELECT CUSTOMER_FIRST_NAME,CUSTOMER_LAST_NAME INTO @FIRST_NAME_VALUE,@LAST_NAME_VALUE FROM CUSTOMER WHERE CUSTOMER_ID = @COLUMN_VALUE;
						SET @REPLACE_STRING = CONCAT('CUSTOMER_FIRST_NAME=',@FIRST_NAME_VALUE,',CUSTOMER_LAST_NAME=',@LAST_NAME_VALUE);
						SELECT REPLACE(@V_TEMP_NEW_VALUE,@VALUE,@REPLACE_STRING) INTO @V_TEMP_NEW_VALUE;
					END IF;
              
					IF UPPER(@COLUMN_NAME) = 'PP_ID' THEN
						SELECT PP_DATA INTO @NEWPPDATA FROM PAYMENT_PROFILE WHERE PP_ID = @COLUMN_VALUE;
						SET @REPLACE_STRING = CONCAT('PP_DATA=',@NEWPPDATA);
						SELECT REPLACE(@V_TEMP_NEW_VALUE,@VALUE,@REPLACE_STRING) INTO @V_TEMP_NEW_VALUE;
					END IF;
                       
					IF UPPER(@COLUMN_NAME) = 'ULD_ID' THEN
						SELECT ULD_LOGINID INTO @NEWPAYMENTDETAILID FROM USER_LOGIN_DETAILS WHERE ULD_ID = @COLUMN_VALUE;
						SET @REPLACE_STRING = CONCAT('ULD_LOGINID=',@NEWPAYMENTDETAILID);
						SELECT REPLACE(@V_TEMP_NEW_VALUE,@VALUE,@REPLACE_STRING) INTO @V_TEMP_NEW_VALUE;
						LEAVE PD_NV_CS_LOOP;
					END IF;
              
					IF @TH_NEW_VALUE IS NULL THEN
						LEAVE  PD_NV_CS_LOOP; 
					END IF;
				END LOOP;  
           ELSE
				SET @V_TEMP_NEW_VALUE = NULL;
           END IF;
           COMMIT;
		   END;