DROP PROCEDURE IF EXISTS SP_ALL_DOMIAN_VIEWS_PART1;
CREATE PROCEDURE SP_ALL_DOMIAN_VIEWS_PART1()
BEGIN
CREATE OR REPLACE VIEW VW_NON_ACTIVE_UNIT AS SELECT UNIT_ID,UNIT_NO FROM UNIT WHERE UNIT_ID IN (SELECT UNIT_ID FROM UNIT_DETAILS WHERE UD_OBSOLETE IS NOT NULL);
CREATE OR REPLACE VIEW VW_NON_ACTIVE_ACCESS_CARD AS SELECT UASD_ID,UASD_ACCESS_CARD FROM UNIT_ACCESS_STAMP_DETAILS WHERE  UASD_ACCESS_INVENTORY = 'X';
CREATE OR REPLACE VIEW VW_DAMAGED_SPOILED_CARD AS SELECT UASD_ID,UASD_ACCESS_CARD FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_LOST = 'X';
CREATE OR REPLACE VIEW VW_ACTIVE_UNIT AS SELECT U.UNIT_ID,U.UNIT_NO,UD.UD_NON_EI FROM UNIT U,UNIT_DETAILS UD WHERE U.UNIT_ID=UD.UNIT_ID AND UD.UD_OBSOLETE IS NULL AND UD.UD_END_DATE > CURDATE();
CREATE OR REPLACE VIEW VW_ACTIVE_ACCESS_CARD AS SELECT UASD_ID,UASD_ACCESS_CARD FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_ACTIVE = 'X';
CREATE OR REPLACE VIEW VW_SUB_CANCEL_CUSTOMER_MAXIMUM_RECVER AS SELECT CED.CUSTOMER_ID,MAX(CED.CED_REC_VER) AS RECVER FROM CUSTOMER_LP_DETAILS CTD ,CUSTOMER_ENTRY_DETAILS CED WHERE CTD.CLP_GUEST_CARD IS NULL AND CTD.CLP_PRETERMINATE_DATE IS NULL 
AND CTD.CUSTOMER_ID=CED.CUSTOMER_ID AND CTD.CED_REC_VER=CED.CED_REC_VER GROUP BY CED.CUSTOMER_ID;
CREATE OR REPLACE VIEW VW_SUB_CANCEL_CUSTOMER AS SELECT CED.CUSTOMER_ID,CED.CED_REC_VER,CTD.CLP_TERMINATE,CTD.CLP_STARTDATE,CTD.CLP_ENDDATE,CTD.CLP_PRETERMINATE_DATE,CTD.UASD_ID,CED.CED_CANCEL_DATE FROM CUSTOMER_LP_DETAILS CTD,CUSTOMER_ENTRY_DETAILS CED,VW_SUB_CANCEL_CUSTOMER_MAXIMUM_RECVER T WHERE CED.CUSTOMER_ID=CTD.CUSTOMER_ID AND
CED.CED_REC_VER=CTD.CED_REC_VER AND T.CUSTOMER_ID=CTD.CUSTOMER_ID AND T.CUSTOMER_ID=CED.CUSTOMER_ID AND T.RECVER=CTD.CED_REC_VER AND T.RECVER=CED.CED_REC_VER AND CTD.CLP_GUEST_CARD IS NULL AND CTD.CLP_TERMINATE IS NULL AND CED.CED_CANCEL_DATE IS NULL AND((CTD.CLP_STARTDATE>CURDATE())OR(CTD.CLP_STARTDATE<=CURDATE() AND CTD.CLP_ENDDATE>=CURDATE() AND CTD.UASD_ID IS NULL ));
CREATE OR REPLACE VIEW VW_CANCEL_SUB_ACTIVE_CUSTOMER AS
SELECT C1.CUSTOMER_ID AS CUSTOMERID,CONCAT(CUSTOMER_FIRST_NAME,'_',CUSTOMER_LAST_NAME)AS CUSTOMERNAME  
FROM CUSTOMER C1 JOIN CUSTOMER_LP_DETAILS C JOIN CUSTOMER_ENTRY_DETAILS C2  WHERE 
 C.CLP_TERMINATE IS NULL AND C.UASD_ID IS NOT NULL AND C.CLP_STARTDATE<=CURDATE() AND if (C.CLP_PRETERMINATE_DATE IS NOT NULL ,C.CLP_PRETERMINATE_DATE>=CURDATE(),C.CLP_ENDDATE>=CURDATE())AND C.CUSTOMER_ID=C1.CUSTOMER_ID AND
C.CLP_GUEST_CARD IS NULL AND C.CUSTOMER_ID=C2.CUSTOMER_ID AND C2.CED_CANCEL_DATE IS NULL AND C.CED_REC_VER=C2.CED_REC_VER  GROUP BY C.CUSTOMER_ID;
CREATE OR REPLACE VIEW VW_CANCEL_CUSTOMER AS SELECT U.UNIT_ID,U.UNIT_NO,C.CUSTOMER_ID,CED.CED_REC_VER,CONCAT(C.CUSTOMER_FIRST_NAME,'_',C.CUSTOMER_LAST_NAME)AS CUSTOMERNAME
FROM UNIT U JOIN CUSTOMER C JOIN CUSTOMER_ENTRY_DETAILS CED JOIN CUSTOMER_LP_DETAILS CTD JOIN VW_SUB_CANCEL_CUSTOMER T LEFT JOIN VW_CANCEL_SUB_ACTIVE_CUSTOMER V ON C.CUSTOMER_ID = V.CUSTOMERID
WHERE V.CUSTOMERID IS NULL AND U.UNIT_ID=CED.UNIT_ID AND CED.CUSTOMER_ID=CTD.CUSTOMER_ID AND C.CUSTOMER_ID=CTD.CUSTOMER_ID AND CTD.CLP_GUEST_CARD IS NULL AND
C.CUSTOMER_ID=CED.CUSTOMER_ID AND CED.CED_REC_VER=CTD.CED_REC_VER AND ((CTD.CLP_STARTDATE>CURDATE())OR(CTD.CLP_STARTDATE<=CURDATE() AND CTD.CLP_ENDDATE>=CURDATE() AND CTD.UASD_ID IS NULL ))AND T.CUSTOMER_ID=CED.CUSTOMER_ID AND T.CUSTOMER_ID=CTD.CUSTOMER_ID AND CTD.CLP_PRETERMINATE_DATE IS NULL GROUP BY C.CUSTOMER_ID ;
CREATE OR REPLACE VIEW VW_SUB_CUSTOMER_MAXIMUM_RECVER AS SELECT C1.CUSTOMER_ID,MAX(C1.CED_REC_VER) AS REC_VER FROM CUSTOMER_LP_DETAILS C1 WHERE C1.CLP_GUEST_CARD IS NULL AND IF(C1.CLP_PRETERMINATE_DATE IS NOT NULL,C1.CLP_STARTDATE<C1.CLP_PRETERMINATE_DATE,C1.CLP_STARTDATE<C1.CLP_ENDDATE ) AND C1.CLP_TERMINATE IS NULL GROUP BY C1.CUSTOMER_ID;
CREATE OR REPLACE VIEW VW_SUB_CARDASSIGN AS  SELECT C1.CUSTOMER_ID,C.CED_REC_VER,C.CLP_STARTDATE,C.CLP_ENDDATE,C.CLP_PRETERMINATE_DATE,C.CLP_TERMINATE,U.UNIT_NO,CED.CED_CANCEL_DATE FROM
CUSTOMER_LP_DETAILS C,VW_SUB_CUSTOMER_MAXIMUM_RECVER C1,CUSTOMER_ENTRY_DETAILS CED,UNIT U WHERE C.CUSTOMER_ID=C1.CUSTOMER_ID AND C.CED_REC_VER=CED.CED_REC_VER AND CED.UNIT_ID=U.UNIT_ID AND CED.CUSTOMER_ID=C1.CUSTOMER_ID AND
IF (C.CLP_PRETERMINATE_DATE IS NOT NULL ,C.CLP_PRETERMINATE_DATE>CURDATE(),C.CLP_ENDDATE>CURDATE())AND IF(C.CLP_PRETERMINATE_DATE IS NOT NULL,C.CLP_STARTDATE<C.CLP_PRETERMINATE_DATE,C.CLP_STARTDATE<C.CLP_ENDDATE ) AND C.CLP_TERMINATE IS NULL AND C.CLP_GUEST_CARD IS NULL;
CREATE OR REPLACE VIEW VW_CARDASSIGN AS SELECT U.UNIT_ID,T.UNIT_NO,T.CED_REC_VER,T.CUSTOMER_ID,CONCAT(C.CUSTOMER_FIRST_NAME,'_',C.CUSTOMER_LAST_NAME)AS CUSTOMERNAME,T.CLP_STARTDATE,T.CLP_ENDDATE,T.CLP_PRETERMINATE_DATE
FROM CUSTOMER C,VW_SUB_CARDASSIGN T,UNIT U WHERE C.CUSTOMER_ID=T.CUSTOMER_ID AND U.UNIT_NO=T.UNIT_NO AND
T.CLP_TERMINATE IS NULL AND T.CED_CANCEL_DATE IS NULL;
CREATE OR REPLACE VIEW VW_SUB_ACTIVE_CUSTOMER_LIST AS SELECT C1.CUSTOMER_ID ,CONCAT(CUSTOMER_FIRST_NAME,'_',CUSTOMER_LAST_NAME)AS CUSTOMERNAME ,U.UNIT_NO,U.UNIT_ID,C.CED_REC_VER
FROM CUSTOMER C1 JOIN CUSTOMER_LP_DETAILS C JOIN CUSTOMER_ENTRY_DETAILS C2,UNIT U  WHERE
 C.CLP_TERMINATE IS NULL AND (C.CLP_STARTDATE<=CURDATE() OR C.CLP_STARTDATE>CURDATE()) AND if (C.CLP_PRETERMINATE_DATE IS NOT NULL ,C.CLP_PRETERMINATE_DATE>=CURDATE(),C.CLP_ENDDATE>=CURDATE())AND C.CUSTOMER_ID=C1.CUSTOMER_ID AND
C.CLP_GUEST_CARD IS NULL AND C.CUSTOMER_ID=C2.CUSTOMER_ID AND C2.CED_CANCEL_DATE IS NULL AND C.CED_REC_VER=C2.CED_REC_VER AND U.UNIT_ID=C2.UNIT_ID GROUP BY C.CUSTOMER_ID;
CREATE OR REPLACE VIEW VW_CURRENT_ACTIVE_CUSTOMER AS SELECT C.CUSTOMER_ID,C.CUSTOMER_FIRST_NAME,C.CUSTOMER_LAST_NAME,CONCAT(CUSTOMER_FIRST_NAME,' ',CUSTOMER_LAST_NAME)AS CUSTOMERNAME ,CED.CED_REC_VER,U.UNIT_NO,CTD.CLP_STARTDATE,CTD.CLP_ENDDATE,CTD.CLP_PRETERMINATE_DATE,
CED.CED_PRETERMINATE,CPD.CPD_EMAIL FROM CUSTOMER_ENTRY_DETAILS CED,CUSTOMER_LP_DETAILS CTD,CUSTOMER C,UNIT U,VW_SUB_ACTIVE_CUSTOMER_LIST V,CUSTOMER_PERSONAL_DETAILS CPD WHERE
C.CUSTOMER_ID=CED.CUSTOMER_ID AND C.CUSTOMER_ID=CTD.CUSTOMER_ID AND C.CUSTOMER_ID=V.CUSTOMER_ID AND U.UNIT_ID=CED.UNIT_ID AND CTD.CUSTOMER_ID=CED.CUSTOMER_ID AND
 CTD.CUSTOMER_ID=V.CUSTOMER_ID AND  CED.CUSTOMER_ID=V.CUSTOMER_ID AND   CTD.CLP_GUEST_CARD IS NULL AND C.CUSTOMER_ID=CPD.CUSTOMER_ID AND
CED.CED_REC_VER=CTD.CED_REC_VER AND CPD.CUSTOMER_ID=CTD.CUSTOMER_ID AND CPD.CUSTOMER_ID=CED.CUSTOMER_ID AND  V.CUSTOMER_ID=CPD.CUSTOMER_ID AND CTD.CLP_TERMINATE IS NULL
AND IF(CTD.CLP_PRETERMINATE_DATE IS NOT NULL,CTD.CLP_STARTDATE<CTD.CLP_PRETERMINATE_DATE,CTD.CLP_STARTDATE<CTD.CLP_ENDDATE)AND CED.CED_CANCEL_DATE IS NULL;
CREATE OR REPLACE VIEW VW_SUB_PAYMENT_ACTIVE_CUSTOMER_LIST AS SELECT C1.CUSTOMER_ID ,CONCAT(CUSTOMER_FIRST_NAME,'_',CUSTOMER_LAST_NAME)AS CUSTOMERNAME ,U.UNIT_NO,U.UNIT_ID,C.CED_REC_VER
FROM CUSTOMER C1 JOIN CUSTOMER_LP_DETAILS C JOIN CUSTOMER_ENTRY_DETAILS C2,UNIT U  WHERE
 C.CLP_TERMINATE IS NULL AND (C.CLP_STARTDATE<=CURDATE() OR C.CLP_STARTDATE>CURDATE()) AND if (C.CLP_PRETERMINATE_DATE IS NOT NULL ,C.CLP_PRETERMINATE_DATE>=CURDATE(),C.CLP_ENDDATE>=CURDATE())AND C.CUSTOMER_ID=C1.CUSTOMER_ID AND
C.CLP_GUEST_CARD IS NULL AND C.CUSTOMER_ID=C2.CUSTOMER_ID AND C2.CED_CANCEL_DATE IS NULL AND C.CED_REC_VER=C2.CED_REC_VER AND U.UNIT_ID=C2.UNIT_ID;
CREATE OR REPLACE VIEW VW_PAYMENT_CURRENT_ACTIVE_CUSTOMER AS SELECT C.CUSTOMER_ID,C.CUSTOMER_FIRST_NAME,C.CUSTOMER_LAST_NAME,CONCAT(CUSTOMER_FIRST_NAME,' ',CUSTOMER_LAST_NAME)AS CUSTOMERNAME ,CED.CED_REC_VER,U.UNIT_NO,CTD.CLP_STARTDATE,CTD.CLP_ENDDATE,CTD.CLP_PRETERMINATE_DATE,
CED.CED_PRETERMINATE,CFD.CFD_AMOUNT AS PAYMENT,CPD.CPD_EMAIL FROM CUSTOMER_ENTRY_DETAILS CED,CUSTOMER_LP_DETAILS CTD,CUSTOMER C,UNIT U,CUSTOMER_FEE_DETAILS CFD,VW_SUB_PAYMENT_ACTIVE_CUSTOMER_LIST V,CUSTOMER_PERSONAL_DETAILS CPD WHERE
C.CUSTOMER_ID=CED.CUSTOMER_ID AND C.CUSTOMER_ID=CTD.CUSTOMER_ID AND C.CUSTOMER_ID=CFD.CUSTOMER_ID AND C.CUSTOMER_ID=V.CUSTOMER_ID AND U.UNIT_ID=CED.UNIT_ID AND CTD.CUSTOMER_ID=CED.CUSTOMER_ID AND
CTD.CUSTOMER_ID=CFD.CUSTOMER_ID AND CTD.CUSTOMER_ID=V.CUSTOMER_ID AND CED.CUSTOMER_ID=CFD.CUSTOMER_ID AND CED.CUSTOMER_ID=V.CUSTOMER_ID AND CFD.CUSTOMER_ID=CTD.CUSTOMER_ID AND CFD.CUSTOMER_ID=CED.CUSTOMER_ID AND CTD.CLP_GUEST_CARD IS NULL AND C.CUSTOMER_ID=CPD.CUSTOMER_ID AND
CPD.CUSTOMER_ID=CTD.CUSTOMER_ID AND CPD.CUSTOMER_ID=CED.CUSTOMER_ID AND CFD.CUSTOMER_ID=CPD.CUSTOMER_ID AND V.CUSTOMER_ID=CPD.CUSTOMER_ID AND CFD.CPP_ID=1 AND CFD.CED_REC_VER=CTD.CED_REC_VER AND CFD.CED_REC_VER=CED.CED_REC_VER AND IF(CTD.CLP_PRETERMINATE_DATE IS NOT NULL,
CTD.CLP_STARTDATE<CTD.CLP_PRETERMINATE_DATE,CTD.CLP_STARTDATE<CTD.CLP_ENDDATE) AND CPD.CUSTOMER_ID=C.CUSTOMER_ID AND CED.CED_CANCEL_DATE IS NULL AND (V.UNIT_ID=CED.UNIT_ID OR CED.CED_REC_VER>V.CED_REC_VER)GROUP BY CTD.CUSTOMER_ID,CTD.CED_REC_VER;
CREATE OR REPLACE VIEW VW_SUB_EXTENSION_CUSTOMER AS  SELECT CUSTOMER_ID,MAX(CED_REC_VER) AS RECVER FROM CUSTOMER_LP_DETAILS WHERE CLP_GUEST_CARD IS NULL AND IF(CLP_PRETERMINATE_DATE IS NOT NULL,CLP_STARTDATE<CLP_PRETERMINATE_DATE,CLP_STARTDATE )GROUP BY CUSTOMER_ID;
CREATE OR REPLACE VIEW VW_SUB_EXTENSION_TERMINATE_CUSTOMER AS SELECT CTD.CUSTOMER_ID,CTD.CED_REC_VER,CTD.CLP_TERMINATE,CED.CED_CANCEL_DATE,CED.UNIT_ID FROM
CUSTOMER_LP_DETAILS CTD,CUSTOMER_ENTRY_DETAILS CED,VW_SUB_EXTENSION_CUSTOMER T
WHERE CTD.CUSTOMER_ID=CED.CUSTOMER_ID AND CTD.CUSTOMER_ID=T.CUSTOMER_ID AND CED.CUSTOMER_ID=T.CUSTOMER_ID 
AND CTD.CED_REC_VER=CED.CED_REC_VER AND T.RECVER=CED.CED_REC_VER AND T.RECVER=CTD.CED_REC_VER AND CTD.CLP_GUEST_CARD IS NULL GROUP BY CTD.CUSTOMER_ID;
CREATE OR REPLACE VIEW VW_EXTENSION_CUSTOMER AS SELECT U.UNIT_ID,U.UNIT_NO,C.CUSTOMER_ID,CONCAT(C.CUSTOMER_FIRST_NAME,'_',C.CUSTOMER_LAST_NAME)AS CUSTOMERNAME,T.CED_REC_VER FROM
UNIT U,CUSTOMER C,VW_SUB_EXTENSION_TERMINATE_CUSTOMER T WHERE U.UNIT_ID=T.UNIT_ID AND C.CUSTOMER_ID=T.CUSTOMER_ID AND 
T.CLP_TERMINATE IS NULL AND T.CED_CANCEL_DATE IS NULL;
CREATE OR REPLACE VIEW VW_SUB_RECHECKIN_CUSTOMER AS 
SELECT CUSTOMER_ID,MAX(CED_REC_VER) AS RECVER FROM CUSTOMER_LP_DETAILS WHERE CLP_GUEST_CARD IS NULL AND IF(CLP_PRETERMINATE_DATE IS NOT NULL,CLP_STARTDATE<CLP_PRETERMINATE_DATE,CLP_STARTDATE )GROUP BY CUSTOMER_ID;
CREATE OR REPLACE VIEW VW_SUB_RECHECKIN_TERMINATE_CUSTOMER AS
SELECT CTD.CUSTOMER_ID,CTD.CED_REC_VER,CTD.CLP_TERMINATE,CTD.CLP_STARTDATE,CTD.CLP_ENDDATE,CED.CED_CANCEL_DATE,CED.UNIT_ID FROM
CUSTOMER_LP_DETAILS CTD,CUSTOMER_ENTRY_DETAILS CED,VW_SUB_RECHECKIN_CUSTOMER T
WHERE CTD.CUSTOMER_ID=CED.CUSTOMER_ID AND CTD.CUSTOMER_ID=T.CUSTOMER_ID AND CED.CUSTOMER_ID=T.CUSTOMER_ID 
AND CTD.CED_REC_VER=CED.CED_REC_VER AND T.RECVER=CED.CED_REC_VER
AND T.RECVER=CTD.CED_REC_VER AND CTD.CLP_GUEST_CARD IS NULL GROUP BY CTD.CUSTOMER_ID;
CREATE OR REPLACE VIEW VW_RECHECKIN_CUSTOMER AS
SELECT U.UNIT_ID,U.UNIT_NO,C.CUSTOMER_ID,T.CED_REC_VER,CONCAT(C.CUSTOMER_FIRST_NAME,'_',C.CUSTOMER_LAST_NAME)AS CUSTOMERNAME FROM
UNIT U,CUSTOMER C,VW_SUB_RECHECKIN_TERMINATE_CUSTOMER T WHERE U.UNIT_ID=T.UNIT_ID AND C.CUSTOMER_ID=T.CUSTOMER_ID AND 
((T.CLP_TERMINATE IS NOT NULL)OR(T.CLP_STARTDATE<CURDATE()AND T.CED_CANCEL_DATE IS NOT NULL));
END;
CALL SP_ALL_DOMIAN_VIEWS_PART1();