DROP PROCEDURE IF EXISTS SP_CUSTOMER_TICKLER_ENTRY_DETAILS;
CREATE PROCEDURE SP_CUSTOMER_TICKLER_ENTRY_DETAILS()
BEGIN
DECLARE FINAL_UNITNO SMALLINT(4) UNSIGNED ZEROFILL;
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
END;
START TRANSACTION;
	CED_OV_CS_LOOP : LOOP
		CALL SP_GET_SPECIAL_CHARACTER_SEPERATED_VALUES(',',@TH_OLD_VALUE,@VALUE,@REMAINING_STRING);
              SELECT @REMAINING_STRING INTO @TH_OLD_VALUE;
              
              
              CALL SP_GET_SPECIAL_CHARACTER_SEPERATED_VALUES('=',@VALUE,@COLUMN_NAME,@COLUMN_VALUE);
              
				IF UPPER(@COLUMN_NAME) = 'CUSTOMER_ID' THEN
                  SELECT CUSTOMER_FIRST_NAME,CUSTOMER_LAST_NAME INTO @FIRST_NAME_VALUE,@LAST_NAME_VALUE FROM CUSTOMER WHERE CUSTOMER_ID = @COLUMN_VALUE;
                  SET @REPLACE_STRING = CONCAT('CUSTOMER_FIRST_NAME=',@FIRST_NAME_VALUE,',CUSTOMER_LAST_NAME=',@LAST_NAME_VALUE);
                  SELECT REPLACE(@V_TEMP_OLD_VALUE,@VALUE,@REPLACE_STRING) INTO @V_TEMP_OLD_VALUE;
				END IF;
              
				IF UPPER(@COLUMN_NAME) = 'UNIT_ID' THEN
                  SELECT UNIT_NO INTO @UNIT_NO FROM UNIT WHERE UNIT_ID = @COLUMN_VALUE;
				  
				  IF(LENGTH (@UNIT_NO)=3 )THEN
						SET FINAL_UNITNO=(SELECT CONCAT ('0',@UNIT_NO));
						ELSE
						SET FINAL_UNITNO=@UNIT_NO;
						END IF;
						
			SET @REPLACE_STRING = CONCAT('UNIT_NO=',FINAL_UNITNO);
                  SELECT REPLACE(@V_TEMP_OLD_VALUE,@VALUE,@REPLACE_STRING) INTO @V_TEMP_OLD_VALUE;
				END IF;
				
				IF UPPER(@COLUMN_NAME) = 'UASD_ID' THEN
       
                  SELECT URTD_ID INTO @URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ID = @COLUMN_VALUE;
					   SELECT URTD_ROOM_TYPE INTO @URTD_ROOMTYPE FROM UNIT_ROOM_TYPE_DETAILS WHERE URTD_ID=@URTD_ID;

                    SET @REPLACE_STRING = CONCAT('URTD_ROOM_TYPE=',@URTD_ROOMTYPE);
                    SELECT REPLACE(@V_TEMP_OLD_VALUE,@VALUE,@REPLACE_STRING) INTO @V_TEMP_OLD_VALUE;
				END IF;
				
                IF UPPER(@COLUMN_NAME) = 'CED_SD_STIME' THEN
                  SELECT CTP_DATA INTO @CTP_DATA_SD_STIME FROM CUSTOMER_TIME_PROFILE WHERE CTP_ID = @COLUMN_VALUE;
                  SET @REPLACE_STRING = CONCAT('CED_SD_STIME=',@CTP_DATA_SD_STIME);
                  SELECT REPLACE(@V_TEMP_OLD_VALUE,@VALUE,@REPLACE_STRING) INTO @V_TEMP_OLD_VALUE;
				END IF;
				  
				IF UPPER(@COLUMN_NAME) = 'CED_SD_ETIME' THEN
                  SELECT CTP_DATA INTO @CTP_DATA_SD_ETIME FROM CUSTOMER_TIME_PROFILE WHERE CTP_ID = @COLUMN_VALUE;
                  SET @REPLACE_STRING = CONCAT('CED_SD_ETIME=',@CTP_DATA_SD_ETIME);
                  SELECT REPLACE(@V_TEMP_OLD_VALUE,@VALUE,@REPLACE_STRING) INTO @V_TEMP_OLD_VALUE;
				END IF;
				
				IF UPPER(@COLUMN_NAME) = 'CED_ED_STIME' THEN
                  SELECT CTP_DATA INTO @CTP_DATA_ED_STIME FROM CUSTOMER_TIME_PROFILE WHERE CTP_ID = @COLUMN_VALUE;
                  SET @REPLACE_STRING = CONCAT('CED_ED_STIME=',@CTP_DATA_ED_STIME);
                  SELECT REPLACE(@V_TEMP_OLD_VALUE,@VALUE,@REPLACE_STRING) INTO @V_TEMP_OLD_VALUE;
				END IF;
				  
				IF UPPER(@COLUMN_NAME) = 'CED_ED_ETIME' THEN
                  SELECT CTP_DATA INTO @CTP_DATA_ED_ETIME FROM CUSTOMER_TIME_PROFILE WHERE CTP_ID = @COLUMN_VALUE;
                  SET @REPLACE_STRING = CONCAT('CED_ED_ETIME=',@CTP_DATA_ED_ETIME);
                  SELECT REPLACE(@V_TEMP_OLD_VALUE,@VALUE,@REPLACE_STRING) INTO @V_TEMP_OLD_VALUE;
				END IF;
				
				IF UPPER(@COLUMN_NAME) = 'ULD_ID' THEN
					SELECT ULD_LOGINID INTO @OLDULDLOGINIDENTRY FROM USER_LOGIN_DETAILS WHERE ULD_ID = @COLUMN_VALUE;
                  	SET @REPLACE_STRING = CONCAT('ULD_LOGINID=',@OLDULDLOGINIDENTRY);
					SELECT REPLACE(@V_TEMP_OLD_VALUE,@VALUE,@REPLACE_STRING) INTO @V_TEMP_OLD_VALUE;
					LEAVE CED_OV_CS_LOOP;
				END IF;
				
                IF @TH_OLD_VALUE IS NULL THEN
  			          LEAVE  CED_OV_CS_LOOP;
  		        END IF;
	END LOOP;
IF @TH_NEW_VALUE IS NOT NULL THEN
              SET @V_TEMP_NEW_VALUE = @TH_NEW_VALUE;
				CED_NV_CS_LOOP : LOOP
              
					CALL SP_GET_SPECIAL_CHARACTER_SEPERATED_VALUES(',',@TH_NEW_VALUE,@VALUE,@REMAINING_STRING);
					SELECT @REMAINING_STRING INTO @TH_NEW_VALUE;
              
					
					CALL SP_GET_SPECIAL_CHARACTER_SEPERATED_VALUES('=',@VALUE,@COLUMN_NAME,@COLUMN_VALUE);
              
					IF UPPER(@COLUMN_NAME) = 'CUSTOMER_ID' THEN
						SELECT CUSTOMER_FIRST_NAME,CUSTOMER_LAST_NAME INTO @FIRST_NAME_VALUE,@LAST_NAME_VALUE FROM CUSTOMER WHERE CUSTOMER_ID = @COLUMN_VALUE;
                  
						SET @REPLACE_STRING = CONCAT('CUSTOMER_FIRST_NAME=',@FIRST_NAME_VALUE,',CUSTOMER_LAST_NAME=',@LAST_NAME_VALUE);
						SELECT REPLACE(@V_TEMP_NEW_VALUE,@VALUE,@REPLACE_STRING) INTO @V_TEMP_NEW_VALUE;
                  
					END IF;
              
					IF UPPER(@COLUMN_NAME) = 'UNIT_ID' THEN
						SELECT UNIT_NO INTO @UNIT_NO FROM UNIT WHERE UNIT_ID = @COLUMN_VALUE;
					IF(LENGTH (@UNIT_NO)=3 )THEN
						SET FINAL_UNITNO=(SELECT CONCAT ('0',@UNIT_NO));
						ELSE
						SET FINAL_UNITNO=@UNIT_NO;
						END IF;
                  
					SET @REPLACE_STRING = CONCAT('UNIT_NO=',FINAL_UNITNO);
						SELECT REPLACE(@V_TEMP_NEW_VALUE,@VALUE,@REPLACE_STRING) INTO @V_TEMP_NEW_VALUE;
                   
					END IF;
					IF UPPER(@COLUMN_NAME) = 'UASD_ID' THEN
						SELECT URTD_ID INTO @URTD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ID = @COLUMN_VALUE;
						SELECT URTD_ROOM_TYPE INTO @URTD_ROOMTYPE FROM UNIT_ROOM_TYPE_DETAILS WHERE URTD_ID=@URTD_ID;
						SET @REPLACE_STRING = CONCAT('URTD_ROOM_TYPE=',@URTD_ROOMTYPE);
						SELECT REPLACE(@V_TEMP_NEW_VALUE,@VALUE,@REPLACE_STRING) INTO @V_TEMP_NEW_VALUE;
                      
					END IF;              
					IF UPPER(@COLUMN_NAME) = 'CED_SD_STIME' THEN
						SELECT CTP_DATA INTO @NEW_CTP_DATA_SD_STIME FROM CUSTOMER_TIME_PROFILE WHERE CTP_ID = @COLUMN_VALUE;
						SET @REPLACE_STRING = CONCAT('CED_SD_STIME=',@NEW_CTP_DATA_SD_STIME);
						SELECT REPLACE(@V_TEMP_NEW_VALUE,@VALUE,@REPLACE_STRING) INTO @V_TEMP_NEW_VALUE;
					END IF;
				  
					IF UPPER(@COLUMN_NAME) = 'CED_SD_ETIME' THEN
						SELECT CTP_DATA INTO @NEW_CTP_DATA_SD_ETIME FROM CUSTOMER_TIME_PROFILE WHERE CTP_ID = @COLUMN_VALUE;
						SET @REPLACE_STRING = CONCAT('CED_SD_ETIME=',@NEW_CTP_DATA_SD_ETIME);
						SELECT REPLACE(@V_TEMP_NEW_VALUE,@VALUE,@REPLACE_STRING) INTO @V_TEMP_NEW_VALUE;
					END IF;
					IF UPPER(@COLUMN_NAME) = 'CED_ED_STIME' THEN
						SELECT CTP_DATA INTO @NEW_CTP_DATA_ED_STIME FROM CUSTOMER_TIME_PROFILE WHERE CTP_ID = @COLUMN_VALUE;
						SET @REPLACE_STRING = CONCAT('CED_ED_STIME=',@NEW_CTP_DATA_ED_STIME);
						SELECT REPLACE(@V_TEMP_NEW_VALUE,@VALUE,@REPLACE_STRING) INTO @V_TEMP_NEW_VALUE;
					END IF;
				  
					IF UPPER(@COLUMN_NAME) = 'CED_ED_ETIME' THEN
						SELECT CTP_DATA INTO @NEW_CTP_DATA_ED_ETIME FROM CUSTOMER_TIME_PROFILE WHERE CTP_ID = @COLUMN_VALUE;
						SET @REPLACE_STRING = CONCAT('CED_ED_ETIME=',@NEW_CTP_DATA_ED_ETIME);
						SELECT REPLACE(@V_TEMP_NEW_VALUE,@VALUE,@REPLACE_STRING) INTO @V_TEMP_NEW_VALUE;
					END IF;
				  
					IF UPPER(@COLUMN_NAME) = 'ULD_ID' THEN
						SELECT ULD_LOGINID INTO @NEWULDLOGINIDPENTRY FROM USER_LOGIN_DETAILS WHERE ULD_ID = @COLUMN_VALUE;
						SET @REPLACE_STRING = CONCAT('ULD_LOGINID=',@NEWULDLOGINIDPENTRY);
						SELECT REPLACE(@V_TEMP_NEW_VALUE,@VALUE,@REPLACE_STRING) INTO @V_TEMP_NEW_VALUE;
						LEAVE CED_NV_CS_LOOP;
					END IF;
				  
					IF @TH_NEW_VALUE IS NULL THEN
			          LEAVE  CED_NV_CS_LOOP;
					END IF;
	           END LOOP;  
           ELSE
             SET @V_TEMP_NEW_VALUE = NULL;
           END IF;
           COMMIT;
		   END;    