DROP PROCEDURE IF EXISTS SP_CUSTOMER_SEARCH_CALENDAR_CREATION_DELETION;
CREATE PROCEDURE SP_CUSTOMER_SEARCH_CALENDAR_CREATION_DELETION(
IN CUSTOMERID INTEGER,
IN USERSTAMP VARCHAR(50),
OUT TEMP_CALENDAR_LIST TEXT
)
BEGIN
DECLARE RECHECKIN_FLAG CHAR(1);
DECLARE EXTENSION_FLAG CHAR(1);
DECLARE TERMINATE_FLAG CHAR(1);
DECLARE TEMP_CUSTOMER_LPDETAILS TEXT;
DECLARE TEMP_CUSTOMER_LP_DETAILS TEXT;
DECLARE USERSTAMP_ID TEXT;
DECLARE SYSDATEANDTIME VARCHAR(50);
DECLARE SYSDATEANDULDID VARCHAR(50);
DECLARE MINIMUM_ID INT;
DECLARE MAXIMUM_ID INT;
DECLARE RECVERTABLENAME TEXT;
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
IF RECVERTABLENAME IS NOT NULL THEN
SET @TEMPMAXRECVERTABLEDROPQUERY=(SELECT CONCAT('DROP TABLE IF EXISTS ',RECVERTABLENAME));
PREPARE TEMPMAXRECVERTABLEDROPQUERY_STMT FROM @TEMPMAXRECVERTABLEDROPQUERY;
EXECUTE TEMPMAXRECVERTABLEDROPQUERY_STMT;
END IF;
IF TEMP_CUSTOMER_LPDETAILS IS NOT NULL THEN 
SET @TEMPTABLEDROPQUERY=(SELECT CONCAT('DROP TABLE IF EXISTS ',TEMP_CUSTOMER_LPDETAILS));
PREPARE TEMPTABLEDROPQUERY_STMT FROM @TEMPTABLEDROPQUERY;
EXECUTE TEMPTABLEDROPQUERY_STMT;
END IF;
IF TEMP_CUSTOMER_LP_DETAILS IS NOT NULL THEN
SET @TEMPTABLEDROP_QUERY=(SELECT CONCAT('DROP TABLE IF EXISTS ',TEMP_CUSTOMER_LP_DETAILS));
PREPARE TEMPTABLEDROP_QUERY_STMT FROM @TEMPTABLEDROP_QUERY;
EXECUTE TEMPTABLEDROP_QUERY_STMT;
END IF;
END;
START TRANSACTION;
CALL SP_CHANGE_USERSTAMP_AS_ULDID(USERSTAMP,@ULDID);
SET USERSTAMP_ID=(SELECT @ULDID);
CALL SP_CUSTOMER_MIN_MAX_RV(USERSTAMP,CUSTOMERID,@MNMAXTBLNAME);
SET RECVERTABLENAME=@MNMAXTBLNAME;
SET SYSDATEANDTIME=(SELECT SYSDATE());
SET SYSDATEANDTIME=(SELECT REPLACE(SYSDATEANDTIME,' ',''));
SET SYSDATEANDTIME=(SELECT REPLACE(SYSDATEANDTIME,'-',''));
SET SYSDATEANDTIME=(SELECT REPLACE(SYSDATEANDTIME,':',''));
SET SYSDATEANDULDID=(SELECT CONCAT(SYSDATEANDTIME,'_',USERSTAMP_ID));
SET @MINIMUM_REC_VERQUERY=(SELECT CONCAT('SELECT TCMM_MINRV INTO @MINRV FROM ',RECVERTABLENAME));
PREPARE MINIMUM_REC_VER_STMT FROM @MINIMUM_REC_VERQUERY;
EXECUTE MINIMUM_REC_VER_STMT;
SET @MAXIMUM_REC_VERQUERY=(SELECT CONCAT('SELECT TCMM_MAXRV INTO @MAXRV FROM ',RECVERTABLENAME));
PREPARE MAXIMUM_REC_VER_STMT FROM @MAXIMUM_REC_VERQUERY;
EXECUTE MAXIMUM_REC_VER_STMT;
SET TEMP_CUSTOMER_LP_DETAILS=(SELECT CONCAT('TEMP_CUSTOMER_LP_DETAILS',SYSDATEANDULDID));
SET @TEMP_CUSTOMER_LP_DETAILSQUERY=(SELECT CONCAT('CREATE TABLE ',TEMP_CUSTOMER_LP_DETAILS,'(SNO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,UNIT INTEGER(4) UNSIGNED ZEROFILL,ROOMTYPE VARCHAR(30),CED_REC_VER INT,CLP_START_DATE DATE,CLP_END_DATE DATE,CLP_PRE_TERMINATE_DATE DATE,PRETERMINATE CHAR(1),EXTENSION CHAR(1),RECHECKIN CHAR(1),CLP_S_STARTTIME TIME,CLP_S_ENDTIME TIME,CLP_E_STARTTIME TIME,CLP_E_ENDTIME TIME)'));
PREPARE TEMP_CUSTOMER_LP_DETAILS_STMT FROM @TEMP_CUSTOMER_LP_DETAILSQUERY;
EXECUTE TEMP_CUSTOMER_LP_DETAILS_STMT;
SET @TEMP_CUSTOMER_LPDETAILS_INSERTQUERY=(SELECT CONCAT('INSERT INTO ',TEMP_CUSTOMER_LP_DETAILS,'(UNIT,ROOMTYPE,CED_REC_VER,CLP_START_DATE,CLP_END_DATE,CLP_PRE_TERMINATE_DATE,PRETERMINATE,EXTENSION,RECHECKIN,CLP_S_STARTTIME,CLP_S_ENDTIME,CLP_E_STARTTIME,CLP_E_ENDTIME)SELECT U.UNIT_NO,URTD.URTD_ROOM_TYPE,CED.CED_REC_VER,CTD.CLP_STARTDATE,CTD.CLP_ENDDATE,CTD.CLP_PRETERMINATE_DATE,CED.CED_PRETERMINATE,CED.CED_EXTENSION,CED.CED_RECHECKIN,CTPA.CTP_DATA AS CED_SD_STIME, CTPB.CTP_DATA AS CED_SD_ETIME,CTPC.CTP_DATA AS CED_ED_STIME, CTPD.CTP_DATA AS CED_ED_ETIME FROM  CUSTOMER_ENTRY_DETAILS CED LEFT JOIN CUSTOMER_TIME_PROFILE CTPA ON CED.CED_SD_STIME = CTPA.CTP_ID LEFT JOIN CUSTOMER_TIME_PROFILE CTPB ON CED.CED_SD_ETIME = CTPB.CTP_ID LEFT JOIN CUSTOMER_TIME_PROFILE CTPC ON CED.CED_ED_STIME = CTPC.CTP_ID LEFT JOIN CUSTOMER_TIME_PROFILE CTPD ON CED.CED_ED_ETIME = CTPD.CTP_ID,CUSTOMER_LP_DETAILS CTD,UNIT U,UNIT_ROOM_TYPE_DETAILS URTD,UNIT_ACCESS_STAMP_DETAILS UASD WHERE CED.CUSTOMER_ID=',CUSTOMERID,' AND CTD.CED_REC_VER BETWEEN @MINRV AND @MAXRV AND CED.CUSTOMER_ID=CTD.CUSTOMER_ID AND CED.CED_REC_VER=CTD.CED_REC_VER AND CED.UNIT_ID=U.UNIT_ID AND URTD.URTD_ID=UASD.URTD_ID AND UASD.UASD_ID=CED.UASD_ID AND CTD.CLP_GUEST_CARD IS NULL AND CED.CED_CANCEL_DATE IS NULL ORDER BY CED.CED_REC_VER ASC'));
PREPARE TEMP_CUSTOMER_LPDETAILS_INSERTSTMT FROM @TEMP_CUSTOMER_LPDETAILS_INSERTQUERY;
EXECUTE TEMP_CUSTOMER_LPDETAILS_INSERTSTMT;
SET @MINIDQUERY=(SELECT CONCAT('SELECT MIN(SNO) INTO @MINID FROM ',TEMP_CUSTOMER_LP_DETAILS));
PREPARE MINIDQUERY_STMT FROM @MINIDQUERY;
EXECUTE MINIDQUERY_STMT;
SET @MAXIDQUERY=(SELECT CONCAT('SELECT MAX(SNO) INTO @MAXID FROM ',TEMP_CUSTOMER_LP_DETAILS));
PREPARE MAXIDQUERY_STMT FROM @MAXIDQUERY;
EXECUTE MAXIDQUERY_STMT;
SET TEMP_CUSTOMER_LPDETAILS=(SELECT CONCAT('TEMP_CUSTOMER_LPDETAILS',SYSDATEANDULDID));
SET @TEMP_CUSTOMER_LPDETAILSQUERY=(SELECT CONCAT('CREATE TABLE ',TEMP_CUSTOMER_LPDETAILS,'(SNO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,UNIT INTEGER(4) UNSIGNED ZEROFILL,ROOMTYPE VARCHAR(30),CED_REC_VER INT,CLP_START_DATE DATE,CLP_END_DATE DATE,CLP_PRE_TERMINATE_DATE DATE,PRETERMINATE CHAR(1),EXTENSION CHAR(1),RECHECKIN CHAR(1),CLP_S_STARTTIME TIME,CLP_S_ENDTIME TIME,CLP_E_STARTTIME TIME,CLP_E_ENDTIME TIME)'));
PREPARE TEMP_CUSTOMER_LPDETAILS_STMT FROM @TEMP_CUSTOMER_LPDETAILSQUERY;
EXECUTE TEMP_CUSTOMER_LPDETAILS_STMT;
WHILE @MINID<=@MAXID DO
SET @F_CLP_STARTDATEQUERY=(SELECT CONCAT('SELECT CLP_START_DATE INTO @F_CLPSTARTDATE FROM ',TEMP_CUSTOMER_LP_DETAILS,' WHERE SNO=@MINID'));
PREPARE F_CLP_STARTDATE_STMT FROM @F_CLP_STARTDATEQUERY;
EXECUTE F_CLP_STARTDATE_STMT;
SET @PRETERMINDATE_QUERY=(SELECT CONCAT('SELECT CLP_PRE_TERMINATE_DATE INTO @PRE_TERM FROM ',TEMP_CUSTOMER_LP_DETAILS,' WHERE SNO=@MINID'));
PREPARE PRETERMIN_DATE_STMT FROM @PRETERMINDATE_QUERY;
EXECUTE PRETERMIN_DATE_STMT;
SET @EXTENSIONFLAGQUERY=(SELECT CONCAT('SELECT EXTENSION INTO @E_EXTENSION FROM ',TEMP_CUSTOMER_LP_DETAILS,' WHERE SNO=@MINID'));
PREPARE EXTENSIONFLAGQUERY_STMT FROM @EXTENSIONFLAGQUERY;
EXECUTE EXTENSIONFLAGQUERY_STMT;
IF @PRE_TERM IS NULL THEN
SET @TEMP_CUSTOMERLP_QUERY=(SELECT CONCAT('INSERT INTO ',TEMP_CUSTOMER_LPDETAILS,'(UNIT,ROOMTYPE,CED_REC_VER,CLP_START_DATE,CLP_END_DATE,CLP_PRE_TERMINATE_DATE,PRETERMINATE,EXTENSION,RECHECKIN,CLP_S_STARTTIME,CLP_S_ENDTIME,CLP_E_STARTTIME,CLP_E_ENDTIME)SELECT UNIT,ROOMTYPE,CED_REC_VER,CLP_START_DATE,CLP_END_DATE,CLP_PRE_TERMINATE_DATE,PRETERMINATE,EXTENSION,RECHECKIN,CLP_S_STARTTIME,CLP_S_ENDTIME,CLP_E_STARTTIME,CLP_E_ENDTIME FROM ',TEMP_CUSTOMER_LP_DETAILS,' WHERE SNO=@MINID'));
PREPARE TEMP_CUSTOMERLP_STMT FROM @TEMP_CUSTOMERLP_QUERY;
EXECUTE TEMP_CUSTOMERLP_STMT;
END IF;
IF @PRE_TERM>=@F_CLPSTARTDATE THEN
SET @TEMP_CUSTOMERLP_QUERY=(SELECT CONCAT('INSERT INTO ',TEMP_CUSTOMER_LPDETAILS,'(UNIT,ROOMTYPE,CED_REC_VER,CLP_START_DATE,CLP_END_DATE,CLP_PRE_TERMINATE_DATE,PRETERMINATE,EXTENSION,RECHECKIN,CLP_S_STARTTIME,CLP_S_ENDTIME,CLP_E_STARTTIME,CLP_E_ENDTIME)SELECT UNIT,ROOMTYPE,CED_REC_VER,CLP_START_DATE,CLP_END_DATE,CLP_PRE_TERMINATE_DATE,PRETERMINATE,EXTENSION,RECHECKIN,CLP_S_STARTTIME,CLP_S_ENDTIME,CLP_E_STARTTIME,CLP_E_ENDTIME FROM ',TEMP_CUSTOMER_LP_DETAILS,' WHERE SNO=@MINID'));
PREPARE TEMP_CUSTOMERLP_STMT FROM @TEMP_CUSTOMERLP_QUERY;
EXECUTE TEMP_CUSTOMERLP_STMT;
END IF;
SET @MINID=@MINID+1;
END WHILE;

SET @MIN_IDQUERY=(SELECT CONCAT('SELECT MIN(SNO) INTO @MIN_ID FROM ',TEMP_CUSTOMER_LPDETAILS));
PREPARE MIN_IDQUERY_STMT FROM @MIN_IDQUERY;
EXECUTE MIN_IDQUERY_STMT;
SET MINIMUM_ID=@MIN_ID;
SET @MAX_IDQUERY=(SELECT CONCAT('SELECT MAX(SNO) INTO @MAX_ID FROM ',TEMP_CUSTOMER_LPDETAILS));
PREPARE MAX_IDQUERY_STMT FROM @MAX_IDQUERY;
EXECUTE MAX_IDQUERY_STMT;
SET MAXIMUM_ID=@MAX_ID;
WHILE @MIN_ID<=@MAX_ID DO
SET @PRETERMINDATEQUERY=(SELECT CONCAT('SELECT CLP_PRE_TERMINATE_DATE INTO @PRETERM FROM ',TEMP_CUSTOMER_LPDETAILS,' WHERE SNO=@MIN_ID'));
PREPARE PRETERMINDATE_STMT FROM @PRETERMINDATEQUERY;
EXECUTE PRETERMINDATE_STMT;
IF @PRETERM IS NOT NULL THEN
SET @ENDDATEUPDATEQUERY=(SELECT CONCAT('UPDATE ',TEMP_CUSTOMER_LPDETAILS,' SET CLP_END_DATE=@PRETERM WHERE SNO=@MIN_ID'));
PREPARE ENDDATEUPDATEQUERY_STMT FROM @ENDDATEUPDATEQUERY;
EXECUTE ENDDATEUPDATEQUERY_STMT;
END IF;
SET @MIN_ID=@MIN_ID+1;
END WHILE;
SET TEMP_CALENDAR_LIST=(SELECT CONCAT('TEMP_CALENDAR_LIST',SYSDATEANDULDID));
SET @TEMP_CALENDAR_LIST_CREATE=(SELECT CONCAT('CREATE TABLE ',TEMP_CALENDAR_LIST,'(SNO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,UNIT INTEGER(4) UNSIGNED ZEROFILL,ROOMTYPE VARCHAR(30),CLP_DATE DATE,CLP_STARTTIME TIME,CLP_ENDTIME TIME,STATUS VARCHAR(15),DIFFUNIT CHAR(1),DIFFROOM CHAR(1))'));
PREPARE TEMP_CALENDAR_LIST_CREATE_STMT FROM @TEMP_CALENDAR_LIST_CREATE;
EXECUTE TEMP_CALENDAR_LIST_CREATE_STMT;
WHILE MINIMUM_ID<= MAXIMUM_ID DO
SET @F_UNIT_NO_QUERY=(SELECT CONCAT('SELECT UNIT INTO @F_UNIT_NO FROM ',TEMP_CUSTOMER_LPDETAILS,' WHERE SNO=',MINIMUM_ID));
PREPARE F_UNIT_NO_QUERY_STMT FROM @F_UNIT_NO_QUERY;
EXECUTE F_UNIT_NO_QUERY_STMT;
SET @F_ROOMTYPE_QUERY=(SELECT CONCAT('SELECT ROOMTYPE INTO @F_ROOMTYPE FROM ',TEMP_CUSTOMER_LPDETAILS,' WHERE SNO=',MINIMUM_ID));
PREPARE F_ROOMTYPE_QUERY_STMT FROM @F_ROOMTYPE_QUERY;
EXECUTE F_ROOMTYPE_QUERY_STMT;
SET @F_CLP_START_DATE_QUERY=(SELECT CONCAT('SELECT CLP_START_DATE INTO @F_CLP_START_DATE FROM ',TEMP_CUSTOMER_LPDETAILS,' WHERE SNO=',MINIMUM_ID));
PREPARE F_CLP_START_DATE_STMT FROM @F_CLP_START_DATE_QUERY;
EXECUTE F_CLP_START_DATE_STMT;
SET @F_CLP_S_STARTTIME_QUERY=(SELECT CONCAT('SELECT CLP_S_STARTTIME INTO @F_CLP_S_STARTTIME FROM ',TEMP_CUSTOMER_LPDETAILS,' WHERE SNO=',MINIMUM_ID));
PREPARE F_CLP_S_STARTTIME_STMT FROM @F_CLP_S_STARTTIME_QUERY;
EXECUTE F_CLP_S_STARTTIME_STMT;
SET @F_CLP_S_ENDTIME_QUERY=(SELECT CONCAT('SELECT CLP_S_ENDTIME INTO @F_CLP_S_ENDTIME FROM ',TEMP_CUSTOMER_LPDETAILS,' WHERE SNO=',MINIMUM_ID));
PREPARE F_CLP_S_ENDTIME_STMT FROM @F_CLP_S_ENDTIME_QUERY;
EXECUTE F_CLP_S_ENDTIME_STMT;
SET @F_CLP_END_DATE_QUERY=(SELECT CONCAT('SELECT CLP_END_DATE INTO @F_CLP_END_DATE FROM ',TEMP_CUSTOMER_LPDETAILS,' WHERE SNO=',MINIMUM_ID));
PREPARE F_CLP_END_DATE_STMT FROM @F_CLP_END_DATE_QUERY;
EXECUTE F_CLP_END_DATE_STMT;
SET @F_CLP_E_STARTTIME_QUERY=(SELECT CONCAT('SELECT CLP_E_STARTTIME INTO @F_CLP_E_STARTTIME FROM ',TEMP_CUSTOMER_LPDETAILS,' WHERE SNO=',MINIMUM_ID));
PREPARE F_CLP_E_STARTTIME_STMT FROM @F_CLP_E_STARTTIME_QUERY;
EXECUTE F_CLP_E_STARTTIME_STMT;
SET @F_CLP_E_ENDTIME_QUERY=(SELECT CONCAT('SELECT CLP_E_ENDTIME INTO @F_CLP_E_ENDTIME FROM ',TEMP_CUSTOMER_LPDETAILS,' WHERE SNO=',MINIMUM_ID));
PREPARE F_CLP_E_ENDTIME_STMT FROM @F_CLP_E_ENDTIME_QUERY;
EXECUTE F_CLP_E_ENDTIME_STMT;
SET @F_UNIT_NO_QUERY_1=(SELECT CONCAT('SELECT UNIT INTO @F_UNIT_NO_1 FROM ',TEMP_CUSTOMER_LPDETAILS,' WHERE SNO=',MINIMUM_ID-1));
PREPARE F_UNIT_NO_QUERY_1_STMT FROM @F_UNIT_NO_QUERY_1;
EXECUTE F_UNIT_NO_QUERY_1_STMT;
SET @F_ROOMTYPE_1_QUERY=(SELECT CONCAT('SELECT ROOMTYPE INTO @F_ROOMTYPE_1 FROM ',TEMP_CUSTOMER_LPDETAILS,' WHERE SNO=',MINIMUM_ID-1));
PREPARE F_ROOMTYPE_1_QUERY_STMT FROM @F_ROOMTYPE_1_QUERY;
EXECUTE F_ROOMTYPE_1_QUERY_STMT;
SET @EXTENSION_FLAGQUERY=(SELECT CONCAT('SELECT EXTENSION INTO @EXTENSIONFLAG FROM ',TEMP_CUSTOMER_LPDETAILS,' WHERE SNO=',MINIMUM_ID));
PREPARE EXTENSION_FLAGQUERY_STMT FROM @EXTENSION_FLAGQUERY;
EXECUTE EXTENSION_FLAGQUERY_STMT;
SET EXTENSION_FLAG=@EXTENSIONFLAG;
SET @TERMINATE_FLAGQUERY=(SELECT CONCAT('SELECT PRETERMINATE INTO @TERMINATEFLAG FROM ',TEMP_CUSTOMER_LPDETAILS,' WHERE SNO=',MINIMUM_ID));
PREPARE TERMINATE_FLAGQUERY_STMT FROM @TERMINATE_FLAGQUERY;
EXECUTE TERMINATE_FLAGQUERY_STMT;
SET TERMINATE_FLAG=@TERMINATEFLAG;
SET @INSTATUS='CHECKIN';
SET @OUTSTATUS='CHECKOUT';
IF MINIMUM_ID=1 THEN
SET @TEMP_CALENDAR_LIST_INSERT1=(SELECT CONCAT('INSERT INTO ',TEMP_CALENDAR_LIST,'(UNIT,ROOMTYPE,CLP_DATE,CLP_STARTTIME,CLP_ENDTIME,STATUS)VALUES(@F_UNIT_NO,@F_ROOMTYPE,@F_CLP_START_DATE,@F_CLP_S_STARTTIME,@F_CLP_S_ENDTIME,@INSTATUS)'));
PREPARE TEMP_CALENDAR_LIST_INSERT1_STMT FROM @TEMP_CALENDAR_LIST_INSERT1;
EXECUTE TEMP_CALENDAR_LIST_INSERT1_STMT;
END IF;
IF MINIMUM_ID=1 AND MAXIMUM_ID=1 THEN 
SET @TEMP_CALENDAR_LIST_INSERT2=(SELECT CONCAT('INSERT INTO ',TEMP_CALENDAR_LIST,'(UNIT,ROOMTYPE,CLP_DATE,CLP_STARTTIME,CLP_ENDTIME,STATUS)VALUES(@F_UNIT_NO,@F_ROOMTYPE,@F_CLP_END_DATE,@F_CLP_E_STARTTIME,@F_CLP_E_ENDTIME,@OUTSTATUS)'));
PREPARE TEMP_CALENDAR_LIST_INSERT2_STMT FROM @TEMP_CALENDAR_LIST_INSERT2;
EXECUTE TEMP_CALENDAR_LIST_INSERT2_STMT;
END IF;
IF EXTENSION_FLAG='X' THEN
IF @F_UNIT_NO=@F_UNIT_NO_1 AND @F_ROOMTYPE_1!=@F_ROOMTYPE THEN
SET @DIFF_ROOM='X';
SET @TEMP_CALENDAR_LIST_INSERT3=(SELECT CONCAT('INSERT INTO ',TEMP_CALENDAR_LIST,'(UNIT,ROOMTYPE,CLP_DATE,CLP_STARTTIME,CLP_ENDTIME,STATUS,DIFFROOM)VALUES(@F_UNIT_NO,@F_ROOMTYPE,@F_CLP_START_DATE,@F_CLP_S_STARTTIME,@F_CLP_S_ENDTIME,@INSTATUS,@DIFF_ROOM)'));
PREPARE TEMP_CALENDAR_LIST_INSERT3_STMT FROM @TEMP_CALENDAR_LIST_INSERT3;
EXECUTE TEMP_CALENDAR_LIST_INSERT3_STMT;
END IF;
END IF;
IF EXTENSION_FLAG='X' THEN
IF @F_UNIT_NO!=@F_UNIT_NO_1 THEN
SET @DIFF_UNIT='X';
SET @TEMP_CALENDAR_LIST_INSERT4=(SELECT CONCAT('INSERT INTO ',TEMP_CALENDAR_LIST,'(UNIT,ROOMTYPE,CLP_DATE,CLP_STARTTIME,CLP_ENDTIME,STATUS,DIFFUNIT)VALUES(@F_UNIT_NO,@F_ROOMTYPE,@F_CLP_START_DATE,@F_CLP_S_STARTTIME,@F_CLP_S_ENDTIME,@INSTATUS,@DIFF_UNIT)'));
PREPARE TEMP_CALENDAR_LIST_INSERT4_STMT FROM @TEMP_CALENDAR_LIST_INSERT4;
EXECUTE TEMP_CALENDAR_LIST_INSERT4_STMT;
END IF;
END IF;
IF MINIMUM_ID=MAXIMUM_ID AND MAXIMUM_ID!=1 THEN
SET @TEMP_CALENDAR_LIST_INSERT5=(SELECT CONCAT('INSERT INTO ',TEMP_CALENDAR_LIST,'(UNIT,ROOMTYPE,CLP_DATE,CLP_STARTTIME,CLP_ENDTIME,STATUS)VALUES(@F_UNIT_NO,@F_ROOMTYPE,@F_CLP_END_DATE,@F_CLP_E_STARTTIME,@F_CLP_E_ENDTIME,@OUTSTATUS)'));
PREPARE TEMP_CALENDAR_LIST_INSERT5_STMT FROM @TEMP_CALENDAR_LIST_INSERT5;
EXECUTE TEMP_CALENDAR_LIST_INSERT5_STMT;
END IF;
SET MINIMUM_ID=MINIMUM_ID+1;
END WHILE;
SET @TEMPMAXRECVERTABLEDROPQUERY=(SELECT CONCAT('DROP TABLE IF EXISTS ',RECVERTABLENAME));
PREPARE TEMPMAXRECVERTABLEDROPQUERY_STMT FROM @TEMPMAXRECVERTABLEDROPQUERY;
EXECUTE TEMPMAXRECVERTABLEDROPQUERY_STMT;
SET @TEMPTABLEDROPQUERY=(SELECT CONCAT('DROP TABLE IF EXISTS ',TEMP_CUSTOMER_LPDETAILS));
PREPARE TEMPTABLEDROPQUERY_STMT FROM @TEMPTABLEDROPQUERY;
EXECUTE TEMPTABLEDROPQUERY_STMT;
SET @TEMPTABLEDROP_QUERY=(SELECT CONCAT('DROP TABLE IF EXISTS ',TEMP_CUSTOMER_LP_DETAILS));
PREPARE TEMPTABLEDROP_QUERY_STMT FROM @TEMPTABLEDROP_QUERY;
EXECUTE TEMPTABLEDROP_QUERY_STMT;
COMMIT;
END;