DROP PROCEDURE IF EXISTS SP_TRG_CUSTOMER_FEE_DETAILS_VALIDATION;
CREATE PROCEDURE SP_TRG_CUSTOMER_FEE_DETAILS_VALIDATION(
IN NEWCFDID INTEGER,
IN NEWCUSTOMERID INTEGER,
IN NEWCPPID INTEGER,
IN NEWCEDRECVER INTEGER,
IN NEWCFDAMOUNT DECIMAL(7,2),
IN PROCESS TEXT)
BEGIN
DECLARE CFDAMOUNT INTEGER;
DECLARE OLDRECVER INTEGER;
DECLARE OLDCPPID INTEGER;
SET OLDRECVER=(SELECT CED_REC_VER FROM CUSTOMER_FEE_DETAILS WHERE CFD_ID=NEWCFDID);
SET OLDCPPID=(SELECT CPP_ID FROM CUSTOMER_FEE_DETAILS WHERE CFD_ID=NEWCFDID);
SET CFDAMOUNT=(SELECT SUBSTRING_INDEX(NEWCFDAMOUNT, '.', 1));
IF PROCESS='INSERT' OR PROCESS='UPDATE' THEN
IF NEWCPPID=5 THEN
	IF LENGTH(CFDAMOUNT)>3 THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'ELECTRICITY CAP SHOULD NOT  BE GREATER THAN 3 DIGITS !!!';
	END IF;  
	IF LENGTH(CFDAMOUNT)<2 THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'ELECTRICITY CAP SHOULD NOT  BE LESS THAN 2 DIGITS !!!';
	END IF;  
END IF;
IF NEWCPPID=1 THEN
	IF LENGTH(CFDAMOUNT)>5 THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'PAYMENT AMOUNT SHOULD NOT  BE GREATER THAN 5 DIGITS !!!';
	END IF;  
	IF LENGTH(CFDAMOUNT)<3 THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'PAYMENT AMOUNT SHOULD NOT  BE LESS THAN 3 DIGITS !!!';
	END IF;  
END IF;
IF NEWCPPID=2 THEN
	IF LENGTH(CFDAMOUNT)>5 THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'DEPOSIT AMOUNT SHOULD NOT  BE GREATER THAN 5 DIGITS !!!';
	END IF;  
	IF LENGTH(CFDAMOUNT)<3 THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'DEPOSIT AMOUNT SHOULD NOT  BE LESS THAN 3 DIGITS !!!';
	END IF;  
END IF;
IF NEWCPPID=3 THEN
	IF LENGTH(CFDAMOUNT)>4 THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'PROCESSING COST SHOULD NOT  BE GREATER THAN 4 DIGITS !!!';
	END IF;  
	IF LENGTH(CFDAMOUNT)<3 THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'PROCESSING COST SHOULD NOT  BE LESS THAN 3 DIGITS !!!';
	END IF;  
END IF;
IF NEWCPPID=4 THEN
	IF LENGTH(CFDAMOUNT)>3 THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'AIRCON FIXED FEE SHOULD NOT  BE GREATER THAN 3 DIGITS !!!';
	END IF; 
END IF; 
IF NEWCPPID=7 THEN
	IF LENGTH(CFDAMOUNT)>3 THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'AIRCON QUARTELY FEE SHOULD NOT  BE GREATER THAN 3 DIGITS !!!';
	END IF; 
END IF; 
IF NEWCPPID=6 THEN
	IF LENGTH(CFDAMOUNT)>3 THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'DRYCLEAN FEE SHOULD BE GREATER THAN 3 DIGITS !!!';
	END IF; 
END IF; 
IF NEWCPPID=8 THEN
	IF LENGTH(CFDAMOUNT)>3 THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'CHECKOUT CLEANING FEE SHOULD  BE GREATER THAN 3 DIGITS !!!';
	END IF; 
END IF; 
END IF;
IF PROCESS='INSERT' THEN
	IF EXISTS(SELECT CPP_ID FROM CUSTOMER_FEE_DETAILS WHERE CUSTOMER_ID=NEWCUSTOMERID AND CED_REC_VER=NEWCEDRECVER AND CPP_ID=NEWCPPID)THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'THIS RECVER & THIS AMOUNT ALREADY EXISTS FOR THIS CUSTOMER !!!';
	END IF;
	IF NEWCPPID=4 THEN
		IF EXISTS(SELECT CPP_ID FROM CUSTOMER_FEE_DETAILS WHERE CUSTOMER_ID=NEWCUSTOMERID AND CED_REC_VER=NEWCEDRECVER AND CPP_ID=7)THEN
			SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = 'THERE SHLD BE ONE AIRCON FEE OR FIXED AIRCON,THIS CUSTOMER ALREADY HAVING AIRCON_QUARTELY_FEE IN THIS LP !!!';
		END IF;
	END IF;
	IF NEWCPPID=7 THEN
		IF EXISTS(SELECT CPP_ID FROM CUSTOMER_FEE_DETAILS WHERE CUSTOMER_ID=NEWCUSTOMERID AND CED_REC_VER=NEWCEDRECVER AND CPP_ID=4)THEN
			SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = 'THERE SHLD BE ONE AIRCON FEE OR FIXED AIRCON,THIS CUSTOMER ALREADY HAVING AIRCON_FIXED_FEE IN THIS LP !!!';
		END IF;
	END IF;
END IF;
IF PROCESS='UPDATE' THEN
	IF NEWCPPID=4 THEN
		IF OLDCPPID!=NEWCPPID THEN
			IF EXISTS(SELECT * FROM CUSTOMER_FEE_DETAILS WHERE CUSTOMER_ID=NEWCUSTOMERID AND CED_REC_VER=NEWCEDRECVER AND CPP_ID=7 AND CFD_ID!=NEWCFDID)THEN
				SIGNAL SQLSTATE '45000'
				SET MESSAGE_TEXT = 'THERE SHLD BE ONE AIRCON FEE OR FIXED AIRCON,THIS CUSTOMER ALREADY HAVING AIRCON_QUARTELY_FEE IN THIS LP !!!';
			END IF;
		END IF;
	END IF;
	IF NEWCPPID=7 THEN
		IF OLDCPPID!=NEWCPPID THEN
			IF EXISTS(SELECT * FROM CUSTOMER_FEE_DETAILS WHERE CUSTOMER_ID=NEWCUSTOMERID AND CED_REC_VER=NEWCEDRECVER AND CPP_ID=4 AND CFD_ID!=NEWCFDID)THEN
				SIGNAL SQLSTATE '45000'
				SET MESSAGE_TEXT = 'THERE SHLD BE ONE AIRCON FEE OR FIXED AIRCON,THIS CUSTOMER ALREADY HAVING AIRCON_FIXED_FEE IN THIS LP !!!';
			END IF;
		END IF;
	END IF; 
	IF OLDRECVER!=NEWCEDRECVER OR OLDCPPID!=NEWCPPID THEN
		IF EXISTS(SELECT * FROM CUSTOMER_FEE_DETAILS WHERE CUSTOMER_ID=NEWCUSTOMERID AND CED_REC_VER=NEWCEDRECVER AND CPP_ID=NEWCPPID )THEN
			SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = 'THIS RECVER & THIS AMOUNT ALREADY EXISTS FOR THIS CUSTOMER !!!';
		END IF;
	END IF;
END IF;
END;