DROP PROCEDURE IF EXISTS SP_TRG_CUSTOMER_ENTRY_DETAILS_VALIDATION;
CREATE PROCEDURE SP_TRG_CUSTOMER_ENTRY_DETAILS_VALIDATION(
IN NEWCEDID INTEGER,
IN NEWCUSTOMERID INTEGER,
IN NEWRECVER INTEGER,
IN PROCESS TEXT)
BEGIN
DECLARE MESSAGE_TEXT TEXT;
DECLARE OLDRECVER INTEGER;
SET OLDRECVER=(SELECT CED_REC_VER FROM CUSTOMER_ENTRY_DETAILS WHERE CED_ID=NEWCEDID);
IF PROCESS='INSERT' THEN
    IF EXISTS(SELECT * FROM CUSTOMER_ENTRY_DETAILS WHERE CUSTOMER_ID=NEWCUSTOMERID AND CED_REC_VER=NEWRECVER)THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'ALREADY THIS RECVER EXISTS FOR THIS CUSTOMER';
	END IF;
END IF;
IF PROCESS='UPDATE' THEN
	IF OLDRECVER!=NEWRECVER THEN
	IF EXISTS(SELECT * FROM CUSTOMER_ENTRY_DETAILS WHERE CUSTOMER_ID=NEWCUSTOMERID AND CED_REC_VER=NEWRECVER)THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'ALREADY THIS RECVER EXISTS FOR THIS CUSTOMER';
	END IF;
	END IF;
END IF;
END;