DROP TRIGGER IF EXISTS TRG_CUSTOMER_FEE_DETAILS_INSERT_VALIDATION;
CREATE TRIGGER TRG_CUSTOMER_FEE_DETAILS_INSERT_VALIDATION
BEFORE INSERT ON CUSTOMER_FEE_DETAILS
FOR EACH ROW  
BEGIN
    CALL SP_TRG_CUSTOMER_FEE_DETAILS_VALIDATION(NEW.CFD_ID,NEW.CUSTOMER_ID,NEW.CPP_ID,NEW.CED_REC_VER,NEW.CFD_AMOUNT,'INSERT');
END;  