DROP TRIGGER IF EXISTS TRG_CUSTOMER_LP_DETAILS_UPDATE_VALIDATION;
CREATE TRIGGER TRG_CUSTOMER_LP_DETAILS_UPDATE_VALIDATION
BEFORE UPDATE ON CUSTOMER_LP_DETAILS
FOR EACH ROW
BEGIN
    CALL SP_TRG_CUSTOMER_LP_DETAILS_VALIDATION(NEW.CLP_ID,NEW.CUSTOMER_ID,NEW.CED_REC_VER,NEW.UASD_ID,NEW.CLP_STARTDATE,NEW.CLP_ENDDATE,NEW.CLP_PRETERMINATE_DATE,NEW.CLP_TERMINATE,NEW.CLP_GUEST_CARD,'UPDATE');
END;