DROP PROCEDURE IF EXISTS SP_BIZDLY_UNIT_DELETION;
CREATE PROCEDURE SP_BIZDLY_UNIT_DELETION(IN TABLE_ID INTEGER,IN ROW_ID INTEGER,IN V_USERSTAMP VARCHAR(50),OUT UPDATE_SUCCESSFLAG INTEGER)
BEGIN
DECLARE CUSTOMERID INTEGER;
DECLARE ID_VALUE INTEGER;
DECLARE CUSTOMER_VALUE INTEGER;
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
SET UPDATE_SUCCESSFLAG=0;
  ROLLBACK;
END;
START TRANSACTION;
SET UPDATE_SUCCESSFLAG=0;
SET CUSTOMER_VALUE=(SELECT CUSTOMER_ID FROM EXPENSE_UNIT WHERE EU_ID=ROW_ID);
CALL SP_SINGLE_TABLE_ROW_DELETION(TABLE_ID,ROW_ID,V_USERSTAMP,@DELETION_FLAG);
SET UPDATE_SUCCESSFLAG=1;
SET ID_VALUE=(SELECT MAX(TH_ID) FROM TICKLER_HISTORY WHERE CUSTOMER_ID IS NULL);
SET CUSTOMERID=(SELECT CUSTOMER_ID FROM TICKLER_HISTORY WHERE TH_ID=ID_VALUE);
IF (CUSTOMER_VALUE IS NOT NULL) THEN
UPDATE TICKLER_HISTORY SET CUSTOMER_ID=CUSTOMER_VALUE WHERE TH_ID=ID_VALUE;
SET UPDATE_SUCCESSFLAG=1;
END IF;
COMMIT;
END;