DROP PROCEDURE IF EXISTS SP_BIZDLY_DIGITAL_VOICE_INSERT;
CREATE PROCEDURE SP_BIZDLY_DIGITAL_VOICE_INSERT(
IN UNIT_NUMBER SMALLINT(4),
IN DV_ECN_ID INTEGER,
IN DV_INVOICE_DATE DATE,
IN DV_FROM_PERIOD DATE,
IN DV_TO_PERIOD DATE,
IN DV_AMOUNT DECIMAL(7,2),
IN DV_COMMENTS TEXT,
IN USERSTAMP VARCHAR(50),
OUT DIGITALVOICE_SUCCESSFLAG INTEGER )
BEGIN
	DECLARE EDDVID INTEGER;
	DECLARE ECNID INTEGER;
	DECLARE USERSTAMP_ID INTEGER(2);
  DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN 
	ROLLBACK; 
	SET DIGITALVOICE_SUCCESSFLAG=0;
	END;
	IF(DV_COMMENTS='' OR DV_COMMENTS IS NULL)THEN
		SET DV_COMMENTS = NULL;
	END IF;
	START TRANSACTION;
	SET DIGITALVOICE_SUCCESSFLAG=0;
	CALL SP_CHANGE_USERSTAMP_AS_ULDID(USERSTAMP,@ULDID);
    SET USERSTAMP_ID = (SELECT @ULDID);
	SET EDDVID = (SELECT MAX(EDDV_ID) FROM EXPENSE_DETAIL_DIGITAL_VOICE WHERE UNIT_ID = (SELECT UNIT_ID FROM UNIT WHERE UNIT_NO=UNIT_NUMBER));
	SET ECNID = (SELECT ECN_ID FROM EXPENSE_DETAIL_DIGITAL_VOICE WHERE EDDV_ID = EDDVID);
	IF  ECNID IS NULL THEN
		SET FOREIGN_KEY_CHECKS=0;
		UPDATE EXPENSE_DETAIL_DIGITAL_VOICE SET ECN_ID=DV_ECN_ID,ULD_ID=USERSTAMP_ID  WHERE EDDV_ID =EDDVID;
	END IF;
		SET FOREIGN_KEY_CHECKS=0;
	IF UNIT_NUMBER IS NOT NULL AND DV_ECN_ID IS NOT NULL AND DV_INVOICE_DATE IS NOT NULL AND DV_FROM_PERIOD IS NOT NULL AND DV_TO_PERIOD IS NOT NULL AND DV_AMOUNT IS NOT NULL AND USERSTAMP IS NOT NULL THEN
		INSERT INTO EXPENSE_DIGITAL_VOICE (EDDV_ID,EDV_INVOICE_DATE,EDV_FROM_PERIOD,EDV_TO_PERIOD,EDV_AMOUNT,EDV_COMMENTS,ULD_ID)VALUES (EDDVID,DV_INVOICE_DATE,DV_FROM_PERIOD,DV_TO_PERIOD,DV_AMOUNT,DV_COMMENTS,USERSTAMP_ID);
		SET DIGITALVOICE_SUCCESSFLAG=1;
	END IF;
COMMIT;
END;