DROP PROCEDURE IF EXISTS SP_EMPDTL_INSERT;
CREATE PROCEDURE SP_EMPDTL_INSERT(IN FIRST_NAME CHAR(30),
 IN LAST_NAME CHAR(30),
 IN DESIGNATION TEXT,
 IN MOBILE  VARCHAR(10),
 IN EMAIL VARCHAR(40),
 IN COMMENTS TEXT,
 IN USERSTAMP varchar(50),
 IN CARD_NO TEXT,
 OUT EMP_SUCCESSFLAG INTEGER)
BEGIN
    DECLARE TEMP_ACCESS_CARD TEXT;
    DECLARE ACCESS_CARD_NO INTEGER(7);
    DECLARE ACCESS_POSITION INTEGER;
    DECLARE ACCESS_LOCATION INTEGER;
    DECLARE ACCESS_LENGTH INTEGER;
    DECLARE TEMP_ACCESS_CARD_FLAG TEXT;
    DECLARE ACCESS_CARD_FLAG INTEGER(7);
    DECLARE ACCESS_POSITION_FLAG INTEGER;
    DECLARE ACCESS_LOCATION_FLAG INTEGER;
    DECLARE ACCESS_LENGTH_FLAG INTEGER;
    DECLARE USERSTAMP_ID INTEGER(2);
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
END;
START TRANSACTION;
SET EMP_SUCCESSFLAG=0;
CALL SP_CHANGE_USERSTAMP_AS_ULDID(USERSTAMP,@ULDID);
SET USERSTAMP_ID = (SELECT @ULDID);
	IF EMAIL = '' THEN
		SET EMAIL=NULL;
	END IF;
	IF COMMENTS = '' THEN
		SET COMMENTS=NULL;
	END IF;
	IF CARD_NO='' THEN
		SET CARD_NO=NULL;
	END IF;
	IF (FIRST_NAME IS NOT NULL AND LAST_NAME IS NOT NULL AND DESIGNATION IS NOT NULL AND MOBILE IS NOT NULL AND USERSTAMP_ID IS NOT NULL ) THEN
	IF CARD_NO IS NULL THEN
		INSERT INTO EMPLOYEE_DETAILS(EMP_FIRST_NAME,EMP_LAST_NAME,ECN_ID,EMP_MOBILE,EMP_EMAIL,EMP_COMMENTS,ULD_ID)
                    VALUES (FIRST_NAME,LAST_NAME,(SELECT ECN_ID FROM EXPENSE_CONFIGURATION WHERE ECN_DATA=DESIGNATION AND CGN_ID=35),MOBILE,EMAIL,COMMENTS,USERSTAMP_ID);
		SET EMP_SUCCESSFLAG=1;

	END IF;
	IF(CARD_NO IS NOT NULL) THEN
       	SET TEMP_ACCESS_CARD=CARD_NO;
        	SET ACCESS_LENGTH=1;
        loop_label:  LOOP
            SET ACCESS_POSITION=(SELECT LOCATE(',', TEMP_ACCESS_CARD,ACCESS_LENGTH));
            IF ACCESS_POSITION<=0 THEN
                SET ACCESS_CARD_NO=TEMP_ACCESS_CARD;
            ELSE
                SELECT SUBSTRING(TEMP_ACCESS_CARD,ACCESS_LENGTH,ACCESS_POSITION-1) INTO ACCESS_CARD_NO;
                SET TEMP_ACCESS_CARD=(SELECT SUBSTRING(TEMP_ACCESS_CARD,ACCESS_POSITION+1));
            END IF;
            IF EXISTS (SELECT UASD_ID FROM EMPLOYEE_CARD_DETAILS WHERE UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=ACCESS_CARD_NO)) THEN
                SET EMP_SUCCESSFLAG=1;
            END IF;
            IF ACCESS_POSITION<=0 THEN
                LEAVE  loop_label;
            END IF;
        END LOOP;
END IF;
 	IF EMP_SUCCESSFLAG!=1 THEN
		INSERT INTO EMPLOYEE_DETAILS (EMP_FIRST_NAME,EMP_LAST_NAME,ECN_ID,EMP_MOBILE,EMP_EMAIL,EMP_COMMENTS,ULD_ID) VALUES (FIRST_NAME,LAST_NAME,(SELECT ECN_ID
		FROM EXPENSE_CONFIGURATION WHERE ECN_DATA=DESIGNATION AND CGN_ID=35),MOBILE,EMAIL,COMMENTS,USERSTAMP_ID);
		SET EMP_SUCCESSFLAG=1;
		SET TEMP_ACCESS_CARD_FLAG =CARD_NO;
        	SET ACCESS_LENGTH_FLAG=1;
        loop_label:  LOOP
            	SET ACCESS_POSITION_FLAG=(SELECT LOCATE(',', TEMP_ACCESS_CARD_FLAG,ACCESS_LENGTH_FLAG));
            IF ACCESS_POSITION_FLAG<=0 THEN
                SET ACCESS_CARD_FLAG=TEMP_ACCESS_CARD_FLAG;
            ELSE
                SELECT SUBSTRING(TEMP_ACCESS_CARD_FLAG,ACCESS_LENGTH_FLAG,ACCESS_POSITION_FLAG-1) INTO ACCESS_CARD_FLAG;
                SET TEMP_ACCESS_CARD_FLAG=(SELECT SUBSTRING(TEMP_ACCESS_CARD_FLAG,ACCESS_POSITION_FLAG+1));
            END IF;
            	INSERT INTO EMPLOYEE_CARD_DETAILS (EMP_ID,UASD_ID) VALUES ((SELECT EMP_ID FROM EMPLOYEE_DETAILS ORDER BY EMP_ID DESC LIMIT 1),( SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=ACCESS_CARD_FLAG));
            	SET EMP_SUCCESSFLAG=1;
            IF ACCESS_POSITION_FLAG<=0 THEN
                LEAVE  loop_label;
            END IF;
        END LOOP;    
	END IF;
	END IF;
	COMMIT;
END;