DROP PROCEDURE IF EXISTS SP_TRG_BIZDTL_DIGITAL_VOICE_VALIDATION;
CREATE PROCEDURE SP_TRG_BIZDTL_DIGITAL_VOICE_VALIDATION(
IN OLDEDDVID INTEGER,
IN NEWEDDVID INTEGER,
IN NEWECNID INTEGER,
IN PROCESS TEXT)
BEGIN
	DECLARE MESSAGE_TEXT VARCHAR(50);
	IF(PROCESS = 'INSERT') THEN
		IF(NEWECNID IS NOT NULL)THEN
			IF NOT EXISTS(SELECT ECN_ID FROM EXPENSE_CONFIGURATION WHERE ECN_ID = NEWECNID AND CGN_ID = 27)THEN
				SIGNAL SQLSTATE '45000'
				SET MESSAGE_TEXT = 'GIVE ECN_ID IN BETWEEN 19 TO 21';
			END IF;
		END IF;
	END IF;
	IF(PROCESS = 'UPDATE') THEN
		IF(NEWECNID IS NOT NULL)THEN
			IF NOT EXISTS(SELECT ECN_ID FROM EXPENSE_CONFIGURATION WHERE ECN_ID = NEWECNID AND CGN_ID = 27)THEN
				SIGNAL SQLSTATE '45000'
				SET MESSAGE_TEXT = 'GIVE ECN_ID IN BETWEEN 19 TO 21';
			END IF;
		END IF;
	END IF;
END;