DROP TRIGGER IF EXISTS TRG_STAFFDLY_AGENT_UPDATE;
CREATE TRIGGER TRG_STAFFDLY_AGENT_UPDATE  
AFTER UPDATE ON EXPENSE_AGENT
FOR EACH ROW
BEGIN 
DECLARE OLD_VALUE TEXT DEFAULT '';
DECLARE NEW_VALUE TEXT DEFAULT '';
IF ((OLD.EA_DATE!=NEW.EA_DATE) OR (OLD.EA_COMM_AMOUNT!=NEW.EA_COMM_AMOUNT) OR (OLD.EA_COMMENTS IS NULL AND NEW.EA_COMMENTS IS NOT NULL) OR (OLD.EA_COMMENTS IS NOT NULL AND NEW.EA_COMMENTS IS NULL) OR (OLD.EA_COMMENTS!= NEW.EA_COMMENTS))THEN  
  SET OLD_VALUE = CONCAT(OLD_VALUE,'EA_ID=', OLD.EA_ID,','); 
END IF;
IF (OLD.EA_DATE!= NEW.EA_DATE) THEN  
  SET OLD_VALUE = CONCAT(OLD_VALUE,'EA_DATE=', OLD.EA_DATE,','); 
  SET NEW_VALUE = CONCAT(NEW_VALUE,'EA_DATE=', NEW.EA_DATE,',');
END IF;
IF (OLD.EA_COMM_AMOUNT!= NEW.EA_COMM_AMOUNT) THEN  
  SET OLD_VALUE = CONCAT(OLD_VALUE,'EA_COMM_AMOUNT=', OLD.EA_COMM_AMOUNT,','); 
  SET NEW_VALUE = CONCAT(NEW_VALUE,'EA_COMM_AMOUNT=', NEW.EA_COMM_AMOUNT,',');
END IF;
IF (OLD.EA_COMMENTS IS NULL AND NEW.EA_COMMENTS IS NOT NULL) THEN
SET OLD_VALUE=CONCAT(OLD_VALUE,'EA_COMMENTS=','<NULL>,');
SET NEW_VALUE=CONCAT(NEW_VALUE,'EA_COMMENTS=',NEW.EA_COMMENTS,',');
ELSEIF(OLD.EA_COMMENTS IS NOT NULL AND NEW.EA_COMMENTS IS NULL) THEN
SET OLD_VALUE=CONCAT(OLD_VALUE,'EA_COMMENTS=',OLD.EA_COMMENTS,',');
SET NEW_VALUE=CONCAT(NEW_VALUE,'EA_COMMENTS=','<NULL>,');
ELSEIF (OLD.EA_COMMENTS!= NEW.EA_COMMENTS) THEN 
SET OLD_VALUE = CONCAT(OLD_VALUE,'EA_COMMENTS=', OLD.EA_COMMENTS,','); 
SET NEW_VALUE = CONCAT(NEW_VALUE,'EA_COMMENTS=', NEW.EA_COMMENTS,','); 
END IF;
IF ((OLD.EA_DATE!=NEW.EA_DATE) OR (OLD.EA_COMM_AMOUNT!=NEW.EA_COMM_AMOUNT) OR (OLD.EA_COMMENTS IS NULL AND NEW.EA_COMMENTS IS NOT NULL) OR (OLD.EA_COMMENTS IS NOT NULL AND NEW.EA_COMMENTS IS NULL) OR (OLD.EA_COMMENTS!= NEW.EA_COMMENTS))THEN  
 IF (OLD.ULD_ID!= NEW.ULD_ID) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'ULD_ID=', OLD.ULD_ID,','); 
END IF;
IF (OLD.EA_TIMESTAMP!= NEW.EA_TIMESTAMP) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'EA_TIMESTAMP=', OLD.EA_TIMESTAMP,','); 
END IF;
END IF;
IF (OLD_VALUE!='' AND NEW_VALUE!='') THEN
IF(OLD_VALUE != NEW_VALUE)THEN
     SET OLD_VALUE = SUBSTRING(OLD_VALUE,1,CHAR_LENGTH(OLD_VALUE)-1);
     SET NEW_VALUE = SUBSTRING(NEW_VALUE,1,CHAR_LENGTH(NEW_VALUE)-1);
INSERT INTO TICKLER_HISTORY
(ULD_ID,TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE)VALUES
((SELECT ULD_ID FROM EXPENSE_AGENT WHERE EA_ID=NEW.EA_ID),
(SELECT TP_ID FROM TICKLER_PROFILE WHERE TP_TYPE='UPDATION'),
(SELECT TTIP_ID FROM TICKLER_TABID_PROFILE WHERE TTIP_DATA='EXPENSE_AGENT'),OLD_VALUE,NEW_VALUE);
END IF;
END IF;
END;