DROP TRIGGER IF EXISTS TRG_BIZDTL_DIGITAL_VOICE_INSERT_VALIDATION;
CREATE TRIGGER TRG_BIZDTL_DIGITAL_VOICE_INSERT_VALIDATION
BEFORE INSERT ON EXPENSE_DETAIL_DIGITAL_VOICE
FOR EACH ROW
BEGIN
	CALL SP_TRG_BIZDTL_DIGITAL_VOICE_VALIDATION(NULL,NULL,NEW.ECN_ID,'INSERT');
END;