DROP TRIGGER IF EXISTS TRG_PERSONAL_BABY_UPDATE_VALIDATION;
CREATE TRIGGER TRG_PERSONAL_BABY_UPDATE_VALIDATION
BEFORE UPDATE ON EXPENSE_BABY
FOR EACH ROW
BEGIN
	CALL SP_TRG_PERSONAL_BABY_VALIDATION(NEW.ECN_ID,NEW.EB_INVOICE_DATE,'UPDATE');
END;