DROP TRIGGER IF EXISTS TRG_PERSONAL_CAR_LOAN_UPDATE_VALIDATION;
CREATE TRIGGER TRG_PERSONAL_CAR_LOAN_UPDATE_VALIDATION
BEFORE UPDATE ON EXPENSE_CAR_LOAN
FOR EACH ROW
BEGIN
	CALL SP_TRG_PERSONAL_CAR_LOAN_VALIDATION(NEW.ECL_PAID_DATE,NEW.ECL_FROM_PERIOD,NEW.ECL_TO_PERIOD,'UPDATE');
END;