DROP TRIGGER IF EXISTS TRG_PERSONAL_UPDATE;
CREATE TRIGGER TRG_PERSONAL_UPDATE  
AFTER UPDATE ON EXPENSE_PERSONAL
FOR EACH ROW
BEGIN 
DECLARE OLD_VALUE TEXT DEFAULT '';
DECLARE NEW_VALUE TEXT DEFAULT '';
IF ((OLD.ECN_ID!= NEW.ECN_ID) OR (OLD.EP_INVOICE_DATE!= NEW.EP_INVOICE_DATE) OR (OLD.EP_AMOUNT!= NEW.EP_AMOUNT) OR (OLD.EP_INVOICE_ITEMS!= NEW.EP_INVOICE_ITEMS) OR (OLD.EP_INVOICE_FROM!= NEW.EP_INVOICE_FROM) OR (OLD.EP_COMMENTS IS NULL AND NEW.EP_COMMENTS IS NOT NULL) OR (OLD.EP_COMMENTS IS NOT NULL AND NEW.EP_COMMENTS IS NULL) OR (OLD.EP_COMMENTS!= NEW.EP_COMMENTS)) THEN  
  SET OLD_VALUE = CONCAT(OLD_VALUE,'EP_ID=', OLD.EP_ID,','); 
END IF;
IF (OLD.ECN_ID!= NEW.ECN_ID) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'ECN_ID=', OLD.ECN_ID,','); 
END IF;
IF (OLD.ECN_ID!= NEW.ECN_ID) THEN SET 
NEW_VALUE = CONCAT(NEW_VALUE,'ECN_ID=', NEW.ECN_ID,','); 
END IF;
IF (OLD.EP_INVOICE_DATE!= NEW.EP_INVOICE_DATE) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'EP_INVOICE_DATE=', OLD.EP_INVOICE_DATE,','); 
END IF;
IF (OLD.EP_INVOICE_DATE!= NEW.EP_INVOICE_DATE) THEN SET 
NEW_VALUE = CONCAT(NEW_VALUE,'EP_INVOICE_DATE=', NEW.EP_INVOICE_DATE,','); 
END IF;
IF (OLD.EP_AMOUNT!= NEW.EP_AMOUNT) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'EP_AMOUNT=', OLD.EP_AMOUNT,','); 
END IF;
IF (OLD.EP_AMOUNT!= NEW.EP_AMOUNT) THEN SET 
NEW_VALUE = CONCAT(NEW_VALUE,'EP_AMOUNT=', NEW.EP_AMOUNT,','); 
END IF;
IF (OLD.EP_INVOICE_ITEMS!= NEW.EP_INVOICE_ITEMS) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'EP_INVOICE_ITEMS=', OLD.EP_INVOICE_ITEMS,','); 
END IF;
IF (OLD.EP_INVOICE_ITEMS!= NEW.EP_INVOICE_ITEMS) THEN SET 
NEW_VALUE = CONCAT(NEW_VALUE,'EP_INVOICE_ITEMS=', NEW.EP_INVOICE_ITEMS,','); 
END IF;
IF (OLD.EP_INVOICE_FROM!= NEW.EP_INVOICE_FROM) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'EP_INVOICE_FROM=', OLD.EP_INVOICE_FROM,','); 
END IF;
IF (OLD.EP_INVOICE_FROM!= NEW.EP_INVOICE_FROM) THEN SET 
NEW_VALUE = CONCAT(NEW_VALUE,'EP_INVOICE_FROM=', NEW.EP_INVOICE_FROM,','); 
END IF;
IF (OLD.EP_COMMENTS IS NULL AND NEW.EP_COMMENTS IS NOT NULL) THEN
SET OLD_VALUE=CONCAT(OLD_VALUE,'EP_COMMENTS=','<NULL>,');
SET NEW_VALUE=CONCAT(NEW_VALUE,'EP_COMMENTS=',NEW.EP_COMMENTS,',');
ELSEIF(OLD.EP_COMMENTS IS NOT NULL AND NEW.EP_COMMENTS IS NULL) THEN
SET OLD_VALUE=CONCAT(OLD_VALUE,'EP_COMMENTS=',OLD.EP_COMMENTS,',');
SET NEW_VALUE=CONCAT(NEW_VALUE,'EP_COMMENTS=','<NULL>,');
ELSEIF (OLD.EP_COMMENTS!= NEW.EP_COMMENTS) THEN 
SET OLD_VALUE = CONCAT(OLD_VALUE,'EP_COMMENTS=', OLD.EP_COMMENTS,','); 
SET NEW_VALUE = CONCAT(NEW_VALUE,'EP_COMMENTS=', NEW.EP_COMMENTS,','); 
END IF;
IF ((OLD.ECN_ID!= NEW.ECN_ID) OR (OLD.EP_INVOICE_DATE!= NEW.EP_INVOICE_DATE) OR (OLD.EP_AMOUNT!= NEW.EP_AMOUNT) OR (OLD.EP_INVOICE_ITEMS!= NEW.EP_INVOICE_ITEMS) OR (OLD.EP_INVOICE_FROM!= NEW.EP_INVOICE_FROM) OR (OLD.EP_COMMENTS IS NULL AND NEW.EP_COMMENTS IS NOT NULL) OR (OLD.EP_COMMENTS IS NOT NULL AND NEW.EP_COMMENTS IS NULL) OR (OLD.EP_COMMENTS!= NEW.EP_COMMENTS)) THEN  
IF (OLD.ULD_ID!= NEW.ULD_ID) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'ULD_ID=', OLD.ULD_ID,','); 
END IF;
IF (OLD.EP_TIMESTAMP!= NEW.EP_TIMESTAMP) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'EP_TIMESTAMP=', OLD.EP_TIMESTAMP,','); 
END IF;
END IF;
IF (OLD_VALUE!='' AND NEW_VALUE!='') THEN
IF(OLD_VALUE!=NEW_VALUE)THEN
SET OLD_VALUE = SUBSTRING(OLD_VALUE,1,CHAR_LENGTH(OLD_VALUE)-1);
SET NEW_VALUE = SUBSTRING(NEW_VALUE,1,CHAR_LENGTH(NEW_VALUE)-1);
INSERT INTO TICKLER_HISTORY
(ULD_ID,TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE)VALUES
((SELECT ULD_ID FROM EXPENSE_PERSONAL WHERE EP_ID=NEW.EP_ID),
(SELECT TP_ID FROM TICKLER_PROFILE WHERE TP_TYPE='UPDATION'),
(SELECT TTIP_ID FROM TICKLER_TABID_PROFILE WHERE TTIP_DATA='EXPENSE_PERSONAL'),OLD_VALUE,NEW_VALUE);
END IF;
END IF;
END;