DROP TRIGGER IF EXISTS TRG_PERSONAL_UPDATE_VALIDATION;
CREATE TRIGGER TRG_PERSONAL_UPDATE_VALIDATION
BEFORE UPDATE ON EXPENSE_PERSONAL
FOR EACH ROW
BEGIN
	CALL SP_TRG_PERSONAL_VALIDATION(NEW.ECN_ID,NEW.EP_INVOICE_DATE,'UPDATE');
END;