DROP TRIGGER IF EXISTS TRG_PERSONAL_CAR_UPDATE_VALIDATION;
CREATE TRIGGER TRG_PERSONAL_CAR_UPDATE_VALIDATION
BEFORE UPDATE ON EXPENSE_CAR
FOR EACH ROW
BEGIN
	CALL SP_TRG_PERSONAL_CAR_VALIDATION(NEW.ECN_ID,NEW.EC_INVOICE_DATE,'UPDATE');
END;