DROP TRIGGER IF EXISTS TRG_PERSONAL_CAR_UPDATE;
CREATE TRIGGER TRG_PERSONAL_CAR_UPDATE  
AFTER UPDATE ON EXPENSE_CAR
FOR EACH ROW
BEGIN 
DECLARE OLD_VALUE TEXT DEFAULT '';
DECLARE NEW_VALUE TEXT DEFAULT '';
IF ((OLD.ECN_ID!= NEW.ECN_ID) OR (OLD.EC_INVOICE_DATE!= NEW.EC_INVOICE_DATE) OR (OLD.EC_AMOUNT!= NEW.EC_AMOUNT) OR (OLD.EC_INVOICE_ITEMS!= NEW.EC_INVOICE_ITEMS) OR (OLD.EC_INVOICE_FROM!= NEW.EC_INVOICE_FROM) OR (OLD.EC_COMMENTS IS NULL AND NEW.EC_COMMENTS IS NOT NULL) OR (OLD.EC_COMMENTS IS NOT NULL AND NEW.EC_COMMENTS IS NULL) OR (OLD.EC_COMMENTS!= NEW.EC_COMMENTS)) THEN  
  SET OLD_VALUE = CONCAT(OLD_VALUE,'EC_ID=', OLD.EC_ID,','); 
END IF;
IF (OLD.ECN_ID!= NEW.ECN_ID) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'ECN_ID=', OLD.ECN_ID,','); 
END IF;
IF (OLD.ECN_ID!= NEW.ECN_ID) THEN SET 
NEW_VALUE = CONCAT(NEW_VALUE,'ECN_ID=', NEW.ECN_ID,','); 
END IF;
IF (OLD.EC_INVOICE_DATE!= NEW.EC_INVOICE_DATE) THEN SET 
OLD_VALUE= CONCAT(OLD_VALUE,'EC_INVOICE_DATE=', OLD.EC_INVOICE_DATE,','); 
END IF;
IF (OLD.EC_INVOICE_DATE!= NEW.EC_INVOICE_DATE) THEN SET 
NEW_VALUE = CONCAT(NEW_VALUE,'EC_INVOICE_DATE=', NEW.EC_INVOICE_DATE,','); 
END IF;
IF (OLD.EC_AMOUNT!= NEW.EC_AMOUNT) THEN SET 
OLD_VALUE= CONCAT(OLD_VALUE,'EC_AMOUNT=', OLD.EC_AMOUNT,','); 
END IF;
IF (OLD.EC_AMOUNT!= NEW.EC_AMOUNT) THEN SET 
NEW_VALUE = CONCAT(NEW_VALUE,'EC_AMOUNT=', NEW.EC_AMOUNT,','); 
END IF;
IF (OLD.EC_INVOICE_ITEMS!= NEW.EC_INVOICE_ITEMS) THEN SET 
OLD_VALUE= CONCAT(OLD_VALUE,'EC_INVOICE_ITEMS=', OLD.EC_INVOICE_ITEMS,','); 
END IF;
IF (OLD.EC_INVOICE_ITEMS!= NEW.EC_INVOICE_ITEMS) THEN SET 
NEW_VALUE = CONCAT(NEW_VALUE,'EC_INVOICE_ITEMS=', NEW.EC_INVOICE_ITEMS,','); 
END IF;
IF (OLD.EC_INVOICE_FROM!= NEW.EC_INVOICE_FROM) THEN SET 
OLD_VALUE= CONCAT(OLD_VALUE,'EC_INVOICE_FROM=', OLD.EC_INVOICE_FROM,','); 
END IF;
IF (OLD.EC_INVOICE_FROM!= NEW.EC_INVOICE_FROM) THEN SET 
NEW_VALUE = CONCAT(NEW_VALUE,'EC_INVOICE_FROM=', NEW.EC_INVOICE_FROM,','); 
END IF;
IF (OLD.EC_COMMENTS IS NULL AND NEW.EC_COMMENTS IS NOT NULL) THEN
SET OLD_VALUE=CONCAT(OLD_VALUE,'EC_COMMENTS=','<NULL>,');
SET NEW_VALUE=CONCAT(NEW_VALUE,'EC_COMMENTS=',NEW.EC_COMMENTS,',');
ELSEIF(OLD.EC_COMMENTS IS NOT NULL AND NEW.EC_COMMENTS IS NULL) THEN
SET OLD_VALUE=CONCAT(OLD_VALUE,'EC_COMMENTS=',OLD.EC_COMMENTS,',');
SET NEW_VALUE=CONCAT(NEW_VALUE,'EC_COMMENTS=','<NULL>,');
ELSEIF (OLD.EC_COMMENTS!= NEW.EC_COMMENTS) THEN 
SET OLD_VALUE= CONCAT(OLD_VALUE,'EC_COMMENTS=', OLD.EC_COMMENTS,','); 
SET NEW_VALUE = CONCAT(NEW_VALUE,'EC_COMMENTS=', NEW.EC_COMMENTS,','); 
END IF;
IF ((OLD.ECN_ID!= NEW.ECN_ID) OR (OLD.EC_INVOICE_DATE!= NEW.EC_INVOICE_DATE) OR (OLD.EC_AMOUNT!= NEW.EC_AMOUNT) OR (OLD.EC_INVOICE_ITEMS!= NEW.EC_INVOICE_ITEMS) OR (OLD.EC_INVOICE_FROM!= NEW.EC_INVOICE_FROM) OR (OLD.EC_COMMENTS IS NULL AND NEW.EC_COMMENTS IS NOT NULL) OR (OLD.EC_COMMENTS IS NOT NULL AND NEW.EC_COMMENTS IS NULL) OR (OLD.EC_COMMENTS!= NEW.EC_COMMENTS)) THEN  
IF (OLD.ULD_ID!= NEW.ULD_ID) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'ULD_ID=', OLD.ULD_ID,','); 
END IF;
IF (OLD.EC_TIMESTAMP!= NEW.EC_TIMESTAMP) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'EC_TIMESTAMP=', OLD.EC_TIMESTAMP,','); 
END IF;
END IF;
IF (OLD_VALUE!='' AND NEW_VALUE!='') THEN
IF(OLD_VALUE!=NEW_VALUE)THEN
SET OLD_VALUE = SUBSTRING(OLD_VALUE,1,CHAR_LENGTH(OLD_VALUE)-1);
SET NEW_VALUE = SUBSTRING(NEW_VALUE,1,CHAR_LENGTH(NEW_VALUE)-1);
INSERT INTO TICKLER_HISTORY
(ULD_ID,TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE)VALUES
((SELECT ULD_ID FROM EXPENSE_CAR WHERE EC_ID=NEW.EC_ID),
(SELECT TP_ID FROM TICKLER_PROFILE WHERE TP_TYPE='UPDATION'),
(SELECT TTIP_ID FROM TICKLER_TABID_PROFILE WHERE TTIP_DATA='EXPENSE_CAR'),OLD_VALUE,NEW_VALUE);
END IF;
END IF;
END;