DROP TRIGGER IF EXISTS TRG_BIZDLY_DIGITAL_VOICE_UPDATE_VALIDATION;
CREATE TRIGGER TRG_BIZDLY_DIGITAL_VOICE_UPDATE_VALIDATION
BEFORE UPDATE ON EXPENSE_DIGITAL_VOICE
FOR EACH ROW
BEGIN
    CALL SP_TRG_BIZDLY_EXPENSE_DIGITAL_VOICE_VALIDATION(NEW.EDV_INVOICE_DATE,NEW.EDV_FROM_PERIOD,NEW.EDV_TO_PERIOD,NEW.EDDV_ID,'UPDATE');
END;