DROP TRIGGER IF EXISTS TRG_BIZDLY_DIGITAL_VOICE_UPDATE;
CREATE TRIGGER TRG_BIZDLY_DIGITAL_VOICE_UPDATE  
AFTER UPDATE ON EXPENSE_DIGITAL_VOICE
FOR EACH ROW
BEGIN 
DECLARE OLD_VALUE TEXT DEFAULT '';
DECLARE NEW_VALUE TEXT DEFAULT '';
IF (OLD.EDDV_ID!= NEW.EDDV_ID) OR (OLD.EDV_INVOICE_DATE!= NEW.EDV_INVOICE_DATE) OR (OLD.EDV_FROM_PERIOD != NEW.EDV_FROM_PERIOD ) OR  (OLD.EDV_TO_PERIOD != NEW.EDV_TO_PERIOD ) OR (OLD.EDV_AMOUNT!= NEW.EDV_AMOUNT) OR (OLD.EDV_COMMENTS IS NULL AND NEW.EDV_COMMENTS IS NOT NULL) OR (OLD.EDV_COMMENTS IS NOT NULL AND NEW.EDV_COMMENTS IS NULL) OR (OLD.EDV_COMMENTS != NEW.EDV_COMMENTS) THEN  
  SET OLD_VALUE = CONCAT(OLD_VALUE,'EDV_ID=', OLD.EDV_ID,','); 
END IF;
IF (OLD.EDDV_ID!= NEW.EDDV_ID) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'EDDV_ID=', OLD.EDDV_ID,','); 
END IF;
IF (OLD.EDDV_ID!= NEW.EDDV_ID) THEN SET 
NEW_VALUE = CONCAT(NEW_VALUE,'EDDV_ID=', NEW.EDDV_ID,','); 
END IF;
IF (OLD.EDV_INVOICE_DATE!= NEW.EDV_INVOICE_DATE) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'EDV_INVOICE_DATE=', OLD.EDV_INVOICE_DATE,','); 
END IF;
IF (OLD.EDV_INVOICE_DATE!= NEW.EDV_INVOICE_DATE) THEN SET 
NEW_VALUE = CONCAT(NEW_VALUE,'EDV_INVOICE_DATE=', NEW.EDV_INVOICE_DATE,','); 
END IF;
IF (OLD.EDV_FROM_PERIOD!= NEW.EDV_FROM_PERIOD) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'EDV_FROM_PERIOD=', OLD.EDV_FROM_PERIOD,','); 
END IF;
IF (OLD.EDV_FROM_PERIOD!= NEW.EDV_FROM_PERIOD) THEN SET 
NEW_VALUE = CONCAT(NEW_VALUE,'EDV_FROM_PERIOD=', NEW.EDV_FROM_PERIOD,','); 
END IF;
IF (OLD.EDV_TO_PERIOD!= NEW.EDV_TO_PERIOD) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'EDV_TO_PERIOD=', OLD.EDV_TO_PERIOD,','); 
END IF;
IF (OLD.EDV_TO_PERIOD!= NEW.EDV_TO_PERIOD) THEN SET 
NEW_VALUE = CONCAT(NEW_VALUE,'EDV_TO_PERIOD=', NEW.EDV_TO_PERIOD,','); 
END IF;
IF (OLD.EDV_AMOUNT!= NEW.EDV_AMOUNT) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'EDV_AMOUNT=', OLD.EDV_AMOUNT,','); 
END IF;
IF (OLD.EDV_AMOUNT!= NEW.EDV_AMOUNT) THEN SET 
NEW_VALUE = CONCAT(NEW_VALUE,'EDV_AMOUNT=', NEW.EDV_AMOUNT,','); 
END IF;
IF (OLD.EDV_COMMENTS IS NULL AND NEW.EDV_COMMENTS IS NOT NULL) THEN
SET OLD_VALUE=CONCAT(OLD_VALUE,'EDV_COMMENTS=','<NULL>,');
SET NEW_VALUE=CONCAT(NEW_VALUE,'EDV_COMMENTS=',NEW.EDV_COMMENTS,',');
ELSEIF(OLD.EDV_COMMENTS IS NOT NULL AND NEW.EDV_COMMENTS IS NULL) THEN
SET OLD_VALUE=CONCAT(OLD_VALUE,'EDV_COMMENTS=',OLD.EDV_COMMENTS,',');
SET NEW_VALUE=CONCAT(NEW_VALUE,'EDV_COMMENTS=','<NULL>,');
ELSEIF (OLD.EDV_COMMENTS!= NEW.EDV_COMMENTS) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'EDV_COMMENTS=', OLD.EDV_COMMENTS,','); 
SET NEW_VALUE = CONCAT(NEW_VALUE,'EDV_COMMENTS=', NEW.EDV_COMMENTS,','); 
END IF;
IF (OLD.EDDV_ID!= NEW.EDDV_ID) OR (OLD.EDV_INVOICE_DATE!= NEW.EDV_INVOICE_DATE) OR (OLD.EDV_FROM_PERIOD != NEW.EDV_FROM_PERIOD ) OR  (OLD.EDV_TO_PERIOD != NEW.EDV_TO_PERIOD ) OR (OLD.EDV_AMOUNT!= NEW.EDV_AMOUNT) OR (OLD.EDV_COMMENTS IS NULL AND NEW.EDV_COMMENTS IS NOT NULL) OR (OLD.EDV_COMMENTS IS NOT NULL AND NEW.EDV_COMMENTS IS NULL) OR (OLD.EDV_COMMENTS != NEW.EDV_COMMENTS) THEN  
IF (OLD.ULD_ID!= NEW.ULD_ID) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'ULD_ID=', OLD.ULD_ID,','); 
END IF;
IF (OLD.EDV_TIMESTAMP!= NEW.EDV_TIMESTAMP) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'EDV_TIMESTAMP=', OLD.EDV_TIMESTAMP,','); 
END IF;
END IF;
IF (OLD_VALUE!='' AND NEW_VALUE!='') THEN
IF(OLD_VALUE!=NEW_VALUE)THEN
SET OLD_VALUE = SUBSTRING(OLD_VALUE,1,CHAR_LENGTH(OLD_VALUE)-1);
SET NEW_VALUE = SUBSTRING(NEW_VALUE,1,CHAR_LENGTH(NEW_VALUE)-1);
INSERT INTO TICKLER_HISTORY
(ULD_ID,TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE)VALUES
((SELECT ULD_ID FROM EXPENSE_DIGITAL_VOICE WHERE EDV_ID=NEW.EDV_ID),
(SELECT TP_ID FROM TICKLER_PROFILE WHERE TP_TYPE='UPDATION'),
(SELECT TTIP_ID FROM TICKLER_TABID_PROFILE WHERE TTIP_DATA='EXPENSE_DIGITAL_VOICE'),OLD_VALUE,NEW_VALUE);
END IF;
END IF;
END;