DROP TRIGGER IF EXISTS TRG_STAFFDLY_STAFF_UPDATE;
CREATE TRIGGER TRG_STAFFDLY_STAFF_UPDATE  
AFTER UPDATE ON EXPENSE_STAFF
FOR EACH ROW
BEGIN 
DECLARE OLD_VALUE TEXT DEFAULT '';
DECLARE NEW_VALUE TEXT DEFAULT '';
IF ((OLD.ES_INVOICE_DATE!= NEW.ES_INVOICE_DATE) OR (OLD.ECN_ID!= NEW.ECN_ID) OR (OLD.ES_INVOICE_AMOUNT!= NEW.ES_INVOICE_AMOUNT) OR (OLD.ES_INVOICE_ITEMS!= NEW.ES_INVOICE_ITEMS) OR 
(OLD.ES_COMMENTS IS NULL AND NEW.ES_COMMENTS IS NOT NULL) OR (OLD.ES_COMMENTS IS NOT NULL AND NEW.ES_COMMENTS IS NULL) OR (OLD.ES_COMMENTS!= NEW.ES_COMMENTS) OR (OLD.ES_INVOICE_FROM!= NEW.ES_INVOICE_FROM)) THEN  
  SET OLD_VALUE = CONCAT(OLD_VALUE,'ES_ID=', OLD.ES_ID,','); 
END IF;
IF (OLD.ES_INVOICE_DATE!= NEW.ES_INVOICE_DATE) THEN  
  SET OLD_VALUE = CONCAT(OLD_VALUE,'ES_INVOICE_DATE=', OLD.ES_INVOICE_DATE,','); 
  SET NEW_VALUE = CONCAT(NEW_VALUE,'ES_INVOICE_DATE=', NEW.ES_INVOICE_DATE,','); 
END IF;
IF (OLD.ECN_ID!= NEW.ECN_ID) THEN  
  SET OLD_VALUE = CONCAT(OLD_VALUE,'ECN_ID=', OLD.ECN_ID,','); 
  SET NEW_VALUE = CONCAT(NEW_VALUE,'ECN_ID=', NEW.ECN_ID,','); 
END IF;
IF (OLD.ES_INVOICE_AMOUNT!= NEW.ES_INVOICE_AMOUNT) THEN  
  SET OLD_VALUE = CONCAT(OLD_VALUE,'ES_INVOICE_AMOUNT=', OLD.ES_INVOICE_AMOUNT,',');
  SET NEW_VALUE = CONCAT(NEW_VALUE,'ES_INVOICE_AMOUNT=', NEW.ES_INVOICE_AMOUNT,','); 
END IF;
IF (OLD.ES_INVOICE_ITEMS!= NEW.ES_INVOICE_ITEMS) THEN  
  SET OLD_VALUE = CONCAT(OLD_VALUE,'ES_INVOICE_ITEMS=', OLD.ES_INVOICE_ITEMS,',');
  SET NEW_VALUE = CONCAT(NEW_VALUE,'ES_INVOICE_ITEMS=', NEW.ES_INVOICE_ITEMS,','); 
END IF;
IF (OLD.ES_COMMENTS IS NULL AND NEW.ES_COMMENTS IS NOT NULL) THEN
SET OLD_VALUE=CONCAT(OLD_VALUE,'ES_COMMENTS=','<NULL>,');
SET NEW_VALUE=CONCAT(NEW_VALUE,'ES_COMMENTS=',NEW.ES_COMMENTS,',');
ELSEIF(OLD.ES_COMMENTS IS NOT NULL AND NEW.ES_COMMENTS IS NULL) THEN
SET OLD_VALUE=CONCAT(OLD_VALUE,'ES_COMMENTS=',OLD.ES_COMMENTS,',');
SET NEW_VALUE=CONCAT(NEW_VALUE,'ES_COMMENTS=','<NULL>,');
ELSEIF (OLD.ES_COMMENTS!= NEW.ES_COMMENTS) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'ES_COMMENTS=', OLD.ES_COMMENTS,','); 
SET NEW_VALUE = CONCAT(NEW_VALUE,'ES_COMMENTS=', NEW.ES_COMMENTS,','); 
END IF;
IF (OLD.ES_INVOICE_FROM!= NEW.ES_INVOICE_FROM) THEN  
  SET OLD_VALUE = CONCAT(OLD_VALUE,'ES_INVOICE_FROM=', OLD.ES_INVOICE_FROM,','); 
  SET NEW_VALUE = CONCAT(NEW_VALUE,'ES_INVOICE_FROM=', NEW.ES_INVOICE_FROM,','); 
END IF;
IF ((OLD.ES_INVOICE_DATE!= NEW.ES_INVOICE_DATE) OR (OLD.ECN_ID!= NEW.ECN_ID) OR (OLD.ES_INVOICE_AMOUNT!= NEW.ES_INVOICE_AMOUNT) OR (OLD.ES_INVOICE_ITEMS!= NEW.ES_INVOICE_ITEMS) OR 
(OLD.ES_COMMENTS IS NULL AND NEW.ES_COMMENTS IS NOT NULL) OR (OLD.ES_COMMENTS IS NOT NULL AND NEW.ES_COMMENTS IS NULL) OR (OLD.ES_COMMENTS!= NEW.ES_COMMENTS) OR (OLD.ES_INVOICE_FROM!= NEW.ES_INVOICE_FROM)) THEN  
 IF (OLD.ULD_ID!= NEW.ULD_ID) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'ULD_ID=', OLD.ULD_ID,','); 
END IF;
IF (OLD.ES_TIMESTAMP!= NEW.ES_TIMESTAMP) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'ES_TIMESTAMP=', OLD.ES_TIMESTAMP,','); 
END IF;
END IF;
IF (OLD_VALUE!='' AND NEW_VALUE!='') THEN
IF(OLD_VALUE != NEW_VALUE)THEN
     SET OLD_VALUE = SUBSTRING(OLD_VALUE,1,CHAR_LENGTH(OLD_VALUE)-1);
    SET NEW_VALUE = SUBSTRING(NEW_VALUE,1,CHAR_LENGTH(NEW_VALUE)-1);
INSERT INTO TICKLER_HISTORY
(ULD_ID,TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE)VALUES
((SELECT ULD_ID FROM EXPENSE_STAFF WHERE ES_ID=NEW.ES_ID),
(SELECT TP_ID FROM TICKLER_PROFILE WHERE TP_TYPE='UPDATION'),
(SELECT TTIP_ID FROM TICKLER_TABID_PROFILE WHERE TTIP_DATA='EXPENSE_STAFF'),OLD_VALUE,NEW_VALUE);
END IF;
END IF;
END;