DROP TRIGGER IF EXISTS TRG_BIZDLY_CARPARK_UPDATE;
CREATE TRIGGER TRG_BIZDLY_CARPARK_UPDATE 
AFTER UPDATE ON EXPENSE_CARPARK
FOR EACH ROW
BEGIN 
DECLARE OLD_VALUE TEXT DEFAULT '';
DECLARE NEW_VALUE TEXT DEFAULT '';
IF (OLD.EDCP_ID!= NEW.EDCP_ID) OR (OLD.ECP_INVOICE_DATE!= NEW.ECP_INVOICE_DATE) OR (OLD.ECP_FROM_PERIOD != NEW.ECP_FROM_PERIOD ) OR  (OLD.ECP_TO_PERIOD != NEW.ECP_TO_PERIOD ) OR (OLD.ECP_AMOUNT!= NEW.ECP_AMOUNT) OR (OLD.ECP_COMMENTS IS NULL AND NEW.ECP_COMMENTS IS NOT NULL) OR (OLD.ECP_COMMENTS IS NOT NULL AND NEW.ECP_COMMENTS IS NULL) OR (OLD.ECP_COMMENTS != NEW.ECP_COMMENTS) THEN  
  SET OLD_VALUE = CONCAT(OLD_VALUE,'ECP_PARK_ID=', OLD.ECP_PARK_ID,','); 
END IF;
IF (OLD.EDCP_ID!= NEW.EDCP_ID) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'EDCP_ID=', OLD.EDCP_ID,','); 
END IF;
IF (OLD.EDCP_ID!= NEW.EDCP_ID) THEN SET 
NEW_VALUE = CONCAT(NEW_VALUE,'EDCP_ID=', NEW.EDCP_ID,','); 
END IF;
IF (OLD.ECP_INVOICE_DATE!= NEW.ECP_INVOICE_DATE) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'ECP_INVOICE_DATE=', OLD.ECP_INVOICE_DATE,','); 
END IF;
IF (OLD.ECP_INVOICE_DATE!= NEW.ECP_INVOICE_DATE) THEN SET 
NEW_VALUE = CONCAT(NEW_VALUE,'ECP_INVOICE_DATE=', NEW.ECP_INVOICE_DATE,','); 
END IF;
IF (OLD.ECP_FROM_PERIOD!= NEW.ECP_FROM_PERIOD) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'ECP_FROM_PERIOD=', OLD.ECP_FROM_PERIOD,','); 
END IF;
IF (OLD.ECP_FROM_PERIOD!= NEW.ECP_FROM_PERIOD) THEN SET 
NEW_VALUE = CONCAT(NEW_VALUE,'ECP_FROM_PERIOD=', NEW.ECP_FROM_PERIOD,','); 
END IF;
IF (OLD.ECP_TO_PERIOD!= NEW.ECP_TO_PERIOD) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'ECP_TO_PERIOD=', OLD.ECP_TO_PERIOD,','); 
END IF;
IF (OLD.ECP_TO_PERIOD!= NEW.ECP_TO_PERIOD) THEN SET 
NEW_VALUE = CONCAT(NEW_VALUE,'ECP_TO_PERIOD=', NEW.ECP_TO_PERIOD,','); 
END IF;
IF (OLD.ECP_AMOUNT!= NEW.ECP_AMOUNT) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'ECP_AMOUNT=', OLD.ECP_AMOUNT,','); 
END IF;
IF (OLD.ECP_AMOUNT!= NEW.ECP_AMOUNT) THEN SET 
NEW_VALUE = CONCAT(NEW_VALUE,'ECP_AMOUNT=', NEW.ECP_AMOUNT,','); 
END IF;
IF (OLD.ECP_COMMENTS IS NULL AND NEW.ECP_COMMENTS IS NOT NULL) THEN
SET OLD_VALUE=CONCAT(OLD_VALUE,'ECP_COMMENTS=','<NULL>,');
SET NEW_VALUE=CONCAT(NEW_VALUE,'ECP_COMMENTS=',NEW.ECP_COMMENTS,',');
ELSEIF(OLD.ECP_COMMENTS IS NOT NULL AND NEW.ECP_COMMENTS IS NULL) THEN
SET OLD_VALUE=CONCAT(OLD_VALUE,'ECP_COMMENTS=',OLD.ECP_COMMENTS,',');
SET NEW_VALUE=CONCAT(NEW_VALUE,'ECP_COMMENTS=','<NULL>,');
ELSEIF (OLD.ECP_COMMENTS!= NEW.ECP_COMMENTS) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'ECP_COMMENTS=', OLD.ECP_COMMENTS,','); 
SET NEW_VALUE = CONCAT(NEW_VALUE,'ECP_COMMENTS=', NEW.ECP_COMMENTS,','); 
END IF;
IF (OLD.EDCP_ID!= NEW.EDCP_ID) OR (OLD.ECP_INVOICE_DATE!= NEW.ECP_INVOICE_DATE) OR (OLD.ECP_FROM_PERIOD != NEW.ECP_FROM_PERIOD ) OR  (OLD.ECP_TO_PERIOD != NEW.ECP_TO_PERIOD ) OR (OLD.ECP_AMOUNT!= NEW.ECP_AMOUNT) OR (OLD.ECP_COMMENTS IS NULL AND NEW.ECP_COMMENTS IS NOT NULL) OR (OLD.ECP_COMMENTS IS NOT NULL AND NEW.ECP_COMMENTS IS NULL) OR (OLD.ECP_COMMENTS != NEW.ECP_COMMENTS) THEN  
IF (OLD.ULD_ID!= NEW.ULD_ID) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'ULD_ID=', OLD.ULD_ID,','); 
END IF;
IF (OLD.ECP_TIMESTAMP!= NEW.ECP_TIMESTAMP) THEN SET 
OLD_VALUE = CONCAT(OLD_VALUE,'ECP_TIMESTAMP=', OLD.ECP_TIMESTAMP,','); 
END IF;
END IF;
IF (OLD_VALUE!='' AND NEW_VALUE!='') THEN
IF(OLD_VALUE != NEW_VALUE)THEN
SET OLD_VALUE = SUBSTRING(OLD_VALUE,1,CHAR_LENGTH(OLD_VALUE)-1);
SET NEW_VALUE = SUBSTRING(NEW_VALUE,1,CHAR_LENGTH(NEW_VALUE)-1);
INSERT INTO TICKLER_HISTORY
(ULD_ID,TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE)VALUES
((SELECT ULD_ID FROM EXPENSE_CARPARK WHERE ECP_PARK_ID=NEW.ECP_PARK_ID),
(SELECT TP_ID FROM TICKLER_PROFILE WHERE TP_TYPE='UPDATION'),
(SELECT TTIP_ID FROM TICKLER_TABID_PROFILE WHERE TTIP_DATA='EXPENSE_CARPARK'),OLD_VALUE,NEW_VALUE);
END IF;
END IF;
END;