DROP PROCEDURE IF EXISTS EXPENSE_AIRCON_SERVICE_BY_INSERT;
CREATE PROCEDURE EXPENSE_AIRCON_SERVICE_BY_INSERT(IN SOURCESCHEMA  VARCHAR(40),IN DESTINATIONSCHEMA  VARCHAR(40),IN MIGUSERSTAMP VARCHAR(50))
BEGIN
	DECLARE START_TIME TIME;
	DECLARE END_TIME TIME;
	DECLARE DURATION TIME;
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
	ROLLBACK;
	END;
	START TRANSACTION;
	SET START_TIME=(SELECT CURTIME());
	SET FOREIGN_KEY_CHECKS=0;
	SET @LOGIN_ID=(SELECT CONCAT('SELECT ULD_ID INTO @ULDID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=','"',MIGUSERSTAMP,'"'));
    PREPARE LOGINID FROM @LOGIN_ID;
    EXECUTE LOGINID;
	SET @DROP_EXPENSE_AIRCON_SERVICE_BY=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.EXPENSE_AIRCON_SERVICE_BY'));
    PREPARE DROP_EXPENSE_AIRCON_SERVICE_BY_STMT FROM @DROP_EXPENSE_AIRCON_SERVICE_BY;
    EXECUTE DROP_EXPENSE_AIRCON_SERVICE_BY_STMT;
	SET @CREATE_EXPENSE_AIRCON_SERVICE_BY=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.EXPENSE_AIRCON_SERVICE_BY(
	EASB_ID	INTEGER NOT NULL AUTO_INCREMENT,
	EASB_DATA CHAR(50) UNIQUE NOT NULL,	
	ULD_ID INTEGER NOT NULL,
	EASB_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(EASB_ID),
	FOREIGN KEY(ULD_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS (ULD_ID))'));
	PREPARE CREATE_EXPENSE_AIRCON_SERVICE_BY_STMT FROM @CREATE_EXPENSE_AIRCON_SERVICE_BY;
    EXECUTE CREATE_EXPENSE_AIRCON_SERVICE_BY_STMT;	
	SET @INSERT_EXPENSE_AIRCON_SERVICE_BY=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.EXPENSE_AIRCON_SERVICE_BY(EASB_DATA,ULD_ID,EASB_TIMESTAMP) 
	SELECT DISTINCT BIZDTL.EXPD_AIRCON_SERVICED_BY,ULD.ULD_ID,BIZDTL.TIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_BIZ_DETAIL_SCDB_FORMAT BIZDTL, ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS ULD  WHERE BIZDTL.EXPD_AIRCON_SERVICED_BY IS NOT NULL AND BIZDTL.USERSTAMP=ULD.ULD_LOGINID GROUP BY BIZDTL.EXPD_AIRCON_SERVICED_BY'));
	PREPARE INSERT_EXPENSE_AIRCON_SERVICE_BY_STMT FROM @INSERT_EXPENSE_AIRCON_SERVICE_BY;
    EXECUTE INSERT_EXPENSE_AIRCON_SERVICE_BY_STMT;
	SET FOREIGN_KEY_CHECKS=1;
	SET END_TIME=(SELECT CURTIME());
	SET DURATION=(SELECT TIMEDIFF(END_TIME,START_TIME));
	SET @COUNTSCDB_EASB=(SELECT CONCAT('SELECT COUNT(DISTINCT(EXPD_AIRCON_SERVICED_BY)) INTO @COUNT_SCDB_EASB FROM ',DESTINATIONSCHEMA,'.TEMP_BIZ_DETAIL_SCDB_FORMAT WHERE EXPD_AIRCON_SERVICED_BY IS NOT NULL'));
	PREPARE COUNTSCDB_EASB_STMT FROM @COUNTSCDB_EASB;
    EXECUTE COUNTSCDB_EASB_STMT;
	SET @COUNTSPLITTED_EASB=(SELECT CONCAT('SELECT COUNT(*) INTO @COUNT_SPLITTED_EASB FROM ',DESTINATIONSCHEMA,'.EXPENSE_AIRCON_SERVICE_BY'));
	PREPARE COUNTSPLITTED_EASB_STMT FROM @COUNTSPLITTED_EASB;
    EXECUTE COUNTSPLITTED_EASB_STMT;
	SET @REJECTION_COUNT=(@COUNT_SCDB_EASB-@COUNT_SPLITTED_EASB);
    SET FOREIGN_KEY_CHECKS=0;
    UPDATE PRE_AUDIT_SUB_PROFILE SET PREASP_NO_OF_REC = @COUNT_SCDB_EASB WHERE PREASP_DATA='EXPENSE_AIRCON_SERVICE_BY';	
     INSERT INTO POST_AUDIT_HISTORY(POSTAP_ID,POSTAH_NO_OF_REC,PREASP_ID,PREAMP_ID,POSTAH_DURATION,POSTAH_NO_OF_REJ,ULD_ID)VALUES((SELECT POSTAP_ID FROM POST_AUDIT_PROFILE WHERE POSTAP_DATA='EXPENSE_AIRCON_SERVICE_BY'),@COUNT_SPLITTED_EASB,
	(SELECT PREASP_ID FROM PRE_AUDIT_SUB_PROFILE WHERE PREASP_DATA='EXPENSE_AIRCON_SERVICE_BY'),
	(SELECT PREAMP_ID FROM PRE_AUDIT_MAIN_PROFILE WHERE PREAMP_DATA='BIZ DETAIL'),DURATION,@REJECTION_COUNT,@ULDID);
	SET FOREIGN_KEY_CHECKS=1;
	COMMIT;
	END;
    