DROP PROCEDURE IF EXISTS SP_EXPENSE_DETAIL_AIRCON_SERVICE_INSERT;
CREATE PROCEDURE SP_EXPENSE_DETAIL_AIRCON_SERVICE_INSERT(IN SOURCESCHEMA  VARCHAR(40),IN DESTINATIONSCHEMA  VARCHAR(40),IN MIGUSERSTAMP VARCHAR(50))
BEGIN
    DECLARE DONE INT DEFAULT FALSE;
	DECLARE UNITNO INTEGER;
	DECLARE AIRCON_UNITID INTEGER;
	DECLARE AIRCONSERVICEBY CHAR(50);
	DECLARE RECVER INTEGER;
	DECLARE COMMENTS TEXT;
	DECLARE AIRCON_USERSTAMP VARCHAR(50);
	DECLARE AIRCON_TIMESTAMP TIMESTAMP;
	DECLARE START_TIME TIME;
	DECLARE END_TIME TIME;
	DECLARE DURATION TIME;
	DECLARE AIRCON_MINID INTEGER;
	DECLARE AIRCON_MAXID INTEGER;
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
	ROLLBACK;
	END;
	START TRANSACTION;
	SET FOREIGN_KEY_CHECKS=0;
	SET @LOGIN_ID=(SELECT CONCAT('SELECT ULD_ID INTO @ULDID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=','"',MIGUSERSTAMP,'"'));
    PREPARE LOGINID FROM @LOGIN_ID;
    EXECUTE LOGINID;
	SET @DROP_EXPENSE_DETAIL_AIRCON_SERVICE=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.EXPENSE_DETAIL_AIRCON_SERVICE'));
    PREPARE DROP_EXPENSE_DETAIL_AIRCON_SERVICE_STMT FROM @DROP_EXPENSE_DETAIL_AIRCON_SERVICE;
    EXECUTE DROP_EXPENSE_DETAIL_AIRCON_SERVICE_STMT;
	SET @CREATE_EXPENSE_DETAIL_AIRCON_SERVICE=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.EXPENSE_DETAIL_AIRCON_SERVICE(
	EDAS_ID	INTEGER NOT NULL AUTO_INCREMENT,
	UNIT_ID	INTEGER NOT NULL,
	EASB_ID	INTEGER NOT NULL,
	EDAS_REC_VER INTEGER NOT NULL,	
	EDAS_COMMENTS TEXT NULL	,
	ULD_ID INTEGER NOT NULL,	
	EDAS_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(EDAS_ID),
	FOREIGN KEY(UNIT_ID) REFERENCES ',DESTINATIONSCHEMA,'.UNIT (UNIT_ID),
	FOREIGN KEY(EASB_ID) REFERENCES ',DESTINATIONSCHEMA,'.EXPENSE_AIRCON_SERVICE_BY (EASB_ID),
	FOREIGN KEY(ULD_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS (ULD_ID))'));
	PREPARE CREATE_EXPENSE_DETAIL_AIRCON_SERVICE_STMT FROM @CREATE_EXPENSE_DETAIL_AIRCON_SERVICE;
    EXECUTE CREATE_EXPENSE_DETAIL_AIRCON_SERVICE_STMT;
	SET @DROP_TEMP_EXPENSE_DETAIL_AIRCON_SERVICE=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_AIRCON_SERVICE'));
    PREPARE DROP_TEMP_EXPENSE_DETAIL_AIRCON_SERVICE_STMT FROM @DROP_TEMP_EXPENSE_DETAIL_AIRCON_SERVICE;
    EXECUTE DROP_TEMP_EXPENSE_DETAIL_AIRCON_SERVICE_STMT;
	SET @CREATE_TEMP_EXPENSE_DETAIL_AIRCON_SERVICE=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_AIRCON_SERVICE(
	ID	INTEGER NOT NULL AUTO_INCREMENT,
	UNIT_NO	INTEGER NOT NULL,
	EASB_AIRCON_SERVICED_BY	TEXT NOT NULL,	
	EDAS_COMMENTS TEXT NULL	,
	EDAS_USERSTAMP VARCHAR(50) NOT NULL,	
	EDAS_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(ID))'));
	PREPARE CREATE_TEMP_EXPENSE_DETAIL_AIRCON_SERVICE_STMT FROM @CREATE_TEMP_EXPENSE_DETAIL_AIRCON_SERVICE;
    EXECUTE CREATE_TEMP_EXPENSE_DETAIL_AIRCON_SERVICE_STMT;	
	SET @SELECT_AIRCON_SERVICES=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_AIRCON_SERVICE(UNIT_NO,EASB_AIRCON_SERVICED_BY,EDAS_COMMENTS,EDAS_USERSTAMP,EDAS_TIMESTAMP) SELECT EXPD_UNIT_NO,EXPD_AIRCON_SERVICED_BY,EXPD_COMMENTS,USERSTAMP,TIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_BIZ_DETAIL_SCDB_FORMAT WHERE EXPD_TYPE_OF_EXPENSE=',"'AIRCON SERVICES'"));	
	PREPARE SELECT_AIRCON_SERVICES_STMT FROM @SELECT_AIRCON_SERVICES;
    EXECUTE SELECT_AIRCON_SERVICES_STMT;	
	SET START_TIME=(SELECT CURTIME());
    SET @EDAS_MINID=(SELECT CONCAT('SELECT MIN(ID) INTO @MIN_ID FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_AIRCON_SERVICE'));
	PREPARE EDAS_MINID_STMT FROM @EDAS_MINID;
    EXECUTE EDAS_MINID_STMT;
	SET @EDAS_MAXID=(SELECT CONCAT('SELECT MAX(ID) INTO @MAX_ID FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_AIRCON_SERVICE'));
	PREPARE EDAS_MAXID_STMT FROM @EDAS_MAXID;
    EXECUTE EDAS_MAXID_STMT;
    SET AIRCON_MINID=@MIN_ID;
    SET AIRCON_MAXID=@MAX_ID;
    WHILE(AIRCON_MINID<=AIRCON_MAXID)DO
	    SET @EDAS_COMMENTS=NULL;
	    SET @SELECT_COMMENT=(SELECT CONCAT('SELECT EDAS_COMMENTS INTO @EDAS_COMMENTS FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_AIRCON_SERVICE WHERE ID=',AIRCON_MINID));
	    PREPARE SELECT_COMMENT_STMT FROM @SELECT_COMMENT;
        EXECUTE SELECT_COMMENT_STMT;
		SET COMMENTS=@EDAS_COMMENTS;		
		IF COMMENTS IS NULL THEN
		SET @EDAS_COMMENT=NULL;		
		ELSE
		SET @EDAS_COMMENT=COMMENTS;
		END IF;
		SET @RECVER=1;
		SET @EDAS_UNITNO=UNITNO;
		SET @EDAS_UNITID=NULL;
		SET @SELECT_UNIT_ID=(SELECT CONCAT('SELECT DISTINCT UNIT_ID INTO @EDAS_UNITID FROM ',DESTINATIONSCHEMA,'.EXPENSE_DETAIL_AIRCON_SERVICE WHERE UNIT_ID=(SELECT UNIT_ID FROM ',DESTINATIONSCHEMA,'.UNIT WHERE UNIT_NO=(SELECT UNIT_NO FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_AIRCON_SERVICE WHERE ID=',AIRCON_MINID,'))'));
		PREPARE SELECT_UNIT_ID_STMT FROM @SELECT_UNIT_ID;		
        EXECUTE SELECT_UNIT_ID_STMT;
		SET AIRCON_UNITID=@EDAS_UNITID;		
		IF(AIRCON_UNITID IS NOT NULL)THEN	
            SET @REC_VER=NULL;		
			SET @SELECT_RECVER=(SELECT CONCAT('SELECT MAX(EDAS_REC_VER) INTO @REC_VER FROM ',DESTINATIONSCHEMA,'.EXPENSE_DETAIL_AIRCON_SERVICE WHERE UNIT_ID=(SELECT UNIT_ID FROM ',DESTINATIONSCHEMA,'.UNIT WHERE UNIT_NO=(SELECT UNIT_NO FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_AIRCON_SERVICE WHERE ID=',AIRCON_MINID,'))'));
			PREPARE SELECT_RECVER_STMT FROM @SELECT_RECVER;
            EXECUTE SELECT_RECVER_STMT;
			SET @RECVER=@REC_VER;
			SET @INSERT_EXPENSE_DETAIL_AIRCON_SERVICE=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.EXPENSE_DETAIL_AIRCON_SERVICE(UNIT_ID,EASB_ID,EDAS_REC_VER,EDAS_COMMENTS,ULD_ID,EDAS_TIMESTAMP)VALUES
			((SELECT UNIT_ID FROM ',DESTINATIONSCHEMA,'.UNIT WHERE UNIT_NO=(SELECT UNIT_NO FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_AIRCON_SERVICE WHERE ID=',AIRCON_MINID,')),(SELECT EASB_ID FROM ',DESTINATIONSCHEMA,'.EXPENSE_AIRCON_SERVICE_BY WHERE EASB_DATA=(SELECT EASB_AIRCON_SERVICED_BY FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_AIRCON_SERVICE WHERE ID=',AIRCON_MINID,')),
			(@RECVER+1),@EDAS_COMMENTS,(SELECT ULD_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=(SELECT EDAS_USERSTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_AIRCON_SERVICE WHERE ID=',AIRCON_MINID,')),(SELECT EDAS_TIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_AIRCON_SERVICE WHERE ID=',AIRCON_MINID,'))'));
			PREPARE INSERT_EXPENSE_DETAIL_AIRCON_SERVICE_STMT FROM @INSERT_EXPENSE_DETAIL_AIRCON_SERVICE;
            EXECUTE INSERT_EXPENSE_DETAIL_AIRCON_SERVICE_STMT;
		ELSE
			SET @INSERT_EXPENSE_DETAIL_AIRCON_SERVICE=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.EXPENSE_DETAIL_AIRCON_SERVICE(UNIT_ID,EASB_ID,EDAS_REC_VER,EDAS_COMMENTS,ULD_ID,EDAS_TIMESTAMP)VALUES
			((SELECT UNIT_ID FROM ',DESTINATIONSCHEMA,'.UNIT WHERE UNIT_NO=(SELECT UNIT_NO FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_AIRCON_SERVICE WHERE ID=',AIRCON_MINID,')),(SELECT EASB_ID FROM ',DESTINATIONSCHEMA,'.EXPENSE_AIRCON_SERVICE_BY WHERE EASB_DATA=(SELECT EASB_AIRCON_SERVICED_BY FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_AIRCON_SERVICE WHERE ID=',AIRCON_MINID,')),
			(@RECVER),@EDAS_COMMENTS,(SELECT ULD_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=(SELECT EDAS_USERSTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_AIRCON_SERVICE WHERE ID=',AIRCON_MINID,')),(SELECT EDAS_TIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_AIRCON_SERVICE WHERE ID=',AIRCON_MINID,'))'));
			PREPARE INSERT_EXPENSE_DETAIL_AIRCON_SERVICE_STMT FROM @INSERT_EXPENSE_DETAIL_AIRCON_SERVICE;
            EXECUTE INSERT_EXPENSE_DETAIL_AIRCON_SERVICE_STMT;
		END IF;
		SET AIRCON_MINID=AIRCON_MINID+1;
		END WHILE;		
		SET END_TIME=(SELECT CURTIME());
		SET DURATION=(SELECT TIMEDIFF(END_TIME,START_TIME));
		SET @COUNTSCDB_EDAS=(SELECT CONCAT('SELECT COUNT(*) INTO @COUNT_SCDB_EDAS FROM ',SOURCESCHEMA,'.BIZ_DETAIL_SCDB_FORMAT WHERE EXPD_TYPE_OF_EXPENSE=',"'AIRCON SERVICES'"));
		PREPARE COUNTSCDB_EDAS_STMT FROM @COUNTSCDB_EDAS;
        EXECUTE COUNTSCDB_EDAS_STMT;
		SET @COUNTSPLITTED_EDAS=(SELECT CONCAT('SELECT COUNT(*) INTO @COUNT_SPLITTED_EDAS FROM ',DESTINATIONSCHEMA,'.EXPENSE_DETAIL_AIRCON_SERVICE'));
		PREPARE COUNTSPLITTED_EDAS_STMT FROM @COUNTSPLITTED_EDAS;
        EXECUTE COUNTSPLITTED_EDAS_STMT;
		SET @REJECTION_COUNT=(@COUNT_SCDB_EDAS-@COUNT_SPLITTED_EDAS);
        SET FOREIGN_KEY_CHECKS=0;
         UPDATE PRE_AUDIT_SUB_PROFILE SET PREASP_NO_OF_REC = @COUNT_SCDB_EDAS WHERE PREASP_DATA='EXPENSE_DETAIL_AIRCON_SERVICE';
		INSERT INTO POST_AUDIT_HISTORY(POSTAP_ID,POSTAH_NO_OF_REC,PREASP_ID,PREAMP_ID,POSTAH_DURATION,POSTAH_NO_OF_REJ,ULD_ID)VALUES((SELECT POSTAP_ID FROM POST_AUDIT_PROFILE WHERE POSTAP_DATA='EXPENSE_DETAIL_AIRCON_SERVICE'),@COUNT_SPLITTED_EDAS,(SELECT PREASP_ID FROM PRE_AUDIT_SUB_PROFILE WHERE PREASP_DATA='EXPENSE_DETAIL_AIRCON_SERVICE'),(SELECT PREAMP_ID FROM PRE_AUDIT_MAIN_PROFILE WHERE PREAMP_DATA='BIZ DETAIL'),DURATION,@REJECTION_COUNT,@ULDID);
        SET FOREIGN_KEY_CHECKS=1;
	   SET @DROP_TEMP_EXPENSE_DETAIL_AIRCON_SERVICE=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_AIRCON_SERVICE'));
       PREPARE DROP_TEMP_EXPENSE_DETAIL_AIRCON_SERVICE_STMT FROM @DROP_TEMP_EXPENSE_DETAIL_AIRCON_SERVICE;
       EXECUTE DROP_TEMP_EXPENSE_DETAIL_AIRCON_SERVICE_STMT;
SET FOREIGN_KEY_CHECKS=1;
COMMIT;	   
END;
