DROP PROCEDURE IF EXISTS SP_EXPENSE_DETAIL_ELECTRICITY_INSERT;
CREATE PROCEDURE SP_EXPENSE_DETAIL_ELECTRICITY_INSERT(IN SOURCESCHEMA  VARCHAR(40),IN DESTINATIONSCHEMA  VARCHAR(40),IN MIGUSERSTAMP VARCHAR(50))
BEGIN
	DECLARE DONE INT DEFAULT FALSE;
	DECLARE UNITNO INTEGER;
	DECLARE ELC_UNIT_ID INTEGER;
	DECLARE INVOICETO TEXT;
	DECLARE RECVER INTEGER;
	DECLARE COMMENTS TEXT;
	DECLARE ELECTRICITY_USERSTAMP VARCHAR(50);
	DECLARE ELECTRICITY_TIMESTAMP TIMESTAMP;
	DECLARE START_TIME TIME;
	DECLARE END_TIME TIME;
	DECLARE DURATION TIME;
	DECLARE ELC_MINID  INTEGER;
	DECLARE ELC_MAXID INTEGER;
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
	ROLLBACK;
	END;
	START TRANSACTION;
	SET FOREIGN_KEY_CHECKS=0;
	SET @LOGIN_ID=(SELECT CONCAT('SELECT ULD_ID INTO @ULDID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=','"',MIGUSERSTAMP,'"'));
    PREPARE LOGINID FROM @LOGIN_ID;
    EXECUTE LOGINID;
	SET @DROP_TEMP_EXPENSE_DETAIL_ELECTRICITY=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_ELECTRICITY'));
	PREPARE DROP_TEMP_EXPENSE_DETAIL_ELECTRICITY_STMT FROM @DROP_TEMP_EXPENSE_DETAIL_ELECTRICITY;
    EXECUTE DROP_TEMP_EXPENSE_DETAIL_ELECTRICITY_STMT;
	SET @CREATE_TEMP_EXPENSE_DETAIL_ELECTRICITY=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_ELECTRICITY(		
	ID INTEGER NOT NULL	AUTO_INCREMENT,
	UNIT_NO INTEGER NOT NULL,
	EDE_INVOICE_TO	TEXT NOT NULL,	
	EDE_COMMENTS TEXT NULL,
	EDE_USERSTAMP VARCHAR(50),	
	EDE_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(ID))'));
	PREPARE CREATE_TEMP_EXPENSE_DETAIL_ELECTRICITY_STMT FROM @CREATE_TEMP_EXPENSE_DETAIL_ELECTRICITY;
    EXECUTE CREATE_TEMP_EXPENSE_DETAIL_ELECTRICITY_STMT;
	SET @DROP_EXPENSE_DETAIL_ELECTRICITY=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.EXPENSE_DETAIL_ELECTRICITY'));    
    PREPARE DROP_EXPENSE_DETAIL_ELECTRICITY_STMT FROM @DROP_EXPENSE_DETAIL_ELECTRICITY;
    EXECUTE DROP_EXPENSE_DETAIL_ELECTRICITY_STMT;
	SET @CREATE_EXPENSE_DETAIL_ELECTRICITY=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.EXPENSE_DETAIL_ELECTRICITY(		
	EDE_ID INTEGER NOT NULL	AUTO_INCREMENT,
	UNIT_ID	INTEGER NOT NULL,
	ECN_ID	INTEGER NOT NULL,
	EDE_REC_VER	INTEGER NOT NULL,	
	EDE_COMMENTS TEXT NULL,
	ULD_ID INTEGER NOT NULL,	
	EDE_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(EDE_ID),
	FOREIGN KEY(UNIT_ID) REFERENCES ',DESTINATIONSCHEMA,'.UNIT (UNIT_ID),
	FOREIGN KEY(ECN_ID) REFERENCES ',DESTINATIONSCHEMA,'.EXPENSE_CONFIGURATION (ECN_ID),
	FOREIGN KEY(ULD_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS (ULD_ID))'));
	PREPARE CREATE_EXPENSE_DETAIL_ELECTRICITY_STMT FROM @CREATE_EXPENSE_DETAIL_ELECTRICITY;
    EXECUTE CREATE_EXPENSE_DETAIL_ELECTRICITY_STMT;
	SET @SELECT_ELECTRICITY=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_ELECTRICITY(UNIT_NO,EDE_INVOICE_TO,EDE_COMMENTS,EDE_USERSTAMP,EDE_TIMESTAMP)SELECT EXPD_UNIT_NO,EXPD_INVOICE_TO,EXPD_COMMENTS,USERSTAMP,TIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_BIZ_DETAIL_SCDB_FORMAT WHERE EXPD_TYPE_OF_EXPENSE=',"'ELECTRICITY'"));
	PREPARE SELECT_ELECTRICITY_STMT FROM @SELECT_ELECTRICITY;
    EXECUTE SELECT_ELECTRICITY_STMT;	
	SET START_TIME=(SELECT CURTIME());
    SET @EDE_MINID=(SELECT CONCAT('SELECT MIN(ID) INTO @MIN_ID FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_ELECTRICITY'));
	PREPARE EDE_MINID_STMT FROM @EDE_MINID;
    EXECUTE EDE_MINID_STMT;
	SET @EDE_MAXID=(SELECT CONCAT('SELECT MAX(ID) INTO @MAX_ID FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_ELECTRICITY'));
	PREPARE EDE_MAXID_STMT FROM @EDE_MAXID;
     EXECUTE EDE_MAXID_STMT;
    SET ELC_MINID=@MIN_ID;
    SET ELC_MAXID=@MAX_ID;
	WHILE(ELC_MINID<=ELC_MAXID)DO
	    SET @ELC_ECN_ID=NULL;
        SET @EDE_COMMENT=NULL;
        SET @UNIT_ID=NULL;		
	    SET @SELECT_COMMENT=(SELECT CONCAT('SELECT EDE_COMMENTS INTO @EDE_COMMENT FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_ELECTRICITY WHERE ID=',ELC_MINID));
	    PREPARE SELECT_COMMENT_STMT FROM @SELECT_COMMENT;
        EXECUTE SELECT_COMMENT_STMT;
		SET COMMENTS=@EDE_COMMENT;		
		IF COMMENTS IS NULL THEN
		SET @ELC_COMMENTS=NULL;		
		ELSE
		SET @ELC_COMMENTS=COMMENTS;
		END IF;
		SET @ELC_UNITID=NULL;
		SET @SELECT_UNITID=(SELECT CONCAT('SELECT DISTINCT UNIT_ID INTO @ELC_UNITID FROM ',DESTINATIONSCHEMA,'.EXPENSE_DETAIL_ELECTRICITY WHERE UNIT_ID=(SELECT UNIT_ID FROM ',DESTINATIONSCHEMA,'.UNIT WHERE UNIT_NO=(SELECT UNIT_NO FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_ELECTRICITY WHERE ID=',ELC_MINID,'))'));
		PREPARE SELECT_UNITID_STMT FROM @SELECT_UNITID;
        EXECUTE SELECT_UNITID_STMT;
		SET ELC_UNIT_ID=@ELC_UNITID;
		SET @SELECT_UNIT_ID=(SELECT CONCAT('SELECT UNIT_ID INTO @UNIT_ID FROM ',DESTINATIONSCHEMA,'.UNIT WHERE UNIT_NO=(SELECT UNIT_NO FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_ELECTRICITY WHERE ID=',ELC_MINID,')'));
		PREPARE SELECT_UNIT_ID_STMT FROM @SELECT_UNIT_ID;
        EXECUTE SELECT_UNIT_ID_STMT;		
		SET @SELECT_ECN_ID=(SELECT CONCAT('SELECT DISTINCT ECN_ID INTO @ELC_ECN_ID FROM ',DESTINATIONSCHEMA,'.EXPENSE_CONFIGURATION WHERE ECN_DATA=(SELECT EDE_INVOICE_TO FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_ELECTRICITY WHERE ID=',ELC_MINID,') AND CGN_ID=27'));
		PREPARE SELECT_ECN_ID_STMT FROM @SELECT_ECN_ID;
        EXECUTE SELECT_ECN_ID_STMT;
		SET @ELC_ULD_ID=NULL;
		SET @SELECT_ELC_ULDID=(SELECT CONCAT('SELECT ULD_ID INTO @ELC_ULD_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=(SELECT EDE_USERSTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_ELECTRICITY WHERE ID=',ELC_MINID,')'));
		PREPARE SELECT_ELC_ULDID_STMT FROM @SELECT_ELC_ULDID;
		EXECUTE SELECT_ELC_ULDID_STMT;
        SET @TIMESTAMP=NULL;		
		SET @SELECT_TIMESTAMP=(SELECT CONCAT('SELECT EDE_TIMESTAMP INTO @TIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_ELECTRICITY WHERE ID=',ELC_MINID));
		PREPARE SELECT_TIMESTAMP_STMT FROM @SELECT_TIMESTAMP;
		EXECUTE SELECT_TIMESTAMP_STMT;
        SET @RECVER=1;		
		IF ELC_UNIT_ID IS NOT NULL THEN
		    SET @REC_VER=NULL;
		    SET @SELECT_RECVER=(SELECT CONCAT('SELECT MAX(EDE_REC_VER) INTO @REC_VER FROM ',DESTINATIONSCHEMA,'.EXPENSE_DETAIL_ELECTRICITY WHERE UNIT_ID=(SELECT UNIT_ID FROM ',DESTINATIONSCHEMA,'.UNIT WHERE UNIT_NO=(SELECT UNIT_NO FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_ELECTRICITY WHERE ID=',ELC_MINID,'))'));
			PREPARE SELECT_RECVER_STMT FROM @SELECT_RECVER;
            EXECUTE SELECT_RECVER_STMT;
			SET @RECVER=@REC_VER;
			SET @INSERT_EXPENSE_DETAIL_ELECTRICITY=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.EXPENSE_DETAIL_ELECTRICITY(UNIT_ID,ECN_ID,EDE_REC_VER,EDE_COMMENTS,ULD_ID,EDE_TIMESTAMP)VALUES
			(@UNIT_ID,@ELC_ECN_ID,(@RECVER+1),@ELC_COMMENTS,@ELC_ULD_ID,@TIMESTAMP)'));
			PREPARE INSERT_EXPENSE_DETAIL_ELECTRICITY_STMT FROM @INSERT_EXPENSE_DETAIL_ELECTRICITY;
            EXECUTE INSERT_EXPENSE_DETAIL_ELECTRICITY_STMT;			
		ELSE		
			SET @INSERT_EXPENSE_DETAIL_ELECTRICITY=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.EXPENSE_DETAIL_ELECTRICITY(UNIT_ID,ECN_ID,EDE_REC_VER,EDE_COMMENTS,ULD_ID,EDE_TIMESTAMP)VALUES
			(@UNIT_ID,@ELC_ECN_ID,@RECVER,@ELC_COMMENTS,@ELC_ULD_ID,@TIMESTAMP)'));
			PREPARE INSERT_EXPENSE_DETAIL_ELECTRICITY_STMT FROM @INSERT_EXPENSE_DETAIL_ELECTRICITY;
            EXECUTE INSERT_EXPENSE_DETAIL_ELECTRICITY_STMT;
		END IF;
		SET ELC_MINID=ELC_MINID+1;
		END WHILE;		
		SET END_TIME=(SELECT CURTIME());
		SET DURATION=(SELECT TIMEDIFF(END_TIME,START_TIME));
		SET @COUNTSCDB_EDE=(SELECT CONCAT('SELECT COUNT(*) INTO @COUNT_SCDB_EDE FROM ',SOURCESCHEMA,'.BIZ_DETAIL_SCDB_FORMAT WHERE EXPD_TYPE_OF_EXPENSE=',"'ELECTRICITY'"));
		PREPARE COUNTSCDB_EDE_STMT FROM @COUNTSCDB_EDE;
        EXECUTE COUNTSCDB_EDE_STMT;
		SET @COUNTSPLITTED_EDE=(SELECT CONCAT('SELECT COUNT(*) INTO @COUNT_SPLITTED_EDE FROM ',DESTINATIONSCHEMA,'.EXPENSE_DETAIL_ELECTRICITY'));
		PREPARE COUNTSPLITTED_EDE_STMT FROM @COUNTSPLITTED_EDE;
        EXECUTE COUNTSPLITTED_EDE_STMT;
		SET @REJECTION_COUNT=(@COUNT_SCDB_EDE-@COUNT_SPLITTED_EDE);
        SET FOREIGN_KEY_CHECKS=0;    
		UPDATE PRE_AUDIT_SUB_PROFILE SET PREASP_NO_OF_REC = @COUNT_SCDB_EDE WHERE PREASP_DATA='EXPENSE_DETAIL_ELECTRICITY';
	    INSERT INTO POST_AUDIT_HISTORY(POSTAP_ID,POSTAH_NO_OF_REC,PREASP_ID,PREAMP_ID,POSTAH_DURATION,POSTAH_NO_OF_REJ,ULD_ID)VALUES((SELECT POSTAP_ID FROM POST_AUDIT_PROFILE WHERE POSTAP_DATA='EXPENSE_DETAIL_ELECTRICITY'),@COUNT_SPLITTED_EDE,(SELECT PREASP_ID FROM PRE_AUDIT_SUB_PROFILE WHERE PREASP_DATA='EXPENSE_DETAIL_ELECTRICITY'),(SELECT PREAMP_ID FROM PRE_AUDIT_MAIN_PROFILE WHERE PREAMP_DATA='BIZ DETAIL'),DURATION,@REJECTION_COUNT,@ULDID);
        SET FOREIGN_KEY_CHECKS=1;    
		SET @DROP_TEMP_EXPENSE_DETAIL_ELECTRICITY=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_ELECTRICITY'));
	    PREPARE DROP_TEMP_EXPENSE_DETAIL_ELECTRICITY_STMT FROM @DROP_TEMP_EXPENSE_DETAIL_ELECTRICITY;
        EXECUTE DROP_TEMP_EXPENSE_DETAIL_ELECTRICITY_STMT;
SET FOREIGN_KEY_CHECKS=1;	
COMMIT;	
END;
