DROP PROCEDURE IF EXISTS SP_CHANGE_USERSTAMP_AS_ULDID;
CREATE PROCEDURE SP_CHANGE_USERSTAMP_AS_ULDID(
IN USERSTAMP VARCHAR(50),OUT ULDID INTEGER(2))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
END;
START TRANSACTION;
SET ULDID = (SELECT ULD_ID FROM USER_LOGIN_DETAILS WHERE ULD_LOGINID=USERSTAMP);
COMMIT;
END;