DROP PROCEDURE IF EXISTS SP_TEMP_EXPENSE_UNIT_INSERT;
CREATE PROCEDURE SP_TEMP_EXPENSE_UNIT_INSERT(IN DESTINATIONSCHEMA VARCHAR(50))
BEGIN
	DECLARE MINIMUMID INTEGER;
	DECLARE MAXIMUMID INTEGER;
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
	ROLLBACK;
	END;
	START TRANSACTION;		
	SET @TEMP_EXPUNIT_DROPQUERY=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_UNIT'));
	PREPARE TEMP_EXPUNIT_DROPQUERYSTMT FROM @TEMP_EXPUNIT_DROPQUERY;
	EXECUTE TEMP_EXPUNIT_DROPQUERYSTMT;	
	SET @TEMP_EXPUNIT_CREATEQUERY = (SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_UNIT(
	ID INTEGER AUTO_INCREMENT,
	UNITNO SMALLINT(4),
	UNIT_NUMBERID INTEGER,
	ECNDATA TEXT,
	ECNID INTEGER,
	FIRSTNAME CHAR(30),
	LASTNAME CHAR(30),
	CUSTOMERID INTEGER,
	INVOICEDATE DATE,
	AMOUNT DECIMAL(7,2),
	INVOICEITEMS TEXT,
	INVOICEFROM VARCHAR(200),
	COMMENTS TEXT,
	USER_STAMP VARCHAR(50),
	USERSTAMPID INTEGER,
	TIME_STAMP VARCHAR(50),
	PRIMARY KEY(ID))'));
	PREPARE TEMP_EXPUNIT_CREATEQUERYSTMT FROM @TEMP_EXPUNIT_CREATEQUERY;
	EXECUTE TEMP_EXPUNIT_CREATEQUERYSTMT;	
	SET @TEMP_EXPUNIT_INSERTQUERY = (SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_UNIT(
	UNITNO,ECNDATA,FIRSTNAME,LASTNAME,INVOICEDATE,AMOUNT,INVOICEITEMS,INVOICEFROM,COMMENTS,USER_STAMP,TIME_STAMP)
	SELECT EXP_UNIT_NO,EXP_UNIT_GCC,EXP_UNIT_FIRST_NAME,EXP_UNIT_LAST_NAME,EXP_UNIT_INVOICE_DATE, EXP_UNIT_AMOUNT, EXP_UNIT_INVOICE_ITEMS, EXP_UNIT_INVOICE_FROM, EXP_UNIT_COMMENTS, USERSTAMP,TIMESTAMP
	FROM ',DESTINATIONSCHEMA,'.TEMP_BIZ_DAILY_SCDB_FORMAT WHERE EXP_TYPE_OF_EXPENSE="UNIT EXPENSE"'));
	PREPARE TEMP_EXPUNIT_INSERTQUERYSTMT FROM @TEMP_EXPUNIT_INSERTQUERY;
	EXECUTE TEMP_EXPUNIT_INSERTQUERYSTMT;	
	SET @UPDATEINVOICEITEM = (SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_UNIT SET INVOICEITEMS=',"'NO ITEM'",' WHERE INVOICEITEMS IS NULL'));
	PREPARE UPDATEINVOICEITEMSTMT FROM @UPDATEINVOICEITEM;
	EXECUTE UPDATEINVOICEITEMSTMT;	
	SET @UPDATEINVOICEFROM = (SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_UNIT SET INVOICEFROM=',"'NO FROM'",' WHERE INVOICEFROM IS NULL'));
	PREPARE UPDATEINVOICEFROMSTMT FROM @UPDATEINVOICEFROM;
	EXECUTE UPDATEINVOICEFROMSTMT;	
	SET @UPDATEUSERSTAMP = (SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_UNIT SET USER_STAMP="expatsintegrated@gmail.com" WHERE USER_STAMP IS NULL'));
	PREPARE UPDATEUSERSTAMPSTMT FROM @UPDATEUSERSTAMP;
	EXECUTE UPDATEUSERSTAMPSTMT;	
  	SET @MINID =(SELECT CONCAT('SELECT MIN(ID)INTO @MIN_ID FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_UNIT'));
	PREPARE MINIDSTMT FROM @MINID;
	EXECUTE MINIDSTMT;
	SET MINIMUMID = @MIN_ID;	
	SET @MAXID =(SELECT CONCAT('SELECT MAX(ID)INTO @MAX_ID FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_UNIT'));
	PREPARE MAXIDSTMT FROM @MAXID;
	EXECUTE MAXIDSTMT;
	SET MAXIMUMID = @MAX_ID;	
	WHILE (MINIMUMID <= MAXIMUMID) DO		
		SET @ULDID = NULL;
		SET @UNITID = NULL;
		SET @EXPID = NULL;		
		SET @USERID =(SELECT CONCAT('SELECT ULD_ID INTO @ULDID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=
		(SELECT USER_STAMP FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_UNIT WHERE ID=',MINIMUMID,')'));
		PREPARE USERIDSTMT FROM @USERID;
		EXECUTE USERIDSTMT;		
		SET @UPDATEULDID = (SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_UNIT SET USERSTAMPID=@ULDID WHERE ID=',MINIMUMID));
		PREPARE UPDATEULDIDSTMT FROM @UPDATEULDID;
		EXECUTE UPDATEULDIDSTMT;		
		SET@UNITNOID = (SELECT CONCAT('SELECT UNIT_ID INTO @UNITID FROM ',DESTINATIONSCHEMA,'.UNIT WHERE UNIT_NO=
		(SELECT UNITNO FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_UNIT WHERE ID=',MINIMUMID,')'));
		PREPARE UNITNOIDSTMT FROM @UNITNOID;
		EXECUTE UNITNOIDSTMT;		
		SET @UPDATEUNITID = (SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_UNIT SET UNIT_NUMBERID=@UNITID WHERE ID=',MINIMUMID));
		PREPARE UPDATEUNITIDSTMT FROM @UPDATEUNITID;
		EXECUTE UPDATEUNITIDSTMT;		
		SET@EXPDATA = (SELECT CONCAT('SELECT ECN_ID INTO @EXPID FROM ',DESTINATIONSCHEMA,'.EXPENSE_CONFIGURATION WHERE ECN_DATA=
		(SELECT ECNDATA FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_UNIT WHERE ID=',MINIMUMID,')'));
		PREPARE EXPDATASTMT FROM @EXPDATA;
		EXECUTE EXPDATASTMT;		
		SET @UPDATEECNID = (SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_UNIT SET ECNID=@EXPID WHERE ID=',MINIMUMID));
		PREPARE UPDATEECNIDSTMT FROM @UPDATEECNID;
		EXECUTE UPDATEECNIDSTMT;		
		SET MINIMUMID = MINIMUMID+1;		
	END WHILE;	
	COMMIT;
END;
