DROP PROCEDURE IF EXISTS SP_TEMP_EXPENSE_UNIT_UPDATE;
CREATE PROCEDURE SP_TEMP_EXPENSE_UNIT_UPDATE(IN DESTINATIONSCHEMA VARCHAR(50))
BEGIN
	DECLARE MINIMUM_ID INTEGER;
	DECLARE MAXIMUM_ID INTEGER;
	DECLARE UNITCATEGORY TEXT;
	DECLARE CUSTFNAME CHAR(30);
	DECLARE CUSTLNAME CHAR(30);	
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
	ROLLBACK;
	END;
	START TRANSACTION;	
	SET @TMINID =(SELECT CONCAT('SELECT MIN(ID)INTO @TUMINID FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_UNIT'));
	PREPARE TMINIDSTMT FROM @TMINID;
	EXECUTE TMINIDSTMT;
	SET MINIMUM_ID = @TUMINID;	
	SET @TMAXID =(SELECT CONCAT('SELECT MAX(ID)INTO @TUMAXID FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_UNIT'));
	PREPARE TMAXIDSTMT FROM @TMAXID;
	EXECUTE TMAXIDSTMT;
	SET MAXIMUM_ID = @TUMAXID;	
	WHILE(MINIMUM_ID <= MAXIMUM_ID) DO	
	SET @CATEGORY = NULL;
	SET @L_NAME = NULL;
	SET @F_NAME = NULL;	
		SET @EXPDATA = (SELECT CONCAT('SELECT ECNDATA INTO @CATEGORY FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_UNIT WHERE ID=',MINIMUM_ID));
		PREPARE EXPDATASTMT FROM @EXPDATA;
		EXECUTE EXPDATASTMT;
		SET UNITCATEGORY = @CATEGORY;		
		IF (UNITCATEGORY = 'CUSTOMER')THEN		
			SET @LNAME = (SELECT CONCAT('SELECT LASTNAME INTO @L_NAME FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_UNIT WHERE ID=',MINIMUM_ID));
			PREPARE LNAMESTMT FROM @LNAME;
			EXECUTE LNAMESTMT;
			SET CUSTLNAME = @L_NAME;			
			IF(CUSTLNAME IS NULL)THEN			
				SET @FNAME = (SELECT CONCAT('SELECT FIRSTNAME INTO @F_NAME FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_UNIT WHERE ID=',MINIMUM_ID));
				PREPARE FNAMESTMT FROM @FNAME;
				EXECUTE FNAMESTMT;
				SET CUSTFNAME = @F_NAME;				
				SET @UPDATELASTNAME = (SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_UNIT SET LASTNAME=@F_NAME WHERE ID=',MINIMUM_ID));
				PREPARE UPDATELASTNAMESTMT FROM @UPDATELASTNAME;
				EXECUTE UPDATELASTNAMESTMT;				
			END IF;			
		END IF;		
		SET MINIMUM_ID = MINIMUM_ID+1;		
	END WHILE;	
	COMMIT;
END;
