DROP PROCEDURE IF EXISTS SP_TEMP_EXPENSE_UNITUPDATE;
CREATE PROCEDURE SP_TEMP_EXPENSE_UNITUPDATE(IN DESTINATIONSCHEMA VARCHAR(50))
BEGIN
	DECLARE EU_MINID INTEGER;
	DECLARE EU_MAXID INTEGER;
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
	ROLLBACK;
	END;
	START TRANSACTION;	
		SET FOREIGN_KEY_CHECKS=0;	
	SET @MINID = (SELECT CONCAT('SELECT MIN(ID) INTO @EUMINID FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_UNIT'));
	PREPARE MINIDSTMT FROM @MINID;
	EXECUTE MINIDSTMT;
	SET EU_MINID = @EUMINID;	
	SET @MAXID = (SELECT CONCAT('SELECT MAX(ID) INTO @EUMAXID FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_UNIT'));
	PREPARE MAXIDSTMT FROM @MAXID;
	EXECUTE MAXIDSTMT;
	SET EU_MAXID = @EUMAXID;	
	WHILE(EU_MINID <= EU_MAXID)DO	
		SET @F_NAME = NULL;
		SET @L_NAME = NULL;
		SET @UNITID = NULL;
		SET @CUST_ID = NULL;	
		SET @FNAME = (SELECT CONCAT('SELECT FIRSTNAME INTO @F_NAME FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_UNIT WHERE ID=',EU_MINID));
		PREPARE FNAMESTMT FROM @FNAME;
		EXECUTE FNAMESTMT;		
		SET @LNAME = (SELECT CONCAT('SELECT LASTNAME INTO @L_NAME FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_UNIT WHERE ID=',EU_MINID));
		PREPARE LNAMESTMT FROM @LNAME;
		EXECUTE LNAMESTMT;		
		SET @UNITNOID = (SELECT CONCAT('SELECT UNIT_NO INTO @UNITID FROM ',DESTINATIONSCHEMA,'.UNIT WHERE UNIT_NO=
		(SELECT UNITNO FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_UNIT WHERE ID=',EU_MINID,')'));
		PREPARE UNITNOIDSTMT FROM @UNITNOID;
		EXECUTE UNITNOIDSTMT;		
		SET @CUSTID = (SELECT CONCAT('SELECT DISTINCT CC_CUST_ID INTO @CUST_ID FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_SCDB_FORMAT 
		WHERE CC_FIRST_NAME=@F_NAME AND CC_LAST_NAME=@L_NAME AND CC_UNIT_NO=@UNITID'));
		PREPARE CUSTIDSTMT FROM @CUSTID;
		EXECUTE CUSTIDSTMT;		
		SET @UPDATECUSTID = (SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_UNIT SET CUSTOMERID=@CUST_ID WHERE ID=',EU_MINID));
		PREPARE UPDATECUSTIDSTMT FROM @UPDATECUSTID;
		EXECUTE UPDATECUSTIDSTMT;		
	SET EU_MINID = EU_MINID+1;
	END WHILE;	
	SET FOREIGN_KEY_CHECKS=1;	
	COMMIT;
END;
