DROP PROCEDURE IF EXISTS SP_EXPENSE_HOUSEKEEPING_PAYMENT_INSERT;
CREATE PROCEDURE SP_EXPENSE_HOUSEKEEPING_PAYMENT_INSERT(IN DESTINATIONSCHEMA VARCHAR(50))
BEGIN
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
	ROLLBACK;
	END;
	START TRANSACTION;	
	SET @EHKP_DROPQUERY=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.EXPENSE_HOUSEKEEPING_PAYMENT'));
	PREPARE EHKP_DROPQUERYSTMT FROM @EHKP_DROPQUERY;
	EXECUTE EHKP_DROPQUERYSTMT;
	SET @EHKP_CREATEQUERY=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.EXPENSE_HOUSEKEEPING_PAYMENT(
	EHKP_ID	INTEGER NOT NULL AUTO_INCREMENT,
	UNIT_ID	INTEGER NULL,	
	EHKU_ID	INTEGER NULL,	
	EHKP_FOR_PERIOD	DATE NOT NULL,	
	EHKP_PAID_DATE DATE NOT NULL,	
	EHKP_AMOUNT	DECIMAL(5,2) NOT NULL,	
	EHKP_COMMENTS TEXT NULL,
	ULD_ID INTEGER(2) NOT NULL,	
	EHKP_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(EHKP_ID),
	FOREIGN KEY(ULD_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS (ULD_ID))'));
	PREPARE EHKP_CREATEQUERYSTMT FROM @EHKP_CREATEQUERY;
	EXECUTE EHKP_CREATEQUERYSTMT;
	SET @EHKP_INSERTQUERY = (SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.EXPENSE_HOUSEKEEPING_PAYMENT
	(EHKP_ID,UNIT_ID,EHKP_FOR_PERIOD,EHKP_PAID_DATE,EHKP_AMOUNT,EHKP_COMMENTS,ULD_ID,EHKP_TIMESTAMP)
	SELECT ID,TEHKP_UNITID,TEHKP_FORPERIOD,TEHKP_PAIDDATE,TEHKP_AMOUNT,TEHKP_COMMENTS,TEHKP_ULDID,TEHKP_TIMESTAMP
	FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_HOUSEKEEPING_PAYMENT'));
	PREPARE EHKP_INSERTQUERYSTMT FROM @EHKP_INSERTQUERY;
	EXECUTE EHKP_INSERTQUERYSTMT;
	SET @EHKPINSERTQUERY = (SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.EXPENSE_HOUSEKEEPING_PAYMENT
	(EHKP_ID,EHKU_ID,EHKP_FOR_PERIOD,EHKP_PAID_DATE,EHKP_AMOUNT,EHKP_COMMENTS,ULD_ID,EHKP_TIMESTAMP)
	SELECT ID,TEHKU_UID,TEHKU_FORPERIOD,TEHKU_PAIDDATE,TEHKU_AMOUNT,TEHKU_COMMENTS,TEHKU_ULDID,TEHKU_TIMESTAMP
	FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_HOUSEKEEPING_UNIT'));
	PREPARE EHKPINSERTQUERYSTMT FROM @EHKPINSERTQUERY;
	EXECUTE EHKPINSERTQUERYSTMT;
	COMMIT;
	END;
	