--version 0.7 startdate:28/02/2014 --enddate:28/02/2014--- issueno 754 commentno:36-->desc: APPLIED SUB_SP TO REPLACE USERSTAMP AS ID-SAFI
--version 0.6 --sdate:27/02/2014 --edate:27/02/2014 --issue:754 --comment:22 --doneby:RL

-- VER 0.5 ISSUE NO:659 COMMENT # STARTDATE:03/02/2014 ENDDATE:04/02/2014 DESC: CALLING SUB SP FOR NEW USER CREATION AND GRANT PERMISSION FOR THAT USER. DONE BY: MANIKANDAN.S
-- VER 0.4 ISSUE NO:659 COMMENT #29 STARTDATE:17/12/2013 ENDDATE:17/12/2013 DESC:CHANGED USER_FILE_DETAILS TABLE HEADER NAME AS PER TABLE MODIFICATION DONE BY:DHIVYA.A
-- VER 0.3 ISSUE NO:659  STARTDATE:13/12/2013 ENDDATE:13/12/2013 DESC:CHANGED PASSING VARIABLES MENUNAME AS MENUID DONE BY:DHIVYA.A
-- VER 0.2 ISSUE NO:670  STARTDATE:11/12/2013 ENDDATE:11/12/2013 DESC:CHANGED PASSING VARIABLES AND INSERT QUERY FOR USER_MENU_DETAILS DONE BY:DHIVYA.A
-- VER 0.1 ISSUE NO:659 COMMENT #3 STARTDATE:07/12/2013 ENDDATE:09/12/2013 DESC:SP FOR ROLE CREATION INSERT DONE BY:DHIVYA.A

DROP PROCEDURE IF EXISTS SP_ROLE_CREATION_INSERT;
CREATE PROCEDURE SP_ROLE_CREATION_INSERT(
CUSTOM_ROLE VARCHAR(15),
BASIC_ROLE TEXT,
MENUID TEXT,
FILEID TEXT,
USERSTAMP VARCHAR(50),
DB_NAME VARCHAR(20))
BEGIN
-- VARIABLE DECLARATION
DECLARE MENU_LENGTH INTEGER;
DECLARE TEMP_MENU TEXT;
DECLARE MENU INTEGER;
DECLARE MENU_POSITION INTEGER;

DECLARE TEMP_FILE TEXT;
DECLARE FPID INTEGER;
DECLARE FILE_POSITION INTEGER;
DECLARE FILE_LENGTH INTEGER;
DECLARE GRANT_MP_ID VARCHAR(250) DEFAULT "'";
DECLARE USER_NAME VARCHAR(50);
DECLARE V_USER_COUNT  SMALLINT(1);
DECLARE V_STRLEN    INT DEFAULT 0;
DECLARE V_SUBSTRLEN INT DEFAULT 0;
DECLARE V_MENU_ID   INT;
DECLARE USERSTAMP_ID INTEGER(2);
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN 
	ROLLBACK; 
END;
START TRANSACTION;
CALL SP_CHANGE_USERSTAMP_AS_ULDID(USERSTAMP,@ULDID);
SET USERSTAMP_ID = (SELECT @ULDID);

		IF CUSTOM_ROLE IS NOT NULL AND BASIC_ROLE IS NOT NULL THEN
			-- INSERT QUERY FOR ROLE_CREATION TABLE
      IF NOT EXISTS (SELECT RC_ID FROM ROLE_CREATION WHERE RC_NAME = CUSTOM_ROLE) THEN
			  INSERT INTO ROLE_CREATION(URC_ID,RC_NAME,RC_USERSTAMP) VALUES ((SELECT URC_ID FROM USER_RIGHTS_CONFIGURATION WHERE URC_DATA=BASIC_ROLE),CUSTOM_ROLE,USERSTAMP);
      END IF;
		END IF;
    
IF MENUID IS NOT NULL THEN
  SET TEMP_MENU = MENUID;
  SET MENU_LENGTH = 1;
  
 loop_label : LOOP
		SET MENU_POSITION=(SELECT LOCATE(',', TEMP_MENU,MENU_LENGTH));
		IF MENU_POSITION<=0 THEN
			SET MENU=TEMP_MENU;
		ELSE
			SELECT SUBSTRING(TEMP_MENU,MENU_LENGTH,MENU_POSITION-1) INTO MENU;
			SET TEMP_MENU=(SELECT SUBSTRING(TEMP_MENU,MENU_POSITION+1));
		END IF;
    
		-- INSERT QUERY FOR USER_FILE_DETAILS
		INSERT INTO USER_MENU_DETAILS(MP_ID,RC_ID,ULD_ID)VALUES(MENU,(SELECT RC_ID FROM ROLE_CREATION WHERE RC_NAME=CUSTOM_ROLE),USERSTAMP_ID);
		
		IF MENU_POSITION<=0 THEN
			LEAVE  loop_label;
		END IF;
	END LOOP;
END IF;
	
IF FILEID IS NOT NULL THEN
	SET TEMP_FILE = FILEID;
	SET FILE_LENGTH=1;
  
	loop_label:  LOOP
		SET FILE_POSITION=(SELECT LOCATE(',', TEMP_FILE,FILE_LENGTH));
    
		IF FILE_POSITION<=0 THEN
			SET FPID=TEMP_FILE;
		ELSE
			SELECT SUBSTRING(TEMP_FILE,FILE_LENGTH,FILE_POSITION-1) INTO FPID;
			SET TEMP_FILE=(SELECT SUBSTRING(TEMP_FILE,FILE_POSITION+1));
		END IF;
    
		-- INSERT QUERY FOR USER_FILE_DETAILS
		INSERT INTO USER_FILE_DETAILS(RC_ID,FP_ID,ULD_ID)VALUES((SELECT RC_ID FROM ROLE_CREATION WHERE RC_NAME=CUSTOM_ROLE),FPID,USERSTAMP_ID);
		
		IF FILE_POSITION<=0 THEN
			LEAVE  loop_label;
		END IF;
	END LOOP;
	
END IF;

  -- GET MENU ID'S AND PUT COMMA(,) 
  MAIN_LOOP:
  LOOP
    SET V_STRLEN = CHAR_LENGTH(MENUID);
 
    SET V_MENU_ID = SUBSTRING_INDEX(MENUID, ',', 1);   
    
    SET GRANT_MP_ID = CONCAT (GRANT_MP_ID,V_MENU_ID,''',''');
    
    SET V_SUBSTRLEN = CHAR_LENGTH(SUBSTRING_INDEX(MENUID, ',', 1)) + 2;
    SET MENUID = MID(MENUID, V_SUBSTRLEN, V_STRLEN);
   
    IF MENUID = '' THEN
      LEAVE MAIN_LOOP;
    END IF;    
  END LOOP MAIN_LOOP;
  
SET GRANT_MP_ID = SUBSTRING(GRANT_MP_ID,1,CHAR_LENGTH(GRANT_MP_ID)-2);

      -- CREATING NEW USER
      SET USER_NAME = CUSTOM_ROLE;
      SET @user_name = USER_NAME;

      select count(user) into V_USER_COUNT from mysql.user WHERE USER = @user_name;

      IF V_USER_COUNT = 0 THEN
      -- CREATING NEW DATABASE USER, TEMPORARILY PASSWORD IS GIVING SAME AS THE USER NAME
      SET @sql = CONCAT('CREATE USER ''',USER_NAME,'''@','''%''',' IDENTIFIED BY ''',USER_NAME,"'");
       
       PREPARE s1 FROM @sql;
       EXECUTE s1;
       DEALLOCATE PREPARE s1;
       END IF;

-- CALLING SUB SP FOR GRANT PERMISSION FOR THAT USER.
CALL SP_PLATFORM_MGMT_DB_USER_RIGHTS_GRANT_REVOKE(DB_NAME, USER_NAME, GRANT_MP_ID,'GRANT');

COMMIT;
END;
/*
call SP_ROLE_CREATION_INSERT('mani','ADMIN','1,2,3','1,3,4','manicandan.s@ssomens.com','development');
select * from TEMP;
DELETE FROM TEMP;
*/