-- version:1.0 -- sadte:08/05/2014 -- edate:08/05/2014 --desc: ALTERED PETTY ID HEADER --doneby:SASIKALA
-- version:0.9 -- sdate:23/04/2014 -- edate:23/04/2014 -- issue:765 --desc:UPDATED TIMESTAMP --doneby:SASIKALA
-- version:0.8 -- sdate:19/03/2014 -- edate:19/03/2014 -- issue:765 --desc:dynamically get source nd destination schema --doneby:RL
-- version:0.7 -- sdate:17/03/2014 -- edate:17/03/2014 -- issue:765 --desc:droped temp table --doneby:RL
-- version:0.6 --sdate:04/03/2014 --edate:04/03/2014 --Desc:ISSUE CORRECTED INUNIT EXPENSE- DONE BY SAFI
-- version:0.5 --sdate:28/02/2014 --edate:28/02/2014 --issue:750 --desc:changed userstamp as ULD_ID and timestamp get from scdb done by:RL
-- version:0.4--sdate:21/02/2014 --edate:22/02/2014 --issue:750 -desc:added preaudit and post audit queries done by:dhivya
-- version:0.3 --sdate:18/02/2014 --edate:18/02/2014 --issue:276 --commentno:26 --desc:ADD USERSTAMP N TIMESTAMP IN EXPENSE_HOUSEKEEPING_UNIT --doneby:RL
-- version:0.2 --sdate:21/01/2014 --edate:21/01/2014 --issue:594 --commentno:50 & 54 --doneby:RL
DROP PROCEDURE IF EXISTS SP_TEMP_BIZ_DAILY_SCDB_FORMAT_INSERT;
CREATE PROCEDURE SP_TEMP_BIZ_DAILY_SCDB_FORMAT_INSERT(IN SOURCESCHEMA VARCHAR(50),IN DESTINATIONSCHEMA VARCHAR(50))
BEGIN
	SET @TBIZDLY_DROPQUERY=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_BIZ_DAILY_SCDB_FORMAT'));
	PREPARE TBIZDLY_DROPQUERYSTMT FROM @TBIZDLY_DROPQUERY;
	EXECUTE TBIZDLY_DROPQUERYSTMT;	
	SET @TBIZDLY_CREATEQUERY=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.TEMP_BIZ_DAILY_SCDB_FORMAT LIKE ',SOURCESCHEMA,'.BIZ_DAILY_SCDB_FORMAT'));
	PREPARE TBIZDLY_CREATEQUERYSTMT FROM @TBIZDLY_CREATEQUERY;
	EXECUTE TBIZDLY_CREATEQUERYSTMT;
	SET @TBIZDLY_INSERTQUERY=(SELECT CONCAT('INSERT ',DESTINATIONSCHEMA,'.TEMP_BIZ_DAILY_SCDB_FORMAT SELECT * FROM ',SOURCESCHEMA,'.BIZ_DAILY_SCDB_FORMAT'));
	PREPARE TBIZDLY_INSERTQUERYSTMT FROM @TBIZDLY_INSERTQUERY;
	EXECUTE TBIZDLY_INSERTQUERYSTMT;	
	SET @UPDATESLORACAIRCON=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_BIZ_DAILY_SCDB_FORMAT SET EXP_AIRCON_SERVICED_BY=',"'LORAC AIRCON AND ENGINEERING PTE LTD'",' WHERE EXP_AIRCON_SERVICED_BY=',"'LORAC AIRCON'"));
	PREPARE UPDATESLORACAIRCONSTMT FROM @UPDATESLORACAIRCON;
	EXECUTE UPDATESLORACAIRCONSTMT;	
	SET @UPDATEBCSAIRCON=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_BIZ_DAILY_SCDB_FORMAT SET EXP_AIRCON_SERVICED_BY=',"'BCS Aircon Engineering Pte Ltd'",' WHERE EXP_AIRCON_SERVICED_BY=',"'BCS AIRCON ENGINEERING'"));
	PREPARE UPDATEBCSAIRCONSTMT FROM @UPDATEBCSAIRCON;
	EXECUTE UPDATEBCSAIRCONSTMT;	
  SET @UPDATETIMESTAMP=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_BIZ_DAILY_SCDB_FORMAT SET TIMESTAMP=(SELECT CONVERT_TZ(TIMESTAMP, "+08:00","+0:00"))'));
  PREPARE UPDATETIMESTAMPSTMT FROM @UPDATETIMESTAMP;
  EXECUTE UPDATETIMESTAMPSTMT;
   SET @UPDATEPETTYID=(SELECT CONCAT('ALTER TABLE ',DESTINATIONSCHEMA,'.TEMP_BIZ_DAILY_SCDB_FORMAT MODIFY COLUMN EXP_PETTY_ID INTEGER'));
  PREPARE UPDATEPETTYIDSTMT FROM @UPDATEPETTYID;
  EXECUTE UPDATEPETTYIDSTMT;
END;
