--version:0.6 --sdate:09/06/2014 --edate:09/06/2014 --issue:566 --commentno#12 --desc:ADDED ROLLBACK AND COMMIT --doneby:SASIKALA
--version:0.5 --sdate:14/05/2014 --edate:14/05/2014 --issue:817 --commentno#55 --desc:changed temp table as dynamic --doneby:RL
-- VER 0.4-->issue tracker no :535 comment no:#222 startdate:01/03/2013 enddate:01/03/2013 description --> INSTEAD OF EMPLOYEE NAME, EMPLOYEE ID LL BE PASSED created by -->PUNITHA
-- VER 0.3-->issue tracker no :636 comment no:#47 startdate:08/11/2013 enddate:09/11/2013 description --> changed sp name created by -->Dhivya.A 
---> version 0.2 -->createddate:06.07.2013 -->issueno:512 -->description: table name changed for house keeping -->created by:loganathan
---> version 0.1 -->date:31.5.2013 -->issueno:512 -->description: SELECT EMPLOYEE WORK DURATION GIVEN MONTH WITH AMMOUNT --> created by:loganathan

DROP PROCEDURE IF EXISTS SP_BIZDLY_HOUSEKEEPING_DURATION_AMOUNT_SRCH;
CREATE PROCEDURE SP_BIZDLY_HOUSEKEEPING_DURATION_AMOUNT_SRCH(
IN EMPLOYEE_ID INTEGER,
IN INPUT_DATE DATE,
IN AMOUNT DECIMAL(7,2),
IN USERSTAMP VARCHAR(50),
OUT HOUSEKEEPING_DURATION_AMOUNT TEXT)

BEGIN

	DECLARE USERSTAMP_ID INTEGER;
	DECLARE SYSDATEANDTIME VARCHAR(50);
	DECLARE SYSDATEANDULDID VARCHAR(50);
	DECLARE INPUT_MONTH INTEGER;
	DECLARE INPUT_YEAR INTEGER;
  DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
END;
START TRANSACTION;
	
	SET INPUT_MONTH = (SELECT MONTH(INPUT_DATE));
	
	SET INPUT_YEAR = (SELECT YEAR(INPUT_DATE));
	
	CALL SP_CHANGE_USERSTAMP_AS_ULDID(USERSTAMP,@ULDID);
	SET USERSTAMP_ID=(SELECT @ULDID);
	
	SET SYSDATEANDTIME=(SELECT SYSDATE());
	SET SYSDATEANDTIME=(SELECT REPLACE(SYSDATEANDTIME,' ',''));
	SET SYSDATEANDTIME=(SELECT REPLACE(SYSDATEANDTIME,'-',''));
	SET SYSDATEANDTIME=(SELECT REPLACE(SYSDATEANDTIME,':',''));
	SET SYSDATEANDULDID=(SELECT CONCAT(SYSDATEANDTIME,'_',USERSTAMP_ID));	
	
	SET HOUSEKEEPING_DURATION_AMOUNT=(SELECT CONCAT('TEMP_HOUSEKEEPING_DURATION_AMOUNT','_',SYSDATEANDULDID));
	
	SET @HKD_AMT_CREATEQUERY = (SELECT CONCAT('CREATE TABLE ',HOUSEKEEPING_DURATION_AMOUNT,' AS 
	(SELECT SUM(EHK_DURATION) AS DURATION,SUM(EHK_DURATION) * ',AMOUNT,' AS AMOUNT FROM EXPENSE_HOUSEKEEPING EHK 
	JOIN  EMPLOYEE_DETAILS ED ON EHK.EMP_ID=ED.EMP_ID AND ED.EMP_ID=',EMPLOYEE_ID,' AND 
	YEAR(EHK.EHK_WORK_DATE)=',INPUT_YEAR,' AND MONTH(EHK.EHK_WORK_DATE)=',INPUT_MONTH,')'));
	PREPARE HKD_AMT_CREATEQUERYSTMT FROM @HKD_AMT_CREATEQUERY;
	EXECUTE HKD_AMT_CREATEQUERYSTMT;
	COMMIT;
END;