-- VERSION:0.3 -- START DATE:09-06-2014 -- END DATE:09-06-2014 -- ISSUE NO:566 -- COMMENT NO:12 -- DESC: ADDED ROLLBACK AND COMMIT -- DONEBY:SASIKALA
-- VERSION:0.2 -- START DATE:31-03-2014 -- END DATE:31-03-2014 -- ISSUE NO:565 -- COMMENT NO:262 -- DESC: IMPLEMENTING UPDATE FLAG IN SP_EXPENSE_UNIT_SINGLE_TABLE_ROW_DELETION -- DONEBY:BHAVANI.R
-- VERSION:0.1 -- START DATE:31-03-2014 -- END DATE:31-03-2014 -- ISSUE NO:565 -- COMMENT NO:262 -- DESC: CREATION OF SP_EXPENSE_UNIT_SINGLE_TABLE_ROW_DELETION -- DONEBY:BHAVANI.R
DROP PROCEDURE IF EXISTS SP_BIZDLY_UNIT_DELETION;
CREATE PROCEDURE SP_BIZDLY_UNIT_DELETION(IN TABLE_ID INTEGER,IN ROW_ID INTEGER,IN V_USERSTAMP VARCHAR(50),OUT UPDATE_SUCCESSFLAG INTEGER)
BEGIN
DECLARE CUSTOMERID INTEGER;
DECLARE ID_VALUE INTEGER;
DECLARE CUSTOMER_VALUE INTEGER;
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
SET UPDATE_SUCCESSFLAG=0;
  ROLLBACK;
END;
START TRANSACTION;
SET UPDATE_SUCCESSFLAG=0;
SET CUSTOMER_VALUE=(SELECT CUSTOMER_ID FROM EXPENSE_UNIT WHERE EU_ID=ROW_ID);
-- CALLING SP_SINGLE_TABLE_ROW_DELETION
CALL SP_SINGLE_TABLE_ROW_DELETION(TABLE_ID,ROW_ID,V_USERSTAMP,@DELETION_FLAG);
SET UPDATE_SUCCESSFLAG=1;
SET ID_VALUE=(SELECT MAX(TH_ID) FROM TICKLER_HISTORY WHERE CUSTOMER_ID IS NULL);
SET CUSTOMERID=(SELECT CUSTOMER_ID FROM TICKLER_HISTORY WHERE TH_ID=ID_VALUE);
-- UPDATING TICKLER_HISTORY TABLE
IF (CUSTOMER_VALUE IS NOT NULL) THEN
UPDATE TICKLER_HISTORY SET CUSTOMER_ID=CUSTOMER_VALUE WHERE TH_ID=ID_VALUE;
SET UPDATE_SUCCESSFLAG=1;
END IF;
COMMIT;
END;