-->version 0.7 -->start date:28/02/2014 -->end date:28/02/2014 --issueno:754 commentno:#36 -->description:changing of datatype and value for userstamp -->done by Bhavani.R
-->version 0.6 -->start date:27/02/2014 -->end date:27/02/2014 --issueno:754 commentno:#22 -->description:changing of datatype and column header as uld_id for userstamp -->done by Bhavani.R
-->version 0.5 -->start date:22/02/2014 -->end date:22/02/2014 --issueno:749 commentno:#17 -->description:CHANGING THE END IF STATEMENT -->created by:ABDUL KADER.M
-->version 0.4 -->start date:18/02/2014 -->end date:18/02/2014 --issueno:749 commentno:#43 -->description:implement flag for success message  -->created by:ABDUL KADER.M
-->version 0.3 -->issueno:253 commentno:#111-->startdate:21/11/2013 -->enddate:21/11/2013-->desc:changed DATA TYPE (INTEGER (7)) FOR CARDNO  -->done by DINESH.M 
-- VER 0.2-->issue tracker no :636 comment no:#47 startdate:08/11/2 013 enddate:09/11/2013 description --> changed sp name created by -->Dhivya.A 
--VER 0.1 ISSUE NO:535 COMMENT NO:#13 START DATE:24/09/2013 END DATE:25/09/2013 DESC:SP FOR TYPE_OF_EXPENSE PURCHASE_NEW_CARD DONE BY:DHIVYA.A 

DROP PROCEDURE IF EXISTS SP_BIZDLY_PURCHASE_NEW_CARD_INSERT;
CREATE PROCEDURE SP_BIZDLY_PURCHASE_NEW_CARD_INSERT(
IN UNITNO SMALLINT(4),
IN CARDNO INTEGER(7),
IN INVOICEDATE DATE,
IN AMOUNT DECIMAL(7,2),
IN COMMENTS TEXT,
IN USERSTAMP VARCHAR(50),
OUT EPNC_FLAG INTEGER(10))
BEGIN
DECLARE USERSTAMP_ID INTEGER(2);
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN 
ROLLBACK;
END;
SET EPNC_FLAG=0;
CALL SP_CHANGE_USERSTAMP_AS_ULDID(USERSTAMP,@ULDID);
SET USERSTAMP_ID = (SELECT @ULDID);
IF (UNITNO IS NOT NULL AND CARDNO IS NOT NULL AND INVOICEDATE IS NOT NULL AND AMOUNT IS NOT NULL AND USERSTAMP IS NOT NULL) THEN
IF NOT EXISTS(SELECT UASD_ACCESS_CARD FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=CARDNO)THEN
-- insert query for EXPENSE_PURCHASE_NEW_CARD table
INSERT INTO EXPENSE_PURCHASE_NEW_CARD(UNIT_ID,EPNC_NUMBER,EPNC_INVOICE_DATE,EPNC_AMOUNT,EPNC_COMMENTS,ULD_ID)
VALUES ((SELECT UNIT_ID FROM UNIT WHERE UNIT_NO=UNITNO),CARDNO,INVOICEDATE,AMOUNT,COMMENTS,USERSTAMP_ID);
SET EPNC_FLAG=1;
END IF;
-- insert query for UNIT_ACCESS_STAMP_DETAILS table

INSERT INTO UNIT_ACCESS_STAMP_DETAILS(UNIT_ID,UASD_ACCESS_CARD,UASD_ACCESS_INVENTORY,UASD_COMMENTS,ULD_ID)
VALUES((SELECT UNIT_ID FROM UNIT WHERE UNIT_NO=UNITNO),CARDNO,'X',COMMENTS,USERSTAMP_ID);
SET EPNC_FLAG=1;
END IF;
COMMIT;
END;