-->version 0.7 -->start date:28/02/2014 end date:28/02/2014 -->issueno:754 commentno:#36 -->description:CHANGING OF DATA TYPE AND VALUE OF USERSTAMP DONE BY:BHAVANI.R
-->version 0.6 -->start date:27/02/2014 end date:27/02/2014 -->issueno:754 commentno:#22 -->description:CHANGING OF DATA TYPE AND CHANGING OF USERSTAMP IN TO ULD_ID DONE BY:BHAVANI.R
-->version 0.5 -->start date:17/02/2014 end date:17/02/2014 -->issueno:749 commentno:#5 -->description:implement flag in SP_BIZDTL_AIRCON_SERVICE_BY_INSERT comments -->created by:ABDUL KADER.M
-->version 0.4 -->createddate:28.08.2013 -->issueno:600 -->description:stored procedure for Aircon service by detail entry form -->created by:DHIVYA.A
-->version 0.2 -->start date:07/11/2013 end date:09/11/2013 -->issueno:636 commentno:#47 -->description:changed sp names and added comments -->created by:DHIVYA.A
-->version 0.1 -->createddate:28.08.2013 -->issueno:600 -->description:stored procedure for Aircon service by detail entry form -->created by:DHIVYA.A

DROP PROCEDURE IF EXISTS SP_BIZDTL_AIRCON_SERVICE_BY_INSERT;
CREATE PROCEDURE SP_BIZDTL_AIRCON_SERVICE_BY_INSERT(
IN UNITNO INTEGER,
IN EASBDATA CHAR(50),
IN COMMENTS TEXT,
IN USERSTAMP VARCHAR(50),
OUT FLAG INTEGER(10))
BEGIN
	DECLARE RECVER INTEGER;
	DECLARE USERSTAMP_ID INTEGER(2);
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN 
		ROLLBACK; 
	END;
	START TRANSACTION;
	SET FLAG=0;
	CALL SP_CHANGE_USERSTAMP_AS_ULDID(USERSTAMP,@ULDID);
    SET USERSTAMP_ID = (SELECT @ULDID);
-- set null for non mandatory fields
	IF COMMENTS='' THEN
		SET COMMENTS=NULL;
	END IF;

	IF EASBDATA IS NOT NULL THEN
		IF NOT EXISTS(SELECT EASB_DATA FROM EXPENSE_AIRCON_SERVICE_BY WHERE EASB_DATA=EASBDATA)THEN
-- insert query for EXPENSE_AIRCON_SERVICE_BY table
			INSERT INTO EXPENSE_AIRCON_SERVICE_BY(EASB_DATA,ULD_ID)VALUES(EASBDATA,USERSTAMP_ID);
			SET FLAG=1;
		END IF;
	END IF;

	IF(UNITNO IS NOT NULL AND EASBDATA IS NOT NULL AND USERSTAMP IS NOT NULL) THEN
		IF NOT EXISTS (SELECT UNIT_ID FROM EXPENSE_DETAIL_AIRCON_SERVICE WHERE UNIT_ID=(SELECT UNIT_ID FROM UNIT WHERE UNIT_NO=UNITNO)) THEN
-- insert query for EXPENSE_DETAIL_AIRCON_SERVICE table
			INSERT INTO EXPENSE_DETAIL_AIRCON_SERVICE(UNIT_ID,EASB_ID,EDAS_REC_VER,EDAS_COMMENTS,ULD_ID)VALUES
			((SELECT UNIT_ID FROM UNIT WHERE UNIT_NO=UNITNO),
			(SELECT EASB_ID FROM EXPENSE_AIRCON_SERVICE_BY WHERE EASB_DATA=EASBDATA),1,COMMENTS,USERSTAMP_ID);
			SET FLAG=1;
		ELSE 
			SET RECVER=(SELECT MAX(EDAS_REC_VER) FROM EXPENSE_DETAIL_AIRCON_SERVICE WHERE UNIT_ID=(SELECT UNIT_ID FROM UNIT WHERE UNIT_NO=UNITNO));
			SET RECVER=RECVER+1;
-- insert query for EXPENSE_DETAIL_AIRCON_SERVICE table
			INSERT INTO EXPENSE_DETAIL_AIRCON_SERVICE(UNIT_ID,EASB_ID,EDAS_REC_VER,EDAS_COMMENTS,ULD_ID)VALUES
			((SELECT UNIT_ID FROM UNIT WHERE UNIT_NO=UNITNO),
			(SELECT EASB_ID FROM EXPENSE_AIRCON_SERVICE_BY WHERE EASB_DATA=EASBDATA),RECVER,COMMENTS,USERSTAMP_ID);
		SET FLAG=1;
		END IF;
	END IF;
COMMIT;
END;
