-- > version 0.9-- >startdate:09/06/2014  enddate:09/06/2014 -- >issueno:566comment:12 -- >desc:ADDED ROLLBACK AND COMMIT -- >doneby:SASIKALA

-- > version 0.8-- >startdate:02/06/2014  enddate:03/06/2014 -- >issueno:825 comment:129 -- >desc:SPLITTED INTO 3 PARTS -- >doneby:DHIVYA

DROP PROCEDURE IF EXISTS SP_SEARCH_BY_ALL_UNIT_ERROR_MSG;
CREATE PROCEDURE SP_SEARCH_BY_ALL_UNIT_ERROR_MSG(
IN TEMP_ACCESS TEXT,IN ACCESS_CARD_COUNT INTEGER,IN TEMP_CUST TEXT,IN CARD_ID INTEGER,IN CARD_NO INTEGER)
BEGIN
DECLARE AMIN_ID INTEGER;
DECLARE AMAX_ID INTEGER;
DECLARE ACTCUSTNAME TEXT;
DECLARE LMIN_ID INTEGER;
DECLARE LMAX_ID INTEGER;
DECLARE LOSTCUSTNAME TEXT;
DECLARE CUSTOMER_ACT_VALUE INTEGER;
DECLARE CUSTOMER_LOST_VALUE INTEGER;
DECLARE FLAG TEXT;
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
END;
SET @SET_CUSTOMER_ACT_COUNT=(SELECT CONCAT('SELECT COUNT(*) INTO @CUSTOMERACTVALUE FROM CUSTOMER_ACCESS_CARD_DETAILS WHERE ACN_ID IS NULL AND CACD_VALID_TILL IS NULL AND UASD_ID=(SELECT UASDID FROM ',TEMP_ACCESS,' WHERE ID=',ACCESS_CARD_COUNT,')'));
PREPARE CUSTOMER_ACT_COUNT_STMT FROM @SET_CUSTOMER_ACT_COUNT;
EXECUTE CUSTOMER_ACT_COUNT_STMT;
SET CUSTOMER_ACT_VALUE= @CUSTOMERACTVALUE;
SET @SET_CUSTOMER_LOST_COUNT=(SELECT CONCAT('SELECT COUNT(*) INTO @CUSTOMERLOSTVALUE FROM CUSTOMER_ACCESS_CARD_DETAILS WHERE ACN_ID !=4 AND CACD_VALID_TILL IS NOT NULL AND UASD_ID=(SELECT UASDID FROM ',TEMP_ACCESS,' WHERE ID=',ACCESS_CARD_COUNT,')'));
PREPARE CUSTOMER_LOST_COUNT_STMT FROM @SET_CUSTOMER_LOST_COUNT;
EXECUTE CUSTOMER_LOST_COUNT_STMT;
SET CUSTOMER_LOST_VALUE= @CUSTOMERLOSTVALUE;
IF CUSTOMER_ACT_VALUE>1 THEN
  SET @INSERT_CUST=(SELECT CONCAT('INSERT INTO ',TEMP_CUST,' (CUST_ID)(SELECT CUSTOMER_ID FROM CUSTOMER_ACCESS_CARD_DETAILS WHERE ACN_ID IS NULL AND CACD_VALID_TILL IS NULL AND UASD_ID=',CARD_ID,')'));
  PREPARE INSERT_CUST_STMT FROM @INSERT_CUST;
  EXECUTE INSERT_CUST_STMT;
  SET @AMIN_ID=(SELECT CONCAT('SELECT MIN(ID)INTO @AMINID FROM ',TEMP_CUST));
  PREPARE AMIN_ID_STMT FROM @AMIN_ID;
  EXECUTE AMIN_ID_STMT;
  SET AMIN_ID= @AMINID;
  SET @AMAX_ID=(SELECT CONCAT('SELECT MAX(ID)INTO @AMAXID FROM ',TEMP_CUST));
  PREPARE AMAX_ID_STMT FROM @AMAX_ID;
  EXECUTE AMAX_ID_STMT;
  SET AMAX_ID=@AMAXID;
  WHILE(AMAX_ID>=AMIN_ID) DO
    SET @SETACTCUSTNAME=(SELECT CONCAT('SELECT CONCAT(CUSTOMER_FIRST_NAME,''-'',CUSTOMER_LAST_NAME)AS CUST_NAME INTO @ACTCUSTOMERNAME FROM CUSTOMER WHERE CUSTOMER_ID=(SELECT CUST_ID FROM ',TEMP_CUST,' WHERE ID=',AMIN_ID,')'));
    PREPARE ACTCUSTNAME_STMT FROM @SETACTCUSTNAME;
    EXECUTE ACTCUSTNAME_STMT;
    IF(AMIN_ID=1)THEN
      SET ACTCUSTNAME=(SELECT CONCAT('',ACTCUSTNAME,'',@ACTCUSTOMERNAME));
      ELSEIF (AMIN_ID!=1)THEN
      SET ACTCUSTNAME=(SELECT CONCAT('',ACTCUSTNAME,', ',@ACTCUSTOMERNAME));
    END IF;
    SET AMIN_ID=AMIN_ID+1;
  END WHILE;
  SET FLAG=(SELECT CONCAT('DUPLICATE CARD (',CARD_NO,') FOR THIS CUSTOMERS (',ACTCUSTNAME,')'));
ELSEIF(CUSTOMER_LOST_VALUE>1)THEN
  SET @INSERT_CUST=(SELECT CONCAT('INSERT INTO ',TEMP_CUST,' (CUST_ID)(SELECT CUSTOMER_ID FROM CUSTOMER_ACCESS_CARD_DETAILS WHERE ACN_ID !=4 AND CACD_VALID_TILL IS NOT NULL AND UASD_ID=',CARD_ID,')'));
  PREPARE INSERT_CUST_STMT FROM @INSERT_CUST;
  EXECUTE INSERT_CUST_STMT;
  SET @LMIN_ID=(SELECT CONCAT('SELECT MIN(ID)INTO @LMINID FROM ',TEMP_CUST));
  PREPARE LMIN_ID_STMT FROM @LMIN_ID;
  EXECUTE LMIN_ID_STMT;
  SET LMIN_ID= @LMINID;
  SET @LMAX_ID=(SELECT CONCAT('SELECT MAX(ID)INTO @LMAXID FROM ',TEMP_CUST));
  PREPARE LMAX_ID_STMT FROM @LMAX_ID;
  EXECUTE LMAX_ID_STMT;
  SET LMAX_ID=@LMAXID;
  WHILE (LMAX_ID>=LMIN_ID) DO
    SET @SETLOSTCUSTNAME=(SELECT CONCAT('SELECT CONCAT(CUSTOMER_FIRST_NAME,''-'',CUSTOMER_LAST_NAME)AS CUST_NAME INTO @LOSTCUSTOMERNAME FROM CUSTOMER WHERE CUSTOMER_ID=(SELECT CUST_ID FROM ',TEMP_CUST,' WHERE ID=',LMIN_ID,')'));
    PREPARE LOSTCUSTNAME_STMT FROM @SETLOSTCUSTNAME;
    EXECUTE LOSTCUSTNAME_STMT;
    IF(LMIN_ID=1)THEN
      SET LOSTCUSTNAME=(SELECT CONCAT('',LOSTCUSTNAME,'',@LOSTCUSTOMERNAME));
      ELSEIF (LMIN_ID!=1)THEN
      SET LOSTCUSTNAME=(SELECT CONCAT('',LOSTCUSTNAME,', ',@LOSTCUSTOMERNAME));
    END IF;
    SET LMIN_ID=LMIN_ID+1;
  END WHILE;
  SET FLAG=(SELECT CONCAT('DUPLICATE CARD (',CARD_NO,') FOR THIS CUSTOMERS (',LOSTCUSTNAME,')'));
END IF;
COMMIT;
END;