--issue no:593 startdate:26/06/2014 enddate:26/06/2014 COMMENT NO:100 DESC:CUSTOMER_LP_DETAILS DONE BY:DHIVYA


-- BEFORE INSERT TRIGGER FOR CUSTOMER_LP_DETAILS
DROP TRIGGER IF EXISTS TRG_CUSTOMER_LP_DETAILS_INSERT_VALIDATION;
CREATE TRIGGER TRG_CUSTOMER_LP_DETAILS_INSERT_VALIDATION
BEFORE INSERT ON CUSTOMER_LP_DETAILS
FOR EACH ROW
BEGIN
    CALL SP_TRG_CUSTOMER_LP_DETAILS_VALIDATION(NEW.CLP_ID,NEW.CUSTOMER_ID,NEW.CED_REC_VER,NEW.UASD_ID,NEW.CLP_STARTDATE,NEW.CLP_ENDDATE,NEW.CLP_PRETERMINATE_DATE,NEW.CLP_TERMINATE,NEW.CLP_GUEST_CARD,'INSERT');
END;