--issue no:593 startdate:26/06/2014 enddate:26/06/2014 COMMENT NO:100 DESC:VALIDATION FOR CUSTOMER_ENTRY_DETAILS DONE BY:DHIVYA


-- BEFORE INSERT TRIGGER FOR CUSTOMER_ACCESS_CARD_DETAILS
DROP TRIGGER IF EXISTS TRG_CUSTOMER_ENTRY_DETAILS_INSERT_VALIDATION;
CREATE TRIGGER TRG_CUSTOMER_ENTRY_DETAILS_INSERT_VALIDATION
BEFORE INSERT ON CUSTOMER_ENTRY_DETAILS
FOR EACH ROW
BEGIN
	CALL SP_TRG_CUSTOMER_ENTRY_DETAILS_VALIDATION(NEW.CED_ID,NEW.CUSTOMER_ID,NEW.CED_REC_VER,'INSERT');
END;