-- version:0.1 --sdate:25-06-2014 --edate:25-06-2014 --issue:593 --commentno#75 --desc:TRIGGER FOR BEFORE INSERT --doneby:DHIVYA


-- TRIGGER FOR BEFORE UPDATE VALIDATION

DROP TRIGGER IF EXISTS TRG_BIZDLY_STARHUB_UPDATE_VALIDATION;
CREATE TRIGGER TRG_BIZDLY_STARHUB_UPDATE_VALIDATION
BEFORE UPDATE ON EXPENSE_STARHUB
FOR EACH ROW
BEGIN
    CALL SP_TRG_BIZDLY_EXPENSE_STARHUB_VALIDATION(NEW.ESH_INVOICE_DATE,NEW.ESH_FROM_PERIOD,NEW.ESH_TO_PERIOD,NEW.EDSH_ID,'UPDATE');
END;