-- VER 0.2 ISSUE NO:593  STARTDATE:26/06/2014 ENDDATE:26/06/2014 DESC:CHANGING TRIGGER NAME DONE BY:SASIKALA
-- VER 0.1 ISSUE NO:593  STARTDATE:25/06/2014 ENDDATE:25/06/2014 DESC:TRIGGER FOR CALLING SP ON THROWING ERROR MESSAGE  DONE BY:SASIKALA

DROP TRIGGER IF EXISTS TRG_BIZDLY_PURCHASE_NEW_CARD_INSERT_VALIDATION;
CREATE TRIGGER TRG_BIZDLY_PURCHASE_NEW_CARD_INSERT_VALIDATION
BEFORE INSERT ON EXPENSE_PURCHASE_NEW_CARD
FOR EACH ROW  
BEGIN
    CALL SP_TRG_BIZDLY_PURCHASE_NEW_CARD_VALIDATION(NEW.EPNC_NUMBER,NEW.UNIT_ID,NEW.EPNC_INVOICE_DATE,'INSERT');
END;