-- version:0.1 --sdate:25-06-2014 --edate:25-06-2014 --issue:593 --commentno#75 --desc:TRIGGER FOR BEFORE INSERT --doneby:DHIVYA


-- TRIGGER FOR BEFORE UPDATE VALIDATION

DROP TRIGGER IF EXISTS TRG_BIZDLY_ELECTRICITY_UPDATE_VALIDATION;
CREATE TRIGGER TRG_BIZDLY_ELECTRICITY_UPDATE_VALIDATION
BEFORE UPDATE ON EXPENSE_ELECTRICITY
FOR EACH ROW
BEGIN
	CALL SP_TRG_BIZDLY_EXPENSE_ELECTRICITY_VALIDATION(NEW.EE_INVOICE_DATE,NEW.EE_FROM_PERIOD,NEW.EE_TO_PERIOD,NEW.EDE_ID,NEW.ECN_ID,'UPDATE');
END;


