-- version:1.3 -- sdate:09/06/2014 -- edate:09/06/2014 -- issue:566 --comment no#12 --desc:IMPLEMENTED ROLLBACK AND COMMIT --done by:DHIVYA
-- version:1.2 -- sdate:23/05/2014 -- edate:23/05/2014 -- issue:765 --comment no#157 --desc:ADDED CGN_ID 76 IN CUSTOMER CONFIGURATION TABLE --done by:RL
-- version:1.1 -- sdate:12/05/2014 -- edate:12/05/2014 -- issue:765 --desc:changed insert query order for expense_configuration --COMMENTNO#110 --done by:RL
-- version:1.0 -- sdate:08/05/2014 -- edate:08/05/2014 -- issue:765 --desc:added 1 insert query for insert values in expense configuration table --COMMENTNO#110 --done by:RL
-- version:0.9 -- sdate:10/04/2014 -- edate:10/04/2014 -- issue:765 --desc:added SCDB  1/4/2014 TIME STAMP FOR ALL SS RECORDS --done by:RL
-- version:0.8 --sdate:01/04/2014 --edate:01/04/2014 --issue:765 --commentno#53 --desc:SPLIT THE CONFIG MIG  SP INTO 4 PART. --dONEBY:RL
-- version:0.7 --sdate:28/03/2013 --edate:28/03/2014 --issue:783 --desc:changed ALL FOREIGN KEY REFERENCES TABLE SHOULD IN DESTINATION SCHEMA --doneby:RL
--VER:0.6 STARTDATE:28/03/2014 ENDDATE:28/03/2014 ISSUENO:783 DESC:CHANGED THE SP:SP_MIG_CONFIG_INSERT  REMOVED THE DESTINATION SCHEMA IN POST_AUDIT_HISTORY DONE BY:LALITHA
--VER:0.5 STARTDATE:25/03/2014 ENDDATE:25/03/2014 ISSUENO:765 COMMENTNO:#8 DESC:CHANGED THE SP:SP_MIG_CONFIG_INSERT CHANGED THE SCHEMA FOR INSERTION IN POST AUDIT HISTORY AND UPDATION IN PRE AUDIT SUB PROFILE  DONE BY:LALITHA
-- version:0.4 -- sdate:20/03/2014 -- edate:22/03/2014 -- issue:765 -- desc:Changed the SP:SP_MIG_CONFIG_INSERT As prepared stmt for dynamic running purpose --Doneby:Lalitha
-- version:0.3 -- sdate:17/03/2014 -- edate:17/03/2014 -- issue:765 -- desc:droped temp table -- doneby:RL
-- version:0.2 -- sdate:25/02/2014 -- edate:25/02/2014 -- issue:750 -- desc:getting userstamp n time stamp from db & userstamp changed as uld_id -- doneby:RL
-- version:0.1 -- sdate:20/02/2014 -- edate:21/02/2014 -- issue:750 -- desc:Implementing audit table insert -- doneby:RL
DROP PROCEDURE IF EXISTS SP_MIG_CONFIG_INSERT1;
CREATE PROCEDURE SP_MIG_CONFIG_INSERT1(IN SOURCESCHEMA  VARCHAR(40),IN DESTINATIONSCHEMA  VARCHAR(40),IN MIGUSERSTAMP VARCHAR(50))
BEGIN

-- DECLARING VARIABLES
	DECLARE START_TIME TIME;
	DECLARE END_TIME TIME;
	DECLARE DURATION TIME;
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
	ROLLBACK;
	END;
	START TRANSACTION;
	
	SET FOREIGN_KEY_CHECKS=0;

-- QUERY FOR CHANGING USERSTAMP AS ULD_ID
    SET @LOGIN_ID=(SELECT CONCAT('SELECT ULD_ID INTO @ULDID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=','"',MIGUSERSTAMP,'"'));
    PREPARE LOGINID FROM @LOGIN_ID;
    EXECUTE LOGINID;

-- 1.QUERY FOR CREATE TEMP_CUSTOMER_CONFIGURATION
	
	SET START_TIME = (SELECT CURTIME());
	
	SET @DROP_TEMP_CUSTOMER_CONFIGURATION=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_CONFIGURATION'));
	PREPARE DROP_TEMP_CUSTOMER_CONFIGURATION_STMT FROM @DROP_TEMP_CUSTOMER_CONFIGURATION;
    EXECUTE DROP_TEMP_CUSTOMER_CONFIGURATION_STMT;
	
	SET @CREATE_TEMP_CUSTOMER_CONFIGURATION=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_CONFIGURATION(
	TCCN_ID INTEGER NOT NULL AUTO_INCREMENT,
	CGN_ID INTEGER NOT NULL,
	TCCN_DATA TEXT NOT NULL,
	TCCN_INITIALIZE_FLAG CHAR(1) NULL,
	TCCN_USERSTAMP VARCHAR(50)NULL,
	TCCN_TIMESTAMP VARCHAR(50),
	PRIMARY KEY(TCCN_ID),
	FOREIGN KEY(CGN_ID) REFERENCES ',DESTINATIONSCHEMA,'.CONFIGURATION(CGN_ID))'));
	PREPARE CREATE_TEMP_CUSTOMER_CONFIGURATION_STMT FROM @CREATE_TEMP_CUSTOMER_CONFIGURATION;
    EXECUTE CREATE_TEMP_CUSTOMER_CONFIGURATION_STMT;

-- QUERY FOR INSERT TEMP_CUSTOMER_CONFIGURATION
	SET @INSERT_TEMP_CUSTOMER_CONFIGURATION=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_CONFIGURATION(TCCN_DATA,CGN_ID,TCCN_INITIALIZE_FLAG,TCCN_USERSTAMP,TCCN_TIMESTAMP) 
	(SELECT DISTINCT(DATA),CGN_ID,INITIALIZE_FLAG,TCSCDB.USERSTAMP,TCSCDB.TIMESTAMP FROM ',SOURCESCHEMA,'.CONFIG_SQL_FORMAT CSQL  LEFT JOIN ',DESTINATIONSCHEMA,'.TEMP_CONFIG_SCDB_FORMAT TCSCDB ON CSQL.DATA = TCSCDB.CF_DATA WHERE CSQL.DATA IS NOT NULL AND CGN_ID IN (1,2,3,4,5,6,7,8,9,10,11,12,13,14,33,39,47,50,53,54,75,76))'));
    PREPARE INSERT_TEMP_CUSTOMER_CONFIGURATION_STMT FROM @INSERT_TEMP_CUSTOMER_CONFIGURATION;
    EXECUTE INSERT_TEMP_CUSTOMER_CONFIGURATION_STMT;

-- QUERY FOR UPDATE TEMP_CUSTOMER_CONFIGURATION
	SET @UPDATE_TEMP_CUSTOMER_CONFIGURATION=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_CONFIGURATION SET TCCN_USERSTAMP=''expatsintegrated@gmail.com'' WHERE TCCN_USERSTAMP IS NULL'));
    PREPARE UPDATE_TEMP_CUSTOMER_CONFIGURATION_STMT FROM @UPDATE_TEMP_CUSTOMER_CONFIGURATION;
    EXECUTE UPDATE_TEMP_CUSTOMER_CONFIGURATION_STMT;
	
	SET @TSTAMP = (SELECT CONCAT('SELECT DISTINCT(TIMESTAMP) INTO @T_STAMP FROM ',SOURCESCHEMA,'.CONFIG_SQL_FORMAT WHERE CGN_ID=2'));
	PREPARE TSTAMPSTMT FROM @TSTAMP;
	EXECUTE TSTAMPSTMT;
	
-- QUERY FOR UPDATE TEMP_CUSTOMER_CONFIGURATION
	SET @UPDATE_TEMP_CUSTOMERCONFIGURATION=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_CONFIGURATION SET TCCN_TIMESTAMP=@T_STAMP WHERE TCCN_TIMESTAMP IS NULL'));
    PREPARE UPDATE_TEMP_CUSTOMERCONFIGURATIONSTMT FROM @UPDATE_TEMP_CUSTOMERCONFIGURATION;
    EXECUTE UPDATE_TEMP_CUSTOMERCONFIGURATIONSTMT;

-- QUERY FOR DROP CUSTOMER_CONFIGURATION
	SET @DROP_CUSTOMER_CONFIGURATION=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.CUSTOMER_CONFIGURATION'));
	PREPARE DROP_CUSTOMER_CONFIGURATIONSTMT FROM @DROP_CUSTOMER_CONFIGURATION;
    EXECUTE DROP_CUSTOMER_CONFIGURATIONSTMT;

-- QUERY FOR CREATE CUSTOMER_CONFIGURATION
	SET @CREATE_CUSTOMER_CONFIGURATION=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.CUSTOMER_CONFIGURATION(
	CCN_ID INTEGER NOT NULL AUTO_INCREMENT,
	CGN_ID INTEGER NOT NULL,
	CCN_DATA TEXT NOT NULL,
	CCN_INITIALIZE_FLAG	CHAR(1) NULL,
	ULD_ID INTEGER(2) NOT NULL,
	CCN_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(CCN_ID),FOREIGN KEY(CGN_ID) REFERENCES ',DESTINATIONSCHEMA,'.CONFIGURATION(CGN_ID),
	FOREIGN KEY(ULD_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS(ULD_ID))'));
	PREPARE CREATE_CUSTOMER_CONFIGURATION_STMT FROM @CREATE_CUSTOMER_CONFIGURATION;
	EXECUTE CREATE_CUSTOMER_CONFIGURATION_STMT;

-- QUERY FOR INSERT VALUES IN CUSTOMER_CONFIGURATION TABLE
	SET @INSERT_CUSTOMER_CONFIGURATION=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.CUSTOMER_CONFIGURATION(CCN_DATA,CGN_ID,CCN_INITIALIZE_FLAG,ULD_ID,CCN_TIMESTAMP)
	(SELECT TCCN.TCCN_DATA,TCCN.CGN_ID,TCCN.TCCN_INITIALIZE_FLAG,ULD.ULD_ID,TCCN.TCCN_TIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_CONFIGURATION TCCN, ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS ULD WHERE ULD.ULD_LOGINID=TCCN.TCCN_USERSTAMP)'));
	PREPARE INSERT_CUSTOMER_CONFIGURATION_STMT FROM @INSERT_CUSTOMER_CONFIGURATION;
    EXECUTE INSERT_CUSTOMER_CONFIGURATION_STMT;

-- QUERY FOR DROP TEMP_CUSTOMER_CONFIGURATION
	SET @DROP_TEMP_CUSTOMER_CONFIGURATION=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_CONFIGURATION'));
	PREPARE DROP_TEMP_CUSTOMER_CONFIGURATION_STMT FROM @DROP_TEMP_CUSTOMER_CONFIGURATION;
    EXECUTE DROP_TEMP_CUSTOMER_CONFIGURATION_STMT;
	
	SET END_TIME = (SELECT CURTIME());
	
	SET DURATION=(SELECT TIMEDIFF(END_TIME,START_TIME));

-- COUNT CHECKING FOR CUSTOMER_CONFIGURATION DETAILS
	SET @COUNTCUSTOMERCONFIGURATIONSQLFORMAT=(SELECT CONCAT('SELECT COUNT(DATA) INTO @COUNT_CUSTOMER_CONFIGURATION_SQL_FORMAT FROM ',SOURCESCHEMA,'.CONFIG_SQL_FORMAT CSQL  LEFT JOIN ',DESTINATIONSCHEMA,'.TEMP_CONFIG_SCDB_FORMAT TCSCDB ON CSQL.DATA = TCSCDB.CF_DATA WHERE CSQL.DATA IS NOT NULL AND CGN_ID IN (1,2,3,4,5,6,7,8,9,10,11,12,13,14,33,39,47,50,53,54,75,76)'));
	PREPARE COUNTCUSTOMERCONFIGURATIONSQLFORMATSTMT FROM @COUNTCUSTOMERCONFIGURATIONSQLFORMAT;
    EXECUTE COUNTCUSTOMERCONFIGURATIONSQLFORMATSTMT;

-- COUNT SPLITING FOR CUSTOMER_CONFIGURATION DETAILS
	SET @COUNTSPLITINGCUSTOMERCONFIGURATION=(SELECT CONCAT('SELECT COUNT(*) INTO @COUNT_SPLITING_CUSTOMER_CONFIGURATION FROM ',DESTINATIONSCHEMA,'.CUSTOMER_CONFIGURATION'));
	PREPARE COUNTSPLITINGCUSTOMERCONFIGURATIONSTMT FROM @COUNTSPLITINGCUSTOMERCONFIGURATION;
    EXECUTE COUNTSPLITINGCUSTOMERCONFIGURATIONSTMT;
	
	SET @REJECTION_COUNT=(@COUNT_CUSTOMER_CONFIGURATION_SQL_FORMAT-@COUNT_SPLITING_CUSTOMER_CONFIGURATION);		

-- QUERY FOR INSERT VALUES IN POST_AUDIT_HISTORY TABLE

	SET @POSTAPID= (SELECT POSTAP_ID FROM POST_AUDIT_PROFILE WHERE POSTAP_DATA='CUSTOMER_CONFIGURATION');
	
	SET @PREASPID = (SELECT PREASP_ID FROM PRE_AUDIT_SUB_PROFILE WHERE PREASP_DATA='CUSTOMER_CONFIGURATION');
	
	SET @PREAMPID = (SELECT PREAMP_ID FROM PRE_AUDIT_MAIN_PROFILE WHERE PREAMP_DATA='CONFIGURATION');
	
	SET @DUR=DURATION;
    
-- QUERY FOR UPDATE VALUES IN PRE_AUDIT_SUB_PROFILE TABLE	
	UPDATE PRE_AUDIT_SUB_PROFILE SET PREASP_NO_OF_REC=@COUNT_CUSTOMER_CONFIGURATION_SQL_FORMAT WHERE PREASP_DATA='CUSTOMER_CONFIGURATION';	
	
	INSERT INTO POST_AUDIT_HISTORY(POSTAP_ID,POSTAH_NO_OF_REC,PREASP_ID,PREAMP_ID,POSTAH_DURATION,POSTAH_NO_OF_REJ,ULD_ID)VALUES
	(@POSTAPID,@COUNT_SPLITING_CUSTOMER_CONFIGURATION,@PREASPID,@PREAMPID,@DUR,@REJECTION_COUNT,@ULDID);  
	
-- 2.QUERY FOR CREATE UNIT_CONFIGURATION
	
	SET START_TIME = (SELECT CURTIME());
	
	SET @DROP_UNIT_CONFIGURATION=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.UNIT_CONFIGURATION'));
	PREPARE DROP_UNIT_CONFIGURATION_STMT FROM @DROP_UNIT_CONFIGURATION;
    EXECUTE DROP_UNIT_CONFIGURATION_STMT;
	
	SET @CREATE_UNIT_CONFIGURATION=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.UNIT_CONFIGURATION(
	UCN_ID INTEGER NOT NULL AUTO_INCREMENT,
	CGN_ID INTEGER NOT NULL,
	UCN_DATA TEXT NOT NULL,
	UCN_INITIALIZE_FLAG	CHAR(1) NULL,
	ULD_ID INTEGER(2) NOT NULL,
	UCN_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(UCN_ID),
	FOREIGN KEY(CGN_ID) REFERENCES ',DESTINATIONSCHEMA,'.CONFIGURATION(CGN_ID),
	FOREIGN KEY(ULD_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS(ULD_ID))'));
	PREPARE CREATE_UNIT_CONFIGURATION_STMT FROM @CREATE_UNIT_CONFIGURATION;
    EXECUTE CREATE_UNIT_CONFIGURATION_STMT;

-- QUERY FOR INSERT VALUES IN UNIT_CONFIGURATION TABLE
	SET @INSERT_UNIT_CONFIGURATION=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.UNIT_CONFIGURATION(CGN_ID,UCN_DATA,UCN_INITIALIZE_FLAG,UCN_TIMESTAMP,ULD_ID) 
	(SELECT CSQL.CGN_ID,CSQL.DATA,CSQL.INITIALIZE_FLAG,CSQL.TIMESTAMP,ULD.ULD_ID FROM ',SOURCESCHEMA,'.CONFIG_SQL_FORMAT CSQL,',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS ULD WHERE  CSQL.DATA IS NOT NULL AND CSQL.CGN_ID=32 AND CSQL.USER_STAMP=ULD.ULD_LOGINID)'));
	PREPARE INSERT_UNIT_CONFIGURATION_STMT FROM @INSERT_UNIT_CONFIGURATION;
    EXECUTE INSERT_UNIT_CONFIGURATION_STMT;
	
	SET END_TIME = (SELECT CURTIME());
	
	SET DURATION=(SELECT TIMEDIFF(END_TIME,START_TIME));

-- COUNT CHECKING FOR UNIT_CONFIGURATION DETAILS
	SET @COUNTUNITCONFIGURATIONSQLFORMAT=(SELECT CONCAT('SELECT COUNT(DATA) INTO @COUNT_UNIT_CONFIGURATION_SQL_FORMAT FROM ',SOURCESCHEMA,'.CONFIG_SQL_FORMAT WHERE DATA IS NOT NULL AND CGN_ID=32'));
	PREPARE COUNTUNITCONFIGURATIONSQLFORMAT_STMT FROM @COUNTUNITCONFIGURATIONSQLFORMAT;
    EXECUTE COUNTUNITCONFIGURATIONSQLFORMAT_STMT;

-- COUNT SPLITING FOR UNIT_CONFIGURATION TABLE
	SET @COUNTSPLITINGUNITCONFIGURATION =(SELECT CONCAT('SELECT COUNT(*) INTO @COUNT_SPLITING_UNIT_CONFIGURATION FROM ',DESTINATIONSCHEMA,'.UNIT_CONFIGURATION'));
	PREPARE COUNTSPLITINGUNITCONFIGURATION_STMT FROM @COUNTSPLITINGUNITCONFIGURATION;
    EXECUTE COUNTSPLITINGUNITCONFIGURATION_STMT;
	
	SET @REJECTION_COUNT=(@COUNT_UNIT_CONFIGURATION_SQL_FORMAT-@COUNT_SPLITING_UNIT_CONFIGURATION);

-- QUERY FOR INSERT VALUES IN POST_AUDIT_HISTORY TABLE	

	SET @POSTAPID= (SELECT POSTAP_ID FROM POST_AUDIT_PROFILE WHERE POSTAP_DATA='UNIT_CONFIGURATION');
	
	SET @PREASPID = (SELECT PREASP_ID FROM PRE_AUDIT_SUB_PROFILE WHERE PREASP_DATA='UNIT_CONFIGURATION');
	
	SET @PREAMPID = (SELECT PREAMP_ID FROM PRE_AUDIT_MAIN_PROFILE WHERE PREAMP_DATA='CONFIGURATION');
	
	SET @DUR=DURATION;
    
-- QUERY FOR UPDATE VALUES IN PRE_AUDIT_SUB_PROFILE TABLE
	UPDATE PRE_AUDIT_SUB_PROFILE SET PREASP_NO_OF_REC=@COUNT_UNIT_CONFIGURATION_SQL_FORMAT WHERE PREASP_DATA='UNIT_CONFIGURATION';	
	
	INSERT INTO POST_AUDIT_HISTORY(POSTAP_ID,POSTAH_NO_OF_REC,PREASP_ID,PREAMP_ID,POSTAH_DURATION,POSTAH_NO_OF_REJ,ULD_ID)VALUES
	(@POSTAPID,@COUNT_SPLITING_UNIT_CONFIGURATION,@PREASPID,@PREAMPID,@DUR,@REJECTION_COUNT,@ULDID); 

-- 3.QUERY FOR CREATE TEMP_PAYMENT_CONFIGURATION
	SET START_TIME = (SELECT CURTIME());
	
	SET @DROP_TEMP_PAYMENT_CONFIGURATION=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_PAYMENT_CONFIGURATION'));
	PREPARE DROP_TEMP_PAYMENT_CONFIGURATION_STMT FROM @DROP_TEMP_PAYMENT_CONFIGURATION;
    EXECUTE DROP_TEMP_PAYMENT_CONFIGURATION_STMT;
	
	SET @CREATE_TEMP_PAYMENT_CONFIGURATION=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.TEMP_PAYMENT_CONFIGURATION(
	TPCN_ID INTEGER NOT NULL AUTO_INCREMENT,
	CGN_ID INTEGER NOT NULL,
	TPCN_DATA TEXT NOT NULL,
	TPCN_INITIALIZE_FLAG CHAR(1) NULL,
	TPCN_USERSTAMP VARCHAR(50) NULL,
	TPCN_TIMESTAMP VARCHAR(50),
	PRIMARY KEY(TPCN_ID),
	FOREIGN KEY(CGN_ID) REFERENCES ',DESTINATIONSCHEMA,'.CONFIGURATION(CGN_ID))'));
	PREPARE CREATE_TEMP_PAYMENT_CONFIGURATION_STMT FROM @CREATE_TEMP_PAYMENT_CONFIGURATION;
    EXECUTE CREATE_TEMP_PAYMENT_CONFIGURATION_STMT;

-- QUERY FOR INSERT VALUES IN TEMP_PAYMENT_CONFIGURATION TABLE	
	SET @INSERT_TEMP_PAYMENT_CONFIGURATION=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_PAYMENT_CONFIGURATION(TPCN_DATA,CGN_ID,TPCN_INITIALIZE_FLAG,TPCN_USERSTAMP,TPCN_TIMESTAMP)
	(SELECT DISTINCT(DATA),CGN_ID,INITIALIZE_FLAG,TCSCDB.USERSTAMP,TCSCDB.TIMESTAMP FROM ',SOURCESCHEMA,'.CONFIG_SQL_FORMAT CSQL  LEFT JOIN ',DESTINATIONSCHEMA,'.TEMP_CONFIG_SCDB_FORMAT TCSCDB ON CSQL.DATA = TCSCDB.CF_DATA WHERE CSQL.DATA IS NOT NULL AND CGN_ID IN (28,49,58))'));
    PREPARE INSERT_TEMP_PAYMENT_CONFIGURATION_STMT FROM @INSERT_TEMP_PAYMENT_CONFIGURATION;
    EXECUTE INSERT_TEMP_PAYMENT_CONFIGURATION_STMT;

-- QUERY FOR UPDATE VALUES IN TEMP_PAYMENT_CONFIGURATION TABLE		
	SET @UPDATE_TEMP_PAYMENT_CONFIGURATION=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_PAYMENT_CONFIGURATION SET TPCN_USERSTAMP=''expatsintegrated@gmail.com'' WHERE TPCN_USERSTAMP IS NULL'));
    PREPARE UPDATE_TEMP_PAYMENT_CONFIGURATION_STMT FROM @UPDATE_TEMP_PAYMENT_CONFIGURATION;
    EXECUTE UPDATE_TEMP_PAYMENT_CONFIGURATION_STMT;
	
	SET @TSTAMP = (SELECT CONCAT('SELECT DISTINCT(TIMESTAMP) INTO @T_STAMP FROM ',SOURCESCHEMA,'.CONFIG_SQL_FORMAT WHERE CGN_ID=2'));
	PREPARE TSTAMPSTMT FROM @TSTAMP;
	EXECUTE TSTAMPSTMT;
	
-- QUERY FOR UPDATE TEMP_PAYMENT_CONFIGURATION
	SET @UPDATE_TEMP_PAYMENTCONFIGURATION=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_PAYMENT_CONFIGURATION SET TPCN_TIMESTAMP=@T_STAMP WHERE TPCN_TIMESTAMP IS NULL'));
    PREPARE UPDATE_TEMP_PAYMENTCONFIGURATIONSTMT FROM @UPDATE_TEMP_PAYMENTCONFIGURATION;
    EXECUTE UPDATE_TEMP_PAYMENTCONFIGURATIONSTMT;

-- QUERY FOR DROP PAYMENT_CONFIGURATION
	SET @DROP_PAYMENT_CONFIGURATION=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.PAYMENT_CONFIGURATION'));
	PREPARE DROP_PAYMENT_CONFIGURATION_STMT FROM @DROP_PAYMENT_CONFIGURATION;
    EXECUTE DROP_PAYMENT_CONFIGURATION_STMT;

-- QUERY FOR CREATE PAYMENT_CONFIGURATION
	SET @CREATE_PAYMENT_CONFIGURATION=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.PAYMENT_CONFIGURATION(
	PCN_ID INTEGER NOT NULL AUTO_INCREMENT,
	CGN_ID INTEGER NOT NULL,
	PCN_DATA TEXT NOT NULL,
	PCN_INITIALIZE_FLAG	CHAR(1) NULL,
	ULD_ID INTEGER(2) NOT NULL,
	PCN_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(PCN_ID),
	FOREIGN KEY(CGN_ID) REFERENCES ',DESTINATIONSCHEMA,'.CONFIGURATION(CGN_ID),
	FOREIGN KEY(ULD_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS(ULD_ID))'));
	PREPARE CREATE_PAYMENT_CONFIGURATION_STMT FROM @CREATE_PAYMENT_CONFIGURATION;
    EXECUTE CREATE_PAYMENT_CONFIGURATION_STMT;

-- QUERY FOR INSERT VALUES IN PAYMENT_CONFIGURATION TABLE
	SET @INSERT_PAYMENT_CONFIGURATION=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.PAYMENT_CONFIGURATION(PCN_DATA,CGN_ID,PCN_INITIALIZE_FLAG,ULD_ID,PCN_TIMESTAMP)
	(SELECT  TPCN.TPCN_DATA,TPCN.CGN_ID,TPCN.TPCN_INITIALIZE_FLAG,ULD.ULD_ID,TPCN.TPCN_TIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_PAYMENT_CONFIGURATION TPCN , ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS ULD WHERE  ULD.ULD_LOGINID=TPCN.TPCN_USERSTAMP)'));
	PREPARE INSERT_PAYMENT_CONFIGURATION_STMT FROM @INSERT_PAYMENT_CONFIGURATION;
    EXECUTE INSERT_PAYMENT_CONFIGURATION_STMT;

-- QUERY FOR CREATE TEMP_PAYMENT_CONFIGURATION
	SET @DROP_TEMP_PAYMENT_CONFIGURATION=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_PAYMENT_CONFIGURATION'));
	PREPARE DROP_TEMP_PAYMENT_CONFIGURATION_STMT FROM @DROP_TEMP_PAYMENT_CONFIGURATION;
    EXECUTE DROP_TEMP_PAYMENT_CONFIGURATION_STMT;
	
	SET END_TIME = (SELECT CURTIME());
	
	SET DURATION=(SELECT TIMEDIFF(END_TIME,START_TIME));

-- COUNT CHECKING FOR PAYMENT_CONFIGURATION DETAILS
	SET @COUNTPAYMENTCONFIGURATIONSQLFORMAT=(SELECT CONCAT('SELECT COUNT(DATA) INTO @COUNT_PAYMENT_CONFIGURATION_SQL_FORMAT FROM ',SOURCESCHEMA,'.CONFIG_SQL_FORMAT CSQL  LEFT JOIN ',DESTINATIONSCHEMA,'. TEMP_CONFIG_SCDB_FORMAT TCSCDB ON CSQL.DATA = TCSCDB.CF_DATA WHERE CSQL.DATA IS NOT NULL AND CGN_ID IN (28,49,58)'));
	PREPARE COUNTPAYMENTCONFIGURATIONSQLFORMAT_STMT FROM @COUNTPAYMENTCONFIGURATIONSQLFORMAT;
    EXECUTE COUNTPAYMENTCONFIGURATIONSQLFORMAT_STMT;

-- COUNT SPLITING FOR PAYMENT_CONFIGURATION DETAILS
	SET @COUNTSPLITINGPAYMENTCONFIGURATION=(SELECT CONCAT('SELECT COUNT(*) INTO @COUNT_SPLITING_PAYMENT_CONFIGURATION FROM ',DESTINATIONSCHEMA,'.PAYMENT_CONFIGURATION'));
	PREPARE COUNTSPLITINGPAYMENTCONFIGURATION_STMT FROM @COUNTSPLITINGPAYMENTCONFIGURATION;
    EXECUTE COUNTSPLITINGPAYMENTCONFIGURATION_STMT;
	
	SET @REJECTION_COUNT=(@COUNT_PAYMENT_CONFIGURATION_SQL_FORMAT-@COUNT_SPLITING_PAYMENT_CONFIGURATION);			

-- QUERY FOR INSERT VALUES IN POST_AUDIT_HISTORY TABLE
    SET @POSTAPID= (SELECT POSTAP_ID FROM POST_AUDIT_PROFILE WHERE POSTAP_DATA='PAYMENT_CONFIGURATION');
	
	SET @PREASPID = (SELECT PREASP_ID FROM PRE_AUDIT_SUB_PROFILE WHERE PREASP_DATA='PAYMENT_CONFIGURATION');
	
	SET @PREAMPID = (SELECT PREAMP_ID FROM PRE_AUDIT_MAIN_PROFILE WHERE PREAMP_DATA='CONFIGURATION');
	
	SET @DUR=DURATION;

-- QUERY FOR UPDATE VALUES IN PRE_AUDIT_SUB_PROFILE TABLE
	UPDATE PRE_AUDIT_SUB_PROFILE SET PREASP_NO_OF_REC=@COUNT_PAYMENT_CONFIGURATION_SQL_FORMAT WHERE PREASP_DATA='PAYMENT_CONFIGURATION';	
	
	INSERT INTO POST_AUDIT_HISTORY(POSTAP_ID,POSTAH_NO_OF_REC,PREASP_ID,PREAMP_ID,POSTAH_DURATION,POSTAH_NO_OF_REJ,ULD_ID)VALUES
	(@POSTAPID,@COUNT_SPLITING_PAYMENT_CONFIGURATION,@PREASPID,@PREAMPID,@DUR,@REJECTION_COUNT,@ULDID);

-- 4.QUERY FOR CREATE ACCESS_CONFIGURATION
	SET START_TIME = (SELECT CURTIME());
	
	SET @DROP_ACCESS_CONFIGURATION=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.ACCESS_CONFIGURATION'));
	PREPARE DROP_ACCESS_CONFIGURATION_STMT FROM @DROP_ACCESS_CONFIGURATION;
    EXECUTE DROP_ACCESS_CONFIGURATION_STMT;
	
	SET @CREATE_ACCESS_CONFIGURATION=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.ACCESS_CONFIGURATION(
	ACN_ID INTEGER NOT NULL AUTO_INCREMENT,
	CGN_ID INTEGER NOT NULL,
	ACN_DATA TEXT NOT NULL,
	ACN_INITIALIZE_FLAG	CHAR(1) NULL,
	ULD_ID INTEGER(2) NOT NULL,
	ACN_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(ACN_ID),
	FOREIGN KEY(CGN_ID) REFERENCES ',DESTINATIONSCHEMA,'.CONFIGURATION(CGN_ID),
	FOREIGN KEY(ULD_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS(ULD_ID))'));
	PREPARE CREATE_ACCESS_CONFIGURATION_STMT FROM @CREATE_ACCESS_CONFIGURATION;
    EXECUTE CREATE_ACCESS_CONFIGURATION_STMT;

-- QUERY FOR INSERT VALUES IN ACCESS_CONFIGURATION TABLE
	SET @INSERT_ACCESS_CONFIGURATION=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.ACCESS_CONFIGURATION(ACN_DATA,CGN_ID,ACN_INITIALIZE_FLAG,ULD_ID,ACN_TIMESTAMP)(SELECT DISTINCT(CSQL.DATA),CSQL.CGN_ID,CSQL.INITIALIZE_FLAG,ULD.ULD_ID,TCSCDB.TIMESTAMP FROM ',SOURCESCHEMA,'.CONFIG_SQL_FORMAT CSQL  LEFT JOIN ',DESTINATIONSCHEMA,'.TEMP_CONFIG_SCDB_FORMAT TCSCDB ON CSQL.DATA = TCSCDB.CF_DATA , ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS ULD  WHERE CSQL.DATA IS NOT NULL AND CGN_ID IN (16,17) AND ULD.ULD_LOGINID=TCSCDB.USERSTAMP ORDER BY CGN_ID)'));
	PREPARE INSERT_ACCESS_CONFIGURATION_STMT FROM @INSERT_ACCESS_CONFIGURATION;
    EXECUTE INSERT_ACCESS_CONFIGURATION_STMT;
	
	SET END_TIME = (SELECT CURTIME());
	
	SET DURATION=(SELECT TIMEDIFF(END_TIME,START_TIME));

-- COUNT CHECKING FOR ACCESS_CONFIGURATION DETAILS
	SET @COUNTACCESSCONFIGURATIONSQLFORMAT=(SELECT CONCAT('SELECT COUNT(DATA) INTO @COUNT_ACCESS_CONFIGURATION_SQL_FORMAT FROM ',SOURCESCHEMA,'.CONFIG_SQL_FORMAT CSQL  LEFT JOIN ',DESTINATIONSCHEMA,'.TEMP_CONFIG_SCDB_FORMAT TCSCDB ON CSQL.DATA = TCSCDB.CF_DATA WHERE CSQL.DATA IS NOT NULL AND CGN_ID IN (16,17)'));
	PREPARE COUNTACCESSCONFIGURATIONSQLFORMAT_STMT FROM @COUNTACCESSCONFIGURATIONSQLFORMAT;
    EXECUTE COUNTACCESSCONFIGURATIONSQLFORMAT_STMT;

-- COUNT SPLITING FOR ACCESS_CONFIGURATION DETAILS
	SET @COUNTSPLITINGACCESSCONFIGURATION=(SELECT CONCAT('SELECT COUNT(*) INTO @COUNT_SPLITING_ACCESS_CONFIGURATION FROM ',DESTINATIONSCHEMA,'.ACCESS_CONFIGURATION'));
	PREPARE COUNTSPLITINGACCESSCONFIGURATION_STMT FROM @COUNTSPLITINGACCESSCONFIGURATION;
    EXECUTE COUNTSPLITINGACCESSCONFIGURATION_STMT;

	SET @REJECTION_COUNT=(@COUNT_ACCESS_CONFIGURATION_SQL_FORMAT-@COUNT_SPLITING_ACCESS_CONFIGURATION);

-- QUERY FOR INSERT VALUES IN POST_AUDIT_HISTORY TABLE
    SET @POSTAPID= (SELECT POSTAP_ID FROM POST_AUDIT_PROFILE WHERE POSTAP_DATA='ACCESS_CONFIGURATION');
	
	SET @PREASPID = (SELECT PREASP_ID FROM PRE_AUDIT_SUB_PROFILE WHERE PREASP_DATA='ACCESS_CONFIGURATION');
	
	SET @PREAMPID = (SELECT PREAMP_ID FROM PRE_AUDIT_MAIN_PROFILE WHERE PREAMP_DATA='CONFIGURATION');
	
	SET @DUR=DURATION;

-- QUERY FOR UPDATE VALUES IN PRE_AUDIT_SUB_PROFILE TABLE	
	UPDATE PRE_AUDIT_SUB_PROFILE SET PREASP_NO_OF_REC=@COUNT_ACCESS_CONFIGURATION_SQL_FORMAT WHERE PREASP_DATA='ACCESS_CONFIGURATION';	

	INSERT INTO POST_AUDIT_HISTORY(POSTAP_ID,POSTAH_NO_OF_REC,PREASP_ID,PREAMP_ID,POSTAH_DURATION,POSTAH_NO_OF_REJ,ULD_ID)VALUES(@POSTAPID,@COUNT_SPLITING_ACCESS_CONFIGURATION,@PREASPID,@PREAMPID,@DUR,@REJECTION_COUNT,@ULDID);  

-- 5.QUERY FOR CREATE OCBC_CONFIGURATION
	SET START_TIME = (SELECT CURTIME());
	
	SET @DROP_OCBC_CONFIGURATION=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.OCBC_CONFIGURATION'));
	PREPARE DROP_OCBC_CONFIGURATION_STMT FROM @DROP_OCBC_CONFIGURATION;
    EXECUTE DROP_OCBC_CONFIGURATION_STMT;
	
	SET @CREATE_OCBC_CONFIGURATION=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.OCBC_CONFIGURATION(
	OCN_ID INTEGER NOT NULL AUTO_INCREMENT,
	CGN_ID INTEGER NOT NULL,
	OCN_DATA TEXT NOT NULL,
	OCN_INITIALIZE_FLAG	CHAR(1) NULL,
	ULD_ID INTEGER(2) NOT NULL,
	OCN_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(OCN_ID),
	FOREIGN KEY(CGN_ID) REFERENCES ',DESTINATIONSCHEMA,'.CONFIGURATION(CGN_ID),
	FOREIGN KEY(ULD_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS(ULD_ID))'));
	PREPARE CREATE_OCBC_CONFIGURATION_STMT FROM @CREATE_OCBC_CONFIGURATION;
    EXECUTE CREATE_OCBC_CONFIGURATION_STMT;

-- QUERY FOR INSERT VALUES IN OCBC_CONFIGURATION TABLE
	SET @INSERT_OCBC_CONFIGURATION=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.OCBC_CONFIGURATION(OCN_DATA,CGN_ID,OCN_INITIALIZE_FLAG,ULD_ID,OCN_TIMESTAMP)
	(SELECT DISTINCT(CSQL.DATA),CSQL.CGN_ID,CSQL.INITIALIZE_FLAG,ULD.ULD_ID,TCSCDB.TIMESTAMP FROM ',SOURCESCHEMA,'.CONFIG_SQL_FORMAT CSQL  LEFT JOIN ',DESTINATIONSCHEMA,'.TEMP_CONFIG_SCDB_FORMAT TCSCDB ON CSQL.DATA = TCSCDB.CF_DATA , ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS ULD WHERE CSQL.DATA IS NOT NULL AND CGN_ID=29 AND ULD.ULD_LOGINID=TCSCDB.USERSTAMP)'));
	PREPARE INSERT_OCBC_CONFIGURATION_STMT FROM @INSERT_OCBC_CONFIGURATION;
    EXECUTE INSERT_OCBC_CONFIGURATION_STMT;
	
	SET END_TIME = (SELECT CURTIME());
	
	SET DURATION=(SELECT TIMEDIFF(END_TIME,START_TIME));

-- COUNT CHECKING FOR OCBC_CONFIGURATION DETAILS
	SET @COUNTOCBCCONFIGURATIONSQLFORMAT=(SELECT CONCAT('SELECT COUNT(DATA) INTO @COUNT_OCBC_CONFIGURATION_SQL_FORMAT FROM ',SOURCESCHEMA,'.CONFIG_SQL_FORMAT CSQL  LEFT JOIN ',DESTINATIONSCHEMA,'.TEMP_CONFIG_SCDB_FORMAT TCSCDB ON CSQL.DATA = TCSCDB.CF_DATA WHERE CSQL.DATA IS NOT NULL AND CSQL.CGN_ID=29'));
	PREPARE COUNTOCBCCONFIGURATIONSQLFORMAT_STMT FROM @COUNTOCBCCONFIGURATIONSQLFORMAT;
    EXECUTE COUNTOCBCCONFIGURATIONSQLFORMAT_STMT;

-- COUNT SPLITING FOR OCBC_CONFIGURATION DETAILS
	SET @COUNTSPLITINGOCBCCONFIGURATION=(SELECT CONCAT('SELECT COUNT(*) INTO @COUNT_SPLITING_OCBC_CONFIGURATION FROM ',DESTINATIONSCHEMA,'.OCBC_CONFIGURATION'));
	PREPARE COUNTSPLITINGOCBCCONFIGURATION_STMT FROM @COUNTSPLITINGOCBCCONFIGURATION;
    EXECUTE COUNTSPLITINGOCBCCONFIGURATION_STMT;
	
	SET @REJECTION_COUNT=(@COUNT_OCBC_CONFIGURATION_SQL_FORMAT-@COUNT_SPLITING_OCBC_CONFIGURATION);

-- QUERY FOR INSERT VALUES IN POST_AUDIT_HISTORY TABLE
	SET @POSTAPID= (SELECT POSTAP_ID FROM POST_AUDIT_PROFILE WHERE POSTAP_DATA='OCBC_CONFIGURATION');
	
	SET @PREASPID = (SELECT PREASP_ID FROM PRE_AUDIT_SUB_PROFILE WHERE PREASP_DATA='OCBC_CONFIGURATION');
	
	SET @PREAMPID = (SELECT PREAMP_ID FROM PRE_AUDIT_MAIN_PROFILE WHERE PREAMP_DATA='CONFIGURATION');
	
	SET @DUR=DURATION;

	UPDATE PRE_AUDIT_SUB_PROFILE SET PREASP_NO_OF_REC=@COUNT_OCBC_CONFIGURATION_SQL_FORMAT WHERE PREASP_DATA='OCBC_CONFIGURATION';	

	INSERT INTO POST_AUDIT_HISTORY(POSTAP_ID,POSTAH_NO_OF_REC,PREASP_ID,PREAMP_ID,POSTAH_DURATION,POSTAH_NO_OF_REJ,ULD_ID)VALUES
	(@POSTAPID,@COUNT_SPLITING_OCBC_CONFIGURATION,@PREASPID,@PREAMPID,@DUR,@REJECTION_COUNT,@ULDID);

-- 6.QUERY FOR CREATE TEMP_EXPENSE_CONFIGURATION
	SET START_TIME = (SELECT CURTIME());
	
	SET @DROP_TEMP_EXPENSE_CONFIGURATION=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_CONFIGURATION'));
	PREPARE DROP_TEMP_EXPENSE_CONFIGURATION_STMT FROM @DROP_TEMP_EXPENSE_CONFIGURATION;
    EXECUTE DROP_TEMP_EXPENSE_CONFIGURATION_STMT;
	
	SET @CREATE_TEMP_EXPENSE_CONFIGURATION=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_CONFIGURATION(
	TECN_ID INTEGER NOT NULL AUTO_INCREMENT,
	CGN_ID INTEGER NOT NULL,
	TECN_DATA TEXT NOT NULL,
	TECN_INITIALIZE_FLAG CHAR(1) NULL,
	TECN_USERSTAMP VARCHAR(50) NULL,
	TECN_TIMESTAMP VARCHAR(50),
	PRIMARY KEY(TECN_ID),
	FOREIGN KEY(CGN_ID) REFERENCES ',DESTINATIONSCHEMA,'.CONFIGURATION(CGN_ID))'));
	PREPARE CREATE_TEMP_EXPENSE_CONFIGURATION_STMT FROM @CREATE_TEMP_EXPENSE_CONFIGURATION;
    EXECUTE CREATE_TEMP_EXPENSE_CONFIGURATION_STMT;

-- QUERY FOR INSERT VALUES IN TEMP_EXPENSE_CONFIGURATION TABLE	
	SET @INSERT_TEMP_EXPENSE_CONFIGURATION=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_CONFIGURATION(TECN_DATA,CGN_ID,TECN_INITIALIZE_FLAG,TECN_USERSTAMP,TECN_TIMESTAMP)
	(SELECT DISTINCT(DATA),CGN_ID,INITIALIZE_FLAG,TCSCDB.USERSTAMP,TCSCDB.TIMESTAMP FROM ',SOURCESCHEMA,'.CONFIG_SQL_FORMAT CSQL  LEFT JOIN ',DESTINATIONSCHEMA,'.TEMP_CONFIG_SCDB_FORMAT TCSCDB ON CSQL.DATA = TCSCDB.CF_DATA 
	WHERE CSQL.DATA IS NOT NULL AND CGN_ID IN(18,19,27,20,26,21,22,23,24,25) AND DATA!="MIGRATED")'));
    PREPARE INSERT_TEMP_EXPENSE_CONFIGURATION_STMT FROM @INSERT_TEMP_EXPENSE_CONFIGURATION;
    EXECUTE INSERT_TEMP_EXPENSE_CONFIGURATION_STMT;
	
-- QUERY FOR INSERT VALUES IN TEMP_EXPENSE_CONFIGURATION TABLE	
	SET @INSERT_TEMP_EXPENSECONFIGURATION=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_CONFIGURATION(TECN_DATA,CGN_ID,TECN_INITIALIZE_FLAG,TECN_USERSTAMP,TECN_TIMESTAMP)
	(SELECT DATA,CGN_ID,INITIALIZE_FLAG,USER_STAMP,TIMESTAMP FROM ',SOURCESCHEMA,'.CONFIG_SQL_FORMAT 
	WHERE DATA IS NOT NULL AND CGN_ID IN(34,35,36,37,38,40,20,41,51,52) AND (DATA!="COMMON" AND DATA!="CUSTOMER" AND DATA!="GENERAL"))'));
    PREPARE INSERT_TEMP_EXPENSE_CONFIGURATIONSTMT FROM @INSERT_TEMP_EXPENSECONFIGURATION;
    EXECUTE INSERT_TEMP_EXPENSE_CONFIGURATIONSTMT;

-- QUERY FOR UPDATE VALUES IN TEMP_EXPENSE_CONFIGURATION TABLE		
	SET @UPDATE_TEMP_EXPENSE_CONFIGURATION=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_CONFIGURATION SET TECN_USERSTAMP=''expatsintegrated@gmail.com'' WHERE TECN_USERSTAMP IS NULL'));
    PREPARE UPDATE_TEMP_EXPENSE_CONFIGURATION_STMT FROM @UPDATE_TEMP_EXPENSE_CONFIGURATION;
    EXECUTE UPDATE_TEMP_EXPENSE_CONFIGURATION_STMT;
	
	SET @TSTAMP = (SELECT CONCAT('SELECT DISTINCT(TIMESTAMP) INTO @T_STAMP FROM ',SOURCESCHEMA,'.CONFIG_SQL_FORMAT WHERE CGN_ID=2'));
	PREPARE TSTAMPSTMT FROM @TSTAMP;
	EXECUTE TSTAMPSTMT;
	
-- QUERY FOR UPDATE TEMP_EXPENSE_CONFIGURATION
	SET @UPDATE_TEMP_EXPENSECONFIGURATION=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_CONFIGURATION SET TECN_TIMESTAMP=@T_STAMP WHERE TECN_TIMESTAMP IS NULL'));
    PREPARE UPDATE_TEMP_EXPENSECONFIGURATIONSTMT FROM @UPDATE_TEMP_EXPENSECONFIGURATION;
    EXECUTE UPDATE_TEMP_EXPENSECONFIGURATIONSTMT;

-- QUERY FOR DROP EXPENSE_CONFIGURATION	
	SET @DROP_EXPENSE_CONFIGURATION=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.EXPENSE_CONFIGURATION'));
	PREPARE DROP_EXPENSE_CONFIGURATION_STMT FROM @DROP_EXPENSE_CONFIGURATION;
    EXECUTE DROP_EXPENSE_CONFIGURATION_STMT;

-- QUERY FOR CREATE EXPENSE_CONFIGURATION
	SET @CREATE_EXPENSE_CONFIGURATION=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.EXPENSE_CONFIGURATION(
	ECN_ID INTEGER NOT NULL AUTO_INCREMENT,
	CGN_ID INTEGER NOT NULL,
	ECN_DATA TEXT NOT NULL,
	ECN_INITIALIZE_FLAG	CHAR(1) NULL,
	ULD_ID INTEGER(2) NOT NULL,
	ECN_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(ECN_ID),
	FOREIGN KEY(CGN_ID) REFERENCES ',DESTINATIONSCHEMA,'.CONFIGURATION(CGN_ID),
	FOREIGN KEY(ULD_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS(ULD_ID))'));
    PREPARE CREATE_EXPENSE_CONFIGURATION_STMT FROM @CREATE_EXPENSE_CONFIGURATION;
    EXECUTE CREATE_EXPENSE_CONFIGURATION_STMT;

-- QUERY FOR INSERT VALUES IN EXPENSE_CONFIGURATION TABLE
	SET @INSERT_EXPENSE_CONFIGURATION=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.EXPENSE_CONFIGURATION(ECN_DATA,CGN_ID,ECN_INITIALIZE_FLAG,ULD_ID,ECN_TIMESTAMP)
	(SELECT TECN.TECN_DATA,TECN.CGN_ID,TECN.TECN_INITIALIZE_FLAG,ULD.ULD_ID,TECN.TECN_TIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_CONFIGURATION TECN , ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS ULD WHERE ULD.ULD_LOGINID=TECN.TECN_USERSTAMP)'));
	PREPARE INSERT_EXPENSE_CONFIGURATION_STMT FROM @INSERT_EXPENSE_CONFIGURATION;
    EXECUTE INSERT_EXPENSE_CONFIGURATION_STMT;

-- QUERY FOR DROP TEMP_EXPENSE_CONFIGURATION
    SET @DROP_TEMP_EXPENSE_CONFIGURATION=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_CONFIGURATION'));
	PREPARE DROP_TEMP_EXPENSE_CONFIGURATION_STMT FROM @DROP_TEMP_EXPENSE_CONFIGURATION;
    EXECUTE DROP_TEMP_EXPENSE_CONFIGURATION_STMT;
	
	SET END_TIME = (SELECT CURTIME());
	
	SET DURATION=(SELECT TIMEDIFF(END_TIME,START_TIME));

-- COUNT CHECKING FOR EXPENSE_CONFIGURATION DETAILS
	SET @COUNTEXPENSECONFIGURATIONSQLFORMAT=(SELECT CONCAT('SELECT COUNT(DATA) INTO @COUNT_EXPENSE_CONFIGURATION_SQL_FORMAT FROM ',SOURCESCHEMA,'.CONFIG_SQL_FORMAT CSQL  WHERE DATA IS NOT NULL AND CGN_ID IN(18,19,20,21,22,23,24,25,26,27,34,35,36,37,38,40,41,51,52)'));
	PREPARE COUNTEXPENSECONFIGURATIONSQLFORMAT_STMT FROM @COUNTEXPENSECONFIGURATIONSQLFORMAT;
    EXECUTE COUNTEXPENSECONFIGURATIONSQLFORMAT_STMT;

-- COUNT SPLITING FOR EXPENSE_CONFIGURATION DETAILS
    SET @COUNTSPLITINGEXPENSECONFIGURATION=(SELECT CONCAT('SELECT COUNT(*) INTO @COUNT_SPLITING_EXPENSE_CONFIGURATION FROM ',DESTINATIONSCHEMA,'.EXPENSE_CONFIGURATION'));
	PREPARE COUNTSPLITINGEXPENSECONFIGURATION_STMT FROM @COUNTSPLITINGEXPENSECONFIGURATION;
    EXECUTE COUNTSPLITINGEXPENSECONFIGURATION_STMT;

	SET @REJECTION_COUNT=(@COUNT_EXPENSE_CONFIGURATION_SQL_FORMAT-@COUNT_SPLITING_EXPENSE_CONFIGURATION);		
-- QUERY FOR INSERT VALUES IN POST_AUDIT_HISTORY TABLE
	SET @POSTAPID= (SELECT POSTAP_ID FROM POST_AUDIT_PROFILE WHERE POSTAP_DATA='EXPENSE_CONFIGURATION');
	
	SET @PREASPID = (SELECT PREASP_ID FROM PRE_AUDIT_SUB_PROFILE WHERE PREASP_DATA='EXPENSE_CONFIGURATION');
	
	SET @PREAMPID = (SELECT PREAMP_ID FROM PRE_AUDIT_MAIN_PROFILE WHERE PREAMP_DATA='CONFIGURATION');
	
	SET @DUR=DURATION;
-- QUERY FOR UPDATE VALUES IN PRE_AUDIT_SUB_PROFILE TABLE
	UPDATE PRE_AUDIT_SUB_PROFILE SET PREASP_NO_OF_REC=@COUNT_EXPENSE_CONFIGURATION_SQL_FORMAT WHERE PREASP_DATA='EXPENSE_CONFIGURATION';	
	
	INSERT INTO POST_AUDIT_HISTORY(POSTAP_ID,POSTAH_NO_OF_REC,PREASP_ID,PREAMP_ID,POSTAH_DURATION,POSTAH_NO_OF_REJ,ULD_ID)VALUES
	(@POSTAPID,@COUNT_SPLITING_EXPENSE_CONFIGURATION,@PREASPID,@PREAMPID,@DUR,@REJECTION_COUNT,@ULDID);     

	SET FOREIGN_KEY_CHECKS = 1;
	COMMIT;
END;

CALL SP_MIG_CONFIG_INSERT1(SOURCESCHEMA,DESTINATIONSCHEMA,MIGUSERSTAMP);