--VER 1.0 ISSUE NO:765 STARTDATE:02/06/2014 ENDDATE:02/06/2014 DESC:CHANGED CUSTOMER COMPANY DETAILS QUERY COMMENT:#185 DONE BY:DHIVYA
--VER 0.9 ISSUE NO:765 STARTDATE:22/04/2014 ENDDATE:22/04/2014 DESC:CHANGED TIME ZONE DONE BY:DHIVYA
--VER 0.8 ISSUE NO:795 STARTDATE:02/04/2014 ENDDATE:02/04/2014 DESC:REMOVED VIEW FOR CUSTOMER_COMPANY_DETAILS   DONE BY:DHIVYA
--VER 0.7 ISSUE NO:765 STARTDATE:19/03/2014 ENDDATE:27/03/2014 DESC:DONE CUSTOMER,COMPANY DETAILS DYNAMICALLY DONE BY:DHIVYA
-- version:0.6 -- sdate:17/03/2014 -- edate:17/03/2014 -- issue:765 --desc:droped temp table --doneby:RL
--version:0.5 --sdate:17/03/2014 --edate:17/03/2014 --issue:766 DESC:REMOVED INSERT QUERY OUTSIDE THE SP by:dhivya
--version:0.4 --sdate:25/02/2014 --edate:26/02/2014 --issue:750 comment:#30 -desc:added uld_id header and source timestamp by:dhivya
--version:0.3--sdate:20/02/2014 --edate:20/02/2014 --issue:750 -desc:added preaudit and post audit queries done by:dhivya
--VER 0.2 STARTDATE:21/01/2014 ENDDATE:22/01/2014 ISSUE NO:594 COMMENT :#50 DESC:ALL UPDATION DONE IN THE SPLITTED TABLE ITSELF NOT IN THE CUSTOMER SCDB FORMAT TABLE DONE BY:DHIVYA


DROP PROCEDURE IF EXISTS SP_TEMP_CUSTOMER_SCDB_FORMAT;
CREATE PROCEDURE SP_TEMP_CUSTOMER_SCDB_FORMAT(IN SOURCESCHEMA VARCHAR(50),DESTINATIONSCHEMA VARCHAR(50))
BEGIN

SET @DROPQUERY=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_SCDB_FORMAT'));
PREPARE DROPQUERYSTMT FROM @DROPQUERY;
EXECUTE DROPQUERYSTMT;
SET @CREATEQUERY=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_SCDB_FORMAT(
CC_STARTDATE VARCHAR(255) NULL,
CC_REC_VER INTEGER NULL,
CC_GUEST_CARD_NO VARCHAR(255) NULL,
CC_PROCESSING_FEE VARCHAR(255) NULL,
TIMESTAMP VARCHAR(255) NULL,
CC_DEPOSIT VARCHAR(255) NULL,
CC_COMPANY_ADDR VARCHAR(255) NULL,
CC_PASSPORT_DATE VARCHAR(255) NULL,
CC_CHECKOUT_CLEANING_FEE VARCHAR(255) NULL,
CC_LEASE_PERIOD VARCHAR(255) NULL,
CC_ID INTEGER NULL,
CC_NOTICE_START_DATE VARCHAR(255) NULL,
CC_POSTAL_CODE VARCHAR(255) NULL,
CC_DRYCLEAN_FEE VARCHAR(255) NULL,
SILOID VARCHAR(255) NULL,
CC_FIRST_NAME VARCHAR(255) NULL,
`CC_QUARTERS` VARCHAR(255) NULL,
`CC_NATIONALITY` VARCHAR(255) NULL,
`CC_RENT_AMOUNT` VARCHAR(255) NULL,
`CC_NOTICE_PERIOD` VARCHAR(255) NULL,
`CC_PASSPORT_NO` VARCHAR(255) NULL,
`CC_MOBILE2` VARCHAR(255) NULL,
`CC_EP_NO` VARCHAR(255) NULL,
`CC_CARD_NO` VARCHAR(255) NULL,
`CC_ROOMTYPE` VARCHAR(255) NULL,
`CC_CUST_ID` INTEGER NULL,
`CC_EXTENSION` VARCHAR(255) NULL,
`CC_ELECTRICITY_CAP` VARCHAR(255) NULL,
`CC_COMPANY_NAME` VARCHAR(255) NULL,
`CC_MOBILE` VARCHAR(255) NULL,
`CC_AIRCON_FIXED_FEE` VARCHAR(255) NULL,
`CC_DOB` VARCHAR(255) NULL,
`CC_EMAIL` VARCHAR(255) NULL,
`CC_CANCEL_DATE` VARCHAR(255) NULL,
`CC_COMMENTS` TEXT NULL,
`CC_TERMINATE` VARCHAR(255) NULL,
`CC_UNIT_NO` VARCHAR(255) NULL,
`CC_EP_DATE` VARCHAR(255) NULL,
`CC_ENDDATE` VARCHAR(255) NULL,
`CC_LAST_NAME` VARCHAR(255) NULL,
`CC_PRETERMINATE` VARCHAR(255) NULL,
`CC_OFFICE_NO` VARCHAR(255) NULL,
`CC_AIRCON_QUARTERLY_FEE` VARCHAR(255) NULL,
`USERSTAMP` VARCHAR(255) NULL,
`CC_PRE_TERMINATE_DATE` VARCHAR(255) NULL,
 CC_PROCESSING_WAIVED VARCHAR(255) NULL)'));
PREPARE CREATEQUERYSTMT FROM @CREATEQUERY;
EXECUTE CREATEQUERYSTMT;
SET @INSERTQUERY=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_SCDB_FORMAT SELECT * FROM ',SOURCESCHEMA,'.CUSTOMER_SCDB_FORMAT'));
PREPARE INSERTQUERYSTMT FROM @INSERTQUERY;
EXECUTE INSERTQUERYSTMT;
SET @UPDATENAME=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_SCDB_FORMAT SET cc_last_name=cc_first_name WHERE cc_last_name IS NULL'));
PREPARE UPDATENAMESTMT FROM @UPDATENAME;
EXECUTE UPDATENAMESTMT;
SET @UPDATEROOMTYPESTUDIO1=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_SCDB_FORMAT SET cc_roomtype=',"'Studio1'" ,' WHERE cc_roomtype=',"'STUDIO 1'"));
PREPARE UPDATEROOMTYPESTUDIO1STMT FROM @UPDATEROOMTYPESTUDIO1;
EXECUTE UPDATEROOMTYPESTUDIO1STMT;
SET @UPDATEROOMTYPESTUDIO2=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_SCDB_FORMAT SET cc_roomtype=',"'Studio2'",' WHERE cc_roomtype=',"'STUDIO 2'"));
PREPARE UPDATEROOMTYPESTUDIO2STMT FROM @UPDATEROOMTYPESTUDIO2;
EXECUTE UPDATEROOMTYPESTUDIO2STMT;
SET @UPDATENATIONALITY=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_SCDB_FORMAT SET CC_NATIONALITY =',"'SINGAPORE'",' WHERE CC_NATIONALITY IS NULL'));
PREPARE UPDATENATIONALITYSTMT FROM @UPDATENATIONALITY;
EXECUTE UPDATENATIONALITYSTMT;
SET @UPDATEEMAIL=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_SCDB_FORMAT SET CC_EMAIL=',"'expatsintegrated@gmail.com'",' WHERE CC_EMAIL IS NULL'));
PREPARE UPDATEEMAILSTMT FROM @UPDATEEMAIL;
EXECUTE UPDATEEMAILSTMT;
SET @UPDATENATIONALITYSPAIN=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_SCDB_FORMAT SET CC_NATIONALITY=',"'SPAIN'", ' WHERE  CC_NATIONALITY LIKE ', "'SPAIN%'"));
PREPARE UPDATENATIONALITYSPAINSTMT FROM @UPDATENATIONALITYSPAIN;
EXECUTE UPDATENATIONALITYSPAINSTMT;
SET @UPDATENATTHAILAND=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_SCDB_FORMAT SET CC_NATIONALITY=',"'THAILAND'", ' WHERE  CC_NATIONALITY LIKE ', "'THAILAND%'"));
PREPARE UPDATENATTHAILANDSTMT FROM @UPDATENATTHAILAND;
EXECUTE UPDATENATTHAILANDSTMT;
SET @UPDATERENT=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_SCDB_FORMAT SET CC_RENT_AMOUNT=2650 WHERE  CC_ID=479'));
PREPARE UPDATERENTSTMT FROM @UPDATERENT;
EXECUTE UPDATERENTSTMT;
SET @UPDATETIMESTAMP=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_SCDB_FORMAT SET TIMESTAMP=(SELECT CONVERT_TZ(TIMESTAMP, "+08:00","+0:00"))'));
PREPARE UPDATETIMESTAMPSTMT FROM @UPDATETIMESTAMP;
EXECUTE UPDATETIMESTAMPSTMT;
END;



DROP PROCEDURE IF EXISTS SP_MIG_CUSTOMER_INSERT;
CREATE PROCEDURE SP_MIG_CUSTOMER_INSERT(IN SOURCESCHEMA VARCHAR(50),IN DESTINATIONSCHEMA VARCHAR(50),IN MIGUSERSTAMP VARCHAR(100))
BEGIN
DECLARE START_TIME TIME;
DECLARE END_TIME TIME;
DECLARE DURATION TIME;
SET @SSCHEMA=SOURCESCHEMA;
SET @DSCHEMA=DESTINATIONSCHEMA;
	SET FOREIGN_KEY_CHECKS=0;
	SET @LOGIN_ID=(SELECT CONCAT('SELECT ULD_ID INTO @ULDID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=','"',MIGUSERSTAMP,'"'));
	PREPARE LOGINID FROM @LOGIN_ID;
	EXECUTE LOGINID;
	SET @CALL_CUS_SCDB_FORMAT=(SELECT CONCAT('CALL ',SOURCESCHEMA,'.SP_TEMP_CUSTOMER_SCDB_FORMAT(@SSCHEMA,@DSCHEMA)'));
	PREPARE CALLCUSSCDBFORMAT FROM @CALL_CUS_SCDB_FORMAT;
	EXECUTE CALLCUSSCDBFORMAT;
    SET @DROP_MIG_CUSTOMER=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_MIG_CUSTOMER'));
	PREPARE DMIGCUSTOMER FROM @DROP_MIG_CUSTOMER;
	EXECUTE DMIGCUSTOMER;
	SET @CREATE_MIG_CUSTOMER=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.TEMP_MIG_CUSTOMER(CUSTOMERID INTEGER,CUSTOMER_FIRST_NAME CHAR(30),CUSTOMER_LAST_NAME CHAR(30))'));
	PREPARE CMIGCUSTOMER FROM @CREATE_MIG_CUSTOMER;
	EXECUTE CMIGCUSTOMER;
	SET @INSERT_MIG_CUSTOMER=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_MIG_CUSTOMER(CUSTOMERID,CUSTOMER_FIRST_NAME,CUSTOMER_LAST_NAME)SELECT DISTINCT(CC_CUST_ID),CC_FIRST_NAME,CC_LAST_NAME FROM 
	CUSTOMER_SCDB_FORMAT'));
	PREPARE INMIGCUSTOMER FROM @INSERT_MIG_CUSTOMER;
	EXECUTE INMIGCUSTOMER;
	SET @UPDATE_MIG_CUSTOMER=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_MIG_CUSTOMER SET CUSTOMER_LAST_NAME=CUSTOMER_FIRST_NAME WHERE CUSTOMER_LAST_NAME IS NULL'));
	PREPARE UPMIGCUSTOMER FROM @UPDATE_MIG_CUSTOMER;
	EXECUTE UPMIGCUSTOMER;
	SET FOREIGN_KEY_CHECKS=0;
	SET START_TIME=(SELECT CURTIME());
	SET FOREIGN_KEY_CHECKS=0;
	SET @DROPCUSTOMER=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.CUSTOMER'));
	PREPARE DRCUSTOMER FROM @DROPCUSTOMER;
	EXECUTE DRCUSTOMER;
	SET @CREATECUSTOMER=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.CUSTOMER(
	CUSTOMER_ID	INTEGER NOT NULL AUTO_INCREMENT,
	CUSTOMER_FIRST_NAME	CHAR(30) NOT NULL,	
	CUSTOMER_LAST_NAME	CHAR(30) NOT NULL,
	PRIMARY KEY(CUSTOMER_ID))'));
	PREPARE CRCUSTOMER FROM @CREATECUSTOMER;
	EXECUTE CRCUSTOMER;
	SET @INSERTCUSTOMER=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.CUSTOMER SELECT distinct(CUSTOMERID),CUSTOMER_FIRST_NAME,CUSTOMER_LAST_NAME FROM ',
	DESTINATIONSCHEMA,'.TEMP_MIG_CUSTOMER'));
	PREPARE INCUSTOMER FROM @INSERTCUSTOMER;
	EXECUTE INCUSTOMER;
	SET END_TIME=(SELECT CURTIME());
	SET DURATION=(SELECT TIMEDIFF(END_TIME,START_TIME));
	SET @SCDBCUSTOMER=(SELECT CONCAT('SELECT DISTINCT COUNT(DISTINCT(CC_CUST_ID))INTO @COUNT_SCDB_CUSTOMER FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_SCDB_FORMAT WHERE CC_FIRST_NAME IS NOT NULL AND CC_LAST_NAME IS NOT NULL'));
	PREPARE COUNTSCDBCUSTOMER FROM @SCDBCUSTOMER;
	EXECUTE COUNTSCDBCUSTOMER;
	SET @SPLITTEDCUSTOMERCOUNT=(SELECT CONCAT('SELECT COUNT(*)INTO @COUNT_SPLITTED_CUSTOMER FROM ',DESTINATIONSCHEMA,'.CUSTOMER'));
	PREPARE COUNTSPLITTIEDCUSTOMER FROM @SPLITTEDCUSTOMERCOUNT;
	EXECUTE COUNTSPLITTIEDCUSTOMER;
	SET @REJECTION_COUNT=(@COUNT_SCDB_CUSTOMER-@COUNT_SPLITTED_CUSTOMER);
	UPDATE PRE_AUDIT_SUB_PROFILE SET PREASP_NO_OF_REC=@COUNT_SCDB_CUSTOMER WHERE PREASP_DATA='CUSTOMER';
	SET FOREIGN_KEY_CHECKS=0;
    INSERT INTO POST_AUDIT_HISTORY(POSTAP_ID,POSTAH_NO_OF_REC,PREASP_ID,PREAMP_ID,POSTAH_DURATION,POSTAH_NO_OF_REJ,ULD_ID)
	VALUES((SELECT POSTAP_ID FROM POST_AUDIT_PROFILE WHERE POSTAP_DATA='CUSTOMER'),@COUNT_SPLITTED_CUSTOMER,(SELECT PREASP_ID FROM PRE_AUDIT_SUB_PROFILE WHERE PREASP_DATA='CUSTOMER'),
	(SELECT PREAMP_ID FROM PRE_AUDIT_MAIN_PROFILE WHERE PREAMP_DATA='CUSTOMER'),DURATION,@REJECTION_COUNT,@ULDID);
	SET FOREIGN_KEY_CHECKS=0;
	SET START_TIME=(SELECT CURTIME());
	SET @DROPCOMPANYDETAILS=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.CUSTOMER_COMPANY_DETAILS'));
	PREPARE DRCUSTOMERCOMPANY FROM @DROPCOMPANYDETAILS;
	EXECUTE DRCUSTOMERCOMPANY;
	SET @CREATECUSTOMERCOMPANYDETAILS=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.CUSTOMER_COMPANY_DETAILS(
	CCD_ID INTEGER NOT NULL	AUTO_INCREMENT,
	CUSTOMER_ID INTEGER NOT NULL,
	CCD_COMPANY_NAME VARCHAR(50) NULL,	
	CCD_COMPANY_ADDR VARCHAR(50) NULL,	
	CCD_POSTAL_CODE	VARCHAR(6) NULL,	
	CCD_OFFICE_NO VARCHAR(8) NULL,	
	PRIMARY KEY(CCD_ID),
	FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID))'));
	PREPARE CRCUSTOMERCOMPANY FROM @CREATECUSTOMERCOMPANYDETAILS;
	EXECUTE CRCUSTOMERCOMPANY;
	SET @SET_MAX_REC_VER=(SELECT CONCAT('CREATE OR REPLACE VIEW VW_MAX_REC_VER AS SELECT CC_CUST_ID,MAX(CC_REC_VER)AS CC_REC_VER FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_SCDB_FORMAT GROUP BY CC_CUST_ID'));
	PREPARE SET_MAX_REC_VER_STMT FROM @SET_MAX_REC_VER;
	EXECUTE SET_MAX_REC_VER_STMT;
	SET @INSERTCUSTOMERCOMPANY=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.CUSTOMER_COMPANY_DETAILS(CUSTOMER_ID,CCD_COMPANY_NAME,CCD_COMPANY_ADDR,CCD_POSTAL_CODE,
	CCD_OFFICE_NO)
    SELECT  CSF.CC_CUST_ID, CSF.CC_COMPANY_NAME, CSF.CC_COMPANY_ADDR, CSF.CC_POSTAL_CODE, CSF.CC_OFFICE_NO FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_SCDB_FORMAT CSF,VW_MAX_REC_VER VMRV  WHERE (CSF.CC_COMPANY_NAME IS NOT NULL OR CSF.CC_COMPANY_ADDR IS NOT NULL OR CSF.CC_POSTAL_CODE IS NOT NULL OR CSF.CC_OFFICE_NO IS NOT NULL) AND CSF.CC_CUST_ID=VMRV.CC_CUST_ID AND CSF.CC_REC_VER =VMRV.CC_REC_VER'));
	PREPARE INCUSCOMPANY FROM @INSERTCUSTOMERCOMPANY;
	EXECUTE INCUSCOMPANY;
	SET END_TIME=(SELECT CURTIME());
	SET DURATION=(SELECT TIMEDIFF(END_TIME,START_TIME));
	SET @VW_CUS_COMPANY=(SELECT CONCAT('CREATE OR REPLACE VIEW ',DESTINATIONSCHEMA,'.VW_CUSTOMER_COMPANY_DETAILS AS SELECT  CSF.CC_CUST_ID, CSF.CC_COMPANY_NAME, CSF.CC_COMPANY_ADDR, CSF.CC_POSTAL_CODE, CSF.CC_OFFICE_NO FROM ',DESTINATIONSCHEMA,'.TEMP_CUSTOMER_SCDB_FORMAT CSF,VW_MAX_REC_VER VMRV  WHERE (CSF.CC_COMPANY_NAME IS NOT NULL OR CSF.CC_COMPANY_ADDR IS NOT NULL OR CSF.CC_POSTAL_CODE IS NOT NULL OR CSF.CC_OFFICE_NO IS NOT NULL) AND CSF.CC_CUST_ID=VMRV.CC_CUST_ID AND CSF.CC_REC_VER =VMRV.CC_REC_VER'));
	PREPARE VWCUSCOMPANY FROM @VW_CUS_COMPANY;
	EXECUTE VWCUSCOMPANY;
	SET @COUNTSCDBCCD=(SELECT CONCAT('SELECT COUNT(*)INTO @COUNT_SCDB_CCD FROM ',DESTINATIONSCHEMA,'.VW_CUSTOMER_COMPANY_DETAILS'));
	PREPARE COUNTCCD FROM @COUNTSCDBCCD;
	EXECUTE COUNTCCD;
	SET @COUNTSPLITTIEDCCD=(SELECT CONCAT('SELECT COUNT(*)INTO @COUNT_SPLITTIED_CCD FROM ',DESTINATIONSCHEMA,'.CUSTOMER_COMPANY_DETAILS'));
	PREPARE SPLITTEDCCD FROM @COUNTSPLITTIEDCCD;
	EXECUTE SPLITTEDCCD;
	SET @REJECTION_COUNT=(@COUNT_SCDB_CCD-@COUNT_SPLITTIED_CCD);
	UPDATE PRE_AUDIT_SUB_PROFILE SET PREASP_NO_OF_REC=@COUNT_SCDB_CCD WHERE PREASP_DATA='CUSTOMER_COMPANY_DETAILS';
	SET FOREIGN_KEY_CHECKS=0;
	INSERT INTO POST_AUDIT_HISTORY(POSTAP_ID,POSTAH_NO_OF_REC,PREASP_ID,PREAMP_ID,POSTAH_DURATION,POSTAH_NO_OF_REJ,ULD_ID)
	VALUES((SELECT POSTAP_ID FROM POST_AUDIT_PROFILE WHERE POSTAP_DATA='CUSTOMER_COMPANY_DETAILS'),@COUNT_SPLITTIED_CCD,(SELECT PREASP_ID FROM PRE_AUDIT_SUB_PROFILE WHERE PREASP_DATA='CUSTOMER_COMPANY_DETAILS'),
	(SELECT PREAMP_ID FROM PRE_AUDIT_MAIN_PROFILE WHERE PREAMP_DATA='CUSTOMER'),DURATION,@REJECTION_COUNT,@ULDID);
	SET FOREIGN_KEY_CHECKS=1;
	SET @DROPTEMPCUSTOMER=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_MIG_CUSTOMER'));
	PREPARE DRTEMPCUSTOMER FROM @DROPTEMPCUSTOMER;
	EXECUTE DRTEMPCUSTOMER;
	SET @DROPVIEWCUSTOMERCMPANY=(SELECT CONCAT('DROP VIEW IF EXISTS ',DESTINATIONSCHEMA,'.VW_CUSTOMER_COMPANY_DETAILS'));
	PREPARE DROPVIEWCUSTOMERCMPANYSTMT FROM @DROPVIEWCUSTOMERCMPANY;
	EXECUTE DROPVIEWCUSTOMERCMPANYSTMT;
	DROP VIEW IF EXISTS VW_MAX_REC_VER;

END;
