-- version:0.7 -- sdate:09/06/2014 -- edate:09/06/2014 -- issue:566 --COMMENT NO: 12--desc:IMPLEMENTED ROLL BACK AND COMMIT --doneby:DHIVYA
-- version:0.6 -- sdate:24/03/2014 -- edate:26/03/2014 -- issue:765 --COMMENT NO: 8--desc:UPDATED SP DYNAMICALLY --doneby:SAFI
-- version:0.5 -- sdate:17/03/2014 -- edate:17/03/2014 -- issue:765 --desc:droped temp table --doneby:RL
--version:0.4 --sdate:28/02/2014 --edate:28/02/2014 --issue:750 --desc:changed userstamp as ULD_ID and timestamp get from scdb done by:RL
--version:0.3 --sdate:21/02/2014 --edate:21/02/2014 --issue:750 --desc:added preaudit and post audit queries done by:dhivya
--version:0.2 --sdate:21/01/2014 --edate:21/01/2014 --issue:594 --commentno:50 & 54 --doneby:RL
DROP PROCEDURE IF EXISTS SP_EXPENSE_DETAIL_CARPARK_INSERT;
CREATE PROCEDURE SP_EXPENSE_DETAIL_CARPARK_INSERT(IN SOURCESCHEMA  VARCHAR(40),IN DESTINATIONSCHEMA  VARCHAR(40),IN MIGUSERSTAMP VARCHAR(50))
BEGIN
    DECLARE DONE INT DEFAULT FALSE;
	DECLARE UNITNO INTEGER;
    DECLARE CAR_UNIT_ID INTEGER;
	DECLARE CARNO VARCHAR(9);
	DECLARE CAR_MINID INTEGER;
	DECLARE CAR_MAXID INTEGER;	
	DECLARE COMMENTS TEXT;
	DECLARE RECVER INTEGER;
	DECLARE CARPARK_USERSTAMP VARCHAR(50);
	DECLARE CARPARK_TIMESTAMP TIMESTAMP;
	DECLARE START_TIME TIME;
	DECLARE END_TIME TIME;
	DECLARE DURATION TIME;
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
	ROLLBACK;
	END;
	START TRANSACTION;
	SET FOREIGN_KEY_CHECKS=0;
	SET @LOGIN_ID=(SELECT CONCAT('SELECT ULD_ID INTO @ULDID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=','"',MIGUSERSTAMP,'"'));
    PREPARE LOGINID FROM @LOGIN_ID;
    EXECUTE LOGINID;
	SET @DROP_EXPENSE_DETAIL_CARPARK=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_CARPARK'));
    PREPARE DROP_EXPENSE_DETAIL_CARPARK_STMT FROM @DROP_EXPENSE_DETAIL_CARPARK;
    EXECUTE DROP_EXPENSE_DETAIL_CARPARK_STMT;
	SET @CREATE_TEMP_EXPENSE_DETAIL_CARPARK=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_CARPARK(
	ID	INTEGER NOT NULL AUTO_INCREMENT,
	UNIT_NO	INTEGER ,	
	EDCP_CAR_NO	VARCHAR(9) 	,
	EDCP_COMMENTS TEXT NULL,
	EDCP_CARPARK_USERSTAMP VARCHAR(40) ,	
	EDCP_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(ID))'
	));
	PREPARE CREATE_TEMP_EXPENSE_DETAIL_CARPARK_STMT FROM @CREATE_TEMP_EXPENSE_DETAIL_CARPARK;
    EXECUTE CREATE_TEMP_EXPENSE_DETAIL_CARPARK_STMT;	
	SET @SELECT_CAR_PARK=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_CARPARK(UNIT_NO,EDCP_CAR_NO,EDCP_COMMENTS,EDCP_CARPARK_USERSTAMP,EDCP_TIMESTAMP) SELECT EXPD_UNIT_NO,EXPD_CAR_NO,EXPD_COMMENTS,USERSTAMP,TIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_BIZ_DETAIL_SCDB_FORMAT WHERE EXPD_TYPE_OF_EXPENSE=',"'CAR PARK'"));	
	PREPARE SELECT_CAR_PARK_STMT FROM @SELECT_CAR_PARK;
    EXECUTE SELECT_CAR_PARK_STMT;
	SET @DROP_EXPENSE_DETAIL_CARPARK=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.EXPENSE_DETAIL_CARPARK'));
    PREPARE DROP_EXPENSE_DETAIL_CARPARK_STMT FROM @DROP_EXPENSE_DETAIL_CARPARK;
    EXECUTE DROP_EXPENSE_DETAIL_CARPARK_STMT;
	SET @CREATE_EXPENSE_DETAIL_CARPARK=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.EXPENSE_DETAIL_CARPARK(
	EDCP_ID	INTEGER NOT NULL AUTO_INCREMENT,
	UNIT_ID	INTEGER NOT NULL,
	EDCP_REC_VER INTEGER NOT NULL,	
	EDCP_CAR_NO	VARCHAR(9) NOT NULL	,
	EDCP_COMMENTS TEXT NULL,
	ULD_ID INTEGER(2) NOT NULL,	
	EDCP_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(EDCP_ID),
	FOREIGN KEY(UNIT_ID) REFERENCES ',DESTINATIONSCHEMA,'.UNIT (UNIT_ID),
	FOREIGN KEY(ULD_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS (ULD_ID))'));
	PREPARE CREATE_EXPENSE_DETAIL_CARPARK_STMT FROM @CREATE_EXPENSE_DETAIL_CARPARK;
    EXECUTE CREATE_EXPENSE_DETAIL_CARPARK_STMT;	
	SET START_TIME=(SELECT CURTIME());		
	SET @EDCP_MINID=(SELECT CONCAT('SELECT MIN(ID) INTO @MIN_ID FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_CARPARK'));
	PREPARE EDCP_MINID_STMT FROM @EDCP_MINID;
    EXECUTE EDCP_MINID_STMT;
	SET @EDCP_MAXID=(SELECT CONCAT('SELECT MAX(ID) INTO @MAX_ID FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_CARPARK'));
	PREPARE EDCP_MAXID_STMT FROM @EDCP_MAXID;
        EXECUTE EDCP_MAXID_STMT;
		SET CAR_MINID=@MIN_ID;
		SET CAR_MAXID=@MAX_ID;
		WHILE(CAR_MINID<=CAR_MAXID)DO		
		SET @CARUNITID=NULL;
		SET @SELECT_UNITID=(SELECT CONCAT('SELECT  DISTINCT UNIT_ID INTO @CARUNITID FROM ',DESTINATIONSCHEMA,'.EXPENSE_DETAIL_CARPARK WHERE UNIT_ID=(SELECT UNIT_ID FROM ',DESTINATIONSCHEMA,'.UNIT WHERE UNIT_NO=(SELECT UNIT_NO FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_CARPARK WHERE ID=',CAR_MINID,'))'));
		PREPARE SELECT_UNITID_STMT FROM @SELECT_UNITID;
        EXECUTE SELECT_UNITID_STMT;		
		SET CAR_UNIT_ID=@CARUNITID;
		SET @RECVER=1;
		SET @EDCP_COMMENT=NULL;
		 SET @SELECT_COMMENT=(SELECT CONCAT('SELECT EDCP_COMMENTS INTO @EDCP_COMMENT FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_CARPARK WHERE ID=',CAR_MINID));
		 PREPARE SELECT_COMMENT_STMT FROM @SELECT_COMMENT;
        EXECUTE SELECT_COMMENT_STMT;	
		 SET COMMENTS=@EDCP_COMMENT;
		 IF COMMENTS IS NULL THEN
		SET @EDCP_COMMENTS=NULL;		
		ELSE
		SET @EDCP_COMMENTS=COMMENTS;
		END IF;
		SET @CUNIT_ID=NULL;
		SET @SELECT_EDCP_UNITID=(SELECT CONCAT('SELECT UNIT_ID INTO @CUNIT_ID FROM ',DESTINATIONSCHEMA,'.UNIT WHERE UNIT_NO=(SELECT UNIT_NO FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_CARPARK WHERE ID=',CAR_MINID,')'));
		PREPARE SELECT_EDCP_UNITID_STMT FROM @SELECT_EDCP_UNITID;
        EXECUTE SELECT_EDCP_UNITID_STMT;
         SET @EDCP_CAR_NO=NULL;		
		 SET @SELECT_EDCP_CAR_NO=(SELECT CONCAT('SELECT EDCP_CAR_NO INTO @EDCP_CAR_NO FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_CARPARK WHERE ID=',CAR_MINID));
		 PREPARE SELECT_EDCP_CAR_NO_STMT FROM @SELECT_EDCP_CAR_NO;
        EXECUTE SELECT_EDCP_CAR_NO_STMT;
        SET @EDCP_ULD_ID=NULL;		
		SET @SELECT_EDCP_ULDID=(SELECT CONCAT('SELECT ULD_ID INTO @EDCP_ULD_ID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=(SELECT EDCP_CARPARK_USERSTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_CARPARK WHERE ID=',CAR_MINID,')'));
		PREPARE SELECT_EDCP_ULDID_STMT FROM @SELECT_EDCP_ULDID;
		EXECUTE SELECT_EDCP_ULDID_STMT;
        SET @TIMESTAMP=NULL;		
		SET @SELECT_TIMESTAMP=(SELECT CONCAT('SELECT EDCP_TIMESTAMP INTO @TIMESTAMP FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_CARPARK WHERE ID=',CAR_MINID));
		PREPARE SELECT_TIMESTAMP_STMT FROM @SELECT_TIMESTAMP;
		EXECUTE SELECT_TIMESTAMP_STMT;       
		IF CAR_UNIT_ID IS NOT NULL THEN	
            SET @REC_VER=NULL;		
			SET @SELECT_RECVER=(SELECT CONCAT('SELECT MAX(EDCP_REC_VER) INTO @REC_VER FROM ',DESTINATIONSCHEMA,'.EXPENSE_DETAIL_CARPARK WHERE UNIT_ID=(SELECT UNIT_ID FROM ',DESTINATIONSCHEMA,'.UNIT WHERE UNIT_NO=(SELECT UNIT_NO FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_CARPARK WHERE ID=',CAR_MINID,'))'));
			PREPARE SELECT_RECVER_STMT FROM @SELECT_RECVER;
            EXECUTE SELECT_RECVER_STMT;
			SET @RECVER=@REC_VER;
			SET @INSERT_EXPENSE_DETAIL_CARPARK=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.EXPENSE_DETAIL_CARPARK(UNIT_ID,EDCP_REC_VER,EDCP_CAR_NO,EDCP_COMMENTS,ULD_ID,EDCP_TIMESTAMP)VALUES
			(@CUNIT_ID,(@RECVER+1),@EDCP_CAR_NO,@EDCP_COMMENTS,@EDCP_ULD_ID,@TIMESTAMP)'));
			PREPARE INSERT_EXPENSE_DETAIL_CARPARK_STMT FROM @INSERT_EXPENSE_DETAIL_CARPARK;
            EXECUTE INSERT_EXPENSE_DETAIL_CARPARK_STMT;
		ELSE
			SET @INSERT_EXPENSE_DETAIL_CARPARK=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.EXPENSE_DETAIL_CARPARK(UNIT_ID,EDCP_REC_VER,EDCP_CAR_NO,EDCP_COMMENTS,ULD_ID,EDCP_TIMESTAMP)VALUES
			(@CUNIT_ID,@RECVER,@EDCP_CAR_NO,@EDCP_COMMENTS,@EDCP_ULD_ID,@TIMESTAMP)'));
			PREPARE INSERT_EXPENSE_DETAIL_CARPARK_STMT FROM @INSERT_EXPENSE_DETAIL_CARPARK;
            EXECUTE INSERT_EXPENSE_DETAIL_CARPARK_STMT;
			END IF;
			SET @CARUNITID=NULL;
			SET CAR_MINID=CAR_MINID+1;
		END WHILE;
	    SET END_TIME=(SELECT CURTIME());
		SET DURATION=(SELECT TIMEDIFF(END_TIME,START_TIME));
		SET @COUNTSCDB_EDCP=(SELECT CONCAT('SELECT COUNT(*) INTO @COUNT_SCDB_EDCP FROM ',SOURCESCHEMA,'.BIZ_DETAIL_SCDB_FORMAT WHERE EXPD_TYPE_OF_EXPENSE=',"'CAR PARK'"));
		PREPARE COUNTSCDB_EDCP_STMT FROM @COUNTSCDB_EDCP;
        EXECUTE COUNTSCDB_EDCP_STMT;
		SET @COUNTSPLITTED_EDCP=(SELECT CONCAT('SELECT COUNT(*) INTO @COUNT_SPLITTED_EDCP FROM ',DESTINATIONSCHEMA,'.EXPENSE_DETAIL_CARPARK'));
		PREPARE COUNTSPLITTED_EDCP_STMT FROM @COUNTSPLITTED_EDCP;
        EXECUTE COUNTSPLITTED_EDCP_STMT;
		SET @REJECTION_COUNT=(@COUNT_SCDB_EDCP-@COUNT_SPLITTED_EDCP);		
		SET @POSTAPIDSTMT=(SELECT CONCAT('SELECT POSTAP_ID INTO @POSTAPID FROM POST_AUDIT_PROFILE WHERE POSTAP_DATA=',"'EXPENSE_DETAIL_CARPARK'"));
        PREPARE POSTAPSTMT FROM @POSTAPIDSTMT;
        EXECUTE POSTAPSTMT;    
        SET @PREASPSTMT=(SELECT CONCAT('SELECT PREASP_ID INTO @PREASPID FROM PRE_AUDIT_SUB_PROFILE WHERE PREASP_DATA=',"'EXPENSE_DETAIL_CARPARK'"));
        PREPARE PREASPIDSTMT FROM @PREASPSTMT;
        EXECUTE PREASPIDSTMT;    
        SET @PREAMPSTMT=(SELECT CONCAT('SELECT PREAMP_ID INTO @PREAMPID FROM PRE_AUDIT_MAIN_PROFILE WHERE PREAMP_DATA=',"'BIZ DETAIL'"));
        PREPARE PREAMPIDSTMT FROM @PREAMPSTMT;
        EXECUTE PREAMPIDSTMT;        
        SET @DUR = DURATION;   
        SET FOREIGN_KEY_CHECKS=0;
        UPDATE PRE_AUDIT_SUB_PROFILE SET PREASP_NO_OF_REC=@COUNT_SCDB_EDCP WHERE PREASP_DATA='EXPENSE_DETAIL_CARPARK';    
        INSERT INTO POST_AUDIT_HISTORY(POSTAP_ID,POSTAH_NO_OF_REC,PREASP_ID,PREAMP_ID,POSTAH_DURATION,POSTAH_NO_OF_REJ,ULD_ID)
        VALUES(@POSTAPID,@COUNT_SPLITTED_EDCP,@PREASPID,@PREAMPID,@DUR,@REJECTION_COUNT,@ULDID);
        SET FOREIGN_KEY_CHECKS=1;
	   	SET @DROP_EXPENSE_DETAIL_CARPARK=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_DETAIL_CARPARK'));
        PREPARE DROP_EXPENSE_DETAIL_CARPARK_STMT FROM @DROP_EXPENSE_DETAIL_CARPARK;
        EXECUTE DROP_EXPENSE_DETAIL_CARPARK_STMT;	
		SET FOREIGN_KEY_CHECKS=1;
		COMMIT;
END;