--> version 0.8-->startdate:21/06/2014  enddate:21/06/2014-->issueno:817 ,commentno:139-->desc:DROPPED TEMP TABLE DURING ROLLBACK BY PUNI
--> version 0.7-->startdate:18/06/2014  enddate:19/06/2014-->issueno:738 ,commentno:33-->desc:UPDATED ULD ID N TIMESTAMP IN OLD VALUE COL IN TICKLER HISTORY BY PUNI
--> version 0.6-->startdate:03/05/2014  enddate:03/05/2014-->issueno:817 -->desc:CHANGED REACTIVE CUSTOMER SP DYNAMICALLY DONE BY :DHIVYA
-- version:0.5 --startdate:07/04/2014 --enddate:07/04/2014 --issue:797 --commentno#28 --desc:changed REPLACED POSTAP_ID AND TTAP_ID --by RAGHU
-- version:0.4 --startdate:03/04/2014 --enddate:03/04/2014 --issue:797 --commentno#4 --desc:changed REPLACED TABLENAME AND HEADERNAME --by SASIKALA.D
-- version:0.3 --startdate:14/03/2014 --enddate:15/03/2014 --issue:345 --commentno#604 --desc:changed userstamp as uld_id , added confirmation flag , changed temp_tickler_update table as tickler_history n changed header names, tickler history data's r changed as id --by RL
-- version:0.2 --startdate:02/01/2014 --enddate:11/01/2014 --issue:345 --changed the whole sp based on from comment #551 --by PUNI
-- version:0.1 --startdate:24/12/2013 --enddate:24/12/2013 --issue:345 --commentno:539 --doneby:rajalakshmi
DROP PROCEDURE IF EXISTS SP_CUSTOMER_REACTIVE_UPDATE;
CREATE PROCEDURE SP_CUSTOMER_REACTIVE_UPDATE(
IN CUSTID INTEGER,
IN USERSTAMP VARCHAR(50),
OUT FLAG INTEGER
)
BEGIN
-- VARIABLE DECLARATION
	DECLARE TRAC_MAXREC_VER INTEGER;
	DECLARE MINID INTEGER;
	DECLARE MAXID INTEGER;
	DECLARE TICK_OLD_VALUE  TEXT;
	DECLARE TICK_NEW_VALUE  TEXT;
	DECLARE TICK_UNIT_NO  INTEGER;
	DECLARE TICK_REC_VER  INTEGER;
	DECLARE TICK_CARD_NO  VARCHAR(7);
	DECLARE TICK_GUEST_CARD  VARCHAR(10);
	DECLARE TICK_PTD TEXT;
	DECLARE USERSTAMP_ID INTEGER(2);
	DECLARE CTDID INTEGER;
	DECLARE UASDID INTEGER;
	DECLARE TEMP_REACTIVE_CUSTOMER TEXT;
	DECLARE TERM_TEMP_REACTIVE_CUSTOMER TEXT;
-- QUERY FOR ROLLBACK COMMAND	
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN		
		ROLLBACK;
		-- DROP TEMP TABLE START	
		SET @DROP_REACTIVE_CUSTOMER=(SELECT CONCAT('DROP TABLE IF EXISTS ',TEMP_REACTIVE_CUSTOMER));
		PREPARE DROP_REACTIVE_CUSTOMER_STMT FROM @DROP_REACTIVE_CUSTOMER;
		EXECUTE DROP_REACTIVE_CUSTOMER_STMT;
		-- DROP TEMP TABLE END	
		SET FLAG = 0;
	END;
	START TRANSACTION;
	SET FLAG = 0;
-- QUERY FOR CALL SP_CHANGE_USERSTAMP_AS_ULDID		
	CALL SP_CHANGE_USERSTAMP_AS_ULDID(USERSTAMP,@ULDID);
	SET USERSTAMP_ID = (SELECT @ULDID);
-- CRAETE TABLE TEMP_REACTIVE_CUSTOMER TO GET TERMINATED RECORD FOR A CUSTOMER	
	SET TERM_TEMP_REACTIVE_CUSTOMER=(SELECT CONCAT('TEMP_REACTIVE_CUSTOMER','_',SYSDATE()));
	SET TERM_TEMP_REACTIVE_CUSTOMER=(SELECT REPLACE(TERM_TEMP_REACTIVE_CUSTOMER,' ',''));
	SET TERM_TEMP_REACTIVE_CUSTOMER=(SELECT REPLACE(TERM_TEMP_REACTIVE_CUSTOMER,'-',''));
	SET TERM_TEMP_REACTIVE_CUSTOMER=(SELECT REPLACE(TERM_TEMP_REACTIVE_CUSTOMER,':',''));
	SET TEMP_REACTIVE_CUSTOMER=(SELECT CONCAT(TERM_TEMP_REACTIVE_CUSTOMER,'_',USERSTAMP_ID));
	SET @CREATE_REACTIVE_CUSTOMER=(SELECT CONCAT('CREATE TABLE ',TEMP_REACTIVE_CUSTOMER,'(
	ID INTEGER AUTO_INCREMENT NOT NULL,TRAC_CTDID INTEGER,TRAC_CUSTOMERID INTEGER,TRAC_UNITNO INTEGER,TRAC_CARDNO INTEGER,TRAC_RECVER INTEGER,TRAC_STARTDATE DATE,
	TRAC_ENDDATE DATE,TRAC_PRETERMINATEDATE DATE,TRAC_TERMINATE CHAR(1),TRAC_GUESTFLAG CHAR(1),PRIMARY KEY(ID))'));
	PREPARE CREATE_REACTIVE_CUSTOMER_STMT FROM @CREATE_REACTIVE_CUSTOMER;
	EXECUTE CREATE_REACTIVE_CUSTOMER_STMT;
-- INSERT INTO TEMP_REACTIVE_CUSTOMER TABLE & VIEW_RECHECKIN_CUSTOMER TAKING FOR GETTING ACTIVE LEASE PERIOD MIN RECVER	
	SET @INSERT_REACTIVE_CUSTOMER=(SELECT CONCAT('INSERT INTO ',TEMP_REACTIVE_CUSTOMER,'(TRAC_UNITNO,TRAC_CARDNO,TRAC_CTDID,TRAC_CUSTOMERID,TRAC_RECVER,TRAC_STARTDATE,TRAC_ENDDATE,TRAC_PRETERMINATEDATE,
	TRAC_TERMINATE,TRAC_GUESTFLAG) SELECT U.UNIT_NO,UASD.UASD_ACCESS_CARD,CTD.CLP_ID,CTD.CUSTOMER_ID,CTD.CED_REC_VER,CTD.CLP_STARTDATE,CTD.CLP_ENDDATE,CTD.CLP_PRETERMINATE_DATE,
	CTD.CLP_TERMINATE,CTD.CLP_GUEST_CARD FROM CUSTOMER_LP_DETAILS CTD LEFT JOIN UNIT_ACCESS_STAMP_DETAILS UASD ON CTD.UASD_ID=UASD.UASD_ID,
	CUSTOMER_ENTRY_DETAILS CED,UNIT U,VW_RECHECKIN_CUSTOMER VRC WHERE U.UNIT_ID=CED.UNIT_ID AND CED.CUSTOMER_ID=VRC.CUSTOMER_ID AND CED.CED_REC_VER=VRC.CED_REC_VER AND CTD.CUSTOMER_ID=CED.CUSTOMER_ID AND CTD.CED_REC_VER=CED.CED_REC_VER AND 
	CTD.CUSTOMER_ID=',CUSTID,' AND IF(CTD.CLP_PRETERMINATE_DATE IS NOT NULL,CTD.CLP_STARTDATE<CTD.CLP_PRETERMINATE_DATE,
	CTD.CLP_STARTDATE<CTD.CLP_ENDDATE) AND (CTD.CLP_ENDDATE <= CURDATE() OR CTD.CLP_PRETERMINATE_DATE <= CURDATE()) AND CTD.CLP_TERMINATE IS NOT NULL'));
	PREPARE INSERT_REACTIVE_CUSTOMER_STMT FROM @INSERT_REACTIVE_CUSTOMER;
	EXECUTE INSERT_REACTIVE_CUSTOMER_STMT;
	SET @SET_TRAC_MAXREC_VER = (SELECT CONCAT('SELECT MAX(TRAC_RECVER) INTO @TRACMAXRECVER FROM ',TEMP_REACTIVE_CUSTOMER));
	PREPARE SET_TRAC_MAXREC_VER_STMT FROM @SET_TRAC_MAXREC_VER;
	EXECUTE SET_TRAC_MAXREC_VER_STMT;
	SET TRAC_MAXREC_VER=@TRACMAXRECVER;
	SET @SET_MINID = (SELECT CONCAT('SELECT MIN(ID)INTO @MIN_ID FROM ',TEMP_REACTIVE_CUSTOMER,' WHERE TRAC_RECVER=',TRAC_MAXREC_VER));
	PREPARE SET_MINID_STMT FROM @SET_MINID;
	EXECUTE SET_MINID_STMT;
	SET MINID=@MIN_ID;
	SET @SET_MAXID = (SELECT CONCAT('SELECT MAX(ID)INTO @MAX_ID FROM ',TEMP_REACTIVE_CUSTOMER,' WHERE TRAC_RECVER=',TRAC_MAXREC_VER));
	PREPARE SET_MAXID_STMT FROM @SET_MAXID;
	EXECUTE SET_MAXID_STMT;
	SET MAXID=@MAX_ID;
	WHILE(MINID<=MAXID)DO	
-- SET CUSTOMER LP DETAILS TO INSERT INTO TICKLER START	
		SET @SET_TICK_UNIT_NO=(SELECT CONCAT('SELECT TRAC_UNITNO INTO @TICKUNITNO FROM ',TEMP_REACTIVE_CUSTOMER,' WHERE ID=',MINID));
		PREPARE SET_TICK_UNIT_NO_STMT FROM @SET_TICK_UNIT_NO;
		EXECUTE SET_TICK_UNIT_NO_STMT;
		SET TICK_UNIT_NO=@TICKUNITNO;
		SET @SET_TICK_REC_VER=(SELECT CONCAT('SELECT TRAC_RECVER INTO @TICKRECVER FROM ',TEMP_REACTIVE_CUSTOMER,' WHERE ID=',MINID));
		PREPARE SET_TICK_REC_VER_STMT FROM @SET_TICK_REC_VER;
		EXECUTE SET_TICK_REC_VER_STMT;
		SET TICK_REC_VER=@TICKRECVER;
		SET @SET_TICK_GUEST_CARD=(SELECT CONCAT('SELECT TRAC_GUESTFLAG INTO @TRACGUESTFLAG FROM ',TEMP_REACTIVE_CUSTOMER,' WHERE ID=',MINID));
		PREPARE SET_TICK_GUEST_CARD_STMT FROM @SET_TICK_GUEST_CARD;
		EXECUTE SET_TICK_GUEST_CARD_STMT;
		SET TICK_GUEST_CARD=@TRACGUESTFLAG;
		SET @SET_TICK_CARD_NO=(SELECT CONCAT('SELECT TRAC_CARDNO INTO @TRACCARDNO FROM ',TEMP_REACTIVE_CUSTOMER,' WHERE ID=',MINID));
		PREPARE SET_TICK_CARD_NO_STMT FROM @SET_TICK_CARD_NO;
		EXECUTE SET_TICK_CARD_NO_STMT;
		SET TICK_CARD_NO=@TRACCARDNO;
		SET @SET_TICK_PTD=(SELECT CONCAT('SELECT TRAC_PRETERMINATEDATE INTO @TICKPTD FROM ',TEMP_REACTIVE_CUSTOMER,' WHERE ID=',MINID));
		PREPARE SET_TICK_PTD_STMT FROM @SET_TICK_PTD;
		EXECUTE SET_TICK_PTD_STMT;
		SET TICK_PTD=@TICKPTD;
		IF(TICK_CARD_NO IS NOT NULL)THEN
			SET CTDID = (SELECT CLP_ID FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CUSTID AND CED_REC_VER=TICK_REC_VER AND UASD_ID = (SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=TICK_CARD_NO));
			SET UASDID = (SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=TICK_CARD_NO);
		END IF;
		IF(TICK_CARD_NO IS NULL)THEN
			SET CTDID = (SELECT CLP_ID FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID = CUSTID AND CED_REC_VER=TICK_REC_VER);
		END IF;
		IF(TICK_GUEST_CARD IS NULL) THEN
			SET TICK_GUEST_CARD=('null');
		END IF;
		IF(TICK_PTD IS NULL) THEN
			SET TICK_PTD=('null');
		END IF;		
		SET TICK_NEW_VALUE='CLP_TERMINATE=null';
		IF(TICK_CARD_NO IS NOT NULL)THEN
			IF (USERSTAMP_ID!=(SELECT ULD_ID FROM CUSTOMER_LP_DETAILS WHERE CLP_ID=CTDID))THEN
				SET TICK_OLD_VALUE=(SELECT CONCAT('CLP_ID=',CTDID,',CED_REC_VER=',TICK_REC_VER,',UASD_ID=',UASDID,',CLP_TERMINATE=X',',CLP_PRETERMINATE_DATE=',TICK_PTD,',CLP_GUEST_CARD=',TICK_GUEST_CARD,',ULD_ID=',(SELECT ULD_ID FROM CUSTOMER_LP_DETAILS WHERE CLP_ID=CTDID),',CLP_TIMESTAMP=',(SELECT CLP_TIMESTAMP FROM CUSTOMER_LP_DETAILS WHERE CLP_ID=CTDID)));
			ELSE
				SET TICK_OLD_VALUE=(SELECT CONCAT('CLP_ID=',CTDID,',CED_REC_VER=',TICK_REC_VER,',UASD_ID=',UASDID,',CLP_TERMINATE=X',',CLP_PRETERMINATE_DATE=',TICK_PTD,',CLP_GUEST_CARD=',TICK_GUEST_CARD,',CLP_TIMESTAMP=',(SELECT CLP_TIMESTAMP FROM CUSTOMER_LP_DETAILS WHERE CLP_ID=CTDID)));
			END IF;	
		ELSE
			IF (USERSTAMP_ID!=(SELECT ULD_ID FROM CUSTOMER_LP_DETAILS WHERE CLP_ID=CTDID))THEN
				SET TICK_OLD_VALUE=(SELECT CONCAT('CLP_ID=',CTDID,',CED_REC_VER=',TICK_REC_VER,',UASD_ID=null',',CLP_TERMINATE=X',',CLP_PRETERMINATE_DATE=',TICK_PTD,',CLP_GUEST_CARD=',TICK_GUEST_CARD,',ULD_ID=',(SELECT ULD_ID FROM CUSTOMER_LP_DETAILS WHERE CLP_ID=CTDID),',CLP_TIMESTAMP=',(SELECT CLP_TIMESTAMP FROM CUSTOMER_LP_DETAILS WHERE CLP_ID=CTDID)));
			ELSE
				SET TICK_OLD_VALUE=(SELECT CONCAT('CLP_ID=',CTDID,',CED_REC_VER=',TICK_REC_VER,',UASD_ID=null',',CLP_TERMINATE=X',',CLP_PRETERMINATE_DATE=',TICK_PTD,',CLP_GUEST_CARD=',TICK_GUEST_CARD,',CLP_TIMESTAMP=',(SELECT CLP_TIMESTAMP FROM CUSTOMER_LP_DETAILS WHERE CLP_ID=CTDID)));	
			END IF;	
		END IF;
		INSERT INTO TICKLER_HISTORY(TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE,ULD_ID,CUSTOMER_ID)VALUES(1,14,TICK_OLD_VALUE,TICK_NEW_VALUE,USERSTAMP_ID,CUSTID);
-- SET CUSTOMER LP DETAILS TO INSERT INTO TICKLER END		
-- UPDATE TERMINATE=NULL WITH TERMINATE=X		
		SET @UPDATE_LP_DTS=(SELECT CONCAT('UPDATE CUSTOMER_LP_DETAILS SET CLP_TERMINATE=NULL,ULD_ID=',USERSTAMP_ID,' WHERE CUSTOMER_ID=',CUSTID,' AND CLP_ID=(SELECT TRAC_CTDID FROM ',TEMP_REACTIVE_CUSTOMER,' WHERE ID=',MINID,') AND CLP_TERMINATE IS NOT NULL'));
		PREPARE UPDATE_LP_DTS_STMT FROM @UPDATE_LP_DTS;
		EXECUTE UPDATE_LP_DTS_STMT;
		SET FLAG = 1;
		SET MINID = MINID+1;
	END WHILE;
-- DROP TEMP TABLE START	
	SET @DROP_REACTIVE_CUSTOMER=(SELECT CONCAT('DROP TABLE IF EXISTS ',TEMP_REACTIVE_CUSTOMER));
	PREPARE DROP_REACTIVE_CUSTOMER_STMT FROM @DROP_REACTIVE_CUSTOMER;
	EXECUTE DROP_REACTIVE_CUSTOMER_STMT;
-- DROP TEMP TABLE END	
COMMIT;
END;
-- CALL QUERY
-- CALL SP_CUSTOMER_REACTIVE_UPDATE(21,'punitha.shanmugam@ssomens.com',@SUCCESSFLAG);
