-- CUSTOMER
SELECT DISTINCT(CC_CUST_ID),CC_FIRST_NAME,IF(CC_LAST_NAME IS NULL,CC_FIRST_NAME,CC_LAST_NAME) AS CC_LAST_NAME FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT ORDER BY CC_CUST_ID;
SELECT DISTINCT * FROM CUSTOMER ORDER BY CUSTOMER_ID;

-- CUSTOMER_ACCESS_CARD_DETAILS

SELECT * FROM CUSTOMER_ACCESS_CARD_DETAILS;
SELECT *  FROM SOURCE_07072014.ACCESS_SCDB_FORMAT 

-- CUSTOMER_ID
SELECT DISTINCT CUSTOMER_ID FROM CUSTOMER_ACCESS_CARD_DETAILS;
SELECT C.CUSTOMER_ID,ASF.AC_FIRST_NAME,ASF.AC_LAST_NAME,C.CUSTOMER_FIRST_NAME,C.CUSTOMER_LAST_NAME,CACD.CUSTOMER_ID FROM SOURCE_07072014.ACCESS_SCDB_FORMAT ASF
INNER JOIN CUSTOMER C ON (ASF.AC_FIRST_NAME=C.CUSTOMER_FIRST_NAME AND ASF.AC_LAST_NAME=C.CUSTOMER_LAST_NAME)OR(C.CUSTOMER_FIRST_NAME=ASF.AC_FIRST_NAME AND C.CUSTOMER_LAST_NAME=ASF.AC_FIRST_NAME)
INNER JOIN CUSTOMER_ACCESS_CARD_DETAILS CACD 
WHERE C.CUSTOMER_ID = CACD.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID
-- UASD_ID
SELECT DISTINCT UASD_ID FROM CUSTOMER_ACCESS_CARD_DETAILS;
SELECT DISTINCT UASD_ID FROM CUSTOMER_ACCESS_CARD_DETAILS WHERE UASD_ID IN (SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS);

-- ACN_ID
SELECT DISTINCT ACN_ID FROM CUSTOMER_ACCESS_CARD_DETAILS;
SELECT DISTINCT ACN_ID FROM ACCESS_CONFIGURATION;

-- AC_VALID_FROM
SELECT DISTINCT AC_VALID_FROM FROM SOURCE_07072014.ACCESS_SCDB_FORMAT;
SELECT DISTINCT CACD_VALID_FROM FROM CUSTOMER_ACCESS_CARD_DETAILS;
SELECT DISTINCT ASF.AC_VALID_FROM,CACD.CACD_VALID_FROM FROM SOURCE_07072014.ACCESS_SCDB_FORMAT ASF,CUSTOMER_ACCESS_CARD_DETAILS CACD WHERE ASF.AC_VALID_FROM=CACD.CACD_VALID_FROM;

-- AC_VALID_TILL
SELECT DISTINCT AC_VALID_TILL FROM SOURCE_07072014.ACCESS_SCDB_FORMAT;
SELECT DISTINCT CACD_VALID_TILL FROM CUSTOMER_ACCESS_CARD_DETAILS;
SELECT DISTINCT A.AC_VALID_TILL,B.CACD_VALID_TILL FROM SOURCE_07072014.ACCESS_SCDB_FORMAT A,CUSTOMER_ACCESS_CARD_DETAILS B WHERE A.AC_VALID_TILL=B.CACD_VALID_TILL;

-- GUEST_CARD
SELECT DISTINCT CUSTOMER_ID,CACD_GUEST_CARD FROM CUSTOMER_ACCESS_CARD_DETAILS WHERE CACD_GUEST_CARD IS NOT NULL;
SELECT DISTINCT IF(AC_LAST_NAME IS NULL ,CONCAT(AC_FIRST_NAME,' ',AC_FIRST_NAME),CONCAT(AC_FIRST_NAME,' ',AC_LAST_NAME)) AS CUSTOMER_NAME,AC_GUEST_CARD FROM SOURCE_07072014.ACCESS_SCDB_FORMAT WHERE AC_GUEST_CARD IS NOT NULL;

-- ULD_ID
SELECT DISTINCT ULD_ID FROM CUSTOMER_ACCESS_CARD_DETAILS;
SELECT DISTINCT USERSTAMP FROM SOURCE_07072014.ACCESS_SCDB_FORMAT;
SELECT DISTINCT A.USERSTAMP,B.ULD_LOGINID,B.ULD_ID,C.ULD_ID
FROM SOURCE_07072014.ACCESS_SCDB_FORMAT A INNER JOIN
USER_LOGIN_DETAILS B ON A.USERSTAMP= B.ULD_LOGINID
INNER JOIN
CUSTOMER_ACCESS_CARD_DETAILS C ON B.ULD_ID=C.ULD_ID

-- TIMESTAMP
SELECT  DISTINCT TIMESTAMP FROM SOURCE_07072014.ACCESS_SCDB_FORMAT;
SELECT DISTINCT CACD_TIMESTAMP FROM CUSTOMER_ACCESS_CARD_DETAILS;
SELECT  DISTINCT SUBTIME(A.TIMESTAMP, '08:00:00'),B.CACD_TIMESTAMP FROM SOURCE_07072014.ACCESS_SCDB_FORMAT A,CUSTOMER_ACCESS_CARD_DETAILS  B WHERE SUBTIME(A.TIMESTAMP, '08:00:00')= B.CACD_TIMESTAMP;

-- CUSTOMER_COMPANY_DETAILS
-- CUSTOMER_ID

SELECT DISTINCT CSF.CC_CUST_ID FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT CSF WHERE CSF.CC_COMPANY_NAME IS NOT NULL;
SELECT DISTINCT CCD.CUSTOMER_ID FROM CUSTOMER_COMPANY_DETAILS CCD WHERE CCD.CCD_COMPANY_NAME IS NOT NULL;
SELECT DISTINCT CSF.CC_CUST_ID,CCD.CUSTOMER_ID FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT CSF,CUSTOMER_COMPANY_DETAILS CCD WHERE CSF.CC_CUST_ID=CCD.CUSTOMER_ID;

-- COMPANY ADDRESS

SELECT DISTINCT(CC_COMPANY_ADDR),CC_CUST_ID FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT WHERE CC_COMPANY_ADDR IS NOT NULL ORDER BY CC_CUST_ID;
SELECT DISTINCT(CCD_COMPANY_ADDR),CUSTOMER_ID FROM CUSTOMER_COMPANY_DETAILS WHERE CCD_COMPANY_ADDR IS NOT NULL ORDER BY CUSTOMER_ID;

SELECT DISTINCT(S.CC_COMPANY_ADDR),S.CC_CUST_ID,D.CUSTOMER_ID,D.CCD_COMPANY_ADDR FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT S,CUSTOMER_COMPANY_DETAILS D
WHERE  S.CC_COMPANY_ADDR=D.CCD_COMPANY_ADDR AND S.CC_CUST_ID=D.CUSTOMER_ID AND S.CC_COMPANY_ADDR IS NOT NULL  ORDER BY CC_CUST_ID;

SELECT DISTINCT CC_COMPANY_ADDR  FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT  WHERE NOT EXISTS
(SELECT CCD_COMPANY_ADDR FROM CUSTOMER_COMPANY_DETAILS WHERE CC_COMPANY_ADDR=CCD_COMPANY_ADDR);

SELECT DISTINCT  CC_CUST_ID FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT  WHERE CC_COMPANY_ADDR='8 MARINA VIEW #09-08'

-- COMPANY NAME
SELECT DISTINCT(CC_COMPANY_NAME),CC_CUST_ID FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT WHERE CC_COMPANY_NAME IS NOT NULL ORDER BY CC_CUST_ID;
SELECT DISTINCT(CCD_COMPANY_NAME),CUSTOMER_ID FROM CUSTOMER_COMPANY_DETAILS WHERE CCD_COMPANY_NAME IS NOT NULL ORDER BY CUSTOMER_ID;
SELECT DISTINCT(S.CC_COMPANY_NAME),S.CC_CUST_ID,D.CUSTOMER_ID,D.CCD_COMPANY_NAME FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT S,CUSTOMER_COMPANY_DETAILS D
WHERE  S.CC_COMPANY_NAME=D.CCD_COMPANY_NAME AND S.CC_CUST_ID=D.CUSTOMER_ID AND S.CC_COMPANY_NAME IS NOT NULL  ORDER BY CC_CUST_ID;

SELECT DISTINCT CC_COMPANY_NAME  FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT WHERE NOT EXISTS
(SELECT CCD_COMPANY_NAME FROM CUSTOMER_COMPANY_DETAILS WHERE CC_COMPANY_NAME=CCD_COMPANY_NAME);

SELECT DISTINCT * FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT WHERE CC_COMPANY_NAME='Mercer (Singapore) Pte Ltd'

SELECT CC_CUST_ID,CC_COMPANY_ADDR,CC_COMPANY_NAME,CC_POSTAL_CODE,CC_OFFICE_NO,CC_REC_VER FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT WHERE CC_FIRST_NAME='MELVIN' AND CC_LAST_NAME='FRANCISQUINI'

-- POSTAL CODE

SELECT DISTINCT(CC_POSTAL_CODE),CC_CUST_ID FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT WHERE CC_POSTAL_CODE IS NOT NULL ORDER BY CC_CUST_ID;
SELECT DISTINCT(CCD_POSTAL_CODE),CUSTOMER_ID FROM CUSTOMER_COMPANY_DETAILS WHERE CCD_POSTAL_CODE IS NOT NULL ORDER BY CUSTOMER_ID;
SELECT DISTINCT(S.CC_POSTAL_CODE),S.CC_CUST_ID,D.CUSTOMER_ID,D.CCD_POSTAL_CODE FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT S,CUSTOMER_COMPANY_DETAILS D
WHERE  S.CC_POSTAL_CODE=D.CCD_POSTAL_CODE AND S.CC_CUST_ID=D.CUSTOMER_ID AND S.CC_POSTAL_CODE IS NOT NULL  ORDER BY CC_CUST_ID;

SELECT DISTINCT CC_POSTAL_CODE  FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT WHERE  NOT EXISTS
(SELECT CCD_POSTAL_CODE FROM CUSTOMER_COMPANY_DETAILS WHERE CC_POSTAL_CODE=CCD_POSTAL_CODE);

-- OFFICE NO

SELECT DISTINCT(CC_OFFICE_NO),CC_CUST_ID FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT WHERE CC_OFFICE_NO IS NOT NULL ORDER BY CC_CUST_ID;
SELECT DISTINCT(CCD_OFFICE_NO),CUSTOMER_ID FROM CUSTOMER_COMPANY_DETAILS WHERE CCD_OFFICE_NO IS NOT NULL ORDER BY CUSTOMER_ID;
SELECT DISTINCT(S.CC_OFFICE_NO),S.CC_CUST_ID,D.CUSTOMER_ID,D.CCD_OFFICE_NO FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT S,CUSTOMER_COMPANY_DETAILS D
WHERE  S.CC_OFFICE_NO=D.CCD_OFFICE_NO AND S.CC_CUST_ID=D.CUSTOMER_ID AND S.CC_OFFICE_NO IS NOT NULL  ORDER BY CC_CUST_ID;

-- CUSTOMER_FEE_DETAILS;
-- CUSTOMER_ID
SELECT DISTINCT CUSTOMER_ID FROM CUSTOMER_FEE_DETAILS;
SELECT DISTINCT CC_CUST_ID FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT;

-- CFD_REC_VER
SELECT DISTINCT CUSTOMER_ID,CED_REC_VER FROM CUSTOMER_FEE_DETAILS;
SELECT DISTINCT CUSTOMER_ID,CED_REC_VER FROM CUSTOMER_ENTRY_DETAILS;
SELECT DISTINCT A.CUSTOMER_ID,B.CUSTOMER_ID,A.CED_REC_VER,B.CED_REC_VER FROM CUSTOMER_FEE_DETAILS A,CUSTOMER_ENTRY_DETAILS B WHERE A.CED_REC_VER=B.CED_REC_VER AND A.CUSTOMER_ID=B.CUSTOMER_ID;

-- CPP_ID
SELECT DISTINCT CPP_ID FROM CUSTOMER_PAYMENT_PROFILE;
SELECT DISTINCT CPP_ID FROM CUSTOMER_FEE_DETAILS;

-- CFD_AMOUNT
SELECT DISTINCT CFD_AMOUNT FROM CUSTOMER_FEE_DETAILS WHERE CPP_ID=1;
SELECT DISTINCT CC_RENT_AMOUNT FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT;
SELECT DISTINCT A.CFD_AMOUNT,B.CC_RENT_AMOUNT FROM CUSTOMER_FEE_DETAILS A,SOURCE_07072014.CUSTOMER_SCDB_FORMAT B WHERE  A.CFD_AMOUNT=B.CC_RENT_AMOUNT AND A.CPP_ID=1;

SELECT DISTINCT CFD_AMOUNT FROM CUSTOMER_FEE_DETAILS WHERE CPP_ID=2;
SELECT DISTINCT CC_DEPOSIT FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT;
SELECT DISTINCT A.CFD_AMOUNT,B.CC_DEPOSIT FROM CUSTOMER_FEE_DETAILS A,SOURCE_07072014.CUSTOMER_SCDB_FORMAT B WHERE A.CFD_AMOUNT=B.CC_DEPOSIT

SELECT DISTINCT CFD_AMOUNT FROM CUSTOMER_FEE_DETAILS WHERE CPP_ID=3;
SELECT DISTINCT CC_PROCESSING_FEE FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT;
SELECT DISTINCT A.CFD_AMOUNT,B.CC_PROCESSING_FEE FROM CUSTOMER_FEE_DETAILS A,SOURCE_07072014.CUSTOMER_SCDB_FORMAT B WHERE A.CFD_AMOUNT=B.CC_PROCESSING_FEE

SELECT DISTINCT CFD_AMOUNT FROM CUSTOMER_FEE_DETAILS WHERE CPP_ID=4;
SELECT DISTINCT CC_AIRCON_FIXED_FEE FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT;
SELECT DISTINCT A.CFD_AMOUNT,B.CC_AIRCON_FIXED_FEE FROM CUSTOMER_FEE_DETAILS A,SOURCE_07072014.CUSTOMER_SCDB_FORMAT B WHERE A.CFD_AMOUNT=B.CC_AIRCON_FIXED_FEE 

SELECT DISTINCT CFD_AMOUNT FROM CUSTOMER_FEE_DETAILS WHERE CPP_ID=5;
SELECT DISTINCT CC_ELECTRICITY_CAP FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT;
SELECT DISTINCT A.CFD_AMOUNT,B.CC_ELECTRICITY_CAP FROM CUSTOMER_FEE_DETAILS A,SOURCE_07072014.CUSTOMER_SCDB_FORMAT B WHERE A.CFD_AMOUNT=B.CC_ELECTRICITY_CAP 

SELECT DISTINCT CFD_AMOUNT FROM CUSTOMER_FEE_DETAILS WHERE CPP_ID=6;
SELECT DISTINCT CC_DRYCLEAN_FEE FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT;
SELECT DISTINCT A.CFD_AMOUNT,B.CC_DRYCLEAN_FEE FROM CUSTOMER_FEE_DETAILS A,SOURCE_07072014.CUSTOMER_SCDB_FORMAT B WHERE A.CFD_AMOUNT=B.CC_DRYCLEAN_FEE 

SELECT DISTINCT CFD_AMOUNT FROM CUSTOMER_FEE_DETAILS WHERE CPP_ID=7;
SELECT DISTINCT CC_AIRCON_QUARTERLY_FEE FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT;
SELECT DISTINCT A.CFD_AMOUNT,B.CC_AIRCON_QUARTERLY_FEE FROM CUSTOMER_FEE_DETAILS A,SOURCE_07072014.CUSTOMER_SCDB_FORMAT B WHERE A.CFD_AMOUNT=B.CC_AIRCON_QUARTERLY_FEE 

SELECT DISTINCT CFD_AMOUNT FROM CUSTOMER_FEE_DETAILS WHERE CPP_ID=8;
SELECT DISTINCT CC_CHECKOUT_CLEANING_FEE FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT;
SELECT DISTINCT A.CFD_AMOUNT,B.CC_CHECKOUT_CLEANING_FEE FROM CUSTOMER_FEE_DETAILS A,SOURCE_07072014.CUSTOMER_SCDB_FORMAT B WHERE A.CFD_AMOUNT=B.CC_CHECKOUT_CLEANING_FEE 

-- CUSTOMER_ENTRY_DETAILS

SELECT * FROM CUSTOMER_ENTRY_DETAILS;

-- CUSTOMER_ID
SELECT DISTINCT CUSTOMER_ID FROM CUSTOMER_ENTRY_DETAILS;
SELECT DISTINCT CC_CUST_ID FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT;

-- UNIT_ID
SELECT DISTINCT UNIT_ID FROM CUSTOMER_ENTRY_DETAILS;
SELECT DISTINCT CC_UNIT_NO FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT;
SELECT DISTINCT A.CC_UNIT_NO,B.UNIT_NO,B.UNIT_ID,C.UNIT_ID
FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT A INNER JOIN
UNIT B ON A.CC_UNIT_NO= B.UNIT_NO
INNER JOIN
CUSTOMER_ENTRY_DETAILS C ON B.UNIT_ID=C.UNIT_ID;

-- UASD_ID
SELECT DISTINCT UNIT_ID,UASD_ID FROM CUSTOMER_ENTRY_DETAILS GROUP BY UNIT_ID;

SELECT DISTINCT A.CC_UNIT_NO,A.CC_ROOMTYPE,B.UNIT_NO,B.UNIT_ID,C.UNIT_ID,C.URTD_ID,D.URTD_ID,D.URTD_ROOM_TYPE,E.UASD_ID,C.UASD_ID
FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT A 
INNER JOIN
UNIT B ON A.CC_UNIT_NO=B.UNIT_NO
INNER JOIN
UNIT_ACCESS_STAMP_DETAILS C ON B.UNIT_ID=C.UNIT_ID 
INNER JOIN
UNIT_ROOM_TYPE_DETAILS D ON A.CC_ROOMTYPE=D.URTD_ROOM_TYPE AND C.URTD_ID=D.URTD_ID
INNER JOIN 
CUSTOMER_ENTRY_DETAILS E ON E.UASD_ID=C.UASD_ID GROUP BY A.CC_UNIT_NO;

-- CED_REC_VER
SELECT DISTINCT CED_REC_VER FROM CUSTOMER_ENTRY_DETAILS;
SELECT DISTINCT CED_REC_VER FROM CUSTOMER_LP_DETAILS;

-- LEASE_PEROID
SELECT DISTINCT CC_LEASE_PERIOD FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT;
SELECT DISTINCT CED_LEASE_PERIOD FROM CUSTOMER_ENTRY_DETAILS;
SELECT DISTINCT A.CC_LEASE_PERIOD,B.CED_LEASE_PERIOD FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT A,CUSTOMER_ENTRY_DETAILS B WHERE A.CC_LEASE_PERIOD=B.CED_LEASE_PERIOD;

-- CED QUARTERS
SELECT DISTINCT CED_QUARTERS FROM CUSTOMER_ENTRY_DETAILS;
SELECT DISTINCT CC_QUARTERS FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT;
SELECT DISTINCT A.CED_QUARTERS,B.CC_QUARTERS FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT B,CUSTOMER_ENTRY_DETAILS A WHERE A.CED_QUARTERS=B.CC_QUARTERS 

-- CED_EXTENSION
SELECT DISTINCT CUSTOMER_ID,CED_EXTENSION FROM CUSTOMER_ENTRY_DETAILS WHERE CED_EXTENSION IS NOT NULL;
SELECT DISTINCT CC_CUST_ID,CC_EXTENSION FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT WHERE CC_EXTENSION IS NOT NULL;

-- CED_PRETERMINATE
SELECT DISTINCT CUSTOMER_ID,CED_PRETERMINATE FROM CUSTOMER_ENTRY_DETAILS WHERE CED_PRETERMINATE IS NOT NULL;
SELECT DISTINCT CC_CUST_ID,CC_PRETERMINATE FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT WHERE CC_PRETERMINATE IS NOT NULL;

-- CED_PROCESSING_WAIVED
SELECT DISTINCT CUSTOMER_ID,CED_PROCESSING_WAIVED FROM CUSTOMER_ENTRY_DETAILS WHERE CED_PROCESSING_WAIVED IS NOT NULL;
SELECT DISTINCT CC_CUST_ID,CC_PROCESSING_WAIVED FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT WHERE CC_PROCESSING_WAIVED IS NOT NULL;

-- CED_NOTICE_START_DATE
SELECT DISTINCT CED_NOTICE_START_DATE FROM CUSTOMER_ENTRY_DETAILS WHERE CED_NOTICE_START_DATE IS NOT NULL;
SELECT DISTINCT CC_NOTICE_START_DATE FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT WHERE CC_NOTICE_START_DATE IS NOT NULL;

-- CED_CANCEL_DATE
SELECT DISTINCT CED_CANCEL_DATE FROM CUSTOMER_ENTRY_DETAILS WHERE CED_CANCEL_DATE IS NOT NULL;
SELECT DISTINCT CC_CANCEL_DATE FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT WHERE CC_CANCEL_DATE IS NOT NULL;


-- CUSTOMER_LP_DETAILS;

-- CUSTOMER_ID
SELECT DISTINCT CUSTOMER_ID FROM CUSTOMER_LP_DETAILS;
SELECT DISTINCT CC_CUST_ID FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT;
SELECT DISTINCT CUSTOMER_ID FROM CUSTOMER;

-- CED_REC_VER 
SELECT DISTINCT CUSTOMER_ID,CED_REC_VER FROM CUSTOMER_LP_DETAILS;
SELECT DISTINCT CUSTOMER_ID,CED_REC_VER FROM CUSTOMER_ENTRY_DETAILS;
SELECT DISTINCT A.CUSTOMER_ID,B.CUSTOMER_ID,A.CED_REC_VER,B.CED_REC_VER FROM CUSTOMER_ENTRY_DETAILS A,CUSTOMER_LP_DETAILS B WHERE A.CUSTOMER_ID=B.CUSTOMER_ID AND A.CED_REC_VER=B.CED_REC_VER;

-- UASD_ID
SELECT DISTINCT A.CC_CARD_NO,B.UASD_ID,B.UASD_ACCESS_CARD,C.UASD_ID 
FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT A
INNER JOIN 
UNIT_ACCESS_STAMP_DETAILS B ON A.CC_CARD_NO=B.UASD_ACCESS_CARD
INNER JOIN
CUSTOMER_LP_DETAILS C ON B.UASD_ID=C.UASD_ID;

-- CLP_START DATE
SELECT DISTINCT CLP_STARTDATE FROM CUSTOMER_LP_DETAILS; 
SELECT DISTINCT CSF.CC_STARTDATE FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT CSF;
SELECT DISTINCT CSF.CC_STARTDATE,CLP.CLP_STARTDATE FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT CSF,CUSTOMER_LP_DETAILS CLP WHERE CSF.CC_STARTDATE=CLP.CLP_STARTDATE

-- CLP-END DATE
SELECT DISTINCT CLP_ENDDATE FROM CUSTOMER_LP_DETAILS;
SELECT DISTINCT CSF.CC_ENDDATE FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT CSF;
SELECT DISTINCT CSF.CC_ENDDATE,CLP.CLP_ENDDATE FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT CSF,CUSTOMER_LP_DETAILS CLP WHERE CSF.CC_ENDDATE=CLP.CLP_ENDDATE
 
-- CLP_TERMINATE
SELECT DISTINCT CUSTOMER_ID,CLP_TERMINATE FROM CUSTOMER_LP_DETAILS WHERE CLP_TERMINATE IS NOT NULL;
SELECT DISTINCT CC_CUST_ID,CC_TERMINATE FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT WHERE CC_TERMINATE IS NOT NULL;

-- CLP_PRETERMINATE DATE
SELECT DISTINCT CLP_PRETERMINATE_DATE FROM CUSTOMER_LP_DETAILS WHERE CLP_PRETERMINATE_DATE IS NOT NULL;
SELECT DISTINCT CC_PRE_TERMINATE_DATE FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT  WHERE CC_PRE_TERMINATE_DATE IS NOT NULL;

-- CLP_GUEST_CARD
SELECT DISTINCT CUSTOMER_ID,CLP_GUEST_CARD FROM CUSTOMER_LP_DETAILS WHERE CLP_GUEST_CARD IS NOT NULL;
SELECT DISTINCT CC_CUST_ID,CC_GUEST_CARD_NO FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT WHERE CC_GUEST_CARD_NO IS NOT NULL;

-- TIMESTAMP
SELECT DISTINCT CSF.TIMESTAMP FROM  SOURCE_07072014.CUSTOMER_SCDB_FORMAT CSF;
SELECT DISTINCT CLP.CLP_TIMESTAMP FROM CUSTOMER_LP_DETAILS CLP;
SELECT  DISTINCT SUBTIME(A.TIMESTAMP, '08:00:00'),B.CLP_TIMESTAMP FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT A,CUSTOMER_LP_DETAILS  B WHERE SUBTIME(A.TIMESTAMP, '08:00:00')= B.CLP_TIMESTAMP;

-- ULDID 
SELECT DISTINCT ULD_ID FROM CUSTOMER_LP_DETAILS;
SELECT DISTINCT A.USERSTAMP,B.ULD_LOGINID,B.ULD_ID,C.ULD_ID
FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT A INNER JOIN
USER_LOGIN_DETAILS B ON A.USERSTAMP= B.ULD_LOGINID
INNER JOIN
CUSTOMER_LP_DETAILS C ON B.ULD_ID=C.ULD_ID

-- CUSTOMER_PAYMENT_PROFILE

SELECT DISTINCT ULD_ID FROM CUSTOMER_PAYMENT_PROFILE;
SELECT DISTINCT A.USERSTAMP,B.ULD_LOGINID,B.ULD_ID,C.ULD_ID
FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT A INNER JOIN
USER_LOGIN_DETAILS B ON A.USERSTAMP= B.ULD_LOGINID
INNER JOIN
CUSTOMER_PAYMENT_PROFILE C ON B.ULD_ID=C.ULD_ID

-- CUSTOMER_PERSONAL_DETAILS;

-- CUSTOMER_ID
SELECT DISTINCT CUSTOMER_ID FROM CUSTOMER_PERSONAL_DETAILS;
SELECT DISTINCT CUSTOMER_ID FROM CUSTOMER;

-- NC-ID
SELECT DISTINCT NC_ID FROM CUSTOMER_PERSONAL_DETAILS;
SELECT DISTINCT A.CC_NATIONALITY,B.NC_DATA,B.NC_ID,C.NC_ID FROM
SOURCE_07072014.CUSTOMER_SCDB_FORMAT A INNER JOIN
NATIONALITY_CONFIGURATION B ON A.CC_NATIONALITY=B.NC_DATA INNER JOIN
CUSTOMER_PERSONAL_DETAILS C ON B.NC_ID=C.NC_ID;

-- CPD_MOBILE
SELECT DISTINCT CUSTOMER_ID,CPD_MOBILE FROM CUSTOMER_PERSONAL_DETAILS WHERE CPD_MOBILE IS NOT NULL AND NC_ID IS NOT NULL AND CPD_EMAIL IS NOT NULL GROUP BY CUSTOMER_ID;
SELECT DISTINCT CC_CUST_ID,CC_MOBILE FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT WHERE CC_MOBILE IS NOT NULL AND CC_NATIONALITY IS NOT NULL AND CC_EMAIL IS NOT NULL GROUP BY CC_CUST_ID;

SELECT DISTINCT CONCAT(CPD_MOBILE,' ',CPD_INTL_MOBILE) AS MOBILE_NO FROM CUSTOMER_PERSONAL_DETAILS  GROUP BY CUSTOMER_ID;
SELECT DISTINCT CONCAT(CC_MOBILE,' ',CC_MOBILE2) FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT GROUP BY CC_CUST_ID;

-- PASSPORT NO
SELECT DISTINCT CPD_PASSPORT_NO FROM CUSTOMER_PERSONAL_DETAILS GROUP BY CUSTOMER_ID;
SELECT DISTINCT CC_PASSPORT_NO FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT GROUP BY CC_CUST_ID;

-- PASSPORT DATE
SELECT DISTINCT CPD_PASSPORT_DATE FROM CUSTOMER_PERSONAL_DETAILS GROUP BY CUSTOMER_ID;
SELECT DISTINCT CC_PASSPORT_DATE FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT GROUP BY CC_CUST_ID;

-- DOB
SELECT DISTINCT CPD_DOB FROM CUSTOMER_PERSONAL_DETAILS GROUP BY CUSTOMER_ID;
SELECT DISTINCT CC_DOB FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT GROUP BY CC_CUST_ID;

-- EP_NO
SELECT DISTINCT CPD_EP_NO FROM CUSTOMER_PERSONAL_DETAILS GROUP BY CUSTOMER_ID;
SELECT DISTINCT CC_EP_NO FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT GROUP BY CC_CUST_ID;

-- EP_DATE
SELECT DISTINCT CPD_EP_DATE FROM CUSTOMER_PERSONAL_DETAILS GROUP BY CUSTOMER_ID;
SELECT DISTINCT CC_EP_DATE FROM SOURCE_07072014.CUSTOMER_SCDB_FORMAT GROUP BY CC_CUST_ID;
SELECT DISTINCT CPD.CPD_EP_DATE,CSF.CC_EP_DATE FROM CUSTOMER_PERSONAL_DETAILS CPD,SOURCE_07072014.CUSTOMER_sCDB_FORMAT CSF WHERE CPD.CPD_EP_DATE=CSF.CC_EP_DATE;
