-- EXPENSE_AGENT
-- EA_DATE

SELECT DISTINCT SE_AGENT_DATE FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT WHERE SE_TYPE_OF_EXPENSE='AGENT COMMISSION';
SELECT DISTINCT EA_DATE FROM EXPENSE_AGENT;
SELECT DISTINCT SD.SE_AGENT_DATE,EA.EA_DATE FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT SD,EXPENSE_AGENT EA WHERE  SD.SE_AGENT_DATE=EA.EA_DATE

-- EA_COMM_AMOUNT

SELECT DISTINCT SE_AGENT_COMM_AMOUNT FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT WHERE SE_TYPE_OF_EXPENSE='AGENT COMMISSION';
SELECT DISTINCT EA_COMM_AMOUNT FROM EXPENSE_AGENT
SELECT DISTINCT SD.SE_AGENT_COMM_AMOUNT,EA.EA_COMM_AMOUNT FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT SD,EXPENSE_AGENT EA WHERE  SD.SE_AGENT_COMM_AMOUNT=EA.EA_COMM_AMOUNT

-- EA_COMMENTS

SELECT DISTINCT EA_COMMENTS FROM EXPENSE_AGENT;
SELECT DISTINCT SE_AGENT_COMMENTS FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT WHERE SE_TYPE_OF_EXPENSE='AGENT COMMISSION';
SELECT DISTINCT SD.SE_AGENT_COMMENTS,EA.EA_COMMENTS FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT SD,EXPENSE_AGENT EA WHERE SD.SE_AGENT_COMMENTS=EA.EA_COMMENTS AND SE_TYPE_OF_EXPENSE='AGENT COMMISSION';

-- ULD_ID

SELECT DISTINCT ULD_ID FROM EXPENSE_AGENT;
SELECT DISTINCT USERSTAMP FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT WHERE SE_TYPE_OF_EXPENSE='AGENT COMMISSION';
SELECT DISTINCT A.USERSTAMP,B.ULD_LOGINID,B.ULD_ID,C.ULD_ID FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT A
INNER JOIN 
USER_LOGIN_DETAILS B ON A.USERSTAMP=B.ULD_LOGINID
INNER JOIN
EXPENSE_AGENT C ON B.ULD_ID=C.ULD_ID WHERE A.SE_TYPE_OF_EXPENSE='AGENT COMMISSION';

-- EA_TIMESTAMP

SELECT DISTINCT TIMESTAMP FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT WHERE SE_TYPE_OF_EXPENSE='AGENT COMMISSION';
SELECT DISTINCT EA_TIMESTAMP FROM EXPENSE_AGENT;
SELECT DISTINCT SUBTIME(SD.TIMESTAMP,'08:00:00'),EA.EA_TIMESTAMP FROM  SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT SD,EXPENSE_AGENT EA WHERE SUBTIME(SD.TIMESTAMP,'08:00:00')=EA.EA_TIMESTAMP

-- EXPENSE_STAFF

-- ECN_ID
SELECT DISTINCT ECN_ID FROM EXPENSE_STAFF;
SELECT DISTINCT SE_STAFF_EXPENSE FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT WHERE SE_TYPE_OF_EXPENSE='STAFF';
SELECT DISTINCT SE.SE_STAFF_EXPENSE ,EC.ECN_DATA ,EC.ECN_ID , ES.ECN_ID
FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT SE
INNER JOIN EXPENSE_CONFIGURATION EC ON SE.SE_STAFF_EXPENSE =EC.ECN_DATA 
INNER JOIN EXPENSE_STAFF ES ON EC.ECN_ID = ES.ECN_ID WHERE SE_TYPE_OF_EXPENSE='STAFF';

-- ES_INVOICE_DATE

SELECT DISTINCT SE_STAFF_INVOICE_DATE FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT WHERE SE_TYPE_OF_EXPENSE='STAFF';
SELECT DISTINCT ES_INVOICE_DATE FROM EXPENSE_STAFF;
SELECT DISTINCT SD.SE_STAFF_INVOICE_DATE,ES.ES_INVOICE_DATE FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT  SD,EXPENSE_STAFF ES WHERE SD.SE_STAFF_INVOICE_DATE=ES.ES_INVOICE_DATE

-- ES_INVOICE_AMOUNT

SELECT DISTINCT  SE_STAFF_INVOICE_AMOUNT FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT WHERE SE_TYPE_OF_EXPENSE='STAFF';
SELECT DISTINCT  ES_INVOICE_AMOUNT FROM EXPENSE_STAFF;
SELECT DISTINCT SD.SE_STAFF_INVOICE_AMOUNT,ES.ES_INVOICE_AMOUNT FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT SD,EXPENSE_STAFF ES WHERE SD.SE_STAFF_INVOICE_AMOUNT=ES.ES_INVOICE_AMOUNT

-- ES_INVOICE_ITEM

SELECT DISTINCT SE_STAFF_INVOICE_ITEMS FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT WHERE SE_TYPE_OF_EXPENSE='STAFF';
SELECT DISTINCT ES_INVOICE_ITEMS FROM EXPENSE_STAFF;
SELECT DISTINCT SD.SE_STAFF_INVOICE_ITEMS,ES.ES_INVOICE_ITEMS FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT SD,EXPENSE_STAFF ES WHERE SD.SE_STAFF_INVOICE_ITEMS=ES.ES_INVOICE_ITEMS
SELECT DISTINCT ES_INVOICE_ITEMS FROM EXPENSE_STAFF WHERE NOT EXISTS(SELECT SE_STAFF_INVOICE_ITEMS FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT  WHERE SE_STAFF_INVOICE_ITEMS=ES_INVOICE_ITEMS)
SELECT DISTINCT * FROM EXPENSE_STAFF WHERE ES_INVOICE_ITEMS='NO ITEM'
SELECT DISTINCT * FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT WHERE SE_TYPE_OF_EXPENSE='STAFF' AND SE_STAFF_INVOICE_ITEMS='NO ITEM';

-- ES_INVOICE_FROM

SELECT DISTINCT SE_STAFF_INVOICE_FROM FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT WHERE SE_TYPE_OF_EXPENSE='STAFF';
SELECT DISTINCT ES_INVOICE_FROM FROM EXPENSE_STAFF;
SELECT DISTINCT SD.SE_STAFF_INVOICE_FROM,ES.ES_INVOICE_FROM FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT SD,EXPENSE_STAFF ES WHERE SD.SE_STAFF_INVOICE_FROM=ES.ES_INVOICE_FROM

-- ES_COMMENTS
SELECT DISTINCT SE_STAFF_COMMENTS FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT WHERE SE_TYPE_OF_EXPENSE='STAFF';
SELECT DISTINCT ES_COMMENTS FROM EXPENSE_STAFF;
SELECT DISTINCT SD.SE_STAFF_COMMENTS,ES.ES_COMMENTS FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT SD,EXPENSE_STAFF ES WHERE SD.SE_STAFF_COMMENTS=ES.ES_COMMENTS AND SD.SE_TYPE_OF_EXPENSE='STAFF';

-- ULD_ID
SELECT DISTINCT ULD_ID FROM EXPENSE_STAFF;
SELECT DISTINCT A.USERSTAMP,B.ULD_LOGINID,B.ULD_ID,C.ULD_ID
FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT A INNER JOIN
USER_LOGIN_DETAILS B ON A.USERSTAMP= B.ULD_LOGINID
INNER JOIN
EXPENSE_STAFF C ON B.ULD_ID=C.ULD_ID

-- ES_TIMESTAMP
SELECT DISTINCT TIMESTAMP FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT WHERE SE_TYPE_OF_EXPENSE='STAFF';
SELECT DISTINCT ES_TIMESTAMP FROM EXPENSE_STAFF;
SELECT DISTINCT SUBTIME(SD.TIMESTAMP,'08:00:00'),ES.ES_TIMESTAMP FROM  SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT SD,EXPENSE_STAFF ES WHERE SUBTIME(SD.TIMESTAMP,'08:00:00')=ES.ES_TIMESTAMP

-- EXPENSE_STAFF_SALARY
-- EDSS_ID
SELECT DISTINCT EDSS_ID FROM EXPENSE_STAFF_SALARY;
SELECT DISTINCT EDSS_ID FROM EXPENSE_DETAIL_STAFF_SALARY;
SELECT DISTINCT A.EDSS_ID,B.EDSS_ID FROM EXPENSE_DETAIL_STAFF_SALARY A,EXPENSE_STAFF_SALARY B WHERE A.EDSS_ID=B.EDSS_ID

-- EXPENSE_INVOICE_DATE
SELECT DISTINCT SE_SALARY_INVOICE_DATE FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT WHERE SE_TYPE_OF_EXPENSE='SALARY ENTRY';
SELECT DISTINCT ESS_INVOICE_DATE FROM EXPENSE_STAFF_SALARY
SELECT DISTINCT SD.SE_SALARY_INVOICE_DATE,ESS.ESS_INVOICE_DATE FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT SD,EXPENSE_STAFF_SALARY ESS WHERE SD.SE_SALARY_INVOICE_DATE=ESS.ESS_INVOICE_DATE

-- EXPENSE_FROM PERIOD
SELECT DISTINCT SE_SALARY_FROM_PERIOD FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT WHERE SE_TYPE_OF_EXPENSE='SALARY ENTRY';
SELECT DISTINCT ESS_FROM_PERIOD FROM EXPENSE_STAFF_SALARY
SELECT DISTINCT SD.SE_SALARY_FROM_PERIOD,ESS.ESS_FROM_PERIOD FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT SD,EXPENSE_STAFF_SALARY ESS WHERE SD.SE_SALARY_FROM_PERIOD=ESS.ESS_FROM_PERIOD

-- EXPENSE_TO_PERIOD
SELECT DISTINCT SE_SALARY_TO_PERIOD FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT WHERE SE_TYPE_OF_EXPENSE='SALARY ENTRY';
SELECT DISTINCT ESS_TO_PERIOD FROM EXPENSE_STAFF_SALARY
SELECT DISTINCT SD.SE_SALARY_TO_PERIOD,ESS.ESS_TO_PERIOD FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT SD,EXPENSE_STAFF_SALARY ESS WHERE SD.SE_SALARY_TO_PERIOD=ESS.ESS_TO_PERIOD

-- CPF_AMOUNT
SELECT DISTINCT SE_CPF_AMOUNT FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT WHERE SE_TYPE_OF_EXPENSE='SALARY ENTRY';
SELECT DISTINCT ESS_CPF_AMOUNT FROM EXPENSE_STAFF_SALARY
SELECT DISTINCT SD.SE_CPF_AMOUNT,ESS.ESS_CPF_AMOUNT FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT SD,EXPENSE_STAFF_SALARY ESS WHERE SD.SE_CPF_AMOUNT=ESS.ESS_CPF_AMOUNT 

-- LEVY AMOUNT
SELECT DISTINCT SE_LEVY_AMOUNT FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT WHERE SE_TYPE_OF_EXPENSE='SALARY ENTRY';
SELECT DISTINCT ESS_LEVY_AMOUNT FROM EXPENSE_STAFF_SALARY
SELECT DISTINCT SD.SE_LEVY_AMOUNT,ESS.ESS_LEVY_AMOUNT FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT SD,EXPENSE_STAFF_SALARY ESS WHERE SD.SE_LEVY_AMOUNT=ESS.ESS_LEVY_AMOUNT

-- SALARY_AMOUNT
SELECT DISTINCT SE_SALARY_AMOUNT FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT WHERE SE_TYPE_OF_EXPENSE='SALARY ENTRY';
SELECT DISTINCT ESS_SALARY_AMOUNT FROM EXPENSE_STAFF_SALARY
SELECT DISTINCT SD.SE_SALARY_AMOUNT,ESS.ESS_SALARY_AMOUNT FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT SD,EXPENSE_STAFF_SALARY ESS WHERE SD.SE_SALARY_AMOUNT=ESS.ESS_SALARY_AMOUNT

-- SALARY_COMMENTS
SELECT DISTINCT ESS_SALARY_COMMENTS FROM EXPENSE_STAFF_SALARY
SELECT DISTINCT SE_SALARY_COMMENTS FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT
SELECT DISTINCT SD.SE_SALARY_COMMENTS,ESS.ESS_SALARY_COMMENTS FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT SD,EXPENSE_STAFF_SALARY ESS WHERE SD.SE_SALARY_COMMENTS=ESS.ESS_SALARY_COMMENTS;

-- ULD_ID
SELECT DISTINCT ULD_ID FROM EXPENSE_STAFF_SALARY;
SELECT DISTINCT USERSTAMP FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT WHERE SE_TYPE_OF_EXPENSE='SALARY ENTRY';
SELECT DISTINCT A.USERSTAMP,B.ULD_LOGINID,B.ULD_ID,C.ULD_ID
FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT A INNER JOIN
USER_LOGIN_DETAILS B ON A.USERSTAMP= B.ULD_LOGINID
INNER JOIN
EXPENSE_STAFF_SALARY C ON B.ULD_ID=C.ULD_ID


-- ESS_TIMESTAMP
SELECT DISTINCT TIMESTAMP FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT WHERE SE_TYPE_OF_EXPENSE='SALARY ENTRY';
SELECT DISTINCT ESS_TIMESTAMP FROM EXPENSE_STAFF_SALARY;
SELECT DISTINCT SUBTIME(SD.TIMESTAMP,'08:00:00'),ESS.ESS_TIMESTAMP FROM  SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT SD,EXPENSE_STAFF_SALARY ESS WHERE SUBTIME(SD.TIMESTAMP,'08:00:00')=ESS.ESS_TIMESTAMP

-- EXPENSE_DETAIL_STAFF_SALARY

-- EMP_ID
SELECT EMP_ID FROM EXPENSE_DETAIL_STAFF_SALARY;
SELECT EMP_ID FROM EMPLOYEE_DETAILS;
SELECT EMP_ID FROM EXPENSE_DETAIL_STAFF_SALARY WHERE EMP_ID IN(SELECT EMP_ID FROM EMPLOYEE_DETAILS)

-- EDSS_CPF_NUMBER
SELECT DISTINCT EDSS_CPF_NUMBER FROM EXPENSE_DETAIL_STAFF_SALARY;
SELECT DISTINCT SED_CPF_NUMBER FROM SOURCE_04062014.STAFF_DETAIL_SCDB_FORMAT;
SELECT DISTINCT EDSS.EDSS_CPF_NUMBER,SD.SED_CPF_NUMBER FROM SOURCE_04062014.STAFF_DETAIL_SCDB_FORMAT SD,EXPENSE_DETAIL_STAFF_SALARY EDSS WHERE EDSS.EDSS_CPF_NUMBER=SD.SED_CPF_NUMBER

-- EDSS_CPF_AMOUNT
SELECT DISTINCT EDSS_CPF_AMOUNT FROM EXPENSE_DETAIL_STAFF_SALARY;
SELECT DISTINCT SED_CPF_AMOUNT FROM SOURCE_04062014.STAFF_DETAIL_SCDB_FORMAT;
SELECT DISTINCT EDSS.EDSS_CPF_AMOUNT,SD.SED_CPF_AMOUNT FROM SOURCE_04062014.STAFF_DETAIL_SCDB_FORMAT SD,EXPENSE_DETAIL_STAFF_SALARY EDSS WHERE EDSS.EDSS_CPF_AMOUNT=SD.SED_CPF_AMOUNT

-- EDSS_LEVY_AMOUNT
SELECT DISTINCT EDSS_LEVY_AMOUNT FROM EXPENSE_DETAIL_STAFF_SALARY;
SELECT DISTINCT SED_LEVY_AMOUNT FROM SOURCE_04062014.STAFF_DETAIL_SCDB_FORMAT;
SELECT DISTINCT EDSS.EDSS_LEVY_AMOUNT,SD.SED_LEVY_AMOUNT FROM SOURCE_04062014.STAFF_DETAIL_SCDB_FORMAT SD,EXPENSE_DETAIL_STAFF_SALARY EDSS WHERE EDSS.EDSS_LEVY_AMOUNT=SD.SED_LEVY_AMOUNT

-- EDSS_SALARY_AMOUNT
SELECT DISTINCT EDSS_SALARY_AMOUNT FROM EXPENSE_DETAIL_STAFF_SALARY;
SELECT DISTINCT SED_SALARY_AMOUNT FROM SOURCE_04062014.STAFF_DETAIL_SCDB_FORMAT;
SELECT DISTINCT EDSS.EDSS_SALARY_AMOUNT,SD.SED_SALARY_AMOUNT FROM SOURCE_04062014.STAFF_DETAIL_SCDB_FORMAT SD,EXPENSE_DETAIL_STAFF_SALARY EDSS WHERE EDSS.EDSS_SALARY_AMOUNT=SD.SED_SALARY_AMOUNT

-- EDSS_COMMENTS 
SELECT DISTINCT EDSS_COMMENTS FROM EXPENSE_DETAIL_STAFF_SALARY;


-- ULD_ID
SELECT DISTINCT ULD_ID FROM EXPENSE_DETAIL_STAFF_SALARY;
SELECT DISTINCT USERSTAMP FROM SOURCE_04062014.STAFF_DETAIL_SCDB_FORMAT;
SELECT DISTINCT A.USERSTAMP,B.ULD_LOGINID,B.ULD_ID,C.ULD_ID
FROM SOURCE_04062014.STAFF_DAILY_SCDB_FORMAT A INNER JOIN
USER_LOGIN_DETAILS B ON A.USERSTAMP= B.ULD_LOGINID
INNER JOIN
EXPENSE_DETAIL_STAFF_SALARY C ON B.ULD_ID=C.ULD_ID

-- EDSS_TIMESTAMP
SELECT DISTINCT EDSS_TIMESTAMP FROM EXPENSE_DETAIL_STAFF_SALARY;
SELECT DISTINCT TIMESTAMP FROM SOURCE_04062014.STAFF_DETAIL_SCDB_FORMAT;
SELECT DISTINCT SUBTIME(SD.TIMESTAMP,'08:00:00'),EDSS.EDSS_TIMESTAMP FROM  SOURCE_04062014.STAFF_DETAIL_SCDB_FORMAT SD,EXPENSE_DETAIL_STAFF_SALARY EDSS WHERE SUBTIME(SD.TIMESTAMP,'08:00:00')=EDSS.EDSS_TIMESTAMP
