-- VER1.0 STARTDATE:09/06/2014 ENDDATE:09/06/2014 ISSUE NO:566 COMMENT:12 DESC:IMPLEMENTED ROLL BACK AND COMMIT DONE BY:DHIVYA

DROP PROCEDURE IF EXISTS SP_MIG_EMAIL_INSERT;
CREATE PROCEDURE SP_MIG_EMAIL_INSERT(IN SOURCESCHEMA  VARCHAR(40),IN DESTINATIONSCHEMA  VARCHAR(40),IN MIGUSERSTAMP VARCHAR(50))
BEGIN
	DECLARE START_TIME TIME;
	DECLARE END_TIME TIME;
	DECLARE DURATION TIME;
    SET @LOGIN_ID=(SELECT CONCAT('SELECT ULD_ID INTO @ULDID FROM ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS WHERE ULD_LOGINID=','"',MIGUSERSTAMP,'"'));
    PREPARE LOGINID FROM @LOGIN_ID;
    EXECUTE LOGINID;
	SET @UPDATE_TEMP_CONFIG_SCDB_FORMAT=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_CONFIG_SCDB_FORMAT SET CF_TYPE = ''OCBC CC'' WHERE CF_TYPE =''OCBC_CC_MAIL_ID'''));
	PREPARE UPDATE_TEMP_CONFIG_SCDB_FORMAT_STMT FROM @UPDATE_TEMP_CONFIG_SCDB_FORMAT;
    EXECUTE UPDATE_TEMP_CONFIG_SCDB_FORMAT_STMT;
	SET @UPDATE_TEMP_CONFIG_SCDB_FORMAT=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_CONFIG_SCDB_FORMAT SET CF_DATA = ''kumar.r@ssomens.com'' WHERE CF_TYPE = ''OCBC CC'''));
	PREPARE UPDATE_TEMP_CONFIG_SCDB_FORMAT_STMT FROM @UPDATE_TEMP_CONFIG_SCDB_FORMAT;
    EXECUTE UPDATE_TEMP_CONFIG_SCDB_FORMAT_STMT;
	SET @UPDATE_TEMP_CONFIG_SCDB_FORMAT=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_CONFIG_SCDB_FORMAT SET CF_TYPE = ''OCBC TO'' WHERE CF_TYPE = ''OCBC_TO_MAIL_ID'''));
	PREPARE UPDATE_TEMP_CONFIG_SCDB_FORMAT_STMT FROM @UPDATE_TEMP_CONFIG_SCDB_FORMAT;
    EXECUTE UPDATE_TEMP_CONFIG_SCDB_FORMAT_STMT;
	SET @UPDATE_TEMP_CONFIG_SCDB_FORMAT=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_CONFIG_SCDB_FORMAT SET CF_DATA = ''dhandapani.sattanathan@ssomens.com'' WHERE CF_TYPE = ''OCBC TO'''));
	PREPARE UPDATE_TEMP_CONFIG_SCDB_FORMAT_STMT FROM @UPDATE_TEMP_CONFIG_SCDB_FORMAT;
    EXECUTE UPDATE_TEMP_CONFIG_SCDB_FORMAT_STMT;
	SET @UPDATE_TEMP_CONFIG_SCDB_FORMAT=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_CONFIG_SCDB_FORMAT SET CF_TYPE = ''OCBC CONFIRM'' WHERE CF_TYPE = ''OCBC_CONFIRM_MAIL_ID'''));
	PREPARE UPDATE_TEMP_CONFIG_SCDB_FORMAT_STMT FROM @UPDATE_TEMP_CONFIG_SCDB_FORMAT;
    EXECUTE UPDATE_TEMP_CONFIG_SCDB_FORMAT_STMT;
	SET @UPDATE_TEMP_CONFIG_SCDB_FORMAT=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_CONFIG_SCDB_FORMAT SET CF_DATA = ''punitha.shanmugam@ssomens.com'' WHERE CF_TYPE = ''OCBC CONFIRM'''));
    PREPARE UPDATE_TEMP_CONFIG_SCDB_FORMAT_STMT FROM @UPDATE_TEMP_CONFIG_SCDB_FORMAT;
    EXECUTE UPDATE_TEMP_CONFIG_SCDB_FORMAT_STMT;
	SET FOREIGN_KEY_CHECKS=0;
	SET START_TIME = (SELECT CURTIME());
	SET @DROP_EMAIL_TEMPLATE=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.EMAIL_TEMPLATE'));
	PREPARE DROP_EMAIL_TEMPLATE_STMT FROM @DROP_EMAIL_TEMPLATE;
    EXECUTE DROP_EMAIL_TEMPLATE_STMT;
	SET @CREATE_EMAIL_TEMPLATE=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.EMAIL_TEMPLATE(
	ET_ID INTEGER NOT NULL AUTO_INCREMENT,
	ET_EMAIL_SCRIPT	VARCHAR(100) UNIQUE	NOT NULL,
	PRIMARY KEY(ET_ID))'));
	PREPARE CREATE_EMAIL_TEMPLATE_STMT FROM @CREATE_EMAIL_TEMPLATE;
    EXECUTE CREATE_EMAIL_TEMPLATE_STMT;
	SET @INSERT_EMAIL_TEMPLATE=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.EMAIL_TEMPLATE(ET_EMAIL_SCRIPT)
	(SELECT ESQL.SCRIPT_NAME FROM ',SOURCESCHEMA,'.EMAIL_SQL_FORMAT ESQL  LEFT JOIN ',DESTINATIONSCHEMA,'.TEMP_CONFIG_SCDB_FORMAT TCSCDB ON ESQL.SCRIPT_NAME = TCSCDB.CF_TYPE WHERE ESQL.SCRIPT_NAME IS NOT NULL)'));
	SET END_TIME = (SELECT CURTIME());
	SET DURATION=(SELECT TIMEDIFF(END_TIME,START_TIME));
	PREPARE INSERT_EMAIL_TEMPLATE_STMT FROM @INSERT_EMAIL_TEMPLATE;
    EXECUTE INSERT_EMAIL_TEMPLATE_STMT;
	SET @COUNT_EMAILTEMPLATESQLFORMAT=(SELECT CONCAT('SELECT COUNT(ESQL.SCRIPT_NAME) INTO @COUNT_EMAIL_TEMPLATE_SQL_FORMAT FROM ',SOURCESCHEMA,'.EMAIL_SQL_FORMAT ESQL  LEFT JOIN ',DESTINATIONSCHEMA,'.TEMP_CONFIG_SCDB_FORMAT TCSCDB ON ESQL.SCRIPT_NAME = TCSCDB.CF_TYPE WHERE ESQL.SCRIPT_NAME IS NOT NULL'));
	PREPARE COUNT_EMAILTEMPLATESQLFORMAT_STMT FROM @COUNT_EMAILTEMPLATESQLFORMAT;
    EXECUTE COUNT_EMAILTEMPLATESQLFORMAT_STMT;
	SET @COUNT_SPLITING_EMAILTEMPLATE=(SELECT CONCAT('SELECT COUNT(*) INTO @COUNT_SPLITING_EMAIL_TEMPLATE FROM ',DESTINATIONSCHEMA,'.EMAIL_TEMPLATE'));
	PREPARE COUNT_SPLITING_EMAILTEMPLATE_STMT FROM @COUNT_SPLITING_EMAILTEMPLATE;
    EXECUTE COUNT_SPLITING_EMAILTEMPLATE_STMT;
	SET @REJECTION_COUNT=(@COUNT_EMAIL_TEMPLATE_SQL_FORMAT-@COUNT_SPLITING_EMAIL_TEMPLATE);		
	SET @POSTAPIDSTMT=(SELECT CONCAT('SELECT POSTAP_ID INTO @POSTAPID FROM POST_AUDIT_PROFILE WHERE POSTAP_DATA=',"'EMAIL_TEMPLATE'"));
    PREPARE POSTAPSTMT FROM @POSTAPIDSTMT;
    EXECUTE POSTAPSTMT;
    SET @PREASPSTMT=(SELECT CONCAT('SELECT PREASP_ID INTO @PREASPID FROM PRE_AUDIT_SUB_PROFILE WHERE PREASP_DATA=',"'EMAIL_TEMPLATE'"));
    PREPARE PREASPIDSTMT FROM @PREASPSTMT;
    EXECUTE PREASPIDSTMT;
    SET @PREAMPSTMT=(SELECT CONCAT('SELECT PREAMP_ID INTO @PREAMPID FROM PRE_AUDIT_MAIN_PROFILE WHERE PREAMP_DATA=',"'EMAIL'"));
    PREPARE PREAMPIDSTMT FROM @PREAMPSTMT;
	EXECUTE PREAMPIDSTMT;
    SET @DUR=DURATION;
	UPDATE PRE_AUDIT_SUB_PROFILE SET PREASP_NO_OF_REC=@COUNT_EMAIL_TEMPLATE_SQL_FORMAT WHERE PREASP_DATA='EMAIL_TEMPLATE';	
    INSERT INTO POST_AUDIT_HISTORY(POSTAP_ID,POSTAH_NO_OF_REC,PREASP_ID,PREAMP_ID,POSTAH_DURATION,POSTAH_NO_OF_REJ,ULD_ID)VALUES(@POSTAPID,@COUNT_SPLITING_EMAIL_TEMPLATE,@PREASPID,@PREAMPID,@DUR,@REJECTION_COUNT,@ULDID);     		
	SET START_TIME = (SELECT CURTIME());
	SET @DROP_EMAIL_TEMPLATE_DETAILS=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.EMAIL_TEMPLATE_DETAILS'));
	PREPARE DROP_EMAIL_TEMPLATE_DETAILS_STMT FROM @DROP_EMAIL_TEMPLATE_DETAILS;
    EXECUTE DROP_EMAIL_TEMPLATE_DETAILS_STMT;
    SET @CREATE_EMAIL_TEMPLATE_DETAILS=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.EMAIL_TEMPLATE_DETAILS
	(ETD_ID INTEGER NOT NULL AUTO_INCREMENT,
	ET_ID INTEGER NOT NULL,
	ETD_EMAIL_SUBJECT VARCHAR(1000) NOT NULL,
	ETD_EMAIL_BODY VARCHAR(1000) NOT NULL,
	ULD_ID INTEGER(2) NOT NULL,
	ETD_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(ETD_ID),
	FOREIGN KEY(ET_ID) REFERENCES ',DESTINATIONSCHEMA,'.EMAIL_TEMPLATE(ET_ID),
	FOREIGN KEY(ULD_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS(ULD_ID))'));
	PREPARE CREATE_EMAIL_TEMPLATE_DETAILS_STMT FROM @CREATE_EMAIL_TEMPLATE_DETAILS;
    EXECUTE CREATE_EMAIL_TEMPLATE_DETAILS_STMT; 
   	SET @INSERT_EMAIL_TEMPLATE_DETAILS=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.EMAIL_TEMPLATE_DETAILS(ET_ID,ETD_EMAIL_SUBJECT,ETD_EMAIL_BODY,ULD_ID,ETD_TIMESTAMP)( SELECT ET.ET_ID,ESQL.SUBJECT,ESQL.BODY,ULD.ULD_ID,ESQL.TIMESTAMP FROM  ',DESTINATIONSCHEMA,'.EMAIL_TEMPLATE ET LEFT JOIN ',SOURCESCHEMA,'.EMAIL_SQL_FORMAT ESQL ON ET.ET_EMAIL_SCRIPT = ESQL.SCRIPT_NAME left join ',SOURCESCHEMA,'.EMAIL_SCDB_FORMAT ESCDB on ESQL.BODY=ESCDB.BODY,',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS ULD WHERE ESQL.SUBJECT IS NOT NULL AND ESQL.BODY IS NOT NULL AND  ULD.ULD_LOGINID=ESQL.USER_STAMP )'));
	PREPARE INSERT_EMAIL_TEMPLATE_DETAILS_STMT FROM @INSERT_EMAIL_TEMPLATE_DETAILS;
    EXECUTE INSERT_EMAIL_TEMPLATE_DETAILS_STMT;
	SET END_TIME = (SELECT CURTIME());
	SET DURATION=(SELECT TIMEDIFF(END_TIME,START_TIME)); 
	SET @COUNT_EMAILTEMPLATEDETAILSSQLFORMAT=(SELECT CONCAT('SELECT COUNT(*) INTO @COUNT_EMAIL_TEMPLATE_DETAILS_SQL_FORMAT FROM ',DESTINATIONSCHEMA,'.EMAIL_TEMPLATE ET LEFT JOIN ',SOURCESCHEMA,'.EMAIL_SQL_FORMAT ESQL ON ET.ET_EMAIL_SCRIPT = ESQL.SCRIPT_NAME left join ',SOURCESCHEMA,'.EMAIL_SCDB_FORMAT ESCDB on ESQL.BODY=ESCDB.BODY,',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS ULD WHERE ESQL.SUBJECT IS NOT NULL AND ESQL.BODY IS NOT NULL AND  ULD.ULD_LOGINID=ESQL.USER_STAMP'));
	PREPARE COUNT_EMAILTEMPLATEDETAILSSQLFORMAT_STMT FROM @COUNT_EMAILTEMPLATEDETAILSSQLFORMAT;
    EXECUTE COUNT_EMAILTEMPLATEDETAILSSQLFORMAT_STMT;    
	SET @COUNT_SPLITING_EMAILTEMPLATEDETAILS=(SELECT CONCAT('SELECT COUNT(*) INTO @COUNT_SPLITING_EMAIL_TEMPLATE_DETAILS FROM ',DESTINATIONSCHEMA,'.EMAIL_TEMPLATE_DETAILS'));
	PREPARE COUNT_SPLITING_EMAILTEMPLATEDETAILS_STMT FROM @COUNT_SPLITING_EMAILTEMPLATEDETAILS;
    EXECUTE COUNT_SPLITING_EMAILTEMPLATEDETAILS_STMT;    
	SET @REJECTION_COUNT=(@COUNT_EMAIL_TEMPLATE_DETAILS_SQL_FORMAT-@COUNT_SPLITING_EMAIL_TEMPLATE_DETAILS);      
    SET @POSTAPIDSTMT=(SELECT CONCAT('SELECT POSTAP_ID INTO @POSTAPID FROM POST_AUDIT_PROFILE WHERE POSTAP_DATA=',"'EMAIL_TEMPLATE_DETAILS'"));
    PREPARE POSTAPSTMT FROM @POSTAPIDSTMT;
    EXECUTE POSTAPSTMT;    
    SET @PREASPSTMT=(SELECT CONCAT('SELECT PREASP_ID INTO @PREASPID FROM PRE_AUDIT_SUB_PROFILE WHERE PREASP_DATA=',"'EMAIL_TEMPLATE_DETAILS'"));
    PREPARE PREASPIDSTMT FROM @PREASPSTMT;
    EXECUTE PREASPIDSTMT;     
    SET @PREAMPSTMT=(SELECT CONCAT('SELECT PREAMP_ID INTO @PREAMPID FROM PRE_AUDIT_MAIN_PROFILE WHERE PREAMP_DATA=',"'EMAIL'"));
    PREPARE PREAMPIDSTMT FROM @PREAMPSTMT;
	EXECUTE PREAMPIDSTMT;    
    SET @DUR=DURATION;   
	UPDATE PRE_AUDIT_SUB_PROFILE SET PREASP_NO_OF_REC=@COUNT_EMAIL_TEMPLATE_DETAILS_SQL_FORMAT WHERE PREASP_DATA='EMAIL_TEMPLATE_DETAILS';	
    INSERT INTO POST_AUDIT_HISTORY(POSTAP_ID,POSTAH_NO_OF_REC,PREASP_ID,PREAMP_ID,POSTAH_DURATION,POSTAH_NO_OF_REJ,ULD_ID)VALUES(@POSTAPID,@COUNT_SPLITING_EMAIL_TEMPLATE_DETAILS,@PREASPID,@PREAMPID,@DUR,@REJECTION_COUNT,@ULDID);     		
	SET START_TIME = (SELECT CURTIME());
	SET @DROP_EMAIL_PROFILE=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.EMAIL_PROFILE'));
	PREPARE DROP_EMAIL_PROFILE_STMT FROM @DROP_EMAIL_PROFILE;
    EXECUTE DROP_EMAIL_PROFILE_STMT;
	SET @CREATE_EMAIL_PROFILE=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.EMAIL_PROFILE(
	EP_ID INTEGER NOT NULL AUTO_INCREMENT,
	EP_EMAIL_DOMAIN	VARCHAR(50) UNIQUE NOT NULL,
	EP_NON_IP_FLAG CHAR(2) NULL,
	PRIMARY KEY(EP_ID))'));
	PREPARE CREATE_EMAIL_PROFILE_STMT FROM @CREATE_EMAIL_PROFILE;
    EXECUTE CREATE_EMAIL_PROFILE_STMT;
	SET @INSERT_EMAIL_PROFILE=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.EMAIL_PROFILE(EP_EMAIL_DOMAIN,EP_NON_IP_FLAG) 
	(SELECT DISTINCT EMAIL_DOMAIN,FLAG FROM ',SOURCESCHEMA,'.EMAIL_SQL_FORMAT WHERE EMAIL_DOMAIN IS NOT NULL)'));
	PREPARE INSERT_EMAIL_PROFILE_STMT FROM @INSERT_EMAIL_PROFILE;
    EXECUTE INSERT_EMAIL_PROFILE_STMT;
	SET END_TIME = (SELECT CURTIME());
	SET DURATION=(SELECT TIMEDIFF(END_TIME,START_TIME));
	SET @COUNT_EMAILPROFILESQLFORMAT=(SELECT CONCAT('SELECT COUNT(DISTINCT(EMAIL_DOMAIN)) INTO @COUNT_EMAIL_PROFILE_SQL_FORMAT FROM ',SOURCESCHEMA,'.EMAIL_SQL_FORMAT WHERE EMAIL_DOMAIN IS NOT NULL'));
	PREPARE COUNT_EMAILPROFILESQLFORMAT_STMT FROM @COUNT_EMAILPROFILESQLFORMAT;
    EXECUTE COUNT_EMAILPROFILESQLFORMAT_STMT;
	SET @COUNT_SPLITING_EMAILPROFILE=(SELECT CONCAT('SELECT COUNT(*) INTO @COUNT_SPLITING_EMAIL_PROFILE FROM ',DESTINATIONSCHEMA,'.EMAIL_PROFILE'));
	PREPARE COUNT_SPLITING_EMAILPROFILE_STMT FROM @COUNT_SPLITING_EMAILPROFILE;
    EXECUTE COUNT_SPLITING_EMAILPROFILE_STMT;
	SET @REJECTION_COUNT=(@COUNT_EMAIL_PROFILE_SQL_FORMAT-@COUNT_SPLITING_EMAIL_PROFILE);
    SET @POSTAPIDSTMT=(SELECT CONCAT('SELECT POSTAP_ID INTO @POSTAPID FROM POST_AUDIT_PROFILE WHERE POSTAP_DATA=',"'EMAIL_PROFILE'"));
    PREPARE POSTAPSTMT FROM @POSTAPIDSTMT;
    EXECUTE POSTAPSTMT;
    SET @PREASPSTMT=(SELECT CONCAT('SELECT PREASP_ID INTO @PREASPID FROM PRE_AUDIT_SUB_PROFILE WHERE PREASP_DATA=',"'EMAIL_PROFILE'"));
    PREPARE PREASPIDSTMT FROM @PREASPSTMT;
    EXECUTE PREASPIDSTMT;
    SET @PREAMPSTMT=(SELECT CONCAT('SELECT PREAMP_ID INTO @PREAMPID FROM PRE_AUDIT_MAIN_PROFILE WHERE PREAMP_DATA=',"'EMAIL'"));
    PREPARE PREAMPIDSTMT FROM @PREAMPSTMT;
	EXECUTE PREAMPIDSTMT;
    SET @DUR=DURATION;
	UPDATE PRE_AUDIT_SUB_PROFILE SET PREASP_NO_OF_REC=@COUNT_EMAIL_PROFILE_SQL_FORMAT WHERE PREASP_DATA='EMAIL_PROFILE';	
    INSERT INTO POST_AUDIT_HISTORY(POSTAP_ID,POSTAH_NO_OF_REC,PREASP_ID,PREAMP_ID,POSTAH_DURATION,POSTAH_NO_OF_REJ,ULD_ID)VALUES(@POSTAPID,@COUNT_SPLITING_EMAIL_PROFILE,@PREASPID,@PREAMPID,@DUR,@REJECTION_COUNT,@ULDID);     		
	SET START_TIME = (SELECT CURTIME());
	SET @DROP_EMAIL_LIST=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.EMAIL_LIST'));
	PREPARE DROP_EMAIL_LIST_STMT FROM @DROP_EMAIL_LIST;
    EXECUTE DROP_EMAIL_LIST_STMT;
	SET @CREATE_EMAIL_LIST=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.EMAIL_LIST(
	EL_ID INTEGER NOT NULL AUTO_INCREMENT,
	EP_ID INTEGER NOT NULL,EL_EMAIL_ID VARCHAR(50) NOT NULL,
	ULD_ID INTEGER(2) NOT NULL,
	EL_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(EL_ID),FOREIGN KEY(EP_ID) REFERENCES ',DESTINATIONSCHEMA,'.EMAIL_PROFILE(EP_ID),
	FOREIGN KEY(ULD_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS(ULD_ID))'));
	PREPARE CREATE_EMAIL_LIST_STMT FROM @CREATE_EMAIL_LIST;
    EXECUTE CREATE_EMAIL_LIST_STMT;
	SET @INSERT_EMAIL_LIST=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.EMAIL_LIST(EP_ID,EL_EMAIL_ID,ULD_ID,EL_TIMESTAMP)
	(SELECT EP.EP_ID, ESQL.EMAIL_ID, ULD.ULD_ID,ESQL.TIMESTAMP FROM ',SOURCESCHEMA,'.EMAIL_SQL_FORMAT ESQL INNER JOIN ',DESTINATIONSCHEMA,'.EMAIL_PROFILE EP , ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS ULD WHERE EP.EP_EMAIL_DOMAIN = ESQL.EMAIL_DOMAIN AND ULD.ULD_LOGINID=ESQL.USER_STAMP)'));
	PREPARE INSERT_EMAIL_LIST_STMT FROM @INSERT_EMAIL_LIST;
    EXECUTE INSERT_EMAIL_LIST_STMT;
	SET END_TIME = (SELECT CURTIME());
	SET DURATION=(SELECT TIMEDIFF(END_TIME,START_TIME));
	SET @COUNT_EMAILLISTSQLFORMAT=(SELECT CONCAT('SELECT COUNT(*) INTO @COUNT_EMAIL_LIST_SQL_FORMAT FROM ',SOURCESCHEMA,'.EMAIL_SQL_FORMAT ESQL INNER JOIN ',DESTINATIONSCHEMA,'.EMAIL_PROFILE EP WHERE EP.EP_EMAIL_DOMAIN = ESQL.EMAIL_DOMAIN'));
	PREPARE COUNT_EMAILLISTSQLFORMAT_STMT FROM @COUNT_EMAILLISTSQLFORMAT;
    EXECUTE COUNT_EMAILLISTSQLFORMAT_STMT;
	SET @COUNT_SPLITING_EMAILLIST=(SELECT CONCAT('SELECT COUNT(*) INTO @COUNT_SPLITING_EMAIL_LIST FROM ',DESTINATIONSCHEMA,'.EMAIL_LIST'));
	PREPARE COUNT_SPLITING_EMAILLIST_STMT FROM @COUNT_SPLITING_EMAILLIST;
    EXECUTE COUNT_SPLITING_EMAILLIST_STMT;
	SET @REJECTION_COUNT=(@COUNT_EMAIL_LIST_SQL_FORMAT-@COUNT_SPLITING_EMAIL_LIST);
    SET @POSTAPIDSTMT=(SELECT CONCAT('SELECT POSTAP_ID INTO @POSTAPID FROM POST_AUDIT_PROFILE WHERE POSTAP_DATA=',"'EMAIL_LIST'"));
    PREPARE POSTAPSTMT FROM @POSTAPIDSTMT;
    EXECUTE POSTAPSTMT;
    SET @PREASPSTMT=(SELECT CONCAT('SELECT PREASP_ID INTO @PREASPID FROM PRE_AUDIT_SUB_PROFILE WHERE PREASP_DATA=',"'EMAIL_LIST'"));
    PREPARE PREASPIDSTMT FROM @PREASPSTMT;
    EXECUTE PREASPIDSTMT;
    SET @PREAMPSTMT=(SELECT CONCAT('SELECT PREAMP_ID INTO @PREAMPID FROM PRE_AUDIT_MAIN_PROFILE WHERE PREAMP_DATA=',"'EMAIL'"));
    PREPARE PREAMPIDSTMT FROM @PREAMPSTMT;
	EXECUTE PREAMPIDSTMT;
    SET @DUR=DURATION;
	UPDATE PRE_AUDIT_SUB_PROFILE SET PREASP_NO_OF_REC=@COUNT_EMAIL_LIST_SQL_FORMAT WHERE PREASP_DATA='EMAIL_LIST';	
    INSERT INTO POST_AUDIT_HISTORY(POSTAP_ID,POSTAH_NO_OF_REC,PREASP_ID,PREAMP_ID,POSTAH_DURATION,POSTAH_NO_OF_REJ,ULD_ID)VALUES(@POSTAPID,@COUNT_SPLITING_EMAIL_LIST,@PREASPID,@PREAMPID,@DUR,@REJECTION_COUNT,@ULDID);     		
    SET @DROP_TEMP_CONFIG_SCDB_FORMAT=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_CONFIG_SCDB_FORMAT'));
    PREPARE DROP_TEMP_CONFIG_SCDB_FORMAT_STMT FROM @DROP_TEMP_CONFIG_SCDB_FORMAT;
	EXECUTE DROP_TEMP_CONFIG_SCDB_FORMAT_STMT;
	SET FOREIGN_KEY_CHECKS=1;
    END;
	CALL(SOURCESCHEMA,DESTINATIONSCHEMA,MIGUSERSTAMP);