DROP PROCEDURE IF EXISTS SP_ERM_INSERT;
CREATE PROCEDURE SP_ERM_INSERT(CUSTOMERNAME VARCHAR(40),RENT DECIMAL(7,2),MOVINGDATE DATE,MINSTAY VARCHAR(10),
ERMODATA VARCHAR(40),NCDATA TEXT,NOOFGUESTS VARCHAR(10),AGE VARCHAR(10),CONTACTNO BIGINT(15),EMAILID VARCHAR(40),
COMMENTS TEXT,USERSTAMP VARCHAR(50),OUT ERM_SUCCESSFLAG INTEGER)
BEGIN
DECLARE USERSTAMP_ID INTEGER(2);
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN 
ROLLBACK;
END;
START TRANSACTION;
SET ERM_SUCCESSFLAG=0;
CALL SP_CHANGE_USERSTAMP_AS_ULDID(USERSTAMP,@ULDID);
SET USERSTAMP_ID = (SELECT @ULDID);
IF (CUSTOMERNAME IS NOT NULL AND RENT IS NOT NULL AND MOVINGDATE IS NOT NULL AND MINSTAY IS NOT NULL AND 
ERMODATA IS NOT NULL AND COMMENTS IS NOT NULL AND USERSTAMP IS NOT NULL)THEN
IF NOT EXISTS(SELECT ERMO_DATA FROM ERM_OCCUPATION_DETAILS WHERE ERMO_DATA=ERMODATA)THEN
INSERT INTO ERM_OCCUPATION_DETAILS(ERMO_DATA,ULD_ID)VALUES(ERMODATA,USERSTAMP_ID);
SET ERM_SUCCESSFLAG=1;
END IF;
INSERT INTO ERM_ENTRY_DETAILS(ERM_CUST_NAME,ERM_RENT,ERM_MOVING_DATE,ERM_MIN_STAY,ERMO_ID,NC_ID,
ERM_NO_OF_GUESTS,ERM_AGE,ERM_CONTACT_NO,ERM_EMAIL_ID,ERM_COMMENTS,ULD_ID)VALUES(CUSTOMERNAME,RENT,
MOVINGDATE,MINSTAY,(SELECT ERMO_ID FROM ERM_OCCUPATION_DETAILS WHERE ERMO_DATA=ERMODATA),(SELECT NC_ID FROM NATIONALITY_CONFIGURATION WHERE NC_DATA=NCDATA),
NOOFGUESTS,AGE,CONTACTNO,EMAILID,COMMENTS,USERSTAMP_ID);
SET ERM_SUCCESSFLAG=1;
END IF;
COMMIT;
END;