SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE  REPORT_CONFIGURATION;
TRUNCATE TABLE  CHEQUE_CONFIGURATION;
TRUNCATE TABLE  BANKTT_CONFIGURATION;
TRUNCATE TABLE  ERM_CONFIGURATION;
TRUNCATE TABLE  USER_RIGHTS_CONFIGURATION;
TRUNCATE TABLE  NATIONALITY_CONFIGURATION;
TRUNCATE TABLE  TRIGGER_CONFIGURATION;
TRUNCATE TABLE  ERROR_MESSAGE_CONFIGURATION;
TRUNCATE TABLE  DEPOSIT_DEDUCTION_CONFIGURATION;
TRUNCATE TABLE  EXPENSE_CONFIGURATION;
TRUNCATE TABLE  OCBC_CONFIGURATION;
TRUNCATE TABLE  ACCESS_CONFIGURATION;
TRUNCATE TABLE  PAYMENT_CONFIGURATION;
TRUNCATE TABLE  UNIT_CONFIGURATION;
TRUNCATE TABLE  CUSTOMER_CONFIGURATION;
TRUNCATE TABLE  CONFIGURATION;
TRUNCATE TABLE  CONFIGURATION_PROFILE;

TRUNCATE TABLE  UNIT_ACCOUNT_DETAILS;
TRUNCATE TABLE  UNIT_LOGIN_DETAILS;
TRUNCATE TABLE  UNIT_ACCESS_STAMP_DETAILS;
TRUNCATE TABLE  UNIT_ROOM_TYPE_DETAILS;
TRUNCATE TABLE  UNIT_STAMP_DUTY_TYPE;
TRUNCATE TABLE  UNIT_DETAILS;
TRUNCATE TABLE  UNIT;

TRUNCATE TABLE  CUSTOMER_TIME_PROFILE;
TRUNCATE TABLE  CUSTOMER_PERSONAL_DETAILS;
TRUNCATE TABLE  CUSTOMER_TERMINATION_DETAILS;
TRUNCATE TABLE  CUSTOMER_ACCESS_CARD_DETAILS;
TRUNCATE TABLE  CUSTOMER_FEE_DETAILS;
TRUNCATE TABLE  CUSTOMER_PAYMENT_PROFILE;
TRUNCATE TABLE  CUSTOMER_ENTRY_DETAILS;
TRUNCATE TABLE  CUSTOMER_COMPANY_DETAILS;
TRUNCATE TABLE  CUSTOMER;

TRUNCATE TABLE  EMAIL_TEMPLATE;
TRUNCATE TABLE  EMAIL_TEMPLATE_DETAILS;
TRUNCATE TABLE  EMAIL_PROFILE;
TRUNCATE TABLE  EMAIL_LIST

TRUNCATE TABLE  PAYMENT_DETAILS;
TRUNCATE TABLE  PAYMENT_PROFILE;

TRUNCATE TABLE  TEMP_TICKLER_UPDATE;
TRUNCATE TABLE  TICKLER_HISTORY;
TRUNCATE TABLE  TICKLER_PROFILE;

TRUNCATE TABLE  POST_AUDIT_HISTORY;
TRUNCATE TABLE  PRE_AUDIT_HISTORY;
TRUNCATE TABLE  POST_AUDIT_PROFILE;
TRUNCATE TABLE  PRE_AUDIT_PROFILE;

TRUNCATE TABLE  EMPLOYEE_CARD_DETAILS;
TRUNCATE TABLE  EMPLOYEE_DETAILS;

TRUNCATE TABLE  EXPENSE_AGENT;
TRUNCATE TABLE  EXPENSE_STAFF;
TRUNCATE TABLE  EXPENSE_STAFF_SALARY;
TRUNCATE TABLE  EXPENSE_DETAIL_STAFF_SALARY;

TRUNCATE TABLE  EXPENSE_DETAIL_CARPARK;
TRUNCATE TABLE  EXPENSE_DETAIL_AIRCON_SERVICE;
TRUNCATE TABLE  EXPENSE_DETAIL_DIGITAL_VOICE;
TRUNCATE TABLE  EXPENSE_DETAIL_ELECTRICITY;
TRUNCATE TABLE  EXPENSE_DETAIL_STARHUB;
TRUNCATE TABLE  EXPENSE_AIRCON_SERVICE_BY;

TRUNCATE TABLE  EXPENSE_HOUSEKEEPING_UNIT;
TRUNCATE TABLE  EXPENSE_HOUSEKEEPING_PAYMENT;
TRUNCATE TABLE  EXPENSE_HOUSEKEEPING;
TRUNCATE TABLE  EXPENSE_PETTY_CASH;
TRUNCATE TABLE  EXPENSE_PURCHASE_NEW_CARD;
TRUNCATE TABLE  EXPENSE_AIRCON_SERVICE;
TRUNCATE TABLE  EXPENSE_MOVING_IN_AND_OUT ;
TRUNCATE TABLE  EXPENSE_CARPARK;
TRUNCATE TABLE  EXPENSE_FACILITY_USE;
TRUNCATE TABLE  EXPENSE_DIGITAL_VOICE;
TRUNCATE TABLE  EXPENSE_STARHUB;
TRUNCATE TABLE  EXPENSE_ELECTRICITY;
TRUNCATE TABLE  EXPENSE_UNIT;

TRUNCATE TABLE  EXPENSE_CAR_LOAN;
TRUNCATE TABLE  EXPENSE_BABY;
TRUNCATE TABLE  EXPENSE_CAR;
TRUNCATE TABLE  EXPENSE_PERSONAL;

TRUNCATE TABLE  USER_FILE_DETAILS;
TRUNCATE TABLE  USER_MENU_DETAILS;
TRUNCATE TABLE  USER_ACCESS;
TRUNCATE TABLE  USER_LOGIN_DETAILS;
TRUNCATE TABLE  ROLE_CREATION;
TRUNCATE TABLE  MENU_PROFILE;

TRUNCATE TABLE  TRIGGER_EXECUTION_DETAILS;

TRUNCATE TABLE  BANK_TRANSFER_STATUS;
TRUNCATE TABLE  BANK_TRANSFER_TYPE;
TRUNCATE TABLE  BANK_TRANSFER_CHARGES_TO;
TRUNCATE TABLE  BANK_TRANSFER_MODELS;
TRUNCATE TABLE  BANK_TRANSFER_CREATED_BY;
TRUNCATE TABLE  BANK_TRANSFER;
TRUNCATE TABLE  BANK_TRANSFER_DETAIL;

TRUNCATE TABLE  CHEQUE_ENTRY_DETAILS;
TRUNCATE TABLE  CHEQUE_STATUS_DETAILS;

TRUNCATE TABLE  ERM_ENTRY_DETAILS;
TRUNCATE TABLE  ERM_OCCUPATION_DETAILS;

TRUNCATE TABLE  OCBC_BANK_RECORDS;
SET FOREIGN_KEY_CHECKS=1;
