-- version:0.7 -- sdate:19/03/2014 -- edate:22/03/2014 -- issue:810 --COMMENT NO: 8--desc:CALCULATED DURATION OF THIS SP --doneby:DHIVYA
-- version:0.6 -- sdate:19/03/2014 -- edate:26/03/2014 -- issue:765 --COMMENT NO: 8--desc:UPDATED SP DYNAMICALLY --doneby:SAFI
-- version:0.5 -- sdate:17/03/2014 -- edate:17/03/2014 -- issue:765 --desc:droped temp table --doneby:RL
--version:0.4 --sdate:26/02/2014 --edate:26/02/2014 --issue:750 --desc:userstamp changed as uld_id --done by:RL
--version:0.3 --sdate:20/02/2014 --edate:20/02/2014 --issue:594 --comment:104 --done by:DHIVYA
--version:0.2 --sdate:24/01/2014 --edate:30/01/2014 --issue:594 --desc:changed migration.rental_scdb_format as rental_scdb_format n update rec version --doneby:RL


DROP PROCEDURE IF EXISTS SP_TEMP_RENTAL_SCDB_FORMAT_INSERT;
CREATE PROCEDURE SP_TEMP_RENTAL_SCDB_FORMAT_INSERT(IN SOURCESCHEMA  VARCHAR(40),IN DESTINATIONSCHEMA  VARCHAR(40))
BEGIN
DECLARE STARTTIME TIME;
DECLARE ENDTIME TIME;
DECLARE DURATION TIME;
SET STARTTIME=(SELECT CURTIME());
SET FOREIGN_KEY_CHECKS=0;
    SET @DROP_TEMP_RENTAL_SCDB_FORMAT=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_RENTAL_SCDB_FORMAT'));
    PREPARE DROP_TEMP_RENTAL_SCDB_FORMAT_STMT FROM @DROP_TEMP_RENTAL_SCDB_FORMAT;
    EXECUTE DROP_TEMP_RENTAL_SCDB_FORMAT_STMT;
    SET @CREATE_TEMP_RENTAL_SCDB_FORMAT=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.TEMP_RENTAL_SCDB_FORMAT LIKE ',SOURCESCHEMA,'.RENTAL_SCDB_FORMAT'));
    PREPARE CREATE_TEMP_RENTAL_SCDB_FORMAT_STMT FROM @CREATE_TEMP_RENTAL_SCDB_FORMAT;
    EXECUTE CREATE_TEMP_RENTAL_SCDB_FORMAT_STMT;    
    SET @INSERT_TEMP_RENTAL_SCDB_FORMAT=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_RENTAL_SCDB_FORMAT  SELECT * FROM ',SOURCESCHEMA,'.RENTAL_SCDB_FORMAT'));
    PREPARE INSERT_TEMP_RENTAL_SCDB_FORMAT_STMT FROM @INSERT_TEMP_RENTAL_SCDB_FORMAT;
    EXECUTE INSERT_TEMP_RENTAL_SCDB_FORMAT_STMT;
	SET @ALTER_TEMP_RENTAL_SCDB_FORMAT=(SELECT CONCAT('ALTER TABLE ',DESTINATIONSCHEMA,'.TEMP_RENTAL_SCDB_FORMAT ADD COLUMN (RD_AMOUNT VARCHAR(255) NULL,RPP_ID VARCHAR(255) NULL)'));
	PREPARE ALTER_TEMP_RENTAL_SCDB_FORMAT_STMT FROM @ALTER_TEMP_RENTAL_SCDB_FORMAT;
    EXECUTE ALTER_TEMP_RENTAL_SCDB_FORMAT_STMT;	
	SET @UPDATE_TEMP_RENTAL_SCDB_FORMAT=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_RENTAL_SCDB_FORMAT SET
    RD_AMOUNT = CONCAT(IFNULL(RENTAL_DEPOSIT,',"'" "'",'), IFNULL(RENTAL_DEPOSIT_REFUND,',"'" "'",'),  IFNULL(RENTAL_AMOUNT,',"'" "'",'), IFNULL(RENTAL_PROCESSING_FEE,',"'" "'",'), IFNULL(RENTAL_CLEANING_FEE,',"' " "'",'))'));
	PREPARE UPDATE_TEMP_RENTAL_SCDB_FORMAT_STMT FROM @UPDATE_TEMP_RENTAL_SCDB_FORMAT;
    EXECUTE UPDATE_TEMP_RENTAL_SCDB_FORMAT_STMT; 	
	SET @UPDATE_RENT_AMOUNT=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_RENTAL_SCDB_FORMAT SET RPP_ID=1 WHERE RENTAL_AMOUNT IS NOT NULL'));
	PREPARE UPDATE_RENT_AMOUNT_STMT FROM @UPDATE_RENT_AMOUNT;
    EXECUTE UPDATE_RENT_AMOUNT_STMT;	
	SET @UPDATE_RENTAL_DEPOSIT=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_RENTAL_SCDB_FORMAT SET RPP_ID=2 WHERE RENTAL_DEPOSIT IS NOT NULL'));
	PREPARE UPDATE_RENTAL_DEPOSIT_STMT FROM @UPDATE_RENTAL_DEPOSIT;
    EXECUTE UPDATE_RENTAL_DEPOSIT_STMT;	
	SET @UPDATE_RENTAL_PROCESSING_FEE=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_RENTAL_SCDB_FORMAT SET RPP_ID=3 WHERE RENTAL_PROCESSING_FEE IS NOT NULL'));
	PREPARE UPDATE_RENTAL_PROCESSING_FEE_STMT FROM @UPDATE_RENTAL_PROCESSING_FEE;
    EXECUTE UPDATE_RENTAL_PROCESSING_FEE_STMT;	
	SET @UPDATE_RENTAL_CLEANING_FEE=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_RENTAL_SCDB_FORMAT SET RPP_ID=4 WHERE RENTAL_CLEANING_FEE IS NOT NULL'));
	PREPARE UPDATE_RENTAL_CLEANING_FEE_STMT FROM @UPDATE_RENTAL_CLEANING_FEE;
    EXECUTE UPDATE_RENTAL_CLEANING_FEE_STMT;	
	SET @UPDATE_RENTAL_DEPOSIT_REFUND=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_RENTAL_SCDB_FORMAT SET RPP_ID=5 WHERE RENTAL_DEPOSIT_REFUND IS NOT NULL'));
	PREPARE UPDATE_RENTAL_DEPOSIT_REFUND_STMT FROM @UPDATE_RENTAL_DEPOSIT_REFUND;
    EXECUTE UPDATE_RENTAL_DEPOSIT_REFUND_STMT;	
	SET @UPDATE_RENTAL_CUSTOMER=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_RENTAL_SCDB_FORMAT SET RENTAL_CUSTOMER=','"CHARLES AND JOANNA"',' WHERE RENTAL_CUSTOMER=','"CHARLES ANDJOANNA"'));
	PREPARE UPDATE_RENTAL_CUSTOMER_STMT FROM @UPDATE_RENTAL_CUSTOMER;
    EXECUTE UPDATE_RENTAL_CUSTOMER_STMT;
	SET @UPDATE_RENTAL_TIMESTAMP=(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_RENTAL_SCDB_FORMAT SET  TIMESTAMP=(SELECT CONVERT_TZ(TIMESTAMP, "+08:00","+0:00"))'));
	PREPARE UPDATE_RENTAL_TIMESTAMP_STMT FROM @UPDATE_RENTAL_TIMESTAMP;
    EXECUTE UPDATE_RENTAL_TIMESTAMP_STMT;
    SET FOREIGN_KEY_CHECKS=1;
	SET ENDTIME=(SELECT CURTIME());
SET DURATION=(SELECT TIMEDIFF(ENDTIME,STARTTIME));
DROP TABLE IF EXISTS TEMP_DURATION_PAYMENT_PART2;
CREATE TABLE TEMP_DURATION_PAYMENT_PART2(ID INTEGER PRIMARY KEY AUTO_INCREMENT,SPLITTING_DURATION2 TIME);
INSERT INTO TEMP_DURATION_PAYMENT_PART2(SPLITTING_DURATION2)VALUES(DURATION);
END;
