 DROP PROCEDURE IF EXISTS SP_CUSTOMER_CARD_ASSIGN_SWAPPING;
 CREATE PROCEDURE SP_CUSTOMER_CARD_ASSIGN_SWAPPING(IN CA_CUSTOMER_ID INTEGER,
 IN OLD_ACCESS_CARD_NO INTEGER,
 IN NEW_ACCESS_CARD_NO INTEGER,
 IN ACTIVE_RECVER INTEGER,
 IN TERMINATE_RECVER INTEGER,
 IN FUTURE_RECVER INTEGER,
 IN TEMP_SAME_CUSTOMER_SWAPPING TEXT,
 IN CA_UNIT_NO INTEGER,
 IN TEMP_CUSTOMER_RECVER TEXT,
 IN TEMP_CUSTOMER_ACCESS_CARD TEXT,
 IN ACCESSOLDCARD INTEGER,
 IN ACCESSNEWCARD INTEGER,
 IN CA_REC_VER INTEGER,
 IN COUNT_VALUE INTEGER,
 IN GUEST_FLAG CHAR(1),
 IN USERSTAMP_ID INTEGER,
 IN SAMEUNITMINID INTEGER,
 OUT SWAP_FLAG INTEGER)
 BEGIN
 DECLARE TEMPCTD TEXT;
 DECLARE PRETERMINATE_DATE DATE;
 DECLARE MINTERMID INTEGER;
 DECLARE MAXTERMID INTEGER;
 DECLARE CURRENT_REC_VER INTEGER;
 DECLARE TEMP_CTD TEXT;
 DECLARE OLD_ULDID INTEGER;
 DECLARE OLD_CACD_ULDID INTEGER;
 DECLARE EXIT HANDLER FOR SQLEXCEPTION
 BEGIN
 ROLLBACK;
 IF TEMP_SAME_CUSTOMER_SWAPPING IS NOT NULL THEN
  SET @DROP_TEMPSAMECUSTSWAPPING=(SELECT CONCAT('DROP TABLE IF EXISTS ',TEMP_SAME_CUSTOMER_SWAPPING));
    PREPARE DROP_TEMPSAMECUSTSWAPPING_STMT FROM @DROP_TEMPSAMECUSTSWAPPING;
    EXECUTE DROP_TEMPSAMECUSTSWAPPING_STMT;
	END IF;
	IF TEMP_CUSTOMER_ACCESS_CARD IS NOT NULL THEN
	 SET @DROP_TEMPCUSTOMERACCESSCARD=(SELECT CONCAT('DROP TABLE IF EXISTS ',TEMP_CUSTOMER_ACCESS_CARD));
	PREPARE DROP_TEMPCUSTOMERACCESSCARD_STMT FROM @DROP_TEMPCUSTOMERACCESSCARD;
    EXECUTE DROP_TEMPCUSTOMERACCESSCARD_STMT; 
END IF;	
	IF TEMP_CUSTOMER_RECVER IS NOT NULL THEN
	SET @DROP_TEMPCUSTOMERRECVER=(SELECT CONCAT('DROP TABLE IF EXISTS ',TEMP_CUSTOMER_RECVER));
	PREPARE DROP_TEMPCUSTOMERRECVER_STMT FROM @DROP_TEMPCUSTOMERRECVER;
    EXECUTE DROP_TEMPCUSTOMERRECVER_STMT;
	END IF;
    IF TEMP_CTD IS NOT NULL THEN		
      SET @DROP_TEMPCTD=(SELECT CONCAT('DROP TABLE IF EXISTS ',TEMP_CTD));
      PREPARE DROP_TEMPCTD_STMT FROM @DROP_TEMPCTD;
      EXECUTE DROP_TEMPCTD_STMT;
    END IF;	  
 END;
 START TRANSACTION; 
 IF (OLD_ACCESS_CARD_NO IS NOT NULL AND NEW_ACCESS_CARD_NO IS NOT NULL AND NEW_ACCESS_CARD_NO!=OLD_ACCESS_CARD_NO)THEN            
			 IF NOT EXISTS(SELECT * FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CA_CUSTOMER_ID AND CED_REC_VER=CA_REC_VER AND UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=NEW_ACCESS_CARD_NO AND  IF(CLP_PRETERMINATE_DATE IS NOT NULL,CLP_PRETERMINATE_DATE>CURDATE(),CLP_ENDDATE>CURDATE())))THEN
                UPDATE UNIT_ACCESS_STAMP_DETAILS SET UASD_ACCESS_INVENTORY=NULL , UASD_ACCESS_ACTIVE='X' WHERE UASD_ACCESS_CARD=NEW_ACCESS_CARD_NO AND UNIT_ID=(SELECT UNIT_ID FROM UNIT WHERE UNIT_NO=CA_UNIT_NO);				
            END IF;		    
    		    SET TEMPCTD=(SELECT CONCAT('TEMP_CTD_',SYSDATE()));
                SET TEMPCTD=(SELECT REPLACE(TEMPCTD,' ',''));
                SET TEMPCTD=(SELECT REPLACE(TEMPCTD,'-',''));
                SET TEMPCTD=(SELECT REPLACE(TEMPCTD,':',''));
                SET TEMP_CTD=(SELECT CONCAT(TEMPCTD,'_',USERSTAMP_ID));
              IF ((ACTIVE_RECVER IS NULL OR ACTIVE_RECVER IS NOT NULL )AND TERMINATE_RECVER IS NOT NULL) THEN 
				SET @DROP_TEMPCTD=(SELECT CONCAT('DROP TABLE IF EXISTS ',TEMP_CTD));
                PREPARE DROP_TEMPCTD_STMT FROM @DROP_TEMPCTD;
                EXECUTE DROP_TEMPCTD_STMT;				
                SET @CREATE_TEMPCTD=(SELECT CONCAT('CREATE TABLE ',TEMP_CTD,'(ID INTEGER AUTO_INCREMENT PRIMARY KEY,CTDID INTEGER)'));
				PREPARE CREATE_TEMPCTD_STMT FROM @CREATE_TEMPCTD;
                EXECUTE CREATE_TEMPCTD_STMT;	
                SET @INSERT_TEMPCTD=(SELECT CONCAT('INSERT INTO ',TEMP_CTD,'(CTDID)(SELECT CLP_ID FROM ',TEMP_SAME_CUSTOMER_SWAPPING,' WHERE UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=',OLD_ACCESS_CARD_NO,') AND CUSTOMER_ID=',CA_CUSTOMER_ID,')'));
				PREPARE INSERT_TEMPCTD_STMT FROM @INSERT_TEMPCTD;
                EXECUTE INSERT_TEMPCTD_STMT;
				SET @TEMP_MINID=NULL;
                SET @TEMPMINTERMID=(SELECT CONCAT('SELECT MIN(ID) INTO @TEMP_MINID FROM ',TEMP_CTD));
				PREPARE TEMPMINTERMID_STMT FROM @TEMPMINTERMID;
                EXECUTE TEMPMINTERMID_STMT;
				SET @TEMP_MAXID=NULL;
                SET @TEMPMAXTERMID=(SELECT CONCAT('SELECT MAX(ID) INTO @TEMP_MAXID FROM ',TEMP_CTD));
				PREPARE TEMPMAXTERMID_STMT FROM @TEMPMAXTERMID;
                EXECUTE TEMPMAXTERMID_STMT;
				SET MINTERMID=@TEMP_MINID;
				SET MAXTERMID=@TEMP_MAXID;
                WHILE MINTERMID<=MAXTERMID DO
				  SET @TEMP_RECVER=NULL;
				  SET @SELECT_TEMPRECVER=(SELECT CONCAT('SELECT CED_REC_VER INTO @TEMP_RECVER FROM ',TEMP_SAME_CUSTOMER_SWAPPING,' WHERE CLP_ID=(SELECT CTDID FROM ',TEMP_CTD,' WHERE ID=',MINTERMID,')'));
				  PREPARE SELECT_TEMPRECVER_STMT FROM @SELECT_TEMPRECVER;
                  EXECUTE SELECT_TEMPRECVER_STMT;
				  SET @TEMP_UASDID=NULL;
				  SET @SELECT_TEMPUASDID=(SELECT CONCAT('SELECT UASD_ID INTO @TEMP_UASDID FROM ',TEMP_SAME_CUSTOMER_SWAPPING,' WHERE CLP_ID=(SELECT CTDID FROM ',TEMP_CTD,' WHERE ID=',MINTERMID,')'));
				  PREPARE SELECT_TEMPUASDID_STMT FROM @SELECT_TEMPUASDID;
                  EXECUTE SELECT_TEMPUASDID_STMT;
				  SET @TEMP_CTDID=NULL;
				  SET @SELECT_TEMPCTDID=(SELECT CONCAT('SELECT CLP_ID INTO @TEMP_CTDID FROM ',TEMP_SAME_CUSTOMER_SWAPPING,' WHERE CLP_ID=(SELECT CTDID FROM ',TEMP_CTD,' WHERE ID=',MINTERMID,')'));
				  PREPARE SELECT_TEMPCTDID_STMT FROM @SELECT_TEMPCTDID;
                  EXECUTE SELECT_TEMPCTDID_STMT;
				  SET @TEMP_ULDID=NULL;
				  SET @SELECT_TEMPULDID=(SELECT CONCAT('SELECT ULD_ID INTO @TEMP_ULDID FROM ',TEMP_SAME_CUSTOMER_SWAPPING,' WHERE CLP_ID=(SELECT CTDID FROM ',TEMP_CTD,' WHERE ID=',MINTERMID,')'));
				  PREPARE SELECT_TEMPULDID_STMT FROM @SELECT_TEMPULDID;
                  EXECUTE SELECT_TEMPULDID_STMT;
				  SET OLD_ULDID=@TEMP_ULDID;
				  SET @TEMP_TIMESTAMP=NULL;
				  SET @SELECT_TEMPTIMESTAMP=(SELECT CONCAT('SELECT TIMESTAMP INTO @TEMP_TIMESTAMP FROM ',TEMP_SAME_CUSTOMER_SWAPPING,' WHERE CLP_ID=(SELECT CTDID FROM ',TEMP_CTD,' WHERE ID=',MINTERMID,')'));
				  PREPARE SELECT_TEMPTIMESTAMP_STMT FROM @SELECT_TEMPTIMESTAMP;
                  EXECUTE SELECT_TEMPTIMESTAMP_STMT;
				  IF(OLD_ULDID!=USERSTAMP_ID)THEN
				  SET @TICK_OLD_VALUE=(SELECT CONCAT('CLP_ID=',@TEMP_CTDID,',','CED_REC_VER=',@TEMP_RECVER,',',
                  'UASD_ID=',@TEMP_UASDID,',','ULD_ID=',OLD_ULDID,',','CLP_TIMESTAMP=',@TEMP_TIMESTAMP)); 
				  ELSE
				  SET @TICK_OLD_VALUE=(SELECT CONCAT('CLP_ID=',@TEMP_CTDID,',','CED_REC_VER=',@TEMP_RECVER,',',
                  'UASD_ID=',@TEMP_UASDID,',','CLP_TIMESTAMP=',@TEMP_TIMESTAMP)); 
                  END IF;				  
                  SET @TICK_NEW_VALUE=(SELECT CONCAT('UASD_ID=',(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=NEW_ACCESS_CARD_NO)));
                  INSERT INTO TICKLER_HISTORY(TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE,ULD_ID,CUSTOMER_ID)VALUES((SELECT TP_ID FROM TICKLER_PROFILE WHERE TP_TYPE='UPDATION'),(SELECT TTIP_ID FROM TICKLER_TABID_PROFILE WHERE TTIP_DATA='CUSTOMER_LP_DETAILS'),@TICK_OLD_VALUE,@TICK_NEW_VALUE,USERSTAMP_ID,CA_CUSTOMER_ID);
                  SET MINTERMID=MINTERMID+1;
                END WHILE;
                  SET @UPDATELPDETAILS=(SELECT CONCAT('UPDATE CUSTOMER_LP_DETAILS SET UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=',NEW_ACCESS_CARD_NO,' AND UNIT_ID=(SELECT UNIT_ID FROM UNIT WHERE UNIT_NO=',CA_UNIT_NO,')),ULD_ID=',USERSTAMP_ID,' WHERE CLP_ID IN (SELECT CLP_ID FROM ',TEMP_SAME_CUSTOMER_SWAPPING,' WHERE UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=',OLD_ACCESS_CARD_NO,') AND CUSTOMER_ID=',CA_CUSTOMER_ID,' AND IF(CLP_PRETERMINATE_DATE IS NOT NULL,CLP_PRETERMINATE_DATE>CURDATE(),CLP_ENDDATE>CURDATE())) AND CUSTOMER_ID=',CA_CUSTOMER_ID));
				  PREPARE UPDATELPDETAILS_STMT FROM @UPDATELPDETAILS;
                  EXECUTE UPDATELPDETAILS_STMT;
                    SET @TEMPPRETERMINATE_DATE=NULL;
                   SET @PRETERMINATEDATE=(SELECT CONCAT('SELECT CLP_PRETERMINATE_DATE INTO @TEMPPRETERMINATE_DATE FROM ',TEMP_CUSTOMER_RECVER,' WHERE CED_REC_VER=',TERMINATE_RECVER));
				   PREPARE PRETERMINATEDATE_STMT FROM @PRETERMINATEDATE;
                   EXECUTE PRETERMINATEDATE_STMT;
				   SET PRETERMINATE_DATE=@TEMPPRETERMINATE_DATE;
				    SET @TEMP_ULDID=NULL;
                   SET @TEMPULDID=(SELECT CONCAT('SELECT ULD_ID INTO @TEMP_ULDID FROM  ',TEMP_CUSTOMER_ACCESS_CARD,' WHERE UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=',OLD_ACCESS_CARD_NO,')'));
				   PREPARE TEMPULDID_STMT FROM @TEMPULDID;
                   EXECUTE TEMPULDID_STMT;
                    SET OLD_CACD_ULDID=@TEMP_ULDID;			   
				    SET @TEMP_TIMESTAMP=NULL;
                   SET @TEMPTIMESTAMP=(SELECT CONCAT('SELECT TIMESTAMP INTO @TEMP_TIMESTAMP FROM ',TEMP_CUSTOMER_ACCESS_CARD,' WHERE UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=',OLD_ACCESS_CARD_NO,')'));
				   PREPARE TEMPTIMESTAMP_STMT FROM @TEMPTIMESTAMP;
                   EXECUTE TEMPTIMESTAMP_STMT;
				   SET @TEMP_CACD_ID=NULL;
				   SET @TEMPCACDID=(SELECT CONCAT('(SELECT CACD_ID INTO @TEMP_CACD_ID FROM ',TEMP_CUSTOMER_ACCESS_CARD,' WHERE UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=',OLD_ACCESS_CARD_NO,'))'));
				   PREPARE TEMPCACDID_STMT FROM @TEMPCACDID;
                   EXECUTE TEMPCACDID_STMT;
                    IF PRETERMINATE_DATE IS NULL THEN					
					IF(OLD_CACD_ULDID!=USERSTAMP_ID)THEN
					SET @TICK_ACCESS_OLD_VALUE=(SELECT CONCAT('CACD_ID=',@TEMP_CACD_ID,',','UASD_ID=',(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=OLD_ACCESS_CARD_NO),',','ACN_ID=NULL,CACD_VALID_TILL=NULL,','ULD_ID=',OLD_CACD_ULDID,',','CACD_TIMESTAMP=',@TEMP_TIMESTAMP));					
					ELSE					
                      SET @TICK_ACCESS_OLD_VALUE=(SELECT CONCAT('CACD_ID=',@TEMP_CACD_ID,',','UASD_ID=',(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=OLD_ACCESS_CARD_NO),',','ACN_ID=NULL,CACD_VALID_TILL=NULL,','CACD_TIMESTAMP=',@TEMP_TIMESTAMP));
					END IF;
					  SET @CACD_VALIDTILL=NULL;
					  SET @TEMP_CLPENDATE=(SELECT CONCAT('SELECT CLP_ENDDATE INTO @CACD_VALIDTILL FROM ',TEMP_CUSTOMER_RECVER,' WHERE CED_REC_VER=',TERMINATE_RECVER));
					  PREPARE TEMP_CLPENDATE_STMT FROM @TEMP_CLPENDATE;
                      EXECUTE TEMP_CLPENDATE_STMT;
                      SET @TICK_ACCESS_NEW_VALUE=(SELECT CONCAT('ACN_ID=4',',','CACD_VALID_TILL=',@CACD_VALIDTILL));
                     INSERT INTO TICKLER_HISTORY(TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE,ULD_ID,CUSTOMER_ID)VALUES((SELECT TP_ID FROM TICKLER_PROFILE WHERE TP_TYPE='UPDATION'),(SELECT TTIP_ID FROM TICKLER_TABID_PROFILE WHERE TTIP_DATA='CUSTOMER_ACCESS_CARD_DETAILS'),@TICK_ACCESS_OLD_VALUE,@TICK_ACCESS_NEW_VALUE,USERSTAMP_ID,CA_CUSTOMER_ID);
					 SET @UPDATE_CACD=(SELECT CONCAT('UPDATE CUSTOMER_ACCESS_CARD_DETAILS SET ACN_ID=4,CACD_VALID_TILL=@CACD_VALIDTILL,ULD_ID=',USERSTAMP_ID,'  WHERE CACD_ID=(SELECT CACD_ID FROM ',TEMP_CUSTOMER_ACCESS_CARD,' WHERE UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=',OLD_ACCESS_CARD_NO,'))'));
					 PREPARE UPDATE_CACD_STMT FROM @UPDATE_CACD;
                      EXECUTE UPDATE_CACD_STMT;	                     
                    ELSE
                     IF(OLD_CACD_ULDID!=USERSTAMP_ID)THEN
					SET @TICK_ACCESS_OLD_VALUE=(SELECT CONCAT('CACD_ID=',@TEMP_CACD_ID,',','UASD_ID=',(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=OLD_ACCESS_CARD_NO),',','ACN_ID=NULL,CACD_VALID_TILL=NULL,','ULD_ID=',OLD_CACD_ULDID,',','CACD_TIMESTAMP=',@TEMP_TIMESTAMP));					
					ELSE					
                      SET @TICK_ACCESS_OLD_VALUE=(SELECT CONCAT('CACD_ID=',@TEMP_CACD_ID,',','UASD_ID=',(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=OLD_ACCESS_CARD_NO),',','ACN_ID=NULL,CACD_VALID_TILL=NULL,','CACD_TIMESTAMP=',@TEMP_TIMESTAMP));
					END IF;
					  SET @CACD_VALIDTILL=NULL;
					  SET @TEMP_CLPPRETERMINATEDATE=(SELECT CONCAT('SELECT CLP_PRETERMINATE_DATE INTO @CACD_VALIDTILL FROM ',TEMP_CUSTOMER_RECVER,' WHERE CED_REC_VER=',TERMINATE_RECVER));
					  PREPARE TEMP_CLPPRETERMINATEDATE_STMT FROM @TEMP_CLPPRETERMINATEDATE;
                      EXECUTE TEMP_CLPPRETERMINATEDATE_STMT;
                     SET @TICK_ACCESS_NEW_VALUE=(SELECT CONCAT('ACN_ID=4',',','CACD_VALID_TILL=',@CACD_VALIDTILL));
                     INSERT INTO TICKLER_HISTORY(TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE,ULD_ID,CUSTOMER_ID)VALUES((SELECT TP_ID FROM TICKLER_PROFILE WHERE TP_TYPE='UPDATION'),(SELECT TTIP_ID FROM TICKLER_TABID_PROFILE WHERE TTIP_DATA='CUSTOMER_ACCESS_CARD_DETAILS'),@TICK_ACCESS_OLD_VALUE,@TICK_ACCESS_NEW_VALUE,USERSTAMP_ID,CA_CUSTOMER_ID);
                     SET @UPDATE_CACD=(SELECT CONCAT('UPDATE CUSTOMER_ACCESS_CARD_DETAILS SET ACN_ID=4,CACD_VALID_TILL=@CACD_VALIDTILL,ULD_ID=',USERSTAMP_ID,'  WHERE CACD_ID=(SELECT CACD_ID FROM ',TEMP_CUSTOMER_ACCESS_CARD,' WHERE UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=',OLD_ACCESS_CARD_NO,'))'));
					 PREPARE UPDATE_CACD_STMT FROM @UPDATE_CACD;
                      EXECUTE UPDATE_CACD_STMT;	
                    END IF;
					  SET @VALIDFROM=NULL;
					  SET @SELECT_VALIDFROM=(SELECT CONCAT('SELECT CLP_STARTDATE INTO @VALIDFROM FROM ',TEMP_SAME_CUSTOMER_SWAPPING ,' WHERE CED_REC_VER=(SELECT MIN(CED_REC_VER) FROM ',TEMP_SAME_CUSTOMER_SWAPPING,' WHERE CUSTOMER_ID=',CA_CUSTOMER_ID,' AND CLP_ENDDATE>CURDATE()) AND UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=',OLD_ACCESS_CARD_NO,')'));
					  PREPARE SELECT_VALIDFROM_STMT FROM @SELECT_VALIDFROM;
                      EXECUTE SELECT_VALIDFROM_STMT;					
                      INSERT INTO CUSTOMER_ACCESS_CARD_DETAILS (CUSTOMER_ID,UASD_ID,CACD_VALID_FROM,CACD_GUEST_CARD,ULD_ID) VALUES(CA_CUSTOMER_ID,ACCESSNEWCARD,@VALIDFROM,GUEST_FLAG,USERSTAMP_ID);
                ELSE
				  SET @DROP_TEMPCTD=(SELECT CONCAT('DROP TABLE IF EXISTS ',TEMP_CTD));
                  PREPARE DROP_TEMPCTD_STMT FROM @DROP_TEMPCTD;
                  EXECUTE DROP_TEMPCTD_STMT;				
                  SET @CREATE_TEMPCTD=(SELECT CONCAT('CREATE TABLE ',TEMP_CTD,'(ID INTEGER AUTO_INCREMENT PRIMARY KEY,CTDID INTEGER)'));
				  PREPARE CREATE_TEMPCTD_STMT FROM @CREATE_TEMPCTD;
                  EXECUTE CREATE_TEMPCTD_STMT;
                  SET @INSERT_TEMPCTD=(SELECT CONCAT('INSERT INTO ',TEMP_CTD,'(CTDID)(SELECT CLP_ID FROM ',TEMP_SAME_CUSTOMER_SWAPPING,' WHERE UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=',OLD_ACCESS_CARD_NO,') AND CUSTOMER_ID=',CA_CUSTOMER_ID,' AND IF(CLP_PRETERMINATE_DATE IS NOT NULL,CLP_PRETERMINATE_DATE>CURDATE(),CLP_ENDDATE>CURDATE()))'));
				  PREPARE INSERT_TEMPCTD_STMT FROM @INSERT_TEMPCTD;
                  EXECUTE INSERT_TEMPCTD_STMT;
                  SET @TEMP_MINID=NULL;				  
                  SET @TEMPMINTERMID=(SELECT CONCAT('SELECT MIN(ID) INTO @TEMP_MINID FROM ',TEMP_CTD));
				  PREPARE TEMPMINTERMID_STMT FROM @TEMPMINTERMID;
                  EXECUTE TEMPMINTERMID_STMT;	
                  SET @TEMP_MAXID=NULL;				  
                  SET @TEMPMAXTERMID=(SELECT CONCAT('SELECT MAX(ID) INTO @TEMP_MAXID FROM ',TEMP_CTD));
				  PREPARE TEMPMAXTERMID_STMT FROM @TEMPMAXTERMID;
                  EXECUTE TEMPMAXTERMID_STMT;
				  SET MINTERMID=@TEMP_MINID;
				  SET MAXTERMID=@TEMP_MAXID;
                  WHILE MINTERMID<=MAXTERMID DO	
                  SET @TEMP_RECVER=NULL;				  
				  SET @SELECT_TEMPRECVER=(SELECT CONCAT('SELECT CED_REC_VER INTO @TEMP_RECVER FROM ',TEMP_SAME_CUSTOMER_SWAPPING,' WHERE CLP_ID=(SELECT CTDID FROM ',TEMP_CTD,' WHERE ID=',MINTERMID,')'));
				  PREPARE SELECT_TEMPRECVER_STMT FROM @SELECT_TEMPRECVER;
                  EXECUTE SELECT_TEMPRECVER_STMT;
                  SET @TEMP_UASDID=NULL;				  
				  SET @SELECT_TEMPUASDID=(SELECT CONCAT('SELECT UASD_ID INTO @TEMP_UASDID FROM ',TEMP_SAME_CUSTOMER_SWAPPING,' WHERE CLP_ID=(SELECT CTDID FROM ',TEMP_CTD,' WHERE ID=',MINTERMID,')'));
				  PREPARE SELECT_TEMPUASDID_STMT FROM @SELECT_TEMPUASDID;
                  EXECUTE SELECT_TEMPUASDID_STMT;
				  SET @TEMP_CTDID=NULL;
				  SET @SELECT_TEMPCTDID=(SELECT CONCAT('SELECT CLP_ID INTO @TEMP_CTDID FROM ',TEMP_SAME_CUSTOMER_SWAPPING,' WHERE CLP_ID=(SELECT CTDID FROM ',TEMP_CTD,' WHERE ID=',MINTERMID,')'));
				  PREPARE SELECT_TEMPCTDID_STMT FROM @SELECT_TEMPCTDID;
                  EXECUTE SELECT_TEMPCTDID_STMT;
				  SET @TEMP_ULDID=NULL;
				  SET @SELECT_TEMPULDID=(SELECT CONCAT('SELECT ULD_ID INTO @TEMP_ULDID FROM ',TEMP_SAME_CUSTOMER_SWAPPING,' WHERE CLP_ID=(SELECT CTDID FROM ',TEMP_CTD,' WHERE ID=',MINTERMID,')'));
				  PREPARE SELECT_TEMPULDID_STMT FROM @SELECT_TEMPULDID;
                  EXECUTE SELECT_TEMPULDID_STMT;
				  SET OLD_ULDID=@TEMP_ULDID;
				  SET @TEMP_TIMESTAMP=NULL;
				  SET @SELECT_TEMPTIMESTAMP=(SELECT CONCAT('SELECT TIMESTAMP INTO @TEMP_TIMESTAMP FROM ',TEMP_SAME_CUSTOMER_SWAPPING,' WHERE CLP_ID=(SELECT CTDID FROM ',TEMP_CTD,' WHERE ID=',MINTERMID,')'));
				  PREPARE SELECT_TEMPTIMESTAMP_STMT FROM @SELECT_TEMPTIMESTAMP;
                  EXECUTE SELECT_TEMPTIMESTAMP_STMT;
				  IF(OLD_ULDID!=USERSTAMP_ID)THEN
				  SET @TICK_OLD_VALUE=(SELECT CONCAT('CLP_ID=',@TEMP_CTDID,',CED_REC_VER=',@TEMP_RECVER,',',
                  'UASD_ID=',@TEMP_UASDID,',','ULD_ID=',OLD_ULDID,',','TIMESTAMP=',@TEMP_TIMESTAMP));			  
				  ELSE
				  SET @TICK_OLD_VALUE=(SELECT CONCAT('CLP_ID=',@TEMP_CTDID,',CED_REC_VER=',@TEMP_RECVER,',',
                  'UASD_ID=',@TEMP_UASDID,',','TIMESTAMP=',@TEMP_TIMESTAMP
				   ));  
                  END IF;				  
                  SET @TICK_NEW_VALUE=(SELECT CONCAT('UASD_ID=',(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=NEW_ACCESS_CARD_NO)));
                  INSERT INTO TICKLER_HISTORY(TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE,ULD_ID,CUSTOMER_ID)VALUES((SELECT TP_ID FROM TICKLER_PROFILE WHERE TP_TYPE='UPDATION'),(SELECT TTIP_ID FROM TICKLER_TABID_PROFILE WHERE TTIP_DATA='CUSTOMER_LP_DETAILS'),@TICK_OLD_VALUE,@TICK_NEW_VALUE,USERSTAMP_ID,CA_CUSTOMER_ID);
                  SET MINTERMID=MINTERMID+1;
                END WHILE;
                SET @UPDATE_LPDETAILS=(SELECT CONCAT('UPDATE CUSTOMER_LP_DETAILS SET UASD_ID=',ACCESSNEWCARD,',ULD_ID=',USERSTAMP_ID,' WHERE CLP_ID IN (SELECT CLP_ID FROM ',TEMP_SAME_CUSTOMER_SWAPPING,' WHERE UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=',OLD_ACCESS_CARD_NO,') AND CUSTOMER_ID=',CA_CUSTOMER_ID,' AND IF(CLP_PRETERMINATE_DATE IS NOT NULL,CLP_PRETERMINATE_DATE>CURDATE(),CLP_ENDDATE>CURDATE())) AND CUSTOMER_ID=',CA_CUSTOMER_ID));
				PREPARE UPDATE_LPDETAILS_STMT FROM @UPDATE_LPDETAILS;
                EXECUTE UPDATE_LPDETAILS_STMT;
                		 SET @TEMP_ULDID=NULL;
                   SET @TEMPULDID=(SELECT CONCAT('SELECT ULD_ID INTO @TEMP_ULDID FROM  ',TEMP_CUSTOMER_ACCESS_CARD,' WHERE UASD_ID=',ACCESSOLDCARD));
				   PREPARE TEMPULDID_STMT FROM @TEMPULDID;
                   EXECUTE TEMPULDID_STMT;
                    SET OLD_CACD_ULDID=@TEMP_ULDID;			   
				    SET @TEMP_TIMESTAMP=NULL;
                   SET @TEMPTIMESTAMP=(SELECT CONCAT('SELECT TIMESTAMP INTO @TEMP_TIMESTAMP FROM ',TEMP_CUSTOMER_ACCESS_CARD,' WHERE UASD_ID=',ACCESSOLDCARD));
				   PREPARE TEMPTIMESTAMP_STMT FROM @TEMPTIMESTAMP;
                   EXECUTE TEMPTIMESTAMP_STMT;
				   SET @TEMP_CACD_ID=NULL;
				   SET @TEMPCACDID=(SELECT CONCAT('SELECT CACD_ID INTO @TEMP_CACD_ID FROM ',TEMP_CUSTOMER_ACCESS_CARD,' WHERE UASD_ID=',ACCESSOLDCARD));
				   PREPARE TEMPCACDID_STMT FROM @TEMPCACDID;
                   EXECUTE TEMPCACDID_STMT;	
                IF(OLD_CACD_ULDID!=USERSTAMP_ID)THEN			   
                SET @TICK_ACCESS_OLD_VALUE=(SELECT CONCAT('CACD_ID=',@TEMP_CACD_ID,',UASD_ID=',ACCESSOLDCARD,',ULD_ID=',OLD_CACD_ULDID,',CACD_TIMESTAMP=',@TEMP_TIMESTAMP));
                ELSE
                	SET @TICK_ACCESS_OLD_VALUE=(SELECT CONCAT('CACD_ID=',@TEMP_CACD_ID,',UASD_ID=',ACCESSOLDCARD,',CACD_TIMESTAMP=',@TEMP_TIMESTAMP));
               END IF;					
                SET @TICK_ACCESS_NEW_VALUE=(SELECT CONCAT('UASD_ID=',ACCESSNEWCARD));
                INSERT INTO TICKLER_HISTORY(TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE,ULD_ID,CUSTOMER_ID)VALUES((SELECT TP_ID FROM TICKLER_PROFILE WHERE TP_TYPE='UPDATION'),(SELECT TTIP_ID FROM TICKLER_TABID_PROFILE WHERE TTIP_DATA='CUSTOMER_ACCESS_CARD_DETAILS'),@TICK_ACCESS_OLD_VALUE,@TICK_ACCESS_NEW_VALUE,USERSTAMP_ID,CA_CUSTOMER_ID);
				IF(GUEST_FLAG=NULL)THEN 
				SET @GUESTFLAG='NULL';
				ELSE
				SET @GUESTFLAG=GUEST_FLAG;
				END IF;				
                SET @UPDATE_CACD=(SELECT CONCAT('UPDATE CUSTOMER_ACCESS_CARD_DETAILS SET UASD_ID=',ACCESSNEWCARD,' , ULD_ID=',USERSTAMP_ID,' ,CACD_GUEST_CARD=@GUESTFLAG WHERE CACD_ID=(SELECT CACD_ID FROM ',TEMP_CUSTOMER_ACCESS_CARD,' WHERE UASD_ID=',ACCESSOLDCARD,')'));
				PREPARE UPDATE_CACD_STMT FROM @UPDATE_CACD;
                  EXECUTE UPDATE_CACD_STMT;				  
             END IF; 
             IF NOT EXISTS(SELECT * FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CA_CUSTOMER_ID AND CED_REC_VER=CA_REC_VER AND UASD_ID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=OLD_ACCESS_CARD_NO))THEN
			UPDATE UNIT_ACCESS_STAMP_DETAILS SET UASD_ACCESS_INVENTORY='X' , UASD_ACCESS_ACTIVE=NULL WHERE UASD_ACCESS_CARD=OLD_ACCESS_CARD_NO AND UNIT_ID=(SELECT UNIT_ID FROM UNIT WHERE UNIT_NO=CA_UNIT_NO);
			END IF;			 
            SET SWAP_FLAG=1; 
                  IF TEMP_CTD IS NOT NULL THEN		
                  SET @DROP_TEMPCTD=(SELECT CONCAT('DROP TABLE IF EXISTS ',TEMP_CTD));
                  PREPARE DROP_TEMPCTD_STMT FROM @DROP_TEMPCTD;
                  EXECUTE DROP_TEMPCTD_STMT;
				  END IF;         
    END IF;  
     COMMIT; 
	END;