--VER 0.2-STARTDATE:09/06/2014 ENDDATE:09/06/2014 ISSUE:566-DESC:ADDED ROLLBACK AND COMMIT DONE BY SASIKALA

--VER 0.1-STARTDATE:29/04/2014 ENDDATE:6/05/2014 ISSUE:817-DESC:CHANGED ALL TEMP TABLE DYNAMICALLY DONE BY SAFI


DROP PROCEDURE IF EXISTS SP_SUB_CARD_ASSIGN;
CREATE PROCEDURE SP_SUB_CARD_ASSIGN(IN CA_CUSTOMER_ID INTEGER,
IN CA_UNIT_NO INTEGER(4),
IN CA_REC_VER INTEGER,
IN CA_CARD_NO TEXT,IN OLD_ACCESS_CARD_NO TEXT,IN NEW_ACCESS_CARD_NO TEXT ,IN GUEST_FLAG TEXT,IN SAMEUNITMINID INTEGER,IN USERSTAMP_ID INTEGER,IN CA_VALID_FROM DATE,IN CA_STARTDATE DATE,IN CA_ENDDATE DATE,IN CA_COMMENTS TEXT,IN CA_GUEST_CARD TEXT,IN ACCESSNEWCARD INTEGER,OUT FLAG TEXT)
BEGIN
DECLARE CURRENT_REC_VER INTEGER;
DECLARE PRETERMINATE_DATE DATE;
DECLARE STARTDATE DATE;
DECLARE ENDDATE DATE;
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
END;
START TRANSACTION;
IF CA_CARD_NO IS NOT NULL AND CA_GUEST_CARD IS NOT NULL AND CA_VALID_FROM IS NOT NULL AND CA_STARTDATE IS NOT NULL AND CA_ENDDATE IS NOT NULL THEN
    IF (OLD_ACCESS_CARD_NO IS NULL AND NEW_ACCESS_CARD_NO IS NOT NULL)THEN 
                IF GUEST_FLAG IS NULL THEN   
                    INSERT INTO CUSTOMER_ACCESS_CARD_DETAILS (CUSTOMER_ID,UASD_ID,CACD_VALID_FROM,CACD_GUEST_CARD,ULD_ID) VALUES(CA_CUSTOMER_ID,ACCESSNEWCARD,CA_VALID_FROM,GUEST_FLAG,USERSTAMP_ID);
                    UPDATE UNIT_ACCESS_STAMP_DETAILS SET UASD_ACCESS_ACTIVE='X',UASD_ACCESS_INVENTORY=NULL WHERE UASD_ACCESS_CARD=NEW_ACCESS_CARD_NO AND UNIT_ID=(SELECT UNIT_ID FROM UNIT WHERE UNIT_NO=CA_UNIT_NO);                    
                    IF SAMEUNITMINID IS NULL THEN
                       SET @TICKOLDVALUE=(SELECT CONCAT('CED_REC_VER=',CA_REC_VER,',','UASD_ID=NULL'));
                       SET @TICKNEWVALUE=(SELECT CONCAT('CED_REC_VER=',CA_REC_VER,',','UASD_ID=',ACCESSNEWCARD));
                       INSERT INTO TICKLER_HISTORY(TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE,ULD_ID,CUSTOMER_ID)VALUES((SELECT TP_ID FROM TICKLER_PROFILE WHERE TP_TYPE='UPDATION'),(SELECT TTIP_ID FROM TICKLER_TABID_PROFILE WHERE TTIP_DATA='CUSTOMER_LP_DETAILS'),@TICKOLDVALUE,@TICKNEWVALUE,USERSTAMP_ID,CA_CUSTOMER_ID);
                       UPDATE CUSTOMER_LP_DETAILS CLP,CUSTOMER_ENTRY_DETAILS CED SET CLP.UASD_ID=ACCESSNEWCARD,CLP.ULD_ID=USERSTAMP_ID WHERE CLP.CUSTOMER_ID=CA_CUSTOMER_ID AND CLP.CED_REC_VER=CA_REC_VER AND CLP.UASD_ID IS NULL AND CLP.CED_REC_VER=CED.CED_REC_VER AND CLP.CUSTOMER_ID=CED.CUSTOMER_ID AND CED.UNIT_ID=(SELECT UNIT_ID FROM UNIT WHERE UNIT_NO=CA_UNIT_NO) ;
                    ELSE
                      SET CURRENT_REC_VER=CA_REC_VER;
                      WHILE(CURRENT_REC_VER<=SAMEUNITMINID)DO
                        SET @TICKOLDVALUE=(SELECT CONCAT('CED_REC_VER=',CURRENT_REC_VER,',','UASD_ID=NULL'));
                        SET @TICKNEWVALUE=(SELECT CONCAT('CED_REC_VER=',CURRENT_REC_VER,',','UASD_ID=',ACCESSNEWCARD));
                        INSERT INTO TICKLER_HISTORY(TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE,ULD_ID,CUSTOMER_ID)VALUES((SELECT TP_ID FROM TICKLER_PROFILE WHERE TP_TYPE='UPDATION'),(SELECT TTIP_ID FROM TICKLER_TABID_PROFILE WHERE TTIP_DATA='CUSTOMER_LP_DETAILS'),@TICKOLDVALUE,@TICKNEWVALUE,USERSTAMP_ID,CA_CUSTOMER_ID);
                        SET CURRENT_REC_VER=CURRENT_REC_VER+1;
                      END WHILE;
                      UPDATE CUSTOMER_LP_DETAILS CLP,CUSTOMER_ENTRY_DETAILS CED SET CLP.UASD_ID=ACCESSNEWCARD,CLP.ULD_ID=USERSTAMP_ID WHERE CLP.CUSTOMER_ID=CA_CUSTOMER_ID AND CLP.CED_REC_VER>=CA_REC_VER AND CLP.CED_REC_VER<=SAMEUNITMINID AND CLP.UASD_ID IS NULL AND CLP.CED_REC_VER=CED.CED_REC_VER AND CLP.CUSTOMER_ID=CED.CUSTOMER_ID AND CED.UNIT_ID=(SELECT UNIT_ID FROM UNIT WHERE UNIT_NO=CA_UNIT_NO) ;
                    END IF;  
                ELSE
                 IF SAMEUNITMINID IS NULL THEN                 
                      SET CURRENT_REC_VER=CA_REC_VER;
                      IF (SELECT CLP_PRETERMINATE_DATE FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CA_CUSTOMER_ID AND CED_REC_VER=CURRENT_REC_VER AND CLP_GUEST_CARD IS NULL) IS NOT NULL AND EXISTS (SELECT CLP_PRETERMINATE_DATE FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CA_CUSTOMER_ID AND CED_REC_VER=CURRENT_REC_VER AND CLP_GUEST_CARD IS NULL) THEN
                        SET PRETERMINATE_DATE =(SELECT CLP_PRETERMINATE_DATE FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CA_CUSTOMER_ID AND CED_REC_VER=CURRENT_REC_VER AND CLP_GUEST_CARD IS NULL);
                      ELSE
                        SET PRETERMINATE_DATE=NULL;
                    END IF;                    
                    SET STARTDATE=(SELECT CLP_STARTDATE FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CA_CUSTOMER_ID AND CED_REC_VER=CURRENT_REC_VER AND CLP_GUEST_CARD IS NULL);
                    SET ENDDATE=(SELECT CLP_ENDDATE FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CA_CUSTOMER_ID AND CED_REC_VER=CURRENT_REC_VER AND CLP_GUEST_CARD IS NULL);
                    IF (STARTDATE>CURDATE())THEN
                      INSERT INTO CUSTOMER_LP_DETAILS (CUSTOMER_ID,CED_REC_VER,UASD_ID,CLP_STARTDATE,CLP_ENDDATE,CLP_PRETERMINATE_DATE,CLP_GUEST_CARD,ULD_ID) VALUES (CA_CUSTOMER_ID,CURRENT_REC_VER,ACCESSNEWCARD,STARTDATE,ENDDATE,PRETERMINATE_DATE,GUEST_FLAG,USERSTAMP_ID);
                    ELSE
                      INSERT INTO CUSTOMER_LP_DETAILS (CUSTOMER_ID,CED_REC_VER,UASD_ID,CLP_STARTDATE,CLP_ENDDATE,CLP_PRETERMINATE_DATE,CLP_GUEST_CARD,ULD_ID) VALUES (CA_CUSTOMER_ID,CURRENT_REC_VER,ACCESSNEWCARD,CA_STARTDATE,ENDDATE,PRETERMINATE_DATE,GUEST_FLAG,USERSTAMP_ID);
                    END IF;                    
                      INSERT INTO CUSTOMER_ACCESS_CARD_DETAILS (CUSTOMER_ID,UASD_ID,CACD_VALID_FROM,CACD_GUEST_CARD,ULD_ID) VALUES(CA_CUSTOMER_ID,(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=NEW_ACCESS_CARD_NO AND UNIT_ID=(SELECT UNIT_ID FROM UNIT WHERE UNIT_NO=CA_UNIT_NO)),CA_VALID_FROM,GUEST_FLAG,USERSTAMP_ID);
                      UPDATE UNIT_ACCESS_STAMP_DETAILS SET UASD_ACCESS_ACTIVE='X',UASD_ACCESS_INVENTORY=NULL WHERE UASD_ACCESS_CARD=NEW_ACCESS_CARD_NO AND UNIT_ID=(SELECT UNIT_ID FROM UNIT WHERE UNIT_NO=CA_UNIT_NO);            
                 ELSE 
                    SET CURRENT_REC_VER=CA_REC_VER;
                    WHILE(CURRENT_REC_VER<=SAMEUNITMINID) DO
                   IF((SELECT COUNT(*) FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CA_CUSTOMER_ID AND
                                     CLP_GUEST_CARD IS NOT NULL AND CED_REC_VER=CURRENT_REC_VER)<3) THEN           
                     IF (SELECT CLP_PRETERMINATE_DATE FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CA_CUSTOMER_ID AND CED_REC_VER=CURRENT_REC_VER AND CLP_GUEST_CARD IS NULL) IS NOT NULL AND EXISTS (SELECT CLP_PRETERMINATE_DATE FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CA_CUSTOMER_ID AND CED_REC_VER=CURRENT_REC_VER AND CLP_GUEST_CARD IS NULL) THEN
                        SET PRETERMINATE_DATE =(SELECT CLP_PRETERMINATE_DATE FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CA_CUSTOMER_ID AND CED_REC_VER=CURRENT_REC_VER AND CLP_GUEST_CARD IS NULL);
                    ELSE
                        SET PRETERMINATE_DATE=NULL;
                    END IF;                    
                   SET STARTDATE=(SELECT CLP_STARTDATE FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CA_CUSTOMER_ID AND CED_REC_VER=CURRENT_REC_VER AND CLP_GUEST_CARD IS NULL);
                   SET ENDDATE=(SELECT CLP_ENDDATE FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CA_CUSTOMER_ID AND CED_REC_VER=CURRENT_REC_VER AND CLP_GUEST_CARD IS NULL);
                    IF (STARTDATE>CURDATE())THEN
                      INSERT INTO CUSTOMER_LP_DETAILS (CUSTOMER_ID,CED_REC_VER,UASD_ID,CLP_STARTDATE,CLP_ENDDATE,CLP_PRETERMINATE_DATE,CLP_GUEST_CARD,ULD_ID) VALUES (CA_CUSTOMER_ID,CURRENT_REC_VER,ACCESSNEWCARD,STARTDATE,ENDDATE,PRETERMINATE_DATE,GUEST_FLAG,USERSTAMP_ID);
                    ELSE
                      INSERT INTO CUSTOMER_LP_DETAILS (CUSTOMER_ID,CED_REC_VER,UASD_ID,CLP_STARTDATE,CLP_ENDDATE,CLP_PRETERMINATE_DATE,CLP_GUEST_CARD,ULD_ID) VALUES (CA_CUSTOMER_ID,CURRENT_REC_VER,ACCESSNEWCARD,CA_STARTDATE,ENDDATE,PRETERMINATE_DATE,GUEST_FLAG,USERSTAMP_ID);
                    END IF;
                      SET CURRENT_REC_VER=CURRENT_REC_VER+1;
                    END IF;
                    END WHILE;
                     INSERT INTO CUSTOMER_ACCESS_CARD_DETAILS (CUSTOMER_ID,UASD_ID,CACD_VALID_FROM,CACD_GUEST_CARD,ULD_ID) VALUES(CA_CUSTOMER_ID,ACCESSNEWCARD,CA_VALID_FROM,GUEST_FLAG,USERSTAMP_ID);
                     UPDATE UNIT_ACCESS_STAMP_DETAILS SET UASD_ACCESS_ACTIVE='X',UASD_ACCESS_INVENTORY=NULL WHERE UASD_ACCESS_CARD=NEW_ACCESS_CARD_NO AND UNIT_ID=(SELECT UNIT_ID FROM UNIT WHERE UNIT_NO=CA_UNIT_NO);
                    END IF;
                END IF;
                SET FLAG=1;
            END IF;
    		END IF;	
        COMMIT;
			END;			