DROP PROCEDURE IF EXISTS SP_UNIT_ROOM_TYPE_UPDATE;
CREATE PROCEDURE SP_UNIT_ROOM_TYPE_UPDATE(
IN ID INT,
IN ROOMTYPE VARCHAR(30),
IN USERSTAMP VARCHAR(50),
OUT FLAG INTEGER)
BEGIN 
DECLARE USERSTAMP_ID INTEGER(2);
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN 
ROLLBACK; 
END;
START TRANSACTION;
SET FLAG = 0;
CALL SP_CHANGE_USERSTAMP_AS_ULDID(USERSTAMP,@ULDID);
SET USERSTAMP_ID = (SELECT @ULDID);
IF NOT EXISTS(SELECT URTD_ROOM_TYPE FROM UNIT_ROOM_TYPE_DETAILS WHERE URTD_ROOM_TYPE=ROOMTYPE)THEN
UPDATE UNIT_ROOM_TYPE_DETAILS SET URTD_ROOM_TYPE=ROOMTYPE, ULD_ID=USERSTAMP_ID WHERE URTD_ID = ID;
SET FLAG = 1;
END IF;
COMMIT;
END;