-- version --> 1.1 startdate -->24/03/2014 enddate --> 12/04/2014 description -->changed table name CUSTOMER_TERMINATION_DETAILS TO CUSTOMER_LP_DETAILS,changed ptd null part for guest n cust in prev lps n updated sd in input lp+1 to max lp-->by PUNI issue :345 comment #627
-- version --> 1.0 startdate -->29/01/2014 enddate --> 30/01/2014 description -->UPDATED CUSTOMER ENTRY DETAILS AS PER STIME AND ETIME DATATYPE UPDATION DONE BY:DHIVYA.A -->issue :594 comment #71
-- version --> 0.9 startdate -->07/01/2014 enddate --> 15/01/2014 description --> updated term=x only for customer,added parameter to get active rv as input,updated tickler,n fixed issue in prev unit to release card for cust also n updated ptd null or sd for the prev rv as per comment #557 by PUNI--> issue 345
-- version --> 0.8 startdate -->24/12/2013 enddate --> 24/12/2013 description --> Fixed the bug raised as per comment #44 created by -->RL -->issue :650
-- version --> 0.7 startdate -->28/11/2013 enddate --> 02/12/2013 description --> Fixed the bug raised as per comment #27 & #30 created by -->CL -->issue :650
-- version --> 0.6 startdate -->26/11/2013 enddate --> 26/11/2013 description --> Fixed the bug raised as per comment #13 created by -->CL -->issue :650
-- version --> 0.5 startdate -->21/11/2013 enddate --> 25/11/2013 description --> Added the LPQ parameters, Implemented CR as per comment #3 & #8 created by -->CL -->issue :650
-- version --> 0.4 startdate -->19/10/2013 enddate --> 19/10/2013 description --> Removed the SD's start and end time updation from the SP created by -->CL -->issue :643
-- version --> 0.3 startdate -->18/10/2013 enddate --> 18/10/2013 description --> Changed the SP according to the CR in the termination form created by -->CL -->issue :643
-- version --> 0.2 startdate -->14/10/2013 enddate --> 17/10/2013 description --> Changed the SP according to the CR in the termination form created by -->CL -->issue :345
-- version --> 0.1 startdate -->24/09/2013 enddate --> 03/10/2013 description --> SP for the customer termination form saving part created by -->CL -->issue :345
DROP PROCEDURE IF EXISTS SP_CUSTOMER_MANUAL_TERMINATION_INSERT;
CREATE PROCEDURE SP_CUSTOMER_MANUAL_TERMINATION_INSERT(
IN CT_CUSTOMER_ID INTEGER,
IN CT_REC_VER INTEGER,
IN CT_ACTIVE_REC_VER INTEGER,
IN CT_ACCESS_CARD TEXT,
IN CT_GUEST_CARD TEXT,
IN CT_NEW_PRETERMINATE TEXT,
IN CT_RECVER_LPQ TEXT,
IN CT_ED_STIME TIME,
IN CT_ED_ETIME TIME,
IN CT_COMMENTS TEXT,
IN CT_USERSTAMP VARCHAR(50),
OUT TERMRESULT_FLAG INTEGER)
BEGIN
	DECLARE ACTIVE_RECVER INTEGER;
	DECLARE TEMP_RECVER_LPQ TEXT;
	DECLARE REC_VERSION_LENGTH INTEGER;
	DECLARE REC_VERSION_POSITION INTEGER;
	DECLARE REC_VERSION INTEGER;
	DECLARE LEASE_PERIOD_POSITION INTEGER;
	DECLARE LEASE_PERIOD VARCHAR(30);
	DECLARE QUARTERS_POSITION INTEGER;
	DECLARE QUARTERS DECIMAL(5,2);
	DECLARE TEMP_ACCESS_CARD TEXT;
	DECLARE ACCESS_LENGTH INTEGER;
	DECLARE ACCESS_POSITION INTEGER;
	DECLARE ACCESS_CARD_NO INTEGER(7);
	DECLARE ACCESS_LOCATION INTEGER;
	DECLARE GUEST_ACCESS_LENGTH INTEGER;
	DECLARE GUEST_FLAG CHAR(1);
	DECLARE PTD_ACCESS_LOCATION INTEGER;
	DECLARE PTD_ACCESS_LENGTH INTEGER;
	DECLARE PTD_ACCESS_POSITION INTEGER;
	DECLARE PRETERMINATE_DATE DATE;
	DECLARE UASDID INTEGER DEFAULT NULL;
	DECLARE TERM_UASDID INTEGER DEFAULT NULL;
	DECLARE MIN_RECVER INTEGER;
	DECLARE MAX_RECVER INTEGER;
	DECLARE GUEST_CARD_COUNT INTEGER;
	DECLARE CARD_ON INTEGER;
	DECLARE TEMP_QUATER VARCHAR(10);
	DECLARE TERM_REC_VER INTEGER;
	DECLARE TERM_END_DATE DATE;
	DECLARE TERM_PTD DATE;
	DECLARE TERM_GUEST_CARD_COUNT INTEGER;
	DECLARE TERM_PTD_NULL_COUNT INTEGER;
	DECLARE TERM_NULL_PTD DATE;
	DECLARE TERM_NULL_ENDATE DATE;
	DECLARE TERM_NULL_STARTDATE DATE;
	DECLARE TERM_NULL_NRVSTARTDATE DATE;
	DECLARE TICK_CARD_NO  VARCHAR(7);
	DECLARE TICK_OLD_VALUE  TEXT;
	DECLARE TICK_NEW_VALUE  TEXT;
	DECLARE TICK_GUEST_CARD  VARCHAR(10);
	DECLARE TERM_CUST_COMMTS  TEXT;
	DECLARE TERM_MAX_CUSTRV  INTEGER;
	DECLARE TICK_PTD TEXT;
	DECLARE TICK_OLD_LP TEXT;
	DECLARE TICK_OLD_QUART TEXT;
	DECLARE TICK_NEW_LP TEXT;
	DECLARE TICK_NEW_QUART TEXT;
	DECLARE TICK_OLD_EDSTIME TEXT;	
	DECLARE TICK_OLD_EDETIME TEXT;
	DECLARE CT_ED_STIMEID TEXT;
	DECLARE CT_ED_ETIMEID TEXT;
	DECLARE USERSTAMP_ID INTEGER;
	DECLARE TERM_NULL_NRVENDATE DATE;
	DECLARE PTDFLAG INTEGER DEFAULT 0;
	DECLARE EDFLAG INTEGER DEFAULT 0;
	DECLARE MIN_CTDID INTEGER DEFAULT 0;
	DECLARE MAX_CTDID INTEGER DEFAULT 0;
	DECLARE CLP_GSTVAL VARCHAR(10);
	DECLARE CLP_UASDIDVAL INTEGER;
	DECLARE TICK_ACS_OLD_VALUE TEXT;
	DECLARE GST_NULL_FLAG INTEGER DEFAULT 0;
	-- query for rollback command
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN 
		SET TERMRESULT_FLAG=0;
		ROLLBACK; 
	END;
	START TRANSACTION;
	CALL SP_CHANGE_USERSTAMP_AS_ULDID(CT_USERSTAMP,@ULDID);
	SET USERSTAMP_ID=(SELECT @ULDID);
	SET TERMRESULT_FLAG=0;
	-- SET MNRV=0;
	-- SET MXRV=0;
	SET TERM_CUST_COMMTS=(SELECT CPD_COMMENTS FROM CUSTOMER_PERSONAL_DETAILS WHERE CUSTOMER_ID=CT_CUSTOMER_ID);
	SET TERM_MAX_CUSTRV=(SELECT MAX(CED_REC_VER) FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CT_CUSTOMER_ID AND IF (CLP_PRETERMINATE_DATE IS NOT NULL ,CLP_PRETERMINATE_DATE>CURDATE(),CLP_ENDDATE>CURDATE()));
	SET ACTIVE_RECVER = CT_ACTIVE_REC_VER;
	IF CT_COMMENTS='' THEN
		SET CT_COMMENTS=NULL;
	END IF;
	IF CT_ED_STIME='' THEN
		SET CT_ED_STIME=NULL;
	END IF;
	IF CT_ED_ETIME='' THEN
		SET CT_ED_ETIME=NULL;
	END IF;
	IF CT_RECVER_LPQ='' THEN
		SET CT_RECVER_LPQ=NULL;
	END IF;	
	-- UPDATE LP N QUARTORS START
	IF CT_RECVER_LPQ IS NOT NULL THEN
		SET TEMP_RECVER_LPQ = CT_RECVER_LPQ;
		SET REC_VERSION_LENGTH = 1;
		LPQ_LOOP : LOOP		
			SET REC_VERSION_POSITION=(SELECT LOCATE(',&',TEMP_RECVER_LPQ,REC_VERSION_LENGTH));
			SET REC_VERSION = (SELECT CAST((SELECT SUBSTRING(TEMP_RECVER_LPQ,REC_VERSION_LENGTH,1)) AS UNSIGNED INTEGER));
			SET TEMP_RECVER_LPQ = (SELECT SUBSTRING(TEMP_RECVER_LPQ,REC_VERSION_POSITION+2));
			SET LEASE_PERIOD_POSITION = (SELECT LOCATE(',&',TEMP_RECVER_LPQ,REC_VERSION_LENGTH));
			SET LEASE_PERIOD= (SELECT SUBSTRING(TEMP_RECVER_LPQ,REC_VERSION_LENGTH,LEASE_PERIOD_POSITION-1));
			IF TRIM(LEASE_PERIOD)='' THEN
				SET LEASE_PERIOD = NULL;
			END IF;
			SET TEMP_RECVER_LPQ = (SELECT SUBSTRING(TEMP_RECVER_LPQ,LEASE_PERIOD_POSITION+2));
			SET QUARTERS_POSITION = (SELECT LOCATE(',&',TEMP_RECVER_LPQ,REC_VERSION_LENGTH));
			IF (QUARTERS_POSITION<=0) THEN
				SET QUARTERS = (SELECT CAST((IF(TRIM(TEMP_RECVER_LPQ)='',0,TEMP_RECVER_LPQ)) AS DECIMAL(5,2)));
			ELSE
				SET TEMP_QUATER=(SELECT SUBSTRING(TEMP_RECVER_LPQ,REC_VERSION_LENGTH,QUARTERS_POSITION-1));
				IF TRIM(TEMP_QUATER)='' THEN
					SET QUARTERS = 0;
				ELSE
					SET QUARTERS = (SELECT CAST((SELECT SUBSTRING(TEMP_RECVER_LPQ,REC_VERSION_LENGTH,QUARTERS_POSITION-1)) AS DECIMAL(5,2)));
				END IF;
			END IF;
			IF QUARTERS=0 THEN
				SET QUARTERS=NULL;
			END IF;
			SET TEMP_RECVER_LPQ = (SELECT SUBSTRING(TEMP_RECVER_LPQ,QUARTERS_POSITION+2));
			-- INSERT LP N QUARTORS,START N END TIME FOR ENDDATE/PTD START INTO TICKLER TABLE START
			IF QUARTERS IS NULL THEN
				SET TICK_NEW_QUART='null';
			ELSE
				SET TICK_NEW_QUART=QUARTERS;
			END IF;
			IF LEASE_PERIOD IS NULL THEN
				SET TICK_NEW_LP='null';
			ELSE
				SET TICK_NEW_LP=LEASE_PERIOD;
			END IF;
			SET TICK_OLD_QUART=(SELECT CED_QUARTERS FROM CUSTOMER_ENTRY_DETAILS WHERE CUSTOMER_ID=CT_CUSTOMER_ID AND CED_REC_VER=REC_VERSION);
			SET TICK_OLD_LP=(SELECT CED_LEASE_PERIOD FROM CUSTOMER_ENTRY_DETAILS WHERE CUSTOMER_ID=CT_CUSTOMER_ID AND CED_REC_VER=REC_VERSION);
			SET TICK_OLD_EDSTIME=(SELECT CTP.CTP_ID FROM CUSTOMER_TIME_PROFILE CTP,CUSTOMER_ENTRY_DETAILS CED WHERE CED.CUSTOMER_ID=CT_CUSTOMER_ID AND CED.CED_REC_VER=REC_VERSION AND CTP.CTP_ID=CED.CED_ED_STIME);
			SET TICK_OLD_EDETIME=(SELECT CTP.CTP_ID FROM CUSTOMER_TIME_PROFILE CTP,CUSTOMER_ENTRY_DETAILS CED WHERE CED.CUSTOMER_ID=CT_CUSTOMER_ID AND CED.CED_REC_VER=REC_VERSION AND CTP.CTP_ID=CED.CED_ED_ETIME);
			SET CT_ED_STIMEID=(SELECT CTP_ID FROM CUSTOMER_TIME_PROFILE WHERE CTP_DATA=CT_ED_STIME);
			SET CT_ED_ETIMEID=(SELECT CTP_ID FROM CUSTOMER_TIME_PROFILE WHERE CTP_DATA=CT_ED_ETIME);
			IF TICK_OLD_QUART IS NULL THEN
				SET TICK_OLD_QUART='null';
			END IF;
			IF TICK_OLD_LP IS NULL THEN
				SET TICK_OLD_LP='null';
			END IF;
			SET TICK_OLD_VALUE=(SELECT CONCAT('CED_ID=',(SELECT CED_ID FROM CUSTOMER_ENTRY_DETAILS WHERE CUSTOMER_ID=CT_CUSTOMER_ID AND CED_REC_VER=REC_VERSION),',UNIT_ID=',(SELECT U.UNIT_ID FROM UNIT U,CUSTOMER_ENTRY_DETAILS CED WHERE CED.UNIT_ID=U.UNIT_ID AND CED.CUSTOMER_ID=CT_CUSTOMER_ID AND CED.CED_REC_VER=REC_VERSION),',CED_REC_VER=',REC_VERSION,',CED_ED_STIME=',TICK_OLD_EDSTIME,',CED_ED_ETIME=',TICK_OLD_EDETIME,',CED_LEASE_PERIOD=',TICK_OLD_LP,',CED_QUARTERS=',TICK_OLD_QUART));
			IF  CT_REC_VER=REC_VERSION THEN	
				IF (TICK_OLD_EDSTIME!=CT_ED_STIMEID AND TICK_OLD_EDETIME!=CT_ED_ETIMEID) THEN 
					SET TICK_NEW_VALUE=(SELECT CONCAT('CED_ED_STIME=',CT_ED_STIMEID,',CED_ED_ETIME=',CT_ED_ETIMEID,',CED_LEASE_PERIOD=',TICK_NEW_LP,',CED_QUARTERS=',TICK_NEW_QUART));
				ELSEIF (TICK_OLD_EDSTIME!=CT_ED_STIMEID) THEN	
					SET TICK_NEW_VALUE=(SELECT CONCAT('CED_ED_STIME=',CT_ED_STIMEID,',CED_LEASE_PERIOD=',TICK_NEW_LP,',CED_QUARTERS=',TICK_NEW_QUART));
				ELSEIF (TICK_OLD_EDETIME!=CT_ED_ETIMEID) THEN 
					SET TICK_NEW_VALUE=(SELECT CONCAT('CED_ED_ETIME=',CT_ED_ETIMEID,',CED_LEASE_PERIOD=',TICK_NEW_LP,',CED_QUARTERS=',TICK_NEW_QUART));
				ELSE
					SET TICK_NEW_VALUE=(SELECT CONCAT('CED_LEASE_PERIOD=',TICK_NEW_LP,',CED_QUARTERS=',TICK_NEW_QUART));
				END IF;
				IF (TICK_OLD_EDSTIME!=CT_ED_STIME) OR (TICK_OLD_EDETIME!=CT_ED_ETIME) OR (TICK_NEW_LP!=TICK_OLD_LP) OR(TICK_NEW_QUART!=TICK_OLD_QUART) THEN
					INSERT INTO TICKLER_HISTORY(TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE,ULD_ID,CUSTOMER_ID)VALUES(1,10,TICK_OLD_VALUE,TICK_NEW_VALUE,USERSTAMP_ID,CT_CUSTOMER_ID);
				END IF;
			ELSE
				SET TICK_NEW_VALUE=(SELECT CONCAT('CED_LEASE_PERIOD=',TICK_NEW_LP,',CED_QUARTERS=',TICK_NEW_QUART));
				IF (TICK_NEW_LP!=TICK_OLD_LP) OR(TICK_NEW_QUART!=TICK_OLD_QUART) THEN
					INSERT INTO TICKLER_HISTORY(TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE,ULD_ID,CUSTOMER_ID)VALUES(1,10,TICK_OLD_VALUE,TICK_NEW_VALUE,USERSTAMP_ID,CT_CUSTOMER_ID);
				END IF;
			END IF;				
			-- INSERT LP N QUARTORS,START N END TIME FOR ENDDATE/PTD START INTO TICKLER TABLE END
			-- update query for customer_entry_details table
			UPDATE CUSTOMER_ENTRY_DETAILS SET  CED_LEASE_PERIOD = LEASE_PERIOD, CED_QUARTERS = QUARTERS WHERE CUSTOMER_ID=CT_CUSTOMER_ID AND CED_REC_VER=REC_VERSION;
			SET TERMRESULT_FLAG=1;
			IF QUARTERS_POSITION<=0 THEN
				LEAVE LPQ_LOOP;
			END IF;
		END LOOP;
	END IF;
	-- UPDATE LP N QUARTORS END
	-- UPDATE PTD STIME N ETIME START
	IF CT_ED_STIME IS NOT NULL AND CT_ED_ETIME IS NOT NULL THEN
		UPDATE CUSTOMER_ENTRY_DETAILS CED SET CED.CED_ED_STIME=(SELECT CTP_ID FROM CUSTOMER_TIME_PROFILE WHERE CTP_DATA=CT_ED_STIME), CED.CED_ED_ETIME=(SELECT CTP_ID FROM CUSTOMER_TIME_PROFILE WHERE CTP_DATA=CT_ED_ETIME) WHERE CED.CUSTOMER_ID=CT_CUSTOMER_ID AND CED.CED_REC_VER=CT_REC_VER;
		SET TERMRESULT_FLAG=1;	
	END IF;
	-- UPDATE PTD STIME N ETIME END
	SET TEMP_ACCESS_CARD = CT_ACCESS_CARD;
	SET ACCESS_LENGTH=1;	
	ACCESS_LOOP:  LOOP	
		SET ACCESS_POSITION=(SELECT LOCATE(',', TEMP_ACCESS_CARD,ACCESS_LENGTH));
		IF ACCESS_POSITION<=0 THEN
			SET ACCESS_CARD_NO=(SELECT CAST(TEMP_ACCESS_CARD AS UNSIGNED INTEGER));
		ELSE
			SET ACCESS_CARD_NO=(SELECT CAST((SELECT SUBSTRING(TEMP_ACCESS_CARD,ACCESS_LENGTH,ACCESS_POSITION-1)) AS UNSIGNED INTEGER));
			SET TEMP_ACCESS_CARD=(SELECT SUBSTRING(TEMP_ACCESS_CARD,ACCESS_POSITION+1));
		END IF;
		SET ACCESS_LOCATION=(SELECT LOCATE(ACCESS_CARD_NO, CT_GUEST_CARD));
		SET GUEST_ACCESS_LENGTH=(SELECT LENGTH(ACCESS_CARD_NO));
		SET GUEST_FLAG=(SELECT SUBSTRING(CT_GUEST_CARD,ACCESS_LOCATION+GUEST_ACCESS_LENGTH+1,1));
		SET GUEST_FLAG=TRIM(GUEST_FLAG);
		IF GUEST_FLAG='' THEN
			SET GUEST_FLAG=NULL;
		END IF;
		SET PTD_ACCESS_LOCATION=(SELECT LOCATE(ACCESS_CARD_NO, CT_NEW_PRETERMINATE));
		SET PTD_ACCESS_LENGTH=(SELECT LENGTH(ACCESS_CARD_NO));
		SET PTD_ACCESS_POSITION=(SELECT LOCATE(',', CT_NEW_PRETERMINATE,PTD_ACCESS_LOCATION+PTD_ACCESS_LENGTH+1));
		IF PTD_ACCESS_POSITION<=0 THEN
			SET PRETERMINATE_DATE=(SELECT SUBSTRING(CT_NEW_PRETERMINATE,PTD_ACCESS_LOCATION+PTD_ACCESS_LENGTH+1,(SELECT LENGTH(CT_NEW_PRETERMINATE))));
		ELSE
			SET PRETERMINATE_DATE=(SELECT SUBSTRING(CT_NEW_PRETERMINATE,PTD_ACCESS_LOCATION+PTD_ACCESS_LENGTH+1,PTD_ACCESS_POSITION-(PTD_ACCESS_LOCATION+PTD_ACCESS_LENGTH+1)));
		END IF;
		SET UASDID=(SELECT UASD_ID FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ACCESS_CARD=ACCESS_CARD_NO);
		IF GUEST_FLAG IS NULL THEN
			-- update ptd=null from active rv to input rv -1 start
			SET MIN_RECVER=ACTIVE_RECVER;-- input rv
			SET MAX_RECVER=TERM_MAX_CUSTRV;-- CT_REC_VER;
			IF(MAX_RECVER>=MIN_RECVER) THEN
				RECVER_LOOP:  LOOP	
					SET TERM_NULL_STARTDATE=(SELECT CLP_STARTDATE FROM CUSTOMER_LP_DETAILS WHERE CED_REC_VER=MIN_RECVER AND CUSTOMER_ID=CT_CUSTOMER_ID AND CLP_GUEST_CARD IS NULL AND IF (CLP_PRETERMINATE_DATE IS NOT NULL ,CLP_PRETERMINATE_DATE>CURDATE(),CLP_ENDDATE>CURDATE()));
					SET TERM_NULL_PTD=(SELECT CLP_PRETERMINATE_DATE FROM CUSTOMER_LP_DETAILS WHERE CED_REC_VER=MIN_RECVER AND CUSTOMER_ID=CT_CUSTOMER_ID AND CLP_GUEST_CARD IS NULL AND IF (CLP_PRETERMINATE_DATE IS NOT NULL ,CLP_PRETERMINATE_DATE>CURDATE(),CLP_ENDDATE>CURDATE()));
					SET TERM_NULL_ENDATE=(SELECT CLP_ENDDATE FROM CUSTOMER_LP_DETAILS WHERE CED_REC_VER=MIN_RECVER AND CUSTOMER_ID=CT_CUSTOMER_ID AND CLP_GUEST_CARD IS NULL AND IF (CLP_PRETERMINATE_DATE IS NOT NULL ,CLP_PRETERMINATE_DATE>CURDATE(),CLP_ENDDATE>CURDATE()));
					SET TERM_NULL_NRVSTARTDATE=(SELECT CLP_STARTDATE FROM CUSTOMER_LP_DETAILS WHERE CED_REC_VER=(MIN_RECVER+1) AND CUSTOMER_ID=CT_CUSTOMER_ID AND CLP_GUEST_CARD IS NULL AND IF (CLP_PRETERMINATE_DATE IS NOT NULL ,CLP_PRETERMINATE_DATE>CURDATE(),CLP_ENDDATE>CURDATE()));					
					SET TERM_NULL_NRVENDATE=(SELECT CLP_ENDDATE FROM CUSTOMER_LP_DETAILS WHERE CED_REC_VER=(MIN_RECVER+1) AND CUSTOMER_ID=CT_CUSTOMER_ID AND CLP_GUEST_CARD IS NULL AND IF (CLP_PRETERMINATE_DATE IS NOT NULL ,CLP_PRETERMINATE_DATE>CURDATE(),CLP_ENDDATE>CURDATE()));					
					-- TICKLER PART FOR TERM DETAILS
					SET TERM_UASDID = (SELECT UASD_ID FROM CUSTOMER_LP_DETAILS WHERE CED_REC_VER=MIN_RECVER AND CLP_GUEST_CARD IS NULL AND CUSTOMER_ID=CT_CUSTOMER_ID AND IF (CLP_PRETERMINATE_DATE IS NOT NULL ,CLP_PRETERMINATE_DATE>CURDATE(),CLP_ENDDATE>CURDATE()));
					SET TICK_PTD=(SELECT CLP_PRETERMINATE_DATE FROM CUSTOMER_LP_DETAILS WHERE CED_REC_VER=MIN_RECVER AND CLP_GUEST_CARD IS NULL AND CUSTOMER_ID=CT_CUSTOMER_ID AND IF (CLP_PRETERMINATE_DATE IS NOT NULL ,CLP_PRETERMINATE_DATE>CURDATE(),CLP_ENDDATE>CURDATE()));
					IF TICK_PTD IS NULL THEN 
					    SET TICK_PTD='null';
					END IF;					
					-- INSERT TERM DETAILS IN TICKLER TABLE FOR CUST START					
					-- TICKLER PART FOR TERM DETAILS						
						IF (SELECT COUNT(*) FROM CUSTOMER_LP_DETAILS WHERE CED_REC_VER=(MIN_RECVER+1) AND CLP_STARTDATE=TERM_NULL_ENDATE AND CUSTOMER_ID=CT_CUSTOMER_ID AND IF (CLP_PRETERMINATE_DATE IS NOT NULL ,CLP_PRETERMINATE_DATE>CURDATE(),CLP_ENDDATE>CURDATE()))>0 THEN
							IF MIN_RECVER<CT_REC_VER THEN
								IF TERM_UASDID IS NOT NULL THEN
									SET TICK_OLD_VALUE=(SELECT CONCAT('CLP_ID=',(SELECT CLP_ID FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CT_CUSTOMER_ID AND CED_REC_VER=MIN_RECVER AND UASD_ID=TERM_UASDID),',CED_REC_VER=',MIN_RECVER,',CLP_GUEST_CARD=null',',UASD_ID=',TERM_UASDID,',CLP_STARTDATE=',(SELECT CLP_STARTDATE FROM CUSTOMER_LP_DETAILS WHERE CED_REC_VER=MIN_RECVER AND CUSTOMER_ID=CT_CUSTOMER_ID AND CLP_GUEST_CARD IS NULL),',CLP_ENDDATE=',TERM_NULL_ENDATE,',CLP_PRETERMINATE_DATE=',TICK_PTD,',CLP_TERMINATE=null'));
								ELSE
									SET TICK_OLD_VALUE=(SELECT CONCAT('CLP_ID=',(SELECT CLP_ID FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CT_CUSTOMER_ID AND CED_REC_VER=MIN_RECVER ),',CED_REC_VER=',MIN_RECVER,',CLP_GUEST_CARD=null',',UASD_ID=null',',CLP_STARTDATE=',(SELECT CLP_STARTDATE FROM CUSTOMER_LP_DETAILS WHERE CED_REC_VER=MIN_RECVER AND CUSTOMER_ID=CT_CUSTOMER_ID AND CLP_GUEST_CARD IS NULL),',CLP_ENDDATE=',TERM_NULL_ENDATE,',CLP_PRETERMINATE_DATE=',TICK_PTD,',CLP_TERMINATE=null'));
								END IF;							
								IF TERM_NULL_PTD IS NOT NULL THEN
									UPDATE CUSTOMER_LP_DETAILS CTD SET CTD.CLP_PRETERMINATE_DATE=NULL, CTD.ULD_ID=USERSTAMP_ID WHERE CTD.CUSTOMER_ID=CT_CUSTOMER_ID AND CTD.CED_REC_VER=MIN_RECVER AND CTD.CLP_GUEST_CARD IS NULL;
									SET TERMRESULT_FLAG=1;
									SET TICK_NEW_VALUE='CLP_PRETERMINATE_DATE=null';
									INSERT INTO TICKLER_HISTORY(TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE,ULD_ID,CUSTOMER_ID)VALUES(1,14,TICK_OLD_VALUE,TICK_NEW_VALUE,USERSTAMP_ID,CT_CUSTOMER_ID);
								END IF;	
							END IF;	
						ELSE
							IF (SELECT COUNT(*) FROM CUSTOMER_LP_DETAILS WHERE CED_REC_VER=(MIN_RECVER+1) AND (CLP_STARTDATE>TERM_NULL_PTD OR CLP_STARTDATE<TERM_NULL_PTD) AND CUSTOMER_ID=CT_CUSTOMER_ID AND IF (CLP_PRETERMINATE_DATE IS NOT NULL ,CLP_PRETERMINATE_DATE>CURDATE(),CLP_ENDDATE>CURDATE()))>0 AND TERM_NULL_PTD IS NOT NULL  AND TERM_NULL_STARTDATE<TERM_NULL_PTD AND TERM_NULL_ENDATE>=TERM_NULL_PTD THEN								
								IF TERM_NULL_PTD<TERM_NULL_NRVENDATE THEN
									SET PTDFLAG=1;											
								ELSEIF TERM_NULL_ENDATE<TERM_NULL_NRVENDATE THEN
									SET EDFLAG=1;
								END IF;
							ELSEIF (SELECT COUNT(*) FROM CUSTOMER_LP_DETAILS WHERE CED_REC_VER=(MIN_RECVER+1) AND (CLP_STARTDATE>TERM_NULL_PTD OR CLP_STARTDATE<TERM_NULL_PTD) AND CUSTOMER_ID=CT_CUSTOMER_ID AND IF (CLP_PRETERMINATE_DATE IS NOT NULL ,CLP_PRETERMINATE_DATE>CURDATE(),CLP_ENDDATE>CURDATE()))>0 AND TERM_NULL_PTD IS NOT NULL  AND (TERM_NULL_STARTDATE>=TERM_NULL_PTD OR TERM_NULL_ENDATE<TERM_NULL_PTD) THEN								
								IF TERM_NULL_ENDATE<TERM_NULL_NRVENDATE THEN
									SET EDFLAG=1;
								END IF;		
							ELSEIF (SELECT COUNT(*) FROM CUSTOMER_LP_DETAILS WHERE CED_REC_VER=(MIN_RECVER+1) AND (CLP_STARTDATE>TERM_NULL_ENDATE OR CLP_STARTDATE<TERM_NULL_ENDATE) AND CUSTOMER_ID=CT_CUSTOMER_ID AND IF (CLP_PRETERMINATE_DATE IS NOT NULL ,CLP_PRETERMINATE_DATE>CURDATE(),CLP_ENDDATE>CURDATE()))>0 AND TERM_NULL_PTD IS NULL THEN								
								IF TERM_NULL_ENDATE<TERM_NULL_NRVENDATE THEN
									SET EDFLAG=1;								
								END IF;
							END IF;								
							IF PTDFLAG=1 OR EDFLAG=1 THEN									
								SET MIN_CTDID=(SELECT MIN(CLP_ID) FROM CUSTOMER_LP_DETAILS WHERE CED_REC_VER=MIN_RECVER+1 AND CUSTOMER_ID=CT_CUSTOMER_ID);
								SET MAX_CTDID=(SELECT MAX(CLP_ID) FROM CUSTOMER_LP_DETAILS WHERE CED_REC_VER=MIN_RECVER+1 AND CUSTOMER_ID=CT_CUSTOMER_ID);
										WHILE (MIN_CTDID<=MAX_CTDID) DO
											IF EXISTS (SELECT CLP_ID FROM CUSTOMER_LP_DETAILS WHERE CLP_ID=MIN_CTDID AND IF (CLP_PRETERMINATE_DATE IS NOT NULL ,CLP_PRETERMINATE_DATE>CURDATE(),CLP_ENDDATE>CURDATE())) THEN
													SET CLP_GSTVAL=(SELECT CLP_GUEST_CARD FROM CUSTOMER_LP_DETAILS WHERE CLP_ID=MIN_CTDID);
													IF CLP_GSTVAL IS NULL THEN
														SET CLP_GSTVAL='null';
													END IF;
													SET CLP_UASDIDVAL=(SELECT UASD_ID FROM CUSTOMER_LP_DETAILS WHERE CLP_ID=MIN_CTDID);
													IF CLP_UASDIDVAL IS NOT NULL THEN
														SET TICK_OLD_VALUE=(SELECT CONCAT('CLP_ID=',MIN_CTDID,',CED_REC_VER=',(MIN_RECVER+1),',CLP_GUEST_CARD=',CLP_GSTVAL,',UASD_ID=',CLP_UASDIDVAL,',CLP_STARTDATE=',(SELECT CLP_STARTDATE FROM CUSTOMER_LP_DETAILS WHERE CED_REC_VER=MIN_RECVER+1 AND CUSTOMER_ID=CT_CUSTOMER_ID AND CLP_ID=MIN_CTDID),',CLP_ENDDATE=',TERM_NULL_ENDATE,',CLP_PRETERMINATE_DATE=',TICK_PTD,',CLP_TERMINATE=null'));
													ELSE
														SET TICK_OLD_VALUE=(SELECT CONCAT('CLP_ID=',MIN_CTDID,',CED_REC_VER=',(MIN_RECVER+1),',CLP_GUEST_CARD=',CLP_GSTVAL,',UASD_ID=null',',CLP_STARTDATE=',(SELECT CLP_STARTDATE FROM CUSTOMER_LP_DETAILS WHERE CED_REC_VER=MIN_RECVER+1 AND CUSTOMER_ID=CT_CUSTOMER_ID AND CLP_ID=MIN_CTDID),',CLP_ENDDATE=',TERM_NULL_ENDATE,',CLP_PRETERMINATE_DATE=',TICK_PTD,',CLP_TERMINATE=null'));
													END IF;
												IF PTDFLAG=1 THEN
													IF(TERM_NULL_PTD!=TERM_NULL_NRVSTARTDATE) THEN												
														IF CLP_UASDIDVAL IS NOT NULL THEN
															UPDATE CUSTOMER_ACCESS_CARD_DETAILS SET CACD_VALID_FROM=TERM_NULL_PTD WHERE UASD_ID=CLP_UASDIDVAL AND CUSTOMER_ID=CT_CUSTOMER_ID AND ACN_ID IS NULL;
															SET TICK_ACS_OLD_VALUE=(SELECT CONCAT('CACD_ID=',(SELECT CACD_ID FROM CUSTOMER_ACCESS_CARD_DETAILS WHERE UASD_ID=CLP_UASDIDVAL AND CUSTOMER_ID=CT_CUSTOMER_ID AND ACN_ID IS NULL),',UASD_ID=',CLP_UASDIDVAL,',ACN_ID=null',',CACD_VALID_FROM=',(SELECT CACD_VALID_FROM FROM CUSTOMER_ACCESS_CARD_DETAILS WHERE UASD_ID=CLP_UASDIDVAL AND CUSTOMER_ID=CT_CUSTOMER_ID AND ACN_ID IS NULL),',CACD_VALID_TILL=null',',CACD_GUEST_CARD=',CLP_GSTVAL,',ULD_ID=',USERSTAMP_ID));
															SET TICK_NEW_VALUE=(SELECT CONCAT('CACD_VALID_FROM=',TERM_NULL_PTD));
															INSERT INTO TICKLER_HISTORY(TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE,ULD_ID,CUSTOMER_ID)VALUES(1,13,TICK_ACS_OLD_VALUE,TICK_NEW_VALUE,USERSTAMP_ID,CT_CUSTOMER_ID);
														END IF;
														UPDATE CUSTOMER_LP_DETAILS CTD SET CTD.CLP_STARTDATE=TERM_NULL_PTD, CTD.ULD_ID=USERSTAMP_ID WHERE CTD.CUSTOMER_ID=CT_CUSTOMER_ID AND CTD.CED_REC_VER=(MIN_RECVER+1);
														SET TERMRESULT_FLAG=1;													
														SET TICK_NEW_VALUE=(SELECT CONCAT('CLP_STARTDATE=',TERM_NULL_PTD));
														INSERT INTO TICKLER_HISTORY(TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE,ULD_ID,CUSTOMER_ID)VALUES(1,14,TICK_OLD_VALUE,TICK_NEW_VALUE,USERSTAMP_ID,CT_CUSTOMER_ID);
													END IF;											
												ELSEIF EDFLAG=1 THEN
													IF(TERM_NULL_ENDATE!=TERM_NULL_NRVSTARTDATE) THEN
														IF CLP_UASDIDVAL IS NOT NULL THEN
															UPDATE CUSTOMER_ACCESS_CARD_DETAILS SET CACD_VALID_FROM=TERM_NULL_ENDATE WHERE UASD_ID=CLP_UASDIDVAL AND CUSTOMER_ID=CT_CUSTOMER_ID AND ACN_ID IS NULL;
															SET TICK_ACS_OLD_VALUE=(SELECT CONCAT('CACD_ID=',(SELECT CACD_ID FROM CUSTOMER_ACCESS_CARD_DETAILS WHERE UASD_ID=CLP_UASDIDVAL AND CUSTOMER_ID=CT_CUSTOMER_ID AND ACN_ID IS NULL),',UASD_ID=',CLP_UASDIDVAL,',ACN_ID=null',',CACD_VALID_FROM=',(SELECT CACD_VALID_FROM FROM CUSTOMER_ACCESS_CARD_DETAILS WHERE UASD_ID=CLP_UASDIDVAL AND CUSTOMER_ID=CT_CUSTOMER_ID AND ACN_ID IS NULL),',CACD_VALID_TILL=null',',CACD_GUEST_CARD=',CLP_GSTVAL,',ULD_ID=',USERSTAMP_ID));
															SET TICK_NEW_VALUE=(SELECT CONCAT('CACD_VALID_FROM=',TERM_NULL_ENDATE));
															INSERT INTO TICKLER_HISTORY(TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE,ULD_ID,CUSTOMER_ID)VALUES(1,13,TICK_ACS_OLD_VALUE,TICK_NEW_VALUE,USERSTAMP_ID,CT_CUSTOMER_ID);
														END IF;
														UPDATE CUSTOMER_LP_DETAILS CTD SET CTD.CLP_STARTDATE=TERM_NULL_ENDATE, CTD.ULD_ID=USERSTAMP_ID WHERE CTD.CUSTOMER_ID=CT_CUSTOMER_ID AND CTD.CED_REC_VER=(MIN_RECVER+1);
														SET TERMRESULT_FLAG=1;													
														SET TICK_NEW_VALUE=(SELECT CONCAT('CLP_STARTDATE=',TERM_NULL_ENDATE));
														INSERT INTO TICKLER_HISTORY(TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE,ULD_ID,CUSTOMER_ID)VALUES(1,14,TICK_OLD_VALUE,TICK_NEW_VALUE,USERSTAMP_ID,CT_CUSTOMER_ID);
													END IF;
												END IF;
											END IF;
											SET MIN_CTDID=MIN_CTDID+1;
										END WHILE;
									END IF;							
						END IF;
					IF MIN_RECVER=MAX_RECVER THEN
						LEAVE RECVER_LOOP;
					END IF;
					SET MIN_RECVER=MIN_RECVER+1;
					SET EDFLAG=0;
					SET PTDFLAG=0;
				END LOOP;					
			END IF;
			-- update ptd=null from active rv to input rv -1 end
			-- update input ptd >= input rv start
			SET MIN_RECVER=CT_REC_VER;-- input rv			
			SET MAX_RECVER=TERM_MAX_CUSTRV;			
			IF(MAX_RECVER>=MIN_RECVER) THEN			
				RECVER_LOOP:  LOOP
				IF(SELECT COUNT(*) FROM CUSTOMER_LP_DETAILS WHERE CED_REC_VER=MIN_RECVER AND CUSTOMER_ID=CT_CUSTOMER_ID AND IF (CLP_PRETERMINATE_DATE IS NOT NULL ,CLP_PRETERMINATE_DATE>CURDATE(),CLP_ENDDATE>CURDATE())) >0 THEN				
					SET TERM_NULL_PTD=(SELECT CLP_PRETERMINATE_DATE FROM CUSTOMER_LP_DETAILS WHERE CED_REC_VER=MIN_RECVER AND CUSTOMER_ID=CT_CUSTOMER_ID AND CLP_GUEST_CARD IS NULL);
					SET TERM_NULL_ENDATE=(SELECT CLP_ENDDATE FROM CUSTOMER_LP_DETAILS WHERE CED_REC_VER=MIN_RECVER AND CUSTOMER_ID=CT_CUSTOMER_ID AND CLP_GUEST_CARD IS NULL);
					SET TERM_UASDID = (SELECT UASD_ID FROM CUSTOMER_LP_DETAILS WHERE CED_REC_VER=MIN_RECVER AND CLP_GUEST_CARD IS NULL AND CUSTOMER_ID=CT_CUSTOMER_ID );
					SET TICK_PTD=(SELECT CLP_PRETERMINATE_DATE FROM CUSTOMER_LP_DETAILS WHERE CED_REC_VER=MIN_RECVER AND CLP_GUEST_CARD IS NULL AND CUSTOMER_ID=CT_CUSTOMER_ID);
					IF TICK_PTD IS NULL THEN 
					    SET TICK_PTD='null';
					END IF;								
					-- update ptd date in cust rv start					
					UPDATE CUSTOMER_LP_DETAILS CTD SET CTD.CLP_PRETERMINATE_DATE=PRETERMINATE_DATE, CTD.ULD_ID=USERSTAMP_ID WHERE CTD.CUSTOMER_ID=CT_CUSTOMER_ID AND CTD.CED_REC_VER=MIN_RECVER AND CTD.CLP_GUEST_CARD IS NULL;
					SET TERMRESULT_FLAG=1;
					-- update ptd date in cust rv end					
					-- INSERT TERM DETAILS IN TICKLER TABLE FOR CUST START
					IF TERM_UASDID IS NOT NULL THEN
						SET TICK_OLD_VALUE=(SELECT CONCAT('CLP_ID=',(SELECT CLP_ID FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CT_CUSTOMER_ID AND CED_REC_VER=MIN_RECVER AND UASD_ID=TERM_UASDID),',CED_REC_VER=',MIN_RECVER,',CLP_GUEST_CARD=null',',UASD_ID=',TERM_UASDID,',CLP_PRETERMINATE_DATE=',TICK_PTD,',CLP_TERMINATE=null'));					
					ELSE
						SET TICK_OLD_VALUE=(SELECT CONCAT('CLP_ID=',(SELECT CLP_ID FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CT_CUSTOMER_ID AND CED_REC_VER=MIN_RECVER),',CED_REC_VER=',MIN_RECVER,',CLP_GUEST_CARD=null',',UASD_ID=null',',CLP_PRETERMINATE_DATE=',TICK_PTD,',CLP_TERMINATE=null'));					
					END IF;						
					IF PRETERMINATE_DATE<=CURRENT_DATE() AND MIN_RECVER=CT_REC_VER THEN
						SET TICK_NEW_VALUE=(SELECT CONCAT('CLP_PRETERMINATE_DATE=',PRETERMINATE_DATE,',CLP_TERMINATE=X'));
					ELSE
						SET TICK_NEW_VALUE=(SELECT CONCAT('CLP_PRETERMINATE_DATE=',PRETERMINATE_DATE));
					END IF;					
					INSERT INTO TICKLER_HISTORY(TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE,ULD_ID,CUSTOMER_ID)VALUES(1,14,TICK_OLD_VALUE,TICK_NEW_VALUE,USERSTAMP_ID,CT_CUSTOMER_ID);
					-- INSERT TERM DETAILS IN TICKLER TABLE FOR CUST END
					IF MIN_RECVER=MAX_RECVER THEN
						LEAVE RECVER_LOOP;
					END IF;
					SET MIN_RECVER=MIN_RECVER+1;
				END IF;
				END LOOP;				
			END IF;			
			-- update input ptd >= input rv end				
			IF PRETERMINATE_DATE<=CURRENT_DATE() THEN
				SET MIN_RECVER=CT_REC_VER;
				SET MAX_RECVER=(SELECT MAX(CED.CED_REC_VER) FROM CUSTOMER_ENTRY_DETAILS AS CED WHERE CED.CUSTOMER_ID=CT_CUSTOMER_ID);
				RECVER_LOOP:  LOOP
					SET TERM_UASDID = (SELECT UASD_ID FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CT_CUSTOMER_ID AND CED_REC_VER=MIN_RECVER AND CLP_GUEST_CARD IS NULL ORDER BY CLP_ID DESC LIMIT 1);
					SET TICK_CARD_NO=(SELECT UASD_ACCESS_CARD FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ID=TERM_UASDID);		
					IF TERM_UASDID IS NOT NULL THEN
					-- changed terminate=x for the rv cust ptd<=current date for cust only
						IF EXISTS(SELECT * FROM CUSTOMER_ACCESS_CARD_DETAILS WHERE CUSTOMER_ID=CT_CUSTOMER_ID AND UASD_ID=TERM_UASDID AND CACD_VALID_TILL IS NULL) THEN
							UPDATE CUSTOMER_LP_DETAILS CTD SET CTD.CLP_TERMINATE='X' WHERE CTD.CUSTOMER_ID=CT_CUSTOMER_ID AND CTD.CED_REC_VER=CT_REC_VER AND CLP_GUEST_CARD IS NULL ORDER BY CTD.CLP_ID;
							SET TICK_OLD_VALUE=(SELECT CONCAT('CACD_ID=',(SELECT CACD_ID FROM CUSTOMER_ACCESS_CARD_DETAILS WHERE UASD_ID=TERM_UASDID AND ACN_ID IS NULL AND CACD_VALID_TILL IS NULL),',UASD_ID=',TERM_UASDID,',CACD_GUEST_CARD=null',',CACD_VALID_TILL=null,ACN_ID=null'));
							UPDATE CUSTOMER_ACCESS_CARD_DETAILS SET CACD_VALID_TILL=PRETERMINATE_DATE, ACN_ID=4, ULD_ID=USERSTAMP_ID WHERE CUSTOMER_ID=CT_CUSTOMER_ID AND UASD_ID=TERM_UASDID AND CACD_VALID_TILL IS NULL;
							UPDATE UNIT_ACCESS_STAMP_DETAILS SET UASD_ACCESS_ACTIVE=NULL, UASD_ACCESS_INVENTORY='X' WHERE UASD_ID=TERM_UASDID;
							SET TERMRESULT_FLAG=1;
							-- TICKLER FOR ACS CARD DTS FOR CUST START						
							SET TICK_NEW_VALUE=(SELECT CONCAT('CACD_VALID_TILL=',PRETERMINATE_DATE,',ACN_ID=4'));
							INSERT INTO TICKLER_HISTORY(TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE,ULD_ID,CUSTOMER_ID)VALUES(1,13,TICK_OLD_VALUE,TICK_NEW_VALUE,USERSTAMP_ID,CT_CUSTOMER_ID);
							-- TICKLER FOR ACS CARD DTS FOR CUST END
						END IF;						
					ELSE
					-- changed terminate=x for the rv cust ptd<=current date for cust only
						UPDATE CUSTOMER_LP_DETAILS CTD SET CTD.CLP_TERMINATE='X' WHERE CTD.CUSTOMER_ID=CT_CUSTOMER_ID AND CTD.CED_REC_VER=CT_REC_VER AND CLP_GUEST_CARD IS NULL ORDER BY CTD.CLP_ID;
						SET TERMRESULT_FLAG=1;
					END IF;
					IF MIN_RECVER>CT_REC_VER THEN					
						SET GUEST_CARD_COUNT=(SELECT COUNT(*) FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CT_CUSTOMER_ID AND CED_REC_VER=MIN_RECVER AND CLP_GUEST_CARD IS NOT NULL AND ((CLP_PRETERMINATE_DATE IS NOT NULL AND CLP_PRETERMINATE_DATE>=CURRENT_DATE())OR(CLP_PRETERMINATE_DATE IS NULL AND CLP_ENDDATE>=CURRENT_DATE())));
						GUESTCARD_LOOP:  LOOP
							IF GUEST_CARD_COUNT <= 0 THEN
								LEAVE GUESTCARD_LOOP;
							END IF;
							SET CARD_ON=GUEST_CARD_COUNT-1;
							SET TERM_UASDID = (SELECT UASD_ID FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CT_CUSTOMER_ID AND CED_REC_VER=MIN_RECVER AND CLP_GUEST_CARD IS NOT NULL AND ((CLP_PRETERMINATE_DATE IS NOT NULL AND CLP_PRETERMINATE_DATE>=CURRENT_DATE())OR(CLP_PRETERMINATE_DATE IS NULL AND CLP_ENDDATE>=CURRENT_DATE())) ORDER BY CLP_ID DESC LIMIT CARD_ON,1);
							SET TICK_PTD=(SELECT CLP_PRETERMINATE_DATE FROM CUSTOMER_LP_DETAILS WHERE CED_REC_VER=MIN_RECVER AND CLP_GUEST_CARD IS NOT NULL AND CUSTOMER_ID=CT_CUSTOMER_ID AND UASD_ID=TERM_UASDID ORDER BY CLP_ID DESC LIMIT 1);
							IF TICK_PTD IS NULL THEN 
								SET TICK_PTD='null';
							END IF;							
							IF(SELECT COUNT(UASD_ID) FROM CUSTOMER_LP_DETAILS WHERE UASD_ID=TERM_UASDID AND CUSTOMER_ID=CT_CUSTOMER_ID AND CED_REC_VER=CT_REC_VER AND CLP_GUEST_CARD IS NOT NULL AND ((CLP_PRETERMINATE_DATE IS NOT NULL AND CLP_PRETERMINATE_DATE>=CURRENT_DATE())OR(CLP_PRETERMINATE_DATE IS NULL AND CLP_ENDDATE>=CURRENT_DATE())))=0 THEN
								UPDATE CUSTOMER_LP_DETAILS CTD SET CTD.CLP_PRETERMINATE_DATE=PRETERMINATE_DATE, CTD.ULD_ID=USERSTAMP_ID WHERE CTD.CUSTOMER_ID=CT_CUSTOMER_ID AND CTD.CED_REC_VER=MIN_RECVER AND CTD.CLP_GUEST_CARD IS NOT NULL AND UASD_ID=TERM_UASDID ORDER BY CTD.CLP_ID DESC LIMIT 1;
								UPDATE CUSTOMER_ACCESS_CARD_DETAILS SET CACD_VALID_TILL=PRETERMINATE_DATE, ACN_ID=4, ULD_ID=USERSTAMP_ID WHERE CUSTOMER_ID=CT_CUSTOMER_ID AND UASD_ID=TERM_UASDID AND CACD_VALID_TILL IS NULL;
								UPDATE UNIT_ACCESS_STAMP_DETAILS SET UASD_ACCESS_ACTIVE=NULL, UASD_ACCESS_INVENTORY='X' WHERE UASD_ID=TERM_UASDID;	
								SET TERMRESULT_FLAG=1;								
								-- INSERT TERM DETAILS IN TICKLER TABLE FOR GUEST START	
									SET TICK_NEW_VALUE=(SELECT CONCAT('CLP_PRETERMINATE_DATE=',PRETERMINATE_DATE));					
									IF TERM_UASDID IS NOT NULL THEN
										SET TICK_OLD_VALUE=(SELECT CONCAT('CLP_ID=',(SELECT CLP_ID FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CT_CUSTOMER_ID AND CED_REC_VER=MIN_RECVER AND UASD_ID=TERM_UASDID),',CED_REC_VER=',MIN_RECVER,',CLP_GUEST_CARD=X',',UASD_ID=',TERM_UASDID,',CLP_PRETERMINATE_DATE=',TICK_PTD,',CLP_TERMINATE=null'));
										INSERT INTO TICKLER_HISTORY(TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE,ULD_ID,CUSTOMER_ID)VALUES(1,14,TICK_OLD_VALUE,TICK_NEW_VALUE,USERSTAMP_ID,CT_CUSTOMER_ID);
									END IF;
								-- INSERT TERM DETAILS IN TICKLER TABLE FOR GUEST END							
							END IF;
							SET GUEST_CARD_COUNT=(GUEST_CARD_COUNT-1);
						END LOOP;
					END IF;
					SET TERM_UASDID = NULL;
					IF MIN_RECVER=MAX_RECVER THEN
						LEAVE RECVER_LOOP;
					END IF;
					SET MIN_RECVER=MIN_RECVER+1;
				END LOOP;
				-- RELEASING CARD THAT ALREADY PTD<=SYSDATE START
				SET TERM_GUEST_CARD_COUNT=(SELECT COUNT(*) FROM CUSTOMER_ACCESS_CARD_DETAILS CACD WHERE CACD.CUSTOMER_ID=CT_CUSTOMER_ID AND CACD.ACN_ID IS NULL AND CACD.CACD_VALID_TILL IS NULL);
				TERMGUESTCARD_LOOP:  LOOP
					IF TERM_GUEST_CARD_COUNT <= 0 THEN
						LEAVE TERMGUESTCARD_LOOP;
					END IF;					
					SET CARD_ON=TERM_GUEST_CARD_COUNT-1;					
					SET TERM_UASDID = (SELECT UASD_ID FROM CUSTOMER_ACCESS_CARD_DETAILS CACD WHERE CACD.CUSTOMER_ID=CT_CUSTOMER_ID  AND CACD.ACN_ID IS NULL AND CACD.CACD_VALID_TILL IS NULL ORDER BY CACD.CACD_ID DESC LIMIT CARD_ON,1);
					SET TICK_CARD_NO=(SELECT UASD_ACCESS_CARD FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ID=TERM_UASDID);
					SET TICK_GUEST_CARD= (SELECT CACD_GUEST_CARD FROM CUSTOMER_ACCESS_CARD_DETAILS CACD WHERE CACD.CUSTOMER_ID=CT_CUSTOMER_ID  AND CACD.ACN_ID IS NULL AND CACD.CACD_VALID_TILL IS NULL ORDER BY CACD.CACD_ID DESC LIMIT CARD_ON,1);
					SET TERM_REC_VER = (SELECT MAX(CTD.CED_REC_VER) FROM CUSTOMER_LP_DETAILS CTD WHERE CTD.CUSTOMER_ID=CT_CUSTOMER_ID  AND CTD.UASD_ID=TERM_UASDID AND CTD.CLP_STARTDATE<(IF(CTD.CLP_PRETERMINATE_DATE IS NULL,CTD.CLP_ENDDATE,CTD.CLP_PRETERMINATE_DATE)));
					SET TERM_END_DATE = (SELECT CTD.CLP_ENDDATE FROM CUSTOMER_LP_DETAILS CTD WHERE CTD.CUSTOMER_ID=CT_CUSTOMER_ID AND CTD.CED_REC_VER=TERM_REC_VER AND CTD.UASD_ID=TERM_UASDID ORDER BY CTD.CLP_ID DESC LIMIT 1);
					SET TERM_PTD = (SELECT CTD.CLP_PRETERMINATE_DATE FROM CUSTOMER_LP_DETAILS CTD WHERE CTD.CUSTOMER_ID=CT_CUSTOMER_ID AND CTD.CED_REC_VER=TERM_REC_VER AND CTD.UASD_ID=TERM_UASDID ORDER BY CTD.CLP_ID DESC LIMIT 1);
					IF TERM_PTD IS NOT NULL THEN
						SET TERM_END_DATE = TERM_PTD;
					END IF;
					IF(TICK_GUEST_CARD IS NULL) THEN
						SET TICK_GUEST_CARD=('null');
					END IF;
					IF (TERM_END_DATE<=CURRENT_DATE() AND TERM_REC_VER<=CT_REC_VER) THEN					
						-- TICKLER FOR ACS CARD DTS FOR GUEST START						
						SET TICK_NEW_VALUE=(SELECT CONCAT('CACD_VALID_TILL=',TERM_END_DATE,',ACN_ID=4'));
						SET TICK_OLD_VALUE=(SELECT CONCAT('CACD_ID=',(SELECT CACD_ID FROM CUSTOMER_ACCESS_CARD_DETAILS WHERE CUSTOMER_ID=CT_CUSTOMER_ID AND UASD_ID=TERM_UASDID AND CACD_VALID_TILL IS NULL AND ACN_ID IS NULL),',UASD_ID=',TERM_UASDID,',CACD_GUEST_CARD=',TICK_GUEST_CARD,',CACD_VALID_TILL=null,ACN_ID=null'));
						INSERT INTO TICKLER_HISTORY(TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE,ULD_ID,CUSTOMER_ID)VALUES(1,13,TICK_OLD_VALUE,TICK_NEW_VALUE,USERSTAMP_ID,CT_CUSTOMER_ID);
						-- TICKLER FOR ACS CARD DTS FOR GUEST END						
						UPDATE CUSTOMER_ACCESS_CARD_DETAILS SET CACD_VALID_TILL=TERM_END_DATE, ACN_ID=4, ULD_ID=USERSTAMP_ID WHERE CUSTOMER_ID=CT_CUSTOMER_ID AND UASD_ID=TERM_UASDID AND CACD_VALID_TILL IS NULL;
						UPDATE UNIT_ACCESS_STAMP_DETAILS SET UASD_ACCESS_ACTIVE=NULL, UASD_ACCESS_INVENTORY='X' WHERE UASD_ID=TERM_UASDID;
						SET TERMRESULT_FLAG=1;
					END IF;
					SET TERM_GUEST_CARD_COUNT=(TERM_GUEST_CARD_COUNT-1);
					SET TERM_PTD=NULL;
				END LOOP;
				-- RELEASING CARD THAT ALREADY PTD<=SYSDATE START END
			ELSE
				SET MIN_RECVER=CT_REC_VER;
				SET MAX_RECVER=(SELECT MAX(CED.CED_REC_VER) FROM CUSTOMER_ENTRY_DETAILS AS CED WHERE CED.CUSTOMER_ID=CT_CUSTOMER_ID);
				RECVER_LOOP:  LOOP
				IF(SELECT COUNT(*) FROM CUSTOMER_LP_DETAILS WHERE CED_REC_VER=MIN_RECVER AND CUSTOMER_ID=CT_CUSTOMER_ID AND IF (CLP_PRETERMINATE_DATE IS NOT NULL ,CLP_PRETERMINATE_DATE>CURDATE(),CLP_ENDDATE>CURDATE())) >0 THEN				
					IF MIN_RECVER>CT_REC_VER THEN					
						SET GUEST_CARD_COUNT=(SELECT COUNT(*) FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CT_CUSTOMER_ID AND CED_REC_VER=MIN_RECVER AND CLP_GUEST_CARD IS NOT NULL AND ((CLP_PRETERMINATE_DATE IS NOT NULL AND CLP_PRETERMINATE_DATE>=CURRENT_DATE())OR(CLP_PRETERMINATE_DATE IS NULL AND CLP_ENDDATE>=CURRENT_DATE())));
						GUESTCARD_LOOP:  LOOP
							IF GUEST_CARD_COUNT <= 0 THEN
								LEAVE GUESTCARD_LOOP;
							END IF;
							SET CARD_ON=GUEST_CARD_COUNT-1;
							SET TERM_UASDID = (SELECT UASD_ID FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CT_CUSTOMER_ID AND CED_REC_VER=MIN_RECVER AND CLP_GUEST_CARD IS NOT NULL AND ((CLP_PRETERMINATE_DATE IS NOT NULL AND CLP_PRETERMINATE_DATE>=CURRENT_DATE())OR(CLP_PRETERMINATE_DATE IS NULL AND CLP_ENDDATE>=CURRENT_DATE())) ORDER BY CLP_ID DESC LIMIT CARD_ON,1);
							SET TICK_PTD=(SELECT CLP_PRETERMINATE_DATE FROM CUSTOMER_LP_DETAILS WHERE CED_REC_VER=MIN_RECVER AND CLP_GUEST_CARD IS NOT NULL AND CUSTOMER_ID=CT_CUSTOMER_ID AND UASD_ID=TERM_UASDID ORDER BY CLP_ID DESC LIMIT 1);
							IF TICK_PTD IS NULL THEN 
								SET TICK_PTD='null';
							END IF;							
							IF(SELECT COUNT(UASD_ID) FROM CUSTOMER_LP_DETAILS WHERE UASD_ID=TERM_UASDID AND CUSTOMER_ID=CT_CUSTOMER_ID AND CED_REC_VER=CT_REC_VER AND CLP_GUEST_CARD IS NOT NULL AND ((CLP_PRETERMINATE_DATE IS NOT NULL AND CLP_PRETERMINATE_DATE>=CURRENT_DATE())OR(CLP_PRETERMINATE_DATE IS NULL AND CLP_ENDDATE>=CURRENT_DATE())))=0 THEN
								UPDATE CUSTOMER_LP_DETAILS CTD SET CTD.CLP_PRETERMINATE_DATE=PRETERMINATE_DATE, CTD.ULD_ID=USERSTAMP_ID WHERE CTD.CUSTOMER_ID=CT_CUSTOMER_ID AND CTD.CED_REC_VER=MIN_RECVER AND CTD.CLP_GUEST_CARD IS NOT NULL AND UASD_ID=TERM_UASDID ORDER BY CTD.CLP_ID DESC LIMIT 1;
								SET TERMRESULT_FLAG=1;
								-- INSERT TERM DETAILS IN TICKLER TABLE FOR CUST START
									SET TICK_NEW_VALUE=(SELECT CONCAT('CLP_PRETERMINATE_DATE=',PRETERMINATE_DATE));					
									IF TERM_UASDID IS NOT NULL THEN
										SET TICK_OLD_VALUE=(SELECT CONCAT('CLP_ID=',(SELECT CLP_ID FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CT_CUSTOMER_ID AND UASD_ID=TERM_UASDID AND CED_REC_VER=MIN_RECVER),',CED_REC_VER=',MIN_RECVER,',CLP_GUEST_CARD=X',',UASD_ID=',TERM_UASDID,',CLP_PRETERMINATE_DATE=',TICK_PTD,',CLP_TERMINATE=null'));
										INSERT INTO TICKLER_HISTORY(TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE,ULD_ID,CUSTOMER_ID)VALUES(1,14,TICK_OLD_VALUE,TICK_NEW_VALUE,USERSTAMP_ID,CT_CUSTOMER_ID);									
									END IF;
								-- INSERT TERM DETAILS IN TICKLER TABLE FOR CUST END								
							END IF;
							SET GUEST_CARD_COUNT=(GUEST_CARD_COUNT-1);
							SET TERM_UASDID = NULL;
						END LOOP;
					END IF;
					IF MIN_RECVER=MAX_RECVER THEN
						LEAVE RECVER_LOOP;
					END IF;
					SET MIN_RECVER=MIN_RECVER+1;
				END IF;
				END LOOP;
			END IF;
		ELSE
			SET MIN_RECVER=ACTIVE_RECVER;
			SET MAX_RECVER=(SELECT MAX(CED.CED_REC_VER) FROM CUSTOMER_ENTRY_DETAILS AS CED WHERE CED.CUSTOMER_ID=CT_CUSTOMER_ID);
			RECVER_LOOP:  LOOP	
				IF(SELECT COUNT(*) FROM CUSTOMER_LP_DETAILS WHERE CED_REC_VER=MIN_RECVER AND CUSTOMER_ID=CT_CUSTOMER_ID AND IF (CLP_PRETERMINATE_DATE IS NOT NULL ,CLP_PRETERMINATE_DATE>CURDATE(),CLP_ENDDATE>CURDATE())) >0 THEN								
							SET TERM_UASDID = (SELECT CTD.UASD_ID FROM CUSTOMER_LP_DETAILS CTD WHERE CTD.CUSTOMER_ID=CT_CUSTOMER_ID AND CTD.CED_REC_VER=MIN_RECVER AND CTD.CLP_GUEST_CARD IS NOT NULL AND CTD.UASD_ID=UASDID ORDER BY CTD.CLP_ID DESC LIMIT 1);
							SET TICK_PTD=(SELECT CLP_PRETERMINATE_DATE FROM CUSTOMER_LP_DETAILS WHERE CED_REC_VER=MIN_RECVER AND CLP_GUEST_CARD IS NOT NULL AND CUSTOMER_ID=CT_CUSTOMER_ID AND UASD_ID=TERM_UASDID ORDER BY CLP_ID DESC LIMIT 1);
							IF TICK_PTD IS NULL THEN 
								SET TICK_PTD='null';
							END IF;	
						SET TICK_OLD_VALUE=(SELECT CONCAT('CLP_ID=',(SELECT CLP_ID FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CT_CUSTOMER_ID AND UASD_ID=TERM_UASDID AND CED_REC_VER=MIN_RECVER),',CED_REC_VER=',MIN_RECVER,',CLP_GUEST_CARD=X',',UASD_ID=',TERM_UASDID,',CLP_PRETERMINATE_DATE=',TICK_PTD));							
				IF ACTIVE_RECVER<CT_REC_VER THEN
					IF MIN_RECVER BETWEEN ACTIVE_RECVER AND (CT_REC_VER-1) THEN
					SET TICK_NEW_VALUE=(SELECT CONCAT('CLP_PRETERMINATE_DATE=null'));		
					-- CHECK GUEST PTD NULL COND START				
					SET TERM_NULL_PTD=(SELECT CLP_PRETERMINATE_DATE FROM CUSTOMER_LP_DETAILS WHERE CED_REC_VER=MIN_RECVER AND CUSTOMER_ID=CT_CUSTOMER_ID AND CLP_GUEST_CARD IS NULL AND IF (CLP_PRETERMINATE_DATE IS NOT NULL ,CLP_PRETERMINATE_DATE>CURDATE(),CLP_ENDDATE>CURDATE()));
					SET TERM_NULL_ENDATE=(SELECT CLP_ENDDATE FROM CUSTOMER_LP_DETAILS WHERE CED_REC_VER=MIN_RECVER AND CUSTOMER_ID=CT_CUSTOMER_ID AND CLP_GUEST_CARD IS NULL AND IF (CLP_PRETERMINATE_DATE IS NOT NULL ,CLP_PRETERMINATE_DATE>CURDATE(),CLP_ENDDATE>CURDATE()));
					-- CHECK GUEST PTD NULL COND END
					IF(SELECT COUNT(*) FROM CUSTOMER_LP_DETAILS WHERE CED_REC_VER=(MIN_RECVER+1) AND CLP_STARTDATE!=TERM_NULL_PTD AND CLP_GUEST_CARD IS NULL AND CUSTOMER_ID=CT_CUSTOMER_ID AND IF (CLP_PRETERMINATE_DATE IS NOT NULL ,CLP_PRETERMINATE_DATE>CURDATE(),CLP_ENDDATE>CURDATE()))>0 AND TERM_NULL_PTD IS NOT NULL THEN
						SET GST_NULL_FLAG=1;						
					END IF;
					IF(SELECT COUNT(*) FROM CUSTOMER_LP_DETAILS WHERE CED_REC_VER=(MIN_RECVER+1) AND CLP_STARTDATE=TERM_NULL_ENDATE AND CLP_GUEST_CARD IS NULL AND CUSTOMER_ID=CT_CUSTOMER_ID AND IF (CLP_PRETERMINATE_DATE IS NOT NULL ,CLP_PRETERMINATE_DATE>CURDATE(),CLP_ENDDATE>CURDATE()))>0 THEN
						SET GST_NULL_FLAG=1;						
					END IF;					
					IF GST_NULL_FLAG =1 THEN
						IF(SELECT COUNT(*) FROM CUSTOMER_LP_DETAILS WHERE CED_REC_VER=(MIN_RECVER) AND CUSTOMER_ID=CT_CUSTOMER_ID AND CLP_PRETERMINATE_DATE IS NOT NULL AND UASD_ID=UASDID AND IF (CLP_PRETERMINATE_DATE IS NOT NULL ,CLP_PRETERMINATE_DATE>CURDATE(),CLP_ENDDATE>CURDATE()))>0 THEN
							UPDATE CUSTOMER_LP_DETAILS CTD SET CTD.CLP_PRETERMINATE_DATE=NULL, CTD.ULD_ID=USERSTAMP_ID WHERE CTD.CUSTOMER_ID=CT_CUSTOMER_ID AND CTD.CED_REC_VER = MIN_RECVER AND CTD.CLP_GUEST_CARD IS NOT NULL AND CTD.UASD_ID=UASDID ORDER BY CTD.CLP_ID DESC LIMIT 1;
							SET TERMRESULT_FLAG=1;
							INSERT INTO TICKLER_HISTORY(TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE,ULD_ID,CUSTOMER_ID)VALUES(1,14,TICK_OLD_VALUE,TICK_NEW_VALUE,USERSTAMP_ID,CT_CUSTOMER_ID);									
						END IF;
					END IF;					
					ELSEIF MIN_RECVER>=CT_REC_VER THEN						
						UPDATE CUSTOMER_LP_DETAILS CTD SET CTD.CLP_PRETERMINATE_DATE=PRETERMINATE_DATE, CTD.ULD_ID=USERSTAMP_ID WHERE CTD.CUSTOMER_ID=CT_CUSTOMER_ID AND CTD.CED_REC_VER=MIN_RECVER AND CTD.CLP_GUEST_CARD IS NOT NULL AND CTD.UASD_ID=UASDID ORDER BY CTD.CLP_ID DESC LIMIT 1;
						SET TERMRESULT_FLAG=1;
								-- INSERT TERM DETAILS IN TICKLER TABLE FOR GUEST START	
									SET TICK_NEW_VALUE=(SELECT CONCAT('CLP_PRETERMINATE_DATE=',PRETERMINATE_DATE));					
									IF TERM_UASDID IS NOT NULL THEN
										SET TICK_OLD_VALUE=(SELECT CONCAT('CLP_ID=',(SELECT CLP_ID FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CT_CUSTOMER_ID AND UASD_ID=TERM_UASDID AND CED_REC_VER=MIN_RECVER),',CED_REC_VER=',MIN_RECVER,',CLP_GUEST_CARD=X',',UASD_ID=',TERM_UASDID,',CLP_PRETERMINATE_DATE=',TICK_PTD));
										INSERT INTO TICKLER_HISTORY(TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE,ULD_ID,CUSTOMER_ID)VALUES(1,14,TICK_OLD_VALUE,TICK_NEW_VALUE,USERSTAMP_ID,CT_CUSTOMER_ID);									
									END IF;
								-- INSERT TERM DETAILS IN TICKLER TABLE FOR GUEST END						
					END IF;
				ELSEIF ACTIVE_RECVER=CT_REC_VER THEN				
					UPDATE CUSTOMER_LP_DETAILS CTD SET CTD.CLP_PRETERMINATE_DATE=PRETERMINATE_DATE, CTD.ULD_ID=USERSTAMP_ID WHERE CTD.CUSTOMER_ID=CT_CUSTOMER_ID AND CTD.CED_REC_VER=MIN_RECVER AND CTD.CLP_GUEST_CARD IS NOT NULL AND CTD.UASD_ID=UASDID ORDER BY CTD.CLP_ID DESC LIMIT 1;
					SET TERMRESULT_FLAG=1;
								-- INSERT TERM DETAILS IN TICKLER TABLE FOR GUEST START
									SET TICK_NEW_VALUE=(SELECT CONCAT('CLP_PRETERMINATE_DATE=',PRETERMINATE_DATE));					
									IF	TERM_UASDID IS NOT NULL THEN								
										SET TICK_OLD_VALUE=(SELECT CONCAT('CLP_ID=',(SELECT CLP_ID FROM CUSTOMER_LP_DETAILS WHERE CUSTOMER_ID=CT_CUSTOMER_ID AND UASD_ID=TERM_UASDID AND CED_REC_VER=MIN_RECVER),',CED_REC_VER=',MIN_RECVER,',CLP_GUEST_CARD=X',',UASD_ID=',TERM_UASDID,',CLP_PRETERMINATE_DATE=',TICK_PTD));
										INSERT INTO TICKLER_HISTORY(TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE,ULD_ID,CUSTOMER_ID)VALUES(1,14,TICK_OLD_VALUE,TICK_NEW_VALUE,USERSTAMP_ID,CT_CUSTOMER_ID);									
									END IF;
									-- INSERT TERM DETAILS IN TICKLER TABLE FOR GUEST END					
				END IF;
				IF PRETERMINATE_DATE<=CURRENT_DATE() THEN
					SET TERM_UASDID = UASDID;
					SET TICK_CARD_NO=(SELECT UASD_ACCESS_CARD FROM UNIT_ACCESS_STAMP_DETAILS WHERE UASD_ID=UASDID);
					IF TERM_UASDID IS NOT NULL THEN
						IF EXISTS(SELECT * FROM CUSTOMER_ACCESS_CARD_DETAILS WHERE CUSTOMER_ID=CT_CUSTOMER_ID AND UASD_ID=TERM_UASDID AND CACD_VALID_TILL IS NULL) THEN
							SET TICK_OLD_VALUE=(SELECT CONCAT('CACD_ID=',(SELECT CACD_ID FROM CUSTOMER_ACCESS_CARD_DETAILS WHERE CUSTOMER_ID=CT_CUSTOMER_ID AND UASD_ID=TERM_UASDID AND ACN_ID IS NULL AND CACD_VALID_TILL IS NULL),',UASD_ID=',TERM_UASDID,',CACD_GUEST_CARD=X',',CACD_VALID_TILL=null,ACN_ID=null'));
							UPDATE CUSTOMER_ACCESS_CARD_DETAILS SET CACD_VALID_TILL=PRETERMINATE_DATE, ACN_ID=4, ULD_ID=USERSTAMP_ID WHERE CUSTOMER_ID=CT_CUSTOMER_ID AND UASD_ID=TERM_UASDID AND CACD_VALID_TILL IS NULL;
							UPDATE UNIT_ACCESS_STAMP_DETAILS SET UASD_ACCESS_ACTIVE=NULL, UASD_ACCESS_INVENTORY='X' WHERE UASD_ID=TERM_UASDID;	
							SET TERMRESULT_FLAG=1;							
							-- TICKLER FOR ACS CARD DTS FOR GUEST START						
								SET TICK_NEW_VALUE=(SELECT CONCAT('CACD_VALID_TILL=',PRETERMINATE_DATE,',ACN_ID=4'));
								INSERT INTO TICKLER_HISTORY(TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE,ULD_ID,CUSTOMER_ID)VALUES(1,13,TICK_OLD_VALUE,TICK_NEW_VALUE,USERSTAMP_ID,CT_CUSTOMER_ID);							
							-- TICKLER FOR ACS CARD DTS FOR GUEST END
						END IF;							
					END IF;
					SET TERM_UASDID = NULL;
				END IF;
				IF MIN_RECVER=MAX_RECVER THEN
					LEAVE RECVER_LOOP;
				END IF;
				SET MIN_RECVER=MIN_RECVER+1;
			END IF;
			END LOOP;
		END IF;
		IF ACCESS_POSITION<=0 THEN
			LEAVE ACCESS_LOOP;
		END IF;
	END LOOP;
	IF CT_COMMENTS IS NOT NULL THEN
		UPDATE CUSTOMER_PERSONAL_DETAILS SET CPD_COMMENTS=CT_COMMENTS WHERE CUSTOMER_ID=CT_CUSTOMER_ID;
		SET TERMRESULT_FLAG=1;
	ELSE
		UPDATE CUSTOMER_PERSONAL_DETAILS SET CPD_COMMENTS=NULL WHERE CUSTOMER_ID=CT_CUSTOMER_ID;
		SET TERMRESULT_FLAG=1;
	END IF;
	-- INSERT INTO TICKLER FOR COMMENTS START
	IF(TERM_CUST_COMMTS IS NULL) THEN
		SET TERM_CUST_COMMTS='null';
		SET TICK_OLD_VALUE=(SELECT CONCAT('CPD_ID=',(SELECT CPD_ID FROM CUSTOMER_PERSONAL_DETAILS WHERE CUSTOMER_ID=CT_CUSTOMER_ID),',CPD_COMMENTS=null'));		
	ELSE
		SET TICK_OLD_VALUE=(SELECT CONCAT('CPD_ID=',(SELECT CPD_ID FROM CUSTOMER_PERSONAL_DETAILS WHERE CUSTOMER_ID=CT_CUSTOMER_ID),',CPD_COMMENTS=',TERM_CUST_COMMTS));		
	END IF;
	IF(CT_COMMENTS IS NULL) THEN
		SET CT_COMMENTS='null';	
		SET TICK_NEW_VALUE=('CPD_COMMENTS=null');		
	ELSE
		SET TICK_NEW_VALUE=(SELECT CONCAT('CPD_COMMENTS=',CT_COMMENTS));		
	END IF;
	IF TERM_CUST_COMMTS!=CT_COMMENTS THEN
		INSERT INTO TICKLER_HISTORY(TP_ID,TTIP_ID,TH_OLD_VALUE,TH_NEW_VALUE,ULD_ID,CUSTOMER_ID)VALUES(1,15,TICK_OLD_VALUE,TICK_NEW_VALUE,USERSTAMP_ID,CT_CUSTOMER_ID);
	END IF;
-- INSERT INTO TICKLER FOR COMMENTS END	
	COMMIT;
END;
