-- version:1.1 -- sadte:09/06/2014 -- edate:09/06/2014  -- issue:566 COMMENT:12  --desc: IMPLEMENTED ROLLBACK AND COMMIT --doneby:DHIVYA
--  version:1.0 --  sdate:26/04/2014 --  edate:26/04/2014 --  issue:765 -- desc:REMOVE THE UPDATED TIMESTAMP -- doneby:BHAVANI.R
--  version:0.9 --  sdate:23/04/2014 --  edate:23/04/2014 --  issue:765 -- desc:UPDATED TIMESTAMP -- doneby:SASIKALA
--  version:0.8 --  sdate:26/03/2014 --  edate:26/03/2014 --  issue:765 -- desc:dynamically get source nd destination schema -- doneby:RL
--  version:0.7 --  sdate:17/03/2014 --  edate:17/03/2014 --  issue:765 -- desc:droped temp table -- doneby:RL
-- version:0.6 -- sdate:04/03/2014 -- edate:04/03/2014 -- Desc:ISSUE CORRECTED INUNIT EXPENSE- DONE BY SAFI
-- version:0.5 -- sdate:28/02/2014 -- edate:28/02/2014 -- issue:750 -- desc:changed userstamp as ULD_ID and timestamp get from scdb done by:RL
-- version:0.4-- sdate:21/02/2014 -- edate:22/02/2014 -- issue:750 -desc:added preaudit and post audit queries done by:dhivya
-- version:0.3 -- sdate:18/02/2014 -- edate:18/02/2014 -- issue:276 -- commentno:26 -- desc:ADD USERSTAMP N TIMESTAMP IN EXPENSE_HOUSEKEEPING_UNIT -- doneby:RL
-- version:0.2 -- sdate:21/01/2014 -- edate:21/01/2014 -- issue:594 -- commentno:50 & 54 -- doneby:RL
DROP PROCEDURE IF EXISTS SP_EXPENSE_HOUSEKEEPING_UNIT_INSERT;
CREATE PROCEDURE SP_EXPENSE_HOUSEKEEPING_UNIT_INSERT(IN DESTINATIONSCHEMA VARCHAR(50))
BEGIN	
	DECLARE TEHKU_MINIMUMID INTEGER;
	DECLARE TEHKU_MAXIMUMID INTEGER;	
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
	ROLLBACK;
	END;
	START TRANSACTION;
	SET @TEMP_EHKU_DROPQUERY=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_HOUSEKEEPING_UNIT'));
	PREPARE TEMP_EHKU_DROPQUERYSTMT FROM @TEMP_EHKU_DROPQUERY;
	EXECUTE TEMP_EHKU_DROPQUERYSTMT;	
	SET @TEMP_EHKU_CREATEQUERY=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_HOUSEKEEPING_UNIT(
	ID INTEGER AUTO_INCREMENT,
	TEHKU_UNITNO INTEGER,
	TEHKU_UID INTEGER,
	TEHKU_FORPERIOD DATE,
	TEHKU_PAIDDATE DATE,
	TEHKU_AMOUNT DECIMAL(7,2),
	TEHKU_COMMENTS TEXT,
	TEHKU_ULDID INTEGER,
	TEHKU_TIMESTAMP VARCHAR(50),
	PRIMARY KEY(ID))'));
	PREPARE TEMP_EHKU_CREATEQUERYSTMT FROM @TEMP_EHKU_CREATEQUERY;
	EXECUTE TEMP_EHKU_CREATEQUERYSTMT;	
	SET @TEMP_EHKU_INSERTQUERY=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_HOUSEKEEPING_UNIT(
	ID,TEHKU_UNITNO,TEHKU_FORPERIOD,TEHKU_PAIDDATE,TEHKU_AMOUNT,TEHKU_COMMENTS,TEHKU_ULDID,TEHKU_TIMESTAMP)
	SELECT ID,TEHK_UNITNO,TEHK_FORPERIOD,TEHK_PAIDDATE,TEHK_AMOUNT,TEHK_COMMENTS,TEHK_ULDID,TEHK_TIMESTAMP
	FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_HOUSEKEEPING WHERE TEHK_UNITNO NOT IN 
	(SELECT TEHKP_UNITNO FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_HOUSEKEEPING_PAYMENT)'));
	PREPARE TEMP_EHKU_INSERTQUERYSTMT FROM @TEMP_EHKU_INSERTQUERY;
	EXECUTE TEMP_EHKU_INSERTQUERYSTMT;	
	SET @EHKU_DROPQUERY=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.EXPENSE_HOUSEKEEPING_UNIT'));
	PREPARE EHKU_DROPQUERYSTMT FROM @EHKU_DROPQUERY;
	EXECUTE EHKU_DROPQUERYSTMT;	
	SET @EHKU_CREATEQUERY=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.EXPENSE_HOUSEKEEPING_UNIT(
	EHKU_ID	INTEGER NOT NULL AUTO_INCREMENT,
	EHKU_UNIT_NO SMALLINT(4) UNSIGNED ZEROFILL UNIQUE NOT NULL,
	ULD_ID INTEGER(2) NOT NULL,	
	EHKU_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(EHKU_ID),
	FOREIGN KEY(ULD_ID) REFERENCES ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS (ULD_ID))'));
	PREPARE EHKU_CREATEQUERYSTMT FROM @EHKU_CREATEQUERY;
	EXECUTE EHKU_CREATEQUERYSTMT;	
	SET @EHKU_INSERTQUERY=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.EXPENSE_HOUSEKEEPING_UNIT(
	EHKU_UNIT_NO,ULD_ID,EHKU_TIMESTAMP) SELECT TEHKU_UNITNO,TEHKU_ULDID,TEHKU_TIMESTAMP FROM 
	',DESTINATIONSCHEMA,'.TEMP_EXPENSE_HOUSEKEEPING_UNIT GROUP BY TEHKU_UNITNO'));
	PREPARE EHKU_INSERTQUERYSTMT FROM @EHKU_INSERTQUERY;
	EXECUTE EHKU_INSERTQUERYSTMT;	
	SET @TEHKU_MINID =(SELECT CONCAT('SELECT MIN(ID)INTO @TEHKUMINID FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_HOUSEKEEPING_UNIT'));
	PREPARE TEHKU_MINIDSTMT FROM @TEHKU_MINID;
	EXECUTE TEHKU_MINIDSTMT;
	SET TEHKU_MINIMUMID = @TEHKUMINID;	
	SET @TEHUKU_MAXID =(SELECT CONCAT('SELECT MAX(ID)INTO @TEHKUMAXID FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_HOUSEKEEPING_UNIT'));
	PREPARE TEHUKU_MAXIDSTMT FROM @TEHUKU_MAXID;
	EXECUTE TEHUKU_MAXIDSTMT;
	SET TEHKU_MAXIMUMID = @TEHKUMAXID;	
	WHILE(TEHKU_MINIMUMID <= TEHKU_MAXIMUMID)DO	
		SET @EHKUID = NULL;	
		SET @UUNITNO = (SELECT CONCAT('SELECT EHKU_ID INTO @EHKUID FROM ',DESTINATIONSCHEMA,'.EXPENSE_HOUSEKEEPING_UNIT
		WHERE EHKU_UNIT_NO = (SELECT TEHKU_UNITNO FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_HOUSEKEEPING_UNIT
		WHERE ID = ',TEHKU_MINIMUMID,')'));
		PREPARE UUNITNOSTMT FROM @UUNITNO;
		EXECUTE UUNITNOSTMT;		
		SET @UPDATEEHKUID =(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_HOUSEKEEPING_UNIT
		SET TEHKU_UID=@EHKUID WHERE ID=',TEHKU_MINIMUMID));
		PREPARE UPDATEEHKUIDSTMT FROM @UPDATEEHKUID;
		EXECUTE UPDATEEHKUIDSTMT;		
	SET TEHKU_MINIMUMID = TEHKU_MINIMUMID+1;
	END WHILE;	
	COMMIT;
END;
