-- version:1.1 -- sadte:09/06/2014 -- edate:09/06/2014  -- issue:566 COMMENT:12  --desc: IMPLEMENTED ROLLBACK AND COMMIT --doneby:DHIVYA
--  version:1.0 --  sdate:26/04/2014 --  edate:26/04/2014 --  issue:765 -- desc:REMOVE THE UPDATED TIMESTAMP-- doneby:BHAVANI.R
--  version:0.9 --  sdate:23/04/2014 --  edate:23/04/2014 --  issue:765 -- desc:UPDATED TIMESTAMP-- doneby:SASIKALA
--  version:0.8 --  sdate:26/03/2014 --  edate:26/03/2014 --  issue:765 -- desc:dynamically get source nd destination schema -- doneby:RL
--  version:0.7 --  sdate:17/03/2014 --  edate:17/03/2014 --  issue:765 -- desc:droped temp table -- doneby:RL
-- version:0.6 -- sdate:04/03/2014 -- edate:04/03/2014 -- Desc:ISSUE CORRECTED INUNIT EXPENSE- DONE BY SAFI
-- version:0.5 -- sdate:28/02/2014 -- edate:28/02/2014 -- issue:750 -- desc:changed userstamp as ULD_ID and timestamp get from scdb done by:RL
-- version:0.4-- sdate:21/02/2014 -- edate:22/02/2014 -- issue:750 -desc:added preaudit and post audit queries done by:dhivya
-- version:0.3 -- sdate:18/02/2014 -- edate:18/02/2014 -- issue:276 -- commentno:26 -- desc:ADD USERSTAMP N TIMESTAMP IN EXPENSE_HOUSEKEEPING_UNIT -- doneby:RL
-- version:0.2 -- sdate:21/01/2014 -- edate:21/01/2014 -- issue:594 -- commentno:50 & 54 -- doneby:RL
DROP PROCEDURE IF EXISTS SP_TEMP_EXPENSE_HOUSEKEEPING_PAYMENT_INSERT;
CREATE PROCEDURE SP_TEMP_EXPENSE_HOUSEKEEPING_PAYMENT_INSERT(IN DESTINATIONSCHEMA VARCHAR(50))
BEGIN
	DECLARE MINIMUM_ID INTEGER;
	DECLARE MAXIMUM_ID INTEGER;	
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
	ROLLBACK;
	END;
	START TRANSACTION;	
	SET @TEMP_EHK_DROPQUERY=(SELECT CONCAT('DROP TABLE IF EXISTS ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_HOUSEKEEPING_PAYMENT'));
	PREPARE TEMP_EHK_DROPQUERYSTMT FROM @TEMP_EHK_DROPQUERY;
	EXECUTE TEMP_EHK_DROPQUERYSTMT;	
	SET @TEMP_EHK_CREATEQUERY=(SELECT CONCAT('CREATE TABLE ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_HOUSEKEEPING_PAYMENT(
	ID INTEGER AUTO_INCREMENT,
	TEHKP_UNITNO INTEGER,
	TEHKP_UNITID INTEGER,
	TEHKP_FORPERIOD DATE,
	TEHKP_PAIDDATE DATE,
	TEHKP_AMOUNT DECIMAL(7,2),
	TEHKP_COMMENTS TEXT,
	TEHKP_ULDID INTEGER,
	TEHKP_TIMESTAMP VARCHAR(50),
	PRIMARY KEY(ID))'));
	PREPARE TEMP_EHK_CREATEQUERYSTMT FROM @TEMP_EHK_CREATEQUERY;
	EXECUTE TEMP_EHK_CREATEQUERYSTMT;	
	SET @TEMP_EHK_INSERTQUERY=(SELECT CONCAT('INSERT INTO ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_HOUSEKEEPING_PAYMENT(
	ID,TEHKP_UNITNO,TEHKP_FORPERIOD,TEHKP_PAIDDATE,TEHKP_AMOUNT,TEHKP_COMMENTS,TEHKP_ULDID,TEHKP_TIMESTAMP)
	SELECT ID,TEHK_UNITNO,TEHK_FORPERIOD,TEHK_PAIDDATE,TEHK_AMOUNT,TEHK_COMMENTS,TEHK_ULDID,TEHK_TIMESTAMP
	FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_HOUSEKEEPING TEHK , ',DESTINATIONSCHEMA,'.UNIT U
	WHERE U.UNIT_NO = TEHK.TEHK_UNITNO'));
	PREPARE TEMP_EHK_INSERTQUERYSTMT FROM @TEMP_EHK_INSERTQUERY;
	EXECUTE TEMP_EHK_INSERTQUERYSTMT;	
	SET @T_MINID =(SELECT CONCAT('SELECT MIN(ID)INTO @TH_MINID FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_HOUSEKEEPING_PAYMENT'));
	PREPARE T_MINIDSTMT FROM @T_MINID;
	EXECUTE T_MINIDSTMT;
	SET MINIMUM_ID = @TH_MINID;	
	SET @T_MAXID =(SELECT CONCAT('SELECT MAX(ID)INTO @TH_MAXID FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_HOUSEKEEPING_PAYMENT'));
	PREPARE T_MAXIDSTMT FROM @T_MAXID;
	EXECUTE T_MAXIDSTMT;
	SET MAXIMUM_ID = @TH_MAXID;	
	WHILE(MINIMUM_ID <= MAXIMUM_ID) DO	
		SET @UNITID = NULL;	
		SET @U_UNITNO = (SELECT CONCAT('SELECT UNIT_ID INTO @UNITID FROM ',DESTINATIONSCHEMA,'.UNIT
		WHERE UNIT_NO = (SELECT TEHKP_UNITNO FROM ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_HOUSEKEEPING_PAYMENT
		WHERE ID = ',MINIMUM_ID,')'));
		PREPARE U_UNITNOSTMT FROM @U_UNITNO;
		EXECUTE U_UNITNOSTMT;		
		SET @UPDATEUNITID =(SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.TEMP_EXPENSE_HOUSEKEEPING_PAYMENT
		SET TEHKP_UNITID=@UNITID WHERE ID=',MINIMUM_ID));
		PREPARE UPDATEUNITIDSTMT FROM @UPDATEUNITID;
		EXECUTE UPDATEUNITIDSTMT;		
	SET MINIMUM_ID = MINIMUM_ID+1;
	END WHILE;	
	COMMIT;
END;
