DROP PROCEDURE IF EXISTS SP_UPDATE_EMAIL_UPPERCASE_TO_LOWERCASE;
CREATE PROCEDURE SP_UPDATE_EMAIL_UPPERCASE_TO_LOWERCASE(IN DESTINATIONSCHEMA VARCHAR(50))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
END;
START TRANSACTION;
SET @UPDATECPD = (SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.CUSTOMER_PERSONAL_DETAILS SET CPD_EMAIL = LCASE (CPD_EMAIL)'));
PREPARE UPDATECPDSTMT FROM @UPDATECPD;
EXECUTE UPDATECPDSTMT;
SET @UPDATEEMAILLIST = (SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.EMAIL_LIST SET EL_EMAIL_ID = LCASE (EL_EMAIL_ID)'));
PREPARE UPDATEEMAILLISTSTMT FROM @UPDATEEMAILLIST;
EXECUTE UPDATEEMAILLISTSTMT;
SET @UPDATEEMPDTL = (SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.EMPLOYEE_DETAILS SET EMP_EMAIL = LCASE (EMP_EMAIL)'));
PREPARE UPDATEEMPDTLSTMT FROM @UPDATEEMPDTL;
EXECUTE UPDATEEMPDTLSTMT;
SET @UPDATEULD = (SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.USER_LOGIN_DETAILS SET ULD_LOGINID = LCASE (ULD_LOGINID)'));
PREPARE UPDATEULDSTMT FROM @UPDATEULD;
EXECUTE UPDATEULDSTMT;
SET @UPDATEERM = (SELECT CONCAT('UPDATE ',DESTINATIONSCHEMA,'.ERM_ENTRY_DETAILS SET ERM_EMAIL_ID = LCASE (ERM_EMAIL_ID)'));
PREPARE UPDATEERMSTMT FROM @UPDATEERM;
EXECUTE UPDATEERMSTMT;
COMMIT;
END;
CALL SP_UPDATE_EMAIL_UPPERCASE_TO_LOWERCASE(DESTINATIONSCHEMA);