DROP PROCEDURE IF EXISTS SP_CHARTS_GROSS_REVENUE;
CREATE PROCEDURE SP_CHARTS_GROSS_REVENUE(IN FROM_DATE VARCHAR(20), IN TO_DATE VARCHAR(20),IN USERSTAMP VARCHAR(50),OUT CHARTS_GROSS_REVENUE_TMPTBL TEXT)
BEGIN
DECLARE FINAL_FROM_DATE VARCHAR(20);
DECLARE FINAL_TO_DATE VARCHAR(20);
DECLARE CHARTS_GROSS_REVENUE_MAIN_TMPTBL TEXT;
DECLARE CHARTS_GROSS_REVENUE_INTERMEDIATE TEXT;
DECLARE CHARTS_GROSS_REVENUE_INTERMEDIATE_TMPTBL TEXT;
DECLARE USERSTAMP_ID INT;
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
 ROLLBACK;
 IF (CHARTS_GROSS_REVENUE_INTERMEDIATE_TMPTBL IS NOT NULL) THEN
 		SET @DROP_TEMP_INTERMEDIATE_CHARTS_GROSS_REVENUE=(SELECT CONCAT('DROP TABLE IF EXISTS ',CHARTS_GROSS_REVENUE_INTERMEDIATE_TMPTBL));
		PREPARE DROP_TEMP_INTERMEDIATE_CHARTS_GROSS_REVENUE_STMT FROM @DROP_TEMP_INTERMEDIATE_CHARTS_GROSS_REVENUE;
		EXECUTE DROP_TEMP_INTERMEDIATE_CHARTS_GROSS_REVENUE_STMT;
END IF;
END;    
START TRANSACTION;
	CALL SP_CHANGE_USERSTAMP_AS_ULDID(USERSTAMP,@ULDID);
	SET USERSTAMP_ID=(SELECT @ULDID);
	SET CHARTS_GROSS_REVENUE_MAIN_TMPTBL=(SELECT CONCAT('TEMP_CHARTS_GROSS_REVENUE',SYSDATE()));
	SET CHARTS_GROSS_REVENUE_INTERMEDIATE=(SELECT CONCAT('TEMP_INTERMEDIATE_CHARTS_GROSS_REVENUE',SYSDATE()));
	SET CHARTS_GROSS_REVENUE_MAIN_TMPTBL=(SELECT REPLACE(CHARTS_GROSS_REVENUE_MAIN_TMPTBL,' ',''));
	SET CHARTS_GROSS_REVENUE_MAIN_TMPTBL=(SELECT REPLACE(CHARTS_GROSS_REVENUE_MAIN_TMPTBL,'-',''));
	SET CHARTS_GROSS_REVENUE_MAIN_TMPTBL=(SELECT REPLACE(CHARTS_GROSS_REVENUE_MAIN_TMPTBL,':',''));
	SET CHARTS_GROSS_REVENUE_TMPTBL=(SELECT CONCAT(CHARTS_GROSS_REVENUE_MAIN_TMPTBL,'_',USERSTAMP_ID)); 
	SET CHARTS_GROSS_REVENUE_INTERMEDIATE=(SELECT REPLACE(CHARTS_GROSS_REVENUE_INTERMEDIATE,' ',''));
	SET CHARTS_GROSS_REVENUE_INTERMEDIATE=(SELECT REPLACE(CHARTS_GROSS_REVENUE_INTERMEDIATE,'-',''));
	SET CHARTS_GROSS_REVENUE_INTERMEDIATE=(SELECT REPLACE(CHARTS_GROSS_REVENUE_INTERMEDIATE,':',''));
	SET CHARTS_GROSS_REVENUE_INTERMEDIATE_TMPTBL=(SELECT CONCAT(CHARTS_GROSS_REVENUE_INTERMEDIATE,'_',USERSTAMP_ID));
  CALL SP_FORMAT_DATE(FROM_DATE,TO_DATE,@fd,@td);
  SELECT @fd INTO FINAL_FROM_DATE;
  SELECT @td INTO FINAL_TO_DATE;
      SET @CREATE_TEMP_CHARTS_GROSS_REVENUE=(SELECT CONCAT('CREATE TABLE ',CHARTS_GROSS_REVENUE_TMPTBL,'(MONTH_YEAR VARCHAR(20),GROSS_REVENUE DECIMAL(10,2))'));
	PREPARE CREATE_TEMP_CHARTS_GROSS_REVENUE_STMT FROM @CREATE_TEMP_CHARTS_GROSS_REVENUE;
	EXECUTE CREATE_TEMP_CHARTS_GROSS_REVENUE_STMT;
      SET @CREATE_TEMP_INTERMEDIATE_CHARTS_GROSS_REVENUE=(SELECT CONCAT('CREATE TABLE ',CHARTS_GROSS_REVENUE_INTERMEDIATE_TMPTBL,'(MONTH_YEAR VARCHAR(20),GROSS_REVENUE DECIMAL(10,2),  DATE DATE)'));
	  PREPARE CREATE_TEMP_INTERMEDIATE_CHARTS_GROSS_REVENUE_STMT FROM @CREATE_TEMP_INTERMEDIATE_CHARTS_GROSS_REVENUE;
	  EXECUTE CREATE_TEMP_INTERMEDIATE_CHARTS_GROSS_REVENUE_STMT;
   	SET @INSERT_TEMP_INTERMEDIATE_CHARTS_GROSS_REVENUE=(SELECT CONCAT('INSERT INTO ',CHARTS_GROSS_REVENUE_INTERMEDIATE_TMPTBL,' (MONTH_YEAR, GROSS_REVENUE, DATE) SELECT DATE_FORMAT(PD.PD_FOR_PERIOD,"%M-%Y"),PD.PD_AMOUNT, PD.PD_FOR_PERIOD FROM PAYMENT_DETAILS PD WHERE  PD.PD_FOR_PERIOD BETWEEN ','"',FINAL_FROM_DATE,'"', ' AND ','"',FINAL_TO_DATE,'"'));
		PREPARE INSERT_TEMP_INTERMEDIATE_CHARTS_GROSS_REVENUE_STMT FROM @INSERT_TEMP_INTERMEDIATE_CHARTS_GROSS_REVENUE;
		EXECUTE INSERT_TEMP_INTERMEDIATE_CHARTS_GROSS_REVENUE_STMT;
     	SET @INSERT_TEMP_CHARTS_GROSS_REVENUE=(SELECT CONCAT('INSERT INTO ',CHARTS_GROSS_REVENUE_TMPTBL,' (MONTH_YEAR , GROSS_REVENUE) (SELECT MONTH_YEAR,SUM(COALESCE(GROSS_REVENUE,'"0"')) FROM ',CHARTS_GROSS_REVENUE_INTERMEDIATE_TMPTBL,' GROUP BY MONTH_YEAR ORDER BY DATE)'));
		PREPARE INSERT_TEMP_CHARTS_GROSS_REVENUE_STMT FROM @INSERT_TEMP_CHARTS_GROSS_REVENUE;
		EXECUTE INSERT_TEMP_CHARTS_GROSS_REVENUE_STMT;  
		SET @DROP_TEMP_INTERMEDIATE_CHARTS_GROSS_REVENUE=(SELECT CONCAT('DROP TABLE IF EXISTS ',CHARTS_GROSS_REVENUE_INTERMEDIATE_TMPTBL));
		PREPARE DROP_TEMP_INTERMEDIATE_CHARTS_GROSS_REVENUE_STMT FROM @DROP_TEMP_INTERMEDIATE_CHARTS_GROSS_REVENUE;
		EXECUTE DROP_TEMP_INTERMEDIATE_CHARTS_GROSS_REVENUE_STMT;  
 COMMIT;
END;
