DROP PROCEDURE IF EXISTS SP_SUB_SEARCH_BY_ALL_UNIT;
CREATE PROCEDURE SP_SUB_SEARCH_BY_ALL_UNIT(IN TABLENAME TEXT,IN USERSTAMP VARCHAR(50),OUT FINAL_TABLE_NAME TEXT)
BEGIN
DECLARE TEMP_TABLE_NAME TEXT;
DECLARE USERSTAMP_ID INTEGER;
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
END;
CALL SP_CHANGE_USERSTAMP_AS_ULDID(USERSTAMP,@ULDID);
SET USERSTAMP_ID=(SELECT @ULDID);
SET TEMP_TABLE_NAME=(SELECT CONCAT(TABLENAME,'_',SYSDATE()));
SET TEMP_TABLE_NAME=(SELECT REPLACE(TEMP_TABLE_NAME,' ',''));
SET TEMP_TABLE_NAME=(SELECT REPLACE(TEMP_TABLE_NAME,'-',''));
SET TEMP_TABLE_NAME=(SELECT REPLACE(TEMP_TABLE_NAME,':',''));
SET FINAL_TABLE_NAME=(SELECT CONCAT(TEMP_TABLE_NAME,'_',USERSTAMP_ID));
IF TABLENAME='TEMP_ACCESS_CARD_ALL_UNIT' THEN
	SET @DROP_TEMP_UNIT=(SELECT CONCAT('DROP TABLE IF EXISTS ',FINAL_TABLE_NAME));
	PREPARE DROP_TEMP_UNIT_STMT FROM @DROP_TEMP_UNIT;
	EXECUTE DROP_TEMP_UNIT_STMT;
	SET @CREATE_TEMP_ACC_ALL_UNIT=(SELECT CONCAT('CREATE TABLE ',FINAL_TABLE_NAME,
	'(
	   ID INT,
	   UNITID INTEGER,
	   UNITNO  SMALLINT(4) UNSIGNED ZEROFILL,
	   ACTIVE_CARD TEXT,
	   INVENTORY_CARD INTEGER(7),
	   EMPLOYEE_LOST_CARD INTEGER(7),
	   CUSTOMER_LOST_CARD TEXT,
	   REASON VARCHAR(20)
	)'));
	PREPARE CREATE_TEMP_ACC_ALL_UNIT_STMT FROM @CREATE_TEMP_ACC_ALL_UNIT;
	EXECUTE  CREATE_TEMP_ACC_ALL_UNIT_STMT;
END IF;
IF TABLENAME='TEMP_ACCESS_CARD_SINGLE_UNIT' THEN
	SET @DROP_TEMP_SINGLE_UNIT=(SELECT CONCAT('DROP TABLE IF EXISTS ',FINAL_TABLE_NAME));
	PREPARE DROP_TEMP_SINGLE_UNIT_STMT FROM @DROP_TEMP_SINGLE_UNIT;
	EXECUTE DROP_TEMP_SINGLE_UNIT_STMT;
	SET @CREATE_SINGLE_UNIT=(SELECT CONCAT('CREATE TABLE ',FINAL_TABLE_NAME,'
	(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	UNITID INTEGER,
	UNITNO INTEGER,
	ACTIVE_CARD TEXT,
	INVENTORY_CARD INTEGER(7),
	EMPLOYEE_LOST_CARD INTEGER(7),
	CUSTOMER_LOST_CARD TEXT,
	REASON VARCHAR(20)
	)'));
	PREPARE CREATE_SINGLE_UNIT_STMT FROM @CREATE_SINGLE_UNIT;
	EXECUTE CREATE_SINGLE_UNIT_STMT;
END IF;
IF TABLENAME='TEMP_CUST' THEN
	SET @DROP_TEMP_CUST=(SELECT CONCAT('DROP TABLE IF EXISTS ',FINAL_TABLE_NAME));
	PREPARE DROP_TEMP_CUST_STMT FROM @DROP_TEMP_CUST;
	EXECUTE DROP_TEMP_CUST_STMT;
	SET @CREATE_CUST=(SELECT CONCAT('CREATE TABLE ',FINAL_TABLE_NAME,'(ID INT AUTO_INCREMENT PRIMARY KEY, CUST_ID INTEGER)'));
	PREPARE CREATE_CUST_STMT FROM @CREATE_CUST;
	EXECUTE CREATE_CUST_STMT;
END IF;
IF TABLENAME='TEMP_UNITNO' THEN
	SET @DROP_TEMP_UNITNO=(SELECT CONCAT('DROP TABLE IF EXISTS ',FINAL_TABLE_NAME));
	PREPARE DROP_TEMP_UNITNO_STMT FROM @DROP_TEMP_UNITNO;
	EXECUTE DROP_TEMP_UNITNO_STMT;
	SET @CREATE_TEMPUNITNO=(SELECT CONCAT('CREATE TABLE ',FINAL_TABLE_NAME,'(ID INTEGER AUTO_INCREMENT PRIMARY KEY,UNITID INTEGER,UNITNO INTEGER)'));
	PREPARE CREATE_TEMPUNITNO_STMT FROM @CREATE_TEMPUNITNO;
	EXECUTE CREATE_TEMPUNITNO_STMT;
END IF;
IF TABLENAME='TEMP_ACCESS' THEN
	SET @DROP_TEMP_ACCESS=(SELECT CONCAT('DROP TABLE IF EXISTS ',FINAL_TABLE_NAME));
	PREPARE DROP_TEMP_ACCESS_STMT FROM @DROP_TEMP_ACCESS;
	EXECUTE DROP_TEMP_ACCESS_STMT;
	SET @CREATE_TEMP_ACCESS=(SELECT CONCAT('CREATE TABLE ',FINAL_TABLE_NAME,'
	(ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,UNITID INTEGER,UNITNO INTEGER,UASDID INTEGER,ACCESS_CARD VARCHAR(7))'));
	PREPARE CREATE_TEMP_ACCESS_STMT FROM @CREATE_TEMP_ACCESS;
	EXECUTE CREATE_TEMP_ACCESS_STMT;
END IF;
COMMIT;
END;